### ISSUE TITLE
au-slot is not supported seamlessly in table

### ISSUE THREAD

**Issue by Sayan751** [aurelia/aurelia#1007]
# Issue

Currently the following usages of the `au-slot` in a table are not supported. As soon as the template is created via the template element factory, the `au-slot` is thrown out of the table.

```html
<!-- example#1 -->
<table>
  <thead>
    <tr>
      <th>Test</th>
    </tr>
  </thead>
  <tbody>
      <au-slot></au-slot> <!-- thrown out as it is not a tr -->
  </tbody>
</table>

<!-- example#2-->
<table>
  <thead>
    <tr>
      <th>Test</th>
    </tr>
  </thead>
  <tbody>
    <tr repeat.for="item of items">
      <au-slot></au-slot> <!-- thrown out as it is not a td -->
    </tr>
  </tbody>
</table>
```

## 🤔 Expected Behavior

It would be nice to somehow support this.

## 💁 Possible Solution

The template can be 'fixed' as a post-template-creation step. It is interesting that although the above templates are broken on normal parse, but `Element#append` can still be use to have the intended placement of `au-slot`. Example: https://codepen.io/sayan751/pen/wvWNONB

## 🔦 Context

Refer: https://github.com/aurelia/aurelia/issues/565#issuecomment-727514917

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          |
| Language         |
| Browser          |
| Bundler          |
| Operating System |
| NPM/Node/Yarn    |

**Comment by bigopon** [comment]
I'm hoping we can do the following to overcome the issue?
```html
<table>
  <tr>
    <template as-element="au-slot></template>
  </tr>
</table>
```

**Comment by 3cp** [comment]
I think you mean
```html
<table>
    <tbody as-element="au-slot"></tbody>
</table>
```

**Comment by bigopon** [comment]
@3cp thanks for pointing that out. I intentionally used `<template/>` inside `tr`, because `<au-slot/>` is containerless. I think we can make it not containerless by default, for the usage that comes from "as-element" on any element except 'template'.
```html
<table>
    <tbody as-element="au-slot"></tbody> // no containerless
</table>
```

**Comment by 3cp** [comment]
I like the default beheviour on containerless. Yes, it makes more sense to default to non-containerless when uses with as-element.

**Comment by Sayan751** [comment]
Changing the `containerless` property of `AuSlot` in runtime essentially means changing the definition of `AuSlot` for a single instance. As the definition does not get mapped to a node symbol, we actually need to have 2 different registrations for `AuSlot`, one for continerless and one with container. Also for the later we might need a different name. And use that name for those instance where the containered au-slot is needed; the node transformation needs to be done as a compilation step. 

IMO this is not a very clean solution, especially when we can cleanly support the use case with help of `template`+`as-element=au-slot` as a child node of `tr`/`thead`/`tbody` etc. Maybe we can revisit the requirement if the explicit association of a definition with a node symbol is possible.

**Comment by 3cp** [comment]
No matter how we implement this, there is one annoying user experience in both au1 and au2: since we use native browser html parser to parse html template, there is no way we can alert users of their wrong usage at runtime because browser parser just ignored invalid tags.

Au2 has html preprocessing at compile time, maybe we should warn user at compile time and suggest possible solutions and links.

**Comment by Sayan751** [comment]
Link to docs: https://docs.aurelia.io/app-basics/components-revisited#au-slot.
