### ISSUE TITLE
API for au-slot info

### ISSUE THREAD

**Issue by Sayan751** [aurelia/aurelia#1008]
# 🙋 Feature Request

At this point there is no ergonomic way of knowing whether or not any content has been projected for a `au-slot`.
In Au1, the workaround was something like this <https://ilikekillnerds.com/2017/07/checking-view-slot-defined-aurelia/>.

## 🤔 Expected Behavior

In Au2 we should try to provide better API. The proposal is to have a `@auSlots` decorator to inject the info to the host VM.

```ts
export class MyElement {
  @auSlots
  private readonly slots: Record<string, {template: HTMLElement, isProjection: boolean}>;
}
```

The key of the `Record` will be the name of the slot. The `template` in the value should be the original content template (original or fallback). and the `isProjection` will be `true` if content has been project, otherwise `false`.

## 😯 Current Behavior

Current workarounds may look something like these:
- https://stackblitz.com/edit/au-slot-detection?file=my-element.ts
- https://stackblitz.com/edit/au-slot-detection-children?file=my-element.ts

But the new proposal brings more flexibility IMO.

## 💁 Possible Solution

- Create new metadata entry for the class relating `@auSlots`. It should throw error is more that one usage of the decorator is found for the same class.
- When an instance of `AuSlot` is created, it looks for the metadata associated, and injects the info. If no metadata is found, then it is skipped.

## 🔦 Context

It is a need in the community to detect content projection and apply styles dynamically based on that.

[Quoting](https://discordapp.com/channels/448698263508615178/448699089513611266/776204425647226911) our community member @Seebiscuit on this.
> My use case is simple: A Component I'm building can have One or Two columns. The first column is a regular column, the second is a slot. The Component consumer has an option of providing a slot. If she does, then we display two columns of information. If she does not, then we display the first column and let it stretch the full width of the table.

cc: @bigopon @fkleuver

**Comment by Sayan751** [comment]
With the introduction of `processContent` (https://github.com/aurelia/aurelia/pull/1068), it gets easier to grab the template from the usage-side. From that perspective, I am changing the contract from 
```ts
Record<string, {template: HTMLElement, isProjection: boolean}>
```
to 
```ts
Record<string, boolean>
```

where the `boolean` value indicates whether projection has been provided for the slot. With this the contract stays closer to the actual requirement, as well as reduces the duplication of utilities for the same requirements.

**Comment by 3cp** [comment]
Is it possible to use DI for the injection?

**Comment by Sayan751** [comment]
> Is it possible to use DI for the injection?

@3cp Will that bring any particular advantage? This is how it is implemented as of now (#1084).

https://github.com/aurelia/aurelia/blob/d1f65aa8293504570e6ae3efc5b22d0198baffcb/packages/runtime-html/src/templating/controller.ts#L204-L208

IMO this is an effective way of doing it. On other hand injecting via DI might mean to register the instance in an disposable instance provider. Seems bit convoluted.

**Comment by 3cp** [comment]
It just feels bit magical without explicit injection, while DI is an established pattern.

**Comment by Sayan751** [comment]
@3cp You have a point. Changed the impl. to inject the info via DI.

**Comment by Sayan751** [comment]
Link to docs: https://docs.aurelia.io/app-basics/components-revisited#au-slot.
