### ISSUE TITLE
Throw or rewrite in build-time for usage of <slot> in non-shadow-dom project

### ISSUE THREAD

**Issue by 3cp** [aurelia/aurelia#1022]
If user didn't use ShadowDOM, then when `<slot>` is detected in a html template, the conventions preprocessor should 

1. either throw error to notify user that `<au-slot>` should be used instead.
2. or quietly rewrite `<slot>` to `<au-slot>`.

Probably throwing is better, the quiet rewrite might be very surprising.

**Comment by bigopon** [comment]
@3cp this is a nice way to do it. With convention, we can even go further 😬 : make it configurable that `[slot]` is automatically transformed to `[au-slot]`, and `<slot/>` to `<au-slot/>`

**Comment by bigopon** [comment]
Though I should say runtime should be able to do it with `@processContent` + `beforeCompile` resource hook

**Comment by fkleuver** [comment]
An error or warning sounds good
