### ISSUE TITLE
Fast integration page: link to extending templating syntax doesn't work

### ISSUE THREAD

**Issue by ben-girardet** [aurelia/aurelia#1027]
On the [Fast Integration](https://docs.aurelia.io/examples/integration/ms-fast) page the first link doesn't work. It somehow points to a github 404.

**Comment by bigopon** [comment]
Something wrong with the doc publishing step. The link is pointed to a commit 😓 

@fkleuver @EisenbergEffect is there a way to fix this?

**Comment by Sayan751** [comment]
Closing this, as it seems to be now fixed.
