### ISSUE TITLE
INodeObserverLocator interface is missing useConfig and useConfigGlobal

### ISSUE THREAD

**Issue by ben-girardet** [aurelia/aurelia#1028]
# 🐛 Bug Report

I'm trying to implement [Fast Integration](https://docs.aurelia.io/examples/integration/ms-fast) and use the code provided in the exemple. Typescript raises an issue when calling [useConfig](https://github.com/aurelia/aurelia/blob/5dcb1613039f0fa4f97d0114cc47cc7a66f04425/packages/runtime-html/src/observation/observer-locator.ts#L153-L155) on the `nodeObserverLocator: INodeObserverLocator`

## 🤔 Expected Behavior

No typescript error

## 💁 Possible Solution

Adding `useConfig` and `useConfigGlobal` to the [INodeObserverLocator](https://github.com/aurelia/aurelia/blob/4e9028042b738fb4f85f67fd7ccff8548a900422/packages/runtime/src/observation/observer-locator.ts#L34)

**Comment by bigopon** [comment]
@ben-girardet the `INodeObserverLocator` is the base interface. It is by designed conformed to a simple interface:
```ts
interface INodeObserverLocator {
  getAccessor(node, property);
  getObserver(node, property);
}
```
And our default implementation for this interface is the `NodeObserverLocator`, that has those method `useConfig`, `useConfigGlobal` to make it extensible.

So the doc is a bit wrong, it should be:
```ts
import { AppTask, IContainer, IAttrSyntaxTransformer } from 'aurelia';
import { NodeObserverLocator } from '@aurelia/runtime-html';

const nodeObserverLocator = container.get(NodeObserverLocator);
```

We should fix the doc, and the exports. The tasks are:
- add the rexport of `NodeObserverLocator` in `aurelia` package
- change the doc to:
  ```ts
  import { AppTask, IContainer, IAttrSyntaxTransformer, NodeObserverLocator } from 'aurelia';
  ```
  (this is based on the assumption that the application uses the default implementation of `INodeObserverLocator`, which is `NodeObserverLocator`)
