### ISSUE TITLE
Emit EA events for lifecycles

### ISSUE THREAD

**Issue by 3cp** [aurelia/aurelia#1037]
# 💬 RFC

Suggest to emit event-aggregator events for all lifecycles for every ce/ca. So that 3rd party au2 plugins can provide additional features integrated automatically into au2 lifecycles.

For example, add publishing the event for `attached` lifecycle.
```
ea.publish('au:attached', currentVM);
```

Note prefix `au:` is used instead of `au2:` because **this feature can be easily enabled in au1 too**.

## 🔦 Context

This is based on a plugin pattern from au1, like [aurelia-combo](https://github.com/aurelia-contrib/aurelia-combo). Since au1 didn't provide any feature to enable this global integration, it hacks by overwriting `Controller.prototype.attached` which is not pretty. This idea was copied from @JeroenVinke's [aurelia-after-attached-plugin](https://github.com/aurelia-ui-toolkits/aurelia-after-attached-plugin).

Although there are other means to enable global integration, such as Vue's global mixin pattern, our EA is an established pattern in our framework.
1. ea events are very cheap to implement, and relatively cheap at runtime too.
2. it fires all subscribers synchronously. 
3. it's more flexible than other rigid APIs.

For example, our au1 route emits navigation events, they are very handy for app to customise behaviour.
```
export const enum RouterEvent {
  Processing = 'router:navigation:processing',
  Error = 'router:navigation:error',
  Canceled = 'router:navigation:canceled',
  Complete = 'router:navigation:complete',
  Success = 'router:navigation:success',
  ChildComplete = 'router:navigation:child:complete'
}
```

## 💻 Examples

With au2 providing events for all lifecyles for every ce/ca, aurelia-combo plugin can simply do
```
ea.subscribe('au:attached', vm => { ... });
ea.subscribe('au:detached', vm => { ... });
```

**Comment by 3cp** [comment]
Not sure do we need two events for every lifecycle, like `au:attached:processing` and `au:attached:complete` before and after user VM's attached callback respectively.
So that plugin can inject logic before or after user code.

**Comment by fkleuver** [comment]
@3cp  Given <https://github.com/aurelia/aurelia/issues/1044>, would you still want this specifically?

**Comment by 3cp** [comment]
Agree. Not needed.
