### ISSUE TITLE
Webpack typescript setup doesn't generate correct souremap

### ISSUE THREAD

**Issue by 3cp** [aurelia/aurelia#1052]
# 🐛 Bug Report

The source map for `.ts` file is not against original user source file, but a modified source file done by `@aurelia/webpack-loader`.

## 🤔 Expected Behavior

It should display original source in debugger.

## 😯 Current Behavior

Our webpack-loader did generate the initial source map https://github.com/aurelia/aurelia/blob/1bdb122cd1af090b298c934325d917b9bd494949/packages/webpack-loader/src/index.ts#L34, but the ts-loader ignored incoming source map. This is a well known issue in ts-loader since 2017. https://github.com/TypeStrong/ts-loader/issues/552

## 💁 Possible Solution

Not sure what can be done, as ts-loader assumes it's the first loader in the chain.

For reference, ts-loader only reads file contents but not the existing source map.
https://github.com/TypeStrong/ts-loader/blob/172ebeb10cc8d15b91eca0828943bf7b962b4366/src/index.ts#L35

## 🔦 Context

In our webpack-loader, the incoming sourcemap is ignored but that's fine, because our loader is the first to be run in the loader chain. The problem is that ts-loader assumes it's the first loader too.
In comparison, webpack+babel does give you correct source map.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          |
| Language         |
| Browser          |
| Bundler          |
| Operating System |
| NPM/Node/Yarn    |

**Comment by josundt** [comment]
I got this working by setting the `sourceMap` property in the scaffolded tsconfig.json:

```json
{
  "sourceMap": true
}
```

This should definitely be added to the scaffolded code from `makes aurelia`

**Comment by bojanv55** [comment]
Just to comment which babel config worked for me with typescript (and indeed, source mapping works OK).

```
"devDependencies": {
    "@babel/core": "^7.15.0",
    "@babel/plugin-proposal-decorators": "^7.14.5",
    "@babel/preset-typescript": "^7.15.0",
    "babel-loader": "^8.2.2",
    "babel-plugin-transform-typescript-metadata": "^0.3.2",
```

and this config:

```
{
        test: /\.ts$/i,
        use: [
          {
            loader: 'babel-loader',
            options: {
              presets: ['@babel/preset-typescript'],
              plugins: ['babel-plugin-transform-typescript-metadata',
                [
                  '@babel/plugin-proposal-decorators',
                  {
                    legacy: true
                  }
                ]
              ]
            }
          }
          , '@aurelia/webpack-loader'],
        exclude: /node_modules/
      },
```

**Comment by bojanv55** [comment]
Btw, I think this is related to [https://github.com/microsoft/TypeScript/issues/13944](https://github.com/microsoft/TypeScript/issues/13944) since `ts-loader` would need to map between two source maps like here:

![image](https://user-images.githubusercontent.com/1422698/131256266-9b7626c5-4c17-42d8-b22d-628ad5807d16.png)

**Comment by bigopon** [comment]
Thanks for the work @bojanv55 .
@3cp how should we resolve this officially? Do we need to copy the work? or do we wrap ts-loader with the above fix inside our webpack loader?

**Comment by 3cp** [comment]
One possible solution is to avoid problematic ts-loader.

Move to faster [swc-loader](https://github.com/swc-project/pkgs/tree/main/packages/swc-loader). The implementation reads input source maps, I assume it has no such issue. It can replace babel-loader too.

**Comment by bigopon** [comment]
One important thing that only tsc does is typechecking, I think we need it. Or we can have a parallel build process for production to do the type checking, while dev will be with any kind of loader that works with sourcemap.

**Comment by 3cp** [comment]
Type check can be done with tsc --noEmit.
A lot of setups with alternative compilers still use tsc for type checking.

**Comment by bigopon** [comment]
you meant the setup needs to look like this?
```ts
{
  use: ['swc-loader', 'tsc-no-emit', '@aurelia/webpack-loader`]
}
```
?

**Comment by 3cp** [comment]
No, something like "prebuild": "tsc --noEmit" in package.json

**Comment by bigopon** [comment]
But that wouldnt include the compiled html for type checking so it would be partial. But maybe we can start with just that.

**Comment by 3cp** [comment]
Or get rid of webpack :-)
Seems nobody loves it. Now there are many other choices.

**Comment by bigopon** [comment]
Well we can, but we still have to deal with type checking.

**Comment by bigopon** [comment]
Actually in other bundler maybe the equivalent may not be fussy or bad with perf even with type checking. Yeah maybe we can leave this as no fix.

**Comment by 3cp** [comment]
I think ts-loader fixed this issue now. The source map is now correct, but I have to update our config to use slower devtool for better source maps.
https://github.com/aurelia/new/commit/feb0fbc8494c6604920676feb585fabcb8c42aa0
<img width="1533" alt="Screenshot 2024-05-16 at 7 18 01 AM" src="https://github.com/aurelia/aurelia/assets/1188806/3ae1348a-1df7-4ece-9e5c-914d64fe0981">

@bigopon could you double confirm the fix?

**Comment by 3cp** [comment]
BTW, I tested swc-loader, also works fine.
```
{
  loader: 'swc-loader',
  options: {
    jsc: {
      parser: {
        syntax: 'typescript',
        dynamicImport: true,
        decorators: true
      },
      transform: {
        decoratorMetadata: true
      },
      target: 'es2022'
    }
  }
},
```

**Comment by 3cp** [comment]
Reopen if need pls.
