### ISSUE TITLE
[Question]  Will there be a script-tag distribution of Aurelia2? 

### ISSUE THREAD

**Issue by akircher** [aurelia/aurelia#1073]
Apologies if I missed this but will there be a script-tag distribution of Aurelia2? None of the examples in this repo seem to show  that possibility, but I remember that (because of the quicker learning curve for new developers) being a goal.  

I would really love to be able to develop and prototype apps in Aurelia2 without having to use any build tools.  Even the [examples of JIT](https://github.com/aurelia/aurelia/tree/master/examples) seem to be using typescript.  I believe a build-less option would be a great way for folks new to the framework to try out Au2.  Ideally I would want something akin to the image below (of Vue & Svelte) for Au2 without a need for compilation, as this is how I would want to start projects and I think would be the most welcoming way to show code in the documentation / quick start guides.

But I am not sure if that is even possible since the TC39 decorator proposal still seems in flux and the decision/necessity to make conventions part of AOT rather than JIT. Hopefully it is possible and just adding an example into the repo and the docs would be all that is needed.

![Single Page Components](https://miro.medium.com/max/4800/1*q-biaWShCzVxYvOt4nHvAQ.png)

**Comment by PraveenGandhi** [comment]
For Aurelia 1 you can use https://github.com/aurelia/script


Sometime ago there was no bundler option for Aurelia 2 as well, but the link is broken now.

https://aurelia.blob.core.windows.net/releases/dev/au.bundle.js

Old Aurelia Repo fork:

https://github.com/PraveenGandhi/aurelia/tree/master/examples/no-bundlers/jit-iife-inline

@bigopon , please help if there is a way to use Aurelia 2 as aurelia-script

**Comment by brandonseydel** [comment]
Yes there will be.

**Comment by fkleuver** [comment]
Script tag is now released as a native module distribution. Here is an example of the realworld app implemented in a single html page with zero tooling, using `unpkg` as the host:
<https://github.com/aurelia/aurelia/blob/master/examples/realworld-vanilla/index.html#L453>
This can also be done locally by importing the relative path to `node_modules/aurelia/dist/native-modules/index.js`

**Comment by akircher** [comment]
Thanks so much @fkleuver.  This is awesome and easy to follow.  If you haven't yet, please consider putting a script-tag example of this on the homepage or within the quick start.  I believe it will make au2 feel much more approachable

**Comment by fkleuver** [comment]
> please consider putting a script-tag example like this on the homepage or within the quick start.

@Vheissu docs master, what do you think?

**Comment by Vheissu** [comment]
@fkleuver 1000%. Script tag would be the best introduction.

**Comment by akircher** [comment]
@Vheissu are they any working script-tag examples right now?  I was hoping Fred's example would work if I did
https://rawcdn.githack.com/aurelia/aurelia/master/examples/realworld-vanilla/index.html
But sadly it doesn't seem to work other than the initial load.  

Basically I am looking for someway of running a working app without having to serve the html myself.  Even better would interactive example in something like codepen. I think it would be a great intro page to embed a simple hello-world script-tag app that folks could modify in real-time.  Does something like this already exist?

**Comment by Vheissu** [comment]
@akircher Sorry, this one flew under my radar and fell to the bottom of the pile. Let me chase this up for you today and get something sorted out. I'll tag you shortly :)

**Comment by akircher** [comment]
@Vheissu Gently bumping this to the top of your inbox

**Comment by akircher** [comment]
@Vheissu and @fkleuver 

I had my team do an initial stab at an example using vanilla js.  Although it is very simple, I really hope this is helpful. Feel free to borrow all or parts of this for the docs.  Our goals were:

1) Keep it simpler than the current example, just showing very basic functionality, since this would be an intro to a new user.
2) Remove business logic, so that the only interesting parts were the framework.
3) Make it multi-page so the components and routes are not all stuffed into a single file.

https://github.com/dscsa/aurelia_example

We couldn't figure out a way to keep component's JS and HTML in a single file without polluting global scope.  You will see that we have custom-button.js and custom-button.html.  I think the example could go either way in this approach.

Once TC39 finalizes the `decorator` and `html modules` proposals, this example will look pretty close to the pre-transpiled code.  That is the wonderful thing about Aurelia being based on web-standards.

I am interested if either of you see anything wrong, overly-complicated, or that could otherwise be improved in this code.

Thanks
Adam

**Comment by akircher** [comment]
Oh also, we had some issues with just adding the template as an html string.  So right now, we add the templates to the DOM then then use the get_template helper to reference the actual html.  Not sure if that is working as expected or is a bug.

https://github.com/dscsa/aurelia_example/blob/main/index.html#L41
