### ISSUE TITLE
Refreshing on a route that has an asynchronous load hook briefly flicks between the default route

### ISSUE THREAD

**Issue by Vheissu** [aurelia/aurelia#1078]
# 🐛 Bug Report

First and foremost, I am not entirely certain if this is expected behaviour or a half-bug. I am not experiencing anything that is breaking my use of the router, just some strange behaviour. 

- Navigate to a route that has an asynchronous `load` lifecycle method implemented (see linked code example further down)
- Refresh the page
- Pay close attention to the URL, it will flick back to the component specified on `default` and then back to the current route

Please also note that I have tested this with both hashChange as well as pushState routing and the result is the same.

## 🤔 Expected Behavior

The route shouldn't flicker and change, it should remain the same and only redirect if instructed to do so.

## 😯 Current Behavior

It is flicking back to the default route and then back to the current route.

## 🔦 Context

It's not so much a breaking issue, but I do find it jarring and believe it shouldn't be happening. It could be indicative of a bug or possibly not.

## 💻 Code Sample

I have a Aurelia 2 application [here](https://github.com/Vheissu/aurelia2-realworld) on GitHub. Download, `npm install` and then `npm start`. Visit the route titled, "API Content" and your URL should resemble `http://localhost:9000/dynamic-route` now refresh the page and watch the URL, you will notice it flick back and forth briefly to the home route.

**Comment by fkleuver** [comment]
This is fixed now
