### ISSUE TITLE
Webpack seems like it can't resolve path and therefore fails to compile

### ISSUE THREAD

**Issue by ghost** [aurelia/aurelia#1079]
# 🐛 Bug Report
After some days off and a fresh installed Ubuntu 20.04, i've wanted to clone my aurelia2 repo but if i want to "npm start", i'm getting an error. Same happens if i try to make a new aurelia 2 project.
nodejs v10.19.0
npm 6.14.4
webpack 5.11.1 
i'm coding with vsc

I've changed absolutley nothing, just "npx makes aurelia" with default ts settings and tried to start and this is the outcome...

`./src/main.ts 39 bytes [not cacheable] [built] [code generated] [1 error]
./node_modules/webpack/hot/ sync nonrecursive ^\.\/log$ 170 bytes [built] [code generated]
ERROR in ./src/main.ts
Module build failed (from ./node_modules/@aurelia/webpack-loader/dist/cjs/index.js):
/home/andre/Projects/test/node_modules/@aurelia/kernel/dist/cjs/di.js:67
        return new ContainerConfiguration(config.inheritParentResources ?? false, config.defaultResolver ?? exports.DefaultResolver.singleton);`

`SyntaxError: Unexpected token ?
    at new Script (vm.js:83:7)
    at NativeCompileCache._moduleCompile (/home/andre/Projects/test/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/home/andre/Projects/test/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/home/andre/Projects/test/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/andre/Projects/test/node_modules/@aurelia/kernel/dist/cjs/index.js:5:17)`

Maybe someone allready encountered that or do know a solution for this issue?

**Comment by mikeesouth** [comment]
Same here. Any workaround? I'm using `"aurelia": "dev"` in package.json which is a bit annoying since breaking changes occur quite frequently. Where can I find the latest releases so that I can specify a (slightly) older release to circumvent this bug?

**Comment by bigopon** [comment]
We recently changed our dist target from es2018 to es2020, which means `??` syntax won't be transformed to lower level equivalence. If JS parser used by webpack is not configured to understand this, there will be an issue while parsing and the error message will be something like above:
```
SyntaxError: Unexpected token ? at new Script (vm.js:83:7) at NativeCompileCache._moduleCompile (/home/andre/Projects/test/node_modules/v8-compile-cache/v8-compile-cache.js:240:18) at Module._compile
```
Though I remember latest version of webpack (maybe 5-beta?) can deal with this. Can you help give information about your webpack version?

**Comment by methatox** [comment]
Like i mentioned before, i'm using webpack 5.11.1 as default installation from "npx makes aurelia".
`"aurelia": "dev"` doesn't work for me, it's allready default.

**Comment by timfish** [comment]
Thanks to @3cp on Discord... you need to be using nodejs version that supports ES2020 which is >= 14.5.0

**Comment by 3cp** [comment]
See #1081

**Comment by methatox** [comment]
@timfish  @3cp  you made my day, worked like a charm

**Comment by Sayan751** [comment]
Closing this, as it seems to be resolved.
