### ISSUE TITLE
Plugin convention incorrectly removes `<bindable/>` of local custom element

### ISSUE THREAD

**Issue by bigopon** [aurelia/aurelia#1086]
# 🐛 Bug Report

## 🤔 Current Behavior

In this gist https://gist.dumber.app/?gist=5e0ee8db13894687318133bb8125d1b5 it should display `myProp: ....` but it's displaying `myProp:` only. This is **probably** because the following line
```html
  <bindable property="prop" attribute="fiz-bar"></bindable>
```
is incorrectly removed, by the plugin convention.

## 💁 Possible Solution

When plugin convention sees a `<bindable/>`, it should first check whether that `<bindable/>` belongs to a `<template as-custom-element="..." />` first, if it's the immediate child of one, then it's a valid `<bindable/>` for our local template feature https://docs.aurelia.io/getting-started/components/local-templates and shouldn't be removed.

cc @3cp @Sayan751

**Comment by 3cp** [comment]
It's still possible to process `<template as-custom-element="person-info">` and all its inner content statically at compile time, just wrap it as one local customElement (probably a simple recursion in https://github.com/aurelia/aurelia/blob/90911c2a2ca703d57311c6dc65a4e3d83e566f50/packages-cjs/plugin-conventions/src/preprocess-html-template.ts#L15)and add it to local dependencies of current html module.

```js
export const dependencies = [ /* add a local customElement here */];
```

It's probably better not mixing compile time and runtime processing in Aurelia 2, unless there is something that the compile time preprocessor could not cover.

Runtime processing can bring back those invalid tag issue inside `<table>`/`<tbody>`/`<tr>` which we could not bypass because of the native html parser in Aurelia 1.

**Comment by bigopon** [comment]
I think this feature is more than just compile time vs runtime. In scenarios where it's desirable to have complex html only template without any ways to wire up dependencies of a view. We can still pre-compile local template by default, and it's probably desirable that way too, but the capability of doing it at runtime should still be there.

**Comment by 3cp** [comment]
Aurelia 2 moved lots of stuff from runtime to compile time. We need some usage for must-be-runtime `<bindable>` to justify extra runtime code. If this can be covered by compile time preprocessing, we can reduce the runtime code.

**Comment by Sayan751** [comment]
IMO local template is not a convention. Therefore, it should not be supported solely by convention plugin. Also we should probably use the words like "build time"/"bundle time" instead of compile time to avoid confusion, as there is a JIT template compiler in place.

**Comment by 3cp** [comment]
It is certainly very easy to fix conventions implementation (just skip everything in the `<template as-custom-element>`) if local template is processed at runtime. I just have not seen a concrete use case that a local template must be processed at runtime.

**Comment by 3cp** [comment]
Side note, runtime needs to properly deal with `<bindable>` without closing tag, assuming we are using native html parser.

```html
<bindable property="prop">
<bindable property="prop" /> <!-- html5 doesn't recognise self-closing -->
```

Also, our existing build time  `<bindable>` is using a different attribute `name`. Why this local template picked `property`? Overlooked?

https://github.com/aurelia/aurelia/blob/071fd38ed69d74e34b04d0f9d62a3a15796ab9b8/packages-cjs/plugin-conventions/src/strip-meta-data.ts#L164-L171

Also, the local template doc writes single quote on the attribute value `property='prop'`, which is not idea, should use double quote.
```html
<template as-custom-element="foo-bar">
  <bindable property='prop'></bindable>

  Level One ${prop}
</template>
<foo-bar prop.bind="prop"></foo-bar>
```

**Comment by bigopon** [comment]
> Also, our existing build time <bindable> is using a different attribute name. Why this local template picked property? Overlooked?

Seems like it is. Also v1 has name and attributes as well.

**Comment by 3cp** [comment]
The PR fixed the conventions, it doesn't care about the property name on bindable, or anything inside local template.
Someone need to clean up property name in another PR.
