### ISSUE TITLE
Usage of bindable in local template is not consistent with existing bindable

### ISSUE THREAD

**Issue by 3cp** [aurelia/aurelia#1091]
Extracted from #1086 

-----

Our existing build time  `<bindable>` is using attribute `name` and `attribute`. This is inline with Aurelia 1.

https://github.com/aurelia/aurelia/blob/071fd38ed69d74e34b04d0f9d62a3a15796ab9b8/packages-cjs/plugin-conventions/src/strip-meta-data.ts#L164-L171

But local template use attribute `property`. This is probably overlooked, need to change to `name` and `attribute`.
```html
<template as-custom-element="foo-bar">
  <bindable property="prop"></bindable>

  Level One ${prop}
</template>
<foo-bar prop.bind="prop"></foo-bar>
```

**Comment by 3cp** [comment]
BTW, local template can add support of `<template as-custom-element="foo-bar" bindable="prop">` too.
Conventions would not process anything on (or inside) the local template tag.

**Comment by Sayan751** [comment]
> This is inline with Aurelia 1.

I think in Au1 we don't have `<bindable>` element at all. We only have the `bindable` attribute that can be applied on the `template` element.

BTW the use of the `property` attribute was inspired from the bindable definition contract:

https://github.com/aurelia/aurelia/blob/fe528ff762832274cddd9d1203e5699551518c71/packages/runtime-html/src/bindable.ts#L16-L23

**Comment by bigopon** [comment]
@Sayan751 nice, thanks for pointing that out. I think that may be an issue that we need to resolve related to naming. We could employ `name`, tas in v1, we could do this:
```ts
@bindable({ name: 'value', attribute: 'fiz-baz' })
export MyElement {}
```

**Comment by bigopon** [comment]
I meant we could do it everywhere in 1 sweep later, to align 2 versions together, also to align local template & convention as well. The inconsistency probably should be resolved before alpha.

**Comment by Sayan751** [comment]
Is this still valid?

**Comment by bigopon** [comment]
@Sayan751 yes it's still inconsistent. I think we should have it as `name` + `attribute`
