### ISSUE TITLE
Build source code breaks

### ISSUE THREAD

**Issue by nenadvicentic** [aurelia/aurelia#1093]
# 🐛 Bug Report

Trying to follow instruction how to build source code [here](https://docs.aurelia.io/community-contribution/building-and-testing-aurelia#setup) - breaks the build. 

```
git clone https://github.com/aurelia/aurelia.git && cd aurelia
npm ci
npm run build
```

## 🤔 Expected Behavior

Build source code without an error.

## 😯 Current Behavior

Breaks down with an error on the 3rd command from the instruction: `npm run build`

```
verb @aurelia/kernel build failed, took 1.74s
info [Tasks Count] success: 4, skipped: 0, incomplete: 2
info ----------------------------------------------
ERR! [@aurelia/kernel build] ERROR DETECTED
ERR! started
ERR! Running C:\Program Files\nodejs\npm.CMD run build
ERR! > @aurelia/kernel@0.9.0 build
ERR! > tsc -b
ERR! src/platform.ts(1,26): error TS2307: Cannot find module '@aurelia/platform' or its corresponding type declarations.
ERR! src/resource.ts(1,26): error TS2307: Cannot find module '@aurelia/metadata' or its corresponding type declarations.
ERR! src/di.ts(1,59): error TS2307: Cannot find module '@aurelia/metadata' or its corresponding type declarations.
ERR! src/logger.ts(5,26): error TS2307: Cannot find module '@aurelia/metadata' or its corresponding type declarations.
ERR! src/logger.ts(334,24): error TS2339: Property 'console' does not exist on type 'IPlatform'.
ERR! src/index.ts(14,8): error TS2307: Cannot find module '@aurelia/platform' or its corresponding type declarations.
ERR! src/index.ts(63,8): error TS2307: Cannot find module '@aurelia/metadata' or its corresponding type declarations.
ERR!  ERR! code 1
ERR! npm ERR! path d:\dev\GitHub\aurelia\aurelia\packages\kernel
ERR!  command failed
ERR! npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c tsc -b
ERR! npm ERR! A complete log of this run can be found in:
ERR! npm ERR!     C:\Users\Nenad\AppData\Local\npm-cache\_logs\2021-02-06T14_42_29_559Z-debug.log
ERR! failed
info ----------------------------------------------
info Took a total of 3.09s to complete
npm ERR! code 1
npm ERR! path d:\dev\GitHub\aurelia\aurelia
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c lage build --scope @aurelia/* --scope aurelia --scope au --scope @benchmarking-apps/* --no-cache --verbose --no-deps
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | master branch -> SHA-1: fe528ff762832274cddd9d1203e5699551518c71
| Language         |
| Browser          |
| Bundler          |
| Operating System | Windows 10
| NPM/Node/Yarn    | 7.5.2 / v14.15.4 / --

**Comment by Sayan751** [comment]
@nenadvicentic Can you upgrade your node to v15 and retry? 

Also another point to note is that recently we have moved from lerna to lage. This also requires setting the environment variable `PREFERRED_WORKSPACE_MANAGER`, as lage does not yet supports npm7 workspace. For example you can set the variable to `PREFERRED_WORKSPACE_MANAGER=yarn`.

**Comment by nenadvicentic** [comment]
@Sayan751 Thanks for the tip! I've missed Node version requirements.

After I updated to Node v15 build worked fine! I did not even set `PREFERRED_WORKSPACE_MANAGER` variable (I was curious to test what happens). Yarn was used anyway, I could tell that because `yarn.lock` file was modified after build, instead of `package-lock.json`.

However, I've had another issue afterwards. This might be simply a current state of the master branch, but just to report it.

When running tests, using commands described in the documentation page, on Chrome all tests passed, but on Firefox (v85.0) I've got errors:

```
=============================== Coverage summary ===============================
Statements   : 79.08% ( 12290/15542 )
Branches     : 65.27% ( 5565/8526 )
Functions    : 78.48% ( 2371/3021 )
Lines        : 87.11% ( 11655/13380 )
================================================================================
TOTAL: 4 FAILED, 63773 SUCCESS
07 02 2021 17:03:16.284:DEBUG [karma-server]: Run complete, exiting.
07 02 2021 17:03:16.285:DEBUG [launcher]: Disconnecting all browsers
07 02 2021 17:03:16.286:DEBUG [launcher]: BEING_FORCE_KILLED -> BEING_FORCE_KILLED
07 02 2021 17:03:16.286:DEBUG [proxy]: Destroying proxy agents
07 02 2021 17:03:16.296:DEBUG [launcher]: Process FirefoxHeadless exited with code null and signal SIGTERM
07 02 2021 17:03:16.298:DEBUG [temp-dir]: Cleaning temp dir ..\AppData\Local\Temp\karma-52695037
07 02 2021 17:03:16.794:DEBUG [launcher]: Finished all browsers
07 02 2021 17:03:16.794:DEBUG [launcher]: BEING_FORCE_KILLED -> FINISHED
07 02 2021 17:03:16.795:DEBUG [launcher]: FINISHED -> FINISHED
```
Similar to FireFox, Node (v15.8.0) also had 4 errors:

```
4 failing

  1) 3-runtime-html/binding-resources.spec.ts
       debounce
         works with trigger bindings:

      AssertionError [ERR_ASSERTION]: event 2 not yet propagated - Expected values to be strictly equal:

1 !== 0

      + expected - actual

      -1
      +0

      at Context.<anonymous> (file:///d:/dev/GitHub/aurelia/aurelia/packages/__tests__/dist/esm/__tests__/3-runtime-html/binding-resources.spec.js:271:24)

  2) 3-runtime-html/binding-resources.spec.ts
       debounce
         works with capture bindings:

      AssertionError [ERR_ASSERTION]: event 1 not yet propagated - Expected values to be strictly equal:

1 !== 0

      + expected - actual

      -1
      +0

      at Context.<anonymous> (file:///d:/dev/GitHub/aurelia/aurelia/packages/__tests__/dist/esm/__tests__/3-runtime-html/binding-resources.spec.js:267:24)

  3) 3-runtime-html/binding-resources.spec.ts
       debounce
         works with delegate bindings:

      AssertionError [ERR_ASSERTION]: event 2 not yet propagated - Expected values to be strictly equal:

1 !== 0

      + expected - actual

      -1
      +0

      at Context.<anonymous> (file:///d:/dev/GitHub/aurelia/aurelia/packages/__tests__/dist/esm/__tests__/3-runtime-html/binding-resources.spec.js:271:24)

  4) 3-runtime-html/binding-resources.spec.ts
       throttle
         works with [twoWay] bindings to other components:

      AssertionError [ERR_ASSERTION]: change 3 still throttled after 20ms - Expected values to be strictly equal:

'3' !== '2'

      + expected - actual

      -3
      +2

      at Context.<anonymous> (file:///d:/dev/GitHub/aurelia/aurelia/packages/__tests__/dist/esm/__tests__/3-runtime-html/binding-resources.spec.js:375:20)
```

**Comment by Sayan751** [comment]
Awesome now that the build works!

Those might be couple of flaky tests, as those tests clearly run in the CI environment. Maybe @bigopon has better idea than me.

**Comment by bigopon** [comment]
@nenadvicentic thanks for the alert. As @Sayan751 said, they are indeed the most flaky ones, especially on Firefox, since there's something about timing that makes it harder there to control precisely. If you open the source code of those test, it tries to assert the timing quite strictly. I'm not sure how it can be resolve yet, for now, whenever they fail, we only rerun them.

**Comment by nenadvicentic** [comment]
@bigopon just from curiosity, shouldn't following line, after 2nd click event expect `1`, instead of `0`?

```
assert.strictEqual(component.events.length, 0, `event 2 not yet propagated`);
```

The binding is: `click.trigger="handleClick($event) & debounce:25"`

So, after waiting 2x20ms, first event should be in the the list.

And, at the end of the test, logically I would expect `events.length == 3`, not `1`.
```
assert.strictEqual(component.events.length, 1, `event 3 propagated`);
```

I am sure I am missing something here.

**Comment by bigopon** [comment]
In that test, before every assertion that looks like this
```ts
assert.strictEqual(component.events.length, 0, `event 2 not yet propagated`);
```
there's a click "event", that looks like this:
```ts
        const event2 = new ctx.CustomEvent('click', eventInit);
        receiver.dispatchEvent(event2);
```
So it should keep debouncing.

**Comment by nenadvicentic** [comment]
That part, how event click is emulated, is clear to me.

I think I'm missing something here - every click is supposed to call `handleClick($event)`, after 25ms delay:

`<div ref="receiver" click.${command}="handleClick($event) & debounce:25"></div>`

And the function only adds click events to array:
```
public handleClick($event: CustomEvent): void {
  this.events.push($event);
}
```

So, I would expect that, by the 2nd assert, you quoted (`event 2 not yet propagated`), which is 40ms after 1st click, that first `$event` is already in the `component.events` array. And by the 3rd assert - that there are 2 events in the array and that only 3rd one is yet to be pushed at that point.

**Comment by bigopon** [comment]
the timeline should look like this:
- click event: start a 25ms timer that will push a `click` to `events` array
- at 20ms: another click event, cancel the previous timer, start another 25ms timer that will push a `click` to `events` array
- at 40ms: another click event, cancel the previous timer, start another 25ms timer that will push a `click` to `events` array
- and on and on...

Is this what you expecting?

**Comment by nenadvicentic** [comment]
@bigopon Right! I forgot it cancels the events. Does not just delay them. Maybe it's time for me to go to pensions. :)

**Comment by bigopon** [comment]
everyone needs a small break to comeback stronger :)

**Comment by bigopon** [comment]
I think we've got a few improvement to the development aspect of the repo. I'll close this. Please open a new one if you are still hitting some issues. Thanks.
