### ISSUE TITLE
Contact Manager Tutorial should mention that the HTML <base> tag should be updated when enabling Push-State-Routing

### ISSUE THREAD

**Issue by feO2x** [aurelia/aurelia#1100]
I'm new to Auralia and tried the Contact Manager Tutorial. I noticed that the Webpack Dev Bundles were not loaded correctly when pressing F5 to reload the current site while the URL was pointing to the contact details (e.g. `https://localhost:8080/contacts/1`). It took me some time to realize that the HTML meta tag `<base>` is not set to `'/'` by the Aurelia CLI (see this [StackOverflow question](https://stackoverflow.com/a/66135941/1560623) for details).

I would recommend to add a paragraph to the tutorial, describing how to adjust the base meta tag, as well as a paragraph to the corresponding [Options section in the routing docs](https://aurelia.io/docs/routing/configuration#basic-configuration) where it is pointed out that the base tag is not set by default (at least in a webpack scenario).

**Comment by Alexander-Taran** [comment]
Would you like to provide a pull request for it @feO2x ?

**Comment by Sayan751** [comment]
The router [docs](https://aurelia.io/docs/routing/configuration#options) already provide the following details on this topic. Can this be closed?

![image](https://github.com/aurelia/aurelia/assets/3128881/94bab757-c468-40fd-af4f-4d9594a1f828)

**Comment by feO2x** [comment]
Yes, this can be closed.
