### ISSUE TITLE
How to properly integrate the aurelia-i18n plugin in a TypeScript with Webpack scenario?

### ISSUE THREAD

**Issue by feO2x** [aurelia/aurelia#1101]
First of all, I'm new to Aurelia, so please forgive me if this is somewhat of a noob issue.

I set up an Aurelia project with TypeScript and Webpack using aurelia-cli v2.0.2 and tried to follow [the official docs on aurelia.io](https://aurelia.io/docs/plugins/i18n). I want to use the Aurelia loader to provide i18n with translation.json files. However, I wasn't able to correctly configure i18next, it always says that the corresponding JSON files could not be loaded:

![Unable to load translation files](https://user-images.githubusercontent.com/7884158/107606812-92fd3180-6c37-11eb-844b-6256b7655b98.png)

My main.ts file looks like this:

```typescript
import { Aurelia } from 'aurelia-framework';
import * as environment from '../config/environment.json';
import { PLATFORM } from 'aurelia-pal';
import { Backend, TCustomAttribute } from 'aurelia-i18n';

export function configure(aurelia: Aurelia): void {
    aurelia.use
        .standardConfiguration()
        .developmentLogging(environment.debug ? 'debug' : 'warn')
        .plugin(PLATFORM.moduleName('aurelia-i18n'), instance => {
            const aliases = ['t', 'i18n'];
            TCustomAttribute.configureAliases(aliases);
            instance.i18next.use(Backend.with(aurelia.loader));

            return instance.setup({
                backend: {
                    loadPath: './locales/{{lng}}/{{ns}}.json'
                },
                attributes: aliases,
                lng: 'de',
                fallbackLng: 'en',
                debug: true
            });
        });

    if (environment.testing) {
        aurelia.use.plugin(PLATFORM.moduleName('aurelia-testing'));
    }

    aurelia.start().then(() => aurelia.setRoot(PLATFORM.moduleName('app')));
}
```

What I tried so far:

- I removed the dot in in the path. According to [this Discourse request](https://discourse.aurelia.io/t/solved-how-to-use-i18n-with-backend-in-au-cli-webpack-projects/542/6), Webpack cannot handle dots in paths, but `loadPath: 'locales/{{lng}}/{{ns}}.json'` does not fix the problem.
- I also tried to omit the Aurelia loader and apply the parsed JSON files directly to `resources`, but using `import * as en from './locales/en/translation.json'` didn't work as well. I assume this has to do with the webpack configuration where [the default json loader was removed](https://github.com/aurelia/cli/issues/860) a while ago? However, when I simply reintroduce it, compilation failed.

![Import of json files fails](https://user-images.githubusercontent.com/7884158/107608084-356ae400-6c3b-11eb-90ad-6e786e56e516.png)

My next steps will be to re-add the JSON loader to Webpack for the translation files only. However, I think that the docs need to be updated so that the Aurelia loader can be used in a Webpack scenario.

**Comment by zewa666** [comment]
Hey there, the Aurelia loader isnt designed with Webpack in mind as it predates it by a good amount.

Instead the docs mention using the xhr-loader by i18next. That way your translations are loaded on demand. Would that work for you?

**Comment by feO2x** [comment]
Let me give it a try.

**Comment by feO2x** [comment]
Well, it works with the XHR backend (in dev mode). I still think updating the docs would be great, because it says "Also optionally install the i18next-xhr-backend plugin".

**Comment by zewa666** [comment]
So could I instead ask you to provide a PR to said Docs page? You can find the markdown file here. https://github.com/aurelia/documentation/blob/master/current/en-us/7.%20plugins/4.%20i18n.md

I'll review and merge afterwards. Just ping me on the PR.

**Comment by feO2x** [comment]
Sure - I will get to it in the upcoming days.

**Comment by Sayan751** [comment]
I am closing this issue, as it seems to be resolved. Please feel free to continue the discussion.
