### ISSUE TITLE
Break the internationalization.md docs into sub-articles

### ISSUE THREAD

**Issue by Seebiscuit** [aurelia/aurelia#1111]
The internationalization.md doc is lengthy and could use better organization. I have two suggestions on that note:

1. The trivial use case of how to use internationalization in view-model comes very later in the article. This should be moved closer to the top. 
2. Date formatting should be split out into its own article.

Ideally, we'd split the document up into an 1) Intro with quick instructions on getting started 2) Translation usage in depth and advanced cases and 3) Date formatting. This implies a bit of a reworking of the translation usage which, IMO, does not clarify some fundamentals (least clear is the `t` attribute usage, and how locale file should be formatted, or at least where to look for that information).

**Comment by Sayan751** [comment]
Thank you for working on the i18n docs! I wrote those long back, and never revisited :P 
Feel free to restructure that.

**Comment by Vheissu** [comment]
Work on internationalisation efforts has been done, and the sections are clearer in their use.
