### ISSUE TITLE
view-model.ref leaks from the custom element boundary

### ISSUE THREAD

**Issue by MaximBalaganskiy** [aurelia/aurelia#1113]
# 🐛 Bug Report
Consider the following parent element
```html
<template>
  <au-slotted-element>
    <child view-model.ref="child"></child>
  </au-slotted-element>
</template>
```
and the following usage
```html
<parent>Parent 1</parent>
<parent>Parent 2</parent>
```

## 🤔 Expected Behavior

`view-model.ref` should grab the correct value

## 😯 Current Behavior

The first parent's view model will have an incorrect child reference, pointing to the second parent's child.

## 🔦 Context

MDC text fields have quite complex hierarchy with slotted elements and floating labels residing in these elements.

## 💻 Code Sample

https://gist.dumber.app/?gist=727aed61d5d505773d9d82f33d8fb631

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | 0.10.0-dev.202102110248
| Language         | Typescript
| Browser          | Chrome
| Bundler          | Webpack
| Operating System | Windows 10
| NPM/Node   | 7/15

**Comment by bigopon** [comment]
Thanks for this issue. I should fix the scope traversal. Unless you @fkleuver want to fix it

**Comment by fkleuver** [comment]
Go ahead, just ping @Sayan751 as well since he's also been involved in that quite heavily. You two probably understand the scope traversal better than I at this point :)

**Comment by Sayan751** [comment]
The issue looks bit odd, even without view-model.ref https://gist.dumber.app/?gist=ea667dba68e90f1dc7499f91de32210e

**Comment by MaximBalaganskiy** [comment]
probably related https://gist.dumber.app/?gist=903741f3acf8f082e5706618b0cf2b4e

The `ref` captures the reference to the child's container
