### ISSUE TITLE
repeat.for context is not available in au-slot

### ISSUE THREAD

**Issue by MaximBalaganskiy** [aurelia/aurelia#1114]
# 🐛 Bug Report

Using `repeat.for` with an au-slotted element does not render the iterated value

## 🤔 Expected Behavior

Should render regardless of slots

## 😯 Current Behavior

Using `repeat.for` with an au-slotted element does not render the iterated value.
The repeat context is probably not available inside the slot.

## 💻 Code Sample

https://gist.dumber.app/?gist=c2aa7a79faf2a940cfc97eb228e43cff

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | 0.10.0-dev.202102151925

**Comment by bigopon** [comment]
@MaximBalaganskiy thanks for this issue.
@Sayan751 this is probably caused by the misalignment between compile time & runtime scope. I'll fix it together with the other scope issue.

**Comment by Sayan751** [comment]
Generally speaking, dynamic projections with `*[template-controller] > *[au-slot]` is not supported. But that example is an interesting one. I don't think there is any misalignment so to speak. IMO it is not (yet) supported.
