### ISSUE TITLE
Element enhancing guide

### ISSUE THREAD

**Issue by MaximBalaganskiy** [aurelia/aurelia#1117]
Would be great to have a guide on how to dynamically enhance elements.
In Au1 we had `TemplatingEngine.enhance`. I managed to hack together some code which kind of works
```ts
    const renderPlan = createElement(this.platform, MdcDialog, props);
    const sv = renderPlan.createView(this.container);
    const dialogEl = sv.children![0].host!;
    sv.activate(sv, this.appRoot.controller, LifecycleFlags.none, Scope.create(bindingContext));
    document.body.appendChild(dialogEl);
```
In my opinion, this is too verbose and unreliable. 
On top of that, passing `props` to set element attributes fails, see https://gist.dumber.app/?gist=29f1d7ef8a1d002261dd1d93e0973183

As a part of the guide, would be also great to demonstrate how to project another element into the enhanced element `au-slot`.
This is a must have feature for MDC bridge or Aurelia UX dialogs.

**Comment by swalters** [comment]
I've used the following in ag-grid-aurelia to dynamically create dom elements that ag-grid can consume.  It would be great to see some examples of doing this in Aurelia2

```
public createEditorFromTemplate(container: Container, viewFactory: ViewFactory): {new(): ICellEditorComp} {

        class CellEditor implements ICellEditorComp {
            private view: View;
            private editorVm: IAureliaEditorViewModel;

            init(params: any): void {
                let bindingContext = {params: params};
                this.view = viewFactory.create(container);
                this.view.bind(bindingContext);

                let controllers: any[] = (<any> this.view).controllers;

                //only one controller is allowed in editor template
                if (controllers &&
                    controllers.length == 1 &&
                    controllers[0].viewModel) {
                    this.editorVm = controllers[0].viewModel;
                    //must reset params or it will be nothing
                    this.editorVm.params = params;
                }
                else {
                    console.error('The editor template component is missing an IEditorViewModel or it contains more than one component');
                }
            }

            public afterGuiAttached() {
                this.view.attached();
            }

            public getGui(): HTMLElement {
                return this.view.fragment as HTMLElement;
            }

            destroy() {
                if (this.editorVm.destroy) {
                    this.editorVm.destroy();
                }
                this.view.returnToCache();
            }

            getValue(): any {
                return this.editorVm.getValue();
            }
        }

        return CellEditor;
    }
```

**Comment by Sayan751** [comment]
The `enhance` API is already there. Here is the link to the docs: https://docs.aurelia.io/app-basics/app-configuration-and-startup#enhance.

Does that suffice?

**Comment by MaximBalaganskiy** [comment]
No, that enhance is to start a full fledged app. The issue is about a direct analogue of the au1 templating engine enhance.

**Comment by Sayan751** [comment]
Both serve the same purpose of enhancing a DOM root node. Do you see any particular shortcoming with the Au2 enhance API?

**Comment by swalters** [comment]
For my purposes of rendering cells in a grid, I do not think enhance will perform well enough.

**Comment by MaximBalaganskiy** [comment]
Think of ag-grid, for example, which creates cell content on the fly, or UX dialog, or mdc dialog, which crate dynamic dialogs. You wouldn want to start a new app with empty DI for every cell or a dialog.

**Comment by Sayan751** [comment]
Enhancing from an existing container is not yet supported to keep things bit simpler. At this point, the required registration needs to be done again for the root container for enhance. However, at least inheriting the "safe" registrations from the root container is undoubtedly desirable. That way the usage will get simpler.

However, I would like reiterate that ideally even in case of enhancing DOM fragments, the easiest way (considering at some later stage the container registration is made simpler) would be to use the `au.enhance` way, as it provides you with the complete pipeline of template compilation, activation, data binding, change handling, deactivation etc.

**Comment by MaximBalaganskiy** [comment]
Regardless of the implementation specifics, I think everyone agrees that there needs to be feature parity if you want plugin developers to quickly adopt au2.
