### ISSUE TITLE
Use plugin-requirejs in the jit-aurelia-cli example

### ISSUE THREAD

**Issue by fkleuver** [aurelia/aurelia#112]
Use plugin-requirejs in the jit-aurelia-cli example so we can do `import * as view from 'view!./app.html'` and `@customElement(view)` instead of the current (verbose) code.
I'm not sure how to accomplish this. Since @EisenbergEffect knows the plugin and @huochunpeng knows the current cli better, could you two chime in on how this should work?

**Comment by EisenbergEffect** [comment]
I got it to work with the current CLI in our earlier repo...but I confess I forgot if I did anything special ;( It would be a bit different now that we have real packages though. I think we need to configure the view plugin in the config file.

**Comment by fkleuver** [comment]
It was mostly just complaining about not finding the plugin / file. Must be some small silly thing that I used the wrong path or file or something. It errors during page load (not during tracing)

**Comment by huochunpeng** [comment]
The plugin works with current cli because amodro-trace uses requirejs runtime to trace, if you feed the plugin module to requirejs, it uses to rewrite the loading module.

But auto-trace cli doesn't use requirejs runtime to trace, then we need to replicate the plugin functionality in `aurelia-cli/lib/build/loader-plugin.js` to handle it at bundling time.

**Comment by huochunpeng** [comment]
@EisenbergEffect The view plugin generates a very predicable templateSource. I talked with @fkleuver, why not we just enhance `@customElment` api to fill up the gap of templateSource?

**Comment by huochunpeng** [comment]
No problem, we can bake this into auto-trace cli in future. I guess there will be equivalent plugins for parcel and webpack?

I don't think browserify allows you to do that, so browserify can only support inline view template.

**Comment by EisenbergEffect** [comment]
Yes, I was thinking we'd build plugins like this for each loader. It's a bit of work to support several of them but I think it's better for the framework if we keep that out of the core and instead delegate it to the bundlers/loaders.

**Comment by huochunpeng** [comment]
This also means any vNext plugin should be only allowed to build with AOT (or only inline view in jit) to avoid bundler dependency.

**Comment by EisenbergEffect** [comment]
Closing this as no longer relevant.
