### ISSUE TITLE
two-way binding on web component does not work

### ISSUE THREAD

**Issue by bravius** [aurelia/aurelia#1121]
# 🐛 Bug Report

Two-way binding on a web component does not work.

## 🤔 Expected Behavior

Should bind and update both ways. 

## 😯 Current Behavior

Web component shows initial value from model, but does not update either way.

Sometimes throws the following error:

```
Uncaught (in promise) Error: Trying to set value for property value in dirty checker
    at DirtyCheckProperty.setValue (dirty-checker.js:102)
    at PropertyBinding.updateTarget (property-binding.js:31)
    at PropertyBinding.$bind (property-binding.js:115)
    at Controller.bind (controller.js:408)
    at Controller.activate (controller.js:399)
    at ComponentAgent.activate (component-agent.js:38)
    at viewport-agent.js:437
    at Transition.run (router.js:228)
    at viewport-agent.js:435
    at Batch.invoke (util.js:32)
```
## 💁 Possible Solution

A workaround is to use change.trigger or delegate to update the model manually.

## 🔦 Context

Using latest aurelia@dev.

## 💻 Code Sample

```
<mwc-textfield type="text" value.two-way="value"></mwc-textfield>
```

Gist demonstrates two-way binding working with standard input element, but not with web component: 

https://gist.dumber.app/?gist=36a75d20edfbf55f92a99f4993df8e2f

Web component used for test:

https://github.com/material-components/material-components-web-components

**Comment by bigopon** [comment]
Thanks for the issue. We have documentation on how to integrate with any web components, or html elements generally using events here https://docs.aurelia.io/getting-started/observation#html-observation.

Updated gist: https://gist.dumber.app/?gist=e7d0ce4cebe02e4f5982b15b10d7ab03

Examples of how to integrate with:
- MS FAST https://docs.aurelia.io/examples/integration/ms-fast
- Ionic https://docs.aurelia.io/examples/integration/ionic

**Comment by bigopon** [comment]
@bravius the documentation fails to articulate something in easy to understand way, please help send PR to improve it.

**Comment by bravius** [comment]
Thanks for the update, I guess I just misunderstood how it's supposed to work. 

Think I can figure things out from the integration examples.

If I can help you with some mwc documentation, I will give it a go.
