### ISSUE TITLE
useUrlFragmentHash: true breaks the app

### ISSUE THREAD

**Issue by MaximBalaganskiy** [aurelia/aurelia#1122]
# 🐛 Bug Report

Setting `useUrlFragmentHash: true` breaks the app made by `npx makes aurelia` with direct routing

## 🤔 Expected Behavior

Url's contain hashes

## 😯 Current Behavior

Clicking on links does not navigate

## 💻 Code Sample

`npx makes aurelia`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | 0.10.0-dev.202102212309

**Comment by bigopon** [comment]
This has been fixed
