### ISSUE TITLE
Fallback does not work for explicit routing configuration.

### ISSUE THREAD

**Issue by danfma** [aurelia/aurelia#1129]
# 🐛 Bug Report

Last night the routing fallback was fixed for direct routing. However, it's not working yet for explicitly configured routing.

## 🤔 Expected Behavior

No matter if the application is configured directly or explicitly, it should obey and render the fallback route, when a route is not matched.

## 😯 Current Behavior

The fallback is not been shown. Also, when you get a routing error, the application breaks and it stops answering to any user interaction.

![image](https://user-images.githubusercontent.com/101121/110242366-83ba8c80-7f34-11eb-8e3f-fc0d3c3ee5cc.png)

## 🔦 Context

I was playing with Aurelia and then I tried to configure a different path to a route using the explicit configuration.

## 💻 Code Sample

my-app.html

```html
<nav>
  <a load="route:welcome">Home</a>
  <a load="route:about">About</a>
  <a load="route:xyz">Broken</a>
  <a load="route:login">Login</a>
</nav>

<au-viewport default="welcome" fallback="missing"></au-viewport>
```

my-app.ts

```typescript
import { IRouteViewModel, route } from "aurelia";
import { WelcomePage } from "./welcome-page"
import { Login } from './accounts/login'
import { MissingPage } from "./missing-page"
import { AboutPage } from "./about-page"

@route({
  routes: [
    { id: "welcome", path: "welcome", component: WelcomePage },
    { id: "about", path: "about", component: AboutPage },
    { id: "login", path: "accounts/login", component: Login },
    { id: "missing", path: "missing", component: MissingPage },
  ],
})
export class MyApp implements IRouteViewModel {
}

```

Then, I've tried the route `http://localhost:9000/xyz`.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | 2.0.1-dev.202103070436 |
| Language         | Portuguese |
| Browser          | Chrome/Edge latest/Firefox |
| Bundler          | Webpack |
| Operating System | Windows 10 |
| NPM/Node/Yarn    | Node (14.15), Pnpm (5.18) |

**Comment by fkleuver** [comment]
Thanks for the bug report, will fix this the coming week.

Note that it does work when only the fallback is in direct routing mode (as in, you can still use some configured routes). So you could work around this with a small tweak until it's fixed:
```ts
@route({
  routes: [
    { id: "welcome", path: "welcome", component: WelcomePage },
    { id: "about", path: "about", component: AboutPage },
    { id: "login", path: "accounts/login", component: Login },
  ],
})
export class MyApp implements IRouteViewModel {
  static dependencies = [MissingPage];
}
```

```html
<au-viewport default="welcome" fallback="missing-page"></au-viewport>
```

**Comment by Vheissu** [comment]
This has been fixed and works in both routers. Closing.
