### ISSUE TITLE
API doc -> DI -> _emptyParameters  link shows 404, Oops!

### ISSUE THREAD

**Issue by pfurbacher** [aurelia/aurelia#1141]
Clicking on [_emptyParameters](https://aurelia.io/docs/api/dependency-injection/constant/_emptyParameters) on the [aurelia-dependency-injection](https://aurelia.io/docs/api/dependency-injection) page results in a "404: Oops! Something's missing." response.

**Comment by bigopon** [comment]
@pfurbacher thanks for notifying this. It seems like something internal that got accidentally published. We probably can remove it.
