### ISSUE TITLE
New Direct Routing feature used from nested components fails to resolve view port

### ISSUE THREAD

**Issue by atSridharIyer** [aurelia/aurelia#1143]
# 🐛 Bug Report

Direct route loads like **_<a load="welcome-page">Welcome</a>_** works at the top app level. But not at a nested component level.

## 🤔 Expected Behavior

Route loading should work at all levels. It should use the default port defined at app level.

## 😯 Current Behavior

We get the following error:

route-context.js?9e99:287 Uncaught (in promise) Error: Failed to resolve VR(viewport:'',component:'welcome-page',resolution:'dynamic',append:false) at:
RC(path:'my-app',viewports:[VPA(state:currIsActive|nextIsScheduled,plan:'none',resolution:'dynamic',n:RN(ctx:'my-app/welcome-page',c:'welcome-page'),c:RN(ctx:'my-app/welcome-page',c:'welcome-page'),viewport:VP(ctx:'my-app',name:'default',default:'welcome-page',fallback:'missing-page'))])
 RC(path:'my-app/welcome-page',viewports:[])
    at RouteContext.resolveViewportAgent (route-context.js?9e99:287)
    at createDirectNode (route-tree.js?cac5:567)
    at createNode (route-tree.js?cac5:414)
    at createAndAppendNodes (route-tree.js?cac5:353)
    at eval (route-tree.js?cac5:283)
    at Array.map (<anonymous>)
    at eval (route-tree.js?cac5:282)
    at onResolve (functions.js?0404:437)
    at updateNode (route-tree.js?cac5:278)
    at eval (route-tree.js?cac5:296)

## 💻 Code Sample

Attached
[direct-routing-test.zip](https://github.com/aurelia/aurelia/files/6223620/direct-routing-test.zip)

## 🌍 Your Environment

Create project using npx makes aurelia. 
So Aurelia 2 latest. Same problem in dev version also.

**Comment by fkleuver** [comment]
You're telling the router to load `"welcome-page/welcome-page"` which would only work if `welcome-page` itself had a viewport, which it doesn't.

If you want to change the component in the containing viewport from within the current component that's loaded within that viewport, you need to navigate one level up relatively. You should use `href` in that case as well.

So try changing this:
```html
<nav>
  <a load="welcome-page">Welcome</a>
  <a load="about-page">About</a>
</nav>
```

To this:
```html
<nav>
  <a href="../welcome-page">Welcome</a>
  <a href="../about-page">About</a>
</nav>
```

Or, if you don't want a nesting-aware anchor and simply always go to the root (which in this case would have the same effect):
```html
<nav>
  <a href="/welcome-page">Welcome</a>
  <a href="/about-page">About</a>
</nav>
```

The CLI generated example / docs are lagging behind a bit w.r.t. routing, apologies for that. The exact goal with direct routing is unclear at the moment. For a more stable / reliable alpha experience I'd strongly recommend sticking to configured routing for now:
https://docs.aurelia.io/routing/configured-routing

**Comment by atSridharIyer** [comment]
Just experimenting. Not using this for any important project. I will continue experimenting with this.  Closing this issue for now.
