### ISSUE TITLE
add override option for `debounce` and `throttle`

### ISSUE THREAD

**Issue by avrahamcool** [aurelia/aurelia#1145]
[the example references `debounce` - but everything is true for `throttle` as well]

consider the following scenario:

a search input, that is bounded to some property in the VM.

typing into the input need to initiate some kind of search from the backend in "real time".
hitting "Enter" in this same input initiate another method that also need the value of the input.

we typically don't want to initiate the search immediately after each keystroke, so we actually use the `debounce` binding behavior (`bb` from now on).
this will cause the binding to refresh the VM only after some amount of time has passed without the user typing anything new.
barely visible to the human eye - but helps a lot with performance.

but now we have a problem: if a user types really fast and hits "Enter" - before the binding had a chance to update the value.
the value of the input in the VM is still `undefined` (or whatever the last old value was) instead of the "real" text the user typed.

we need to allow some kind of override for the `debounce` bb, that will flush the value immediately.
for AU1, I've created a copy of the `debounce` bb, that "flushes" the value whenever "Enter" was pressed.
and I was thinking of making the same fix for AU2.

but this time, I think this should be baked in original bb itself (and controlled via some kind of smart option), instead of being another copy and almost similar bb.

# 🙋 Feature Request
enable some sort of override for `debounce` and `throttle` binding behaviors - that will flush the value immidiattly.

## 🤔 Expected Behavior

* default: default timeout. no overrides.
```<input value.bind="myValue & debounce" >```

* provided timeout. no overrides.
```<input value.bind="myValue & debounce:200" >```

* provided timeout. with one override.
```<input value.bind="myValue & debounce:200:'Enter'" >```

* provided timeout. with more overrides.
```<input value.bind="myValue & debounce:200:'Enter':'Space'" >```

this is not a good syntax. I would love to hear other thoughts and ideas regarding this.

**EDIT: new syntax based on @zewa666 comments.**

* default: default delay. no flush overrides.
```<input value.bind="myValue & debounce" >```

* provided delay. no fulsh overrides.
```<input value.bind="myValue & debounce:200" >```

* default delay. with a single flush override.
```<input value.bind="myValue & debounce:'Enter'" >```

* default delay. with an array of flush overrides.
```<input value.bind="myValue & debounce:['Enter', 'Space']" >```

* complex option. (where you can specify delay, overrides (single or array), and more if needed..)
```<input value.bind="myValue & debounce:{delay: 200, flushOn: 'Enter'}" >```
```<input value.bind="myValue & debounce:{delay: 200, flushOn: ['Enter', 'Space']}" >```
```<input value.bind="myValue & debounce:{flushOn: ['Enter', 'Space']}" >```
```<input value.bind="myValue & debounce:{delay: 200}" >```
etc..

## 😯 Current Behavior
there is no way to express this kind of behavior.

## 💁 Possible Solution

1. reading the value from the DOM instead of the binding if we want to be sure to have the "latest" value.
2. waiting the amount of time specified by the `debounce` before each operation regarding the value. (not really a solution: because the user might keep on typing - further delaying the binding flush)

**Comment by zewa666** [comment]
I like this idea. How about though accepting still one param. If number, treat it like delay timeout. If object then it could have a `delay` and e.g `flushOn: ("space" | "enter")[]`? That way we'd stay flexible for potential future options

**Comment by avrahamcool** [comment]
sounds very good.

for the values I wanted to use values from the list of keys that are available in [`key` event.](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values)
do you think there is a more generic way of expressing overrides, or `key` names are enough?

**Comment by zewa666** [comment]
Yeah perfect standards-conform approach with the key event. I think this should be totally fine

**Comment by bigopon** [comment]
Will manually flushing be a good option? Different with v1, our binding behaviors like `throttle` & `debounce` now use a task queue to deal with timing & invocation: https://github.com/aurelia/aurelia/blob/b270d9d04843702d2d2b6771f4997337b0886273/packages/runtime-html/src/binding-behaviors/debounce.ts#L26

This means if the `.flush()` is called on that same task queue, the debounced change is gonna be flushed.
It can be done like this:

```html
<form sumit.trigger="updateAndSubmit()">
```
```ts
export class MyForm {
  static inject = [IPlatform];
  updateAndSubmit() {
    this.platform.taskQueue.flush();
    // all values updated here
    // send request
  }
}
```

**Comment by avrahamcool** [comment]
@bigopon that will work. but it will also have many other side effects too. (other stuff that need to wait, will be flushed)
can we flush a specific task instead?

also: you don't think this is a good candidate as an optional option to the bb?

**Comment by bigopon** [comment]
> can we flush a specific task instead?

This may or may not be doable at the moment. At least it's not tested because it's not how it's intended to be used.

> also: you don't think this is a good candidate as an optional option to the bb?

I was mostly trying to exhaust the existing capabilities & primitives. I think we can afford to add it, and PRs are certainly very welcomed. For the syntaxes part, I think we may need to be careful starting with a too wide range of inputs. Maybe let's stick to the verbose but extensible object form?

**Comment by avrahamcool** [comment]
> For the syntaxes part, I think we may need to be careful starting with a too wide range of inputs. Maybe let's stick to the verbose but extensible object form?

Ok.
so those are the only valid form of usage?

```html
<input value.bind="myValue & debounce" >
<input value.bind="myValue & debounce:200" >
<input value.bind="myValue & debounce:{delay: 200, flushOn: ['Enter', 'Space']}" >
<input value.bind="myValue & debounce:options" > // where `options` is an object in the VM.
```

**Comment by bigopon** [comment]
Yes I think that looks good

**Comment by Alexander-Taran** [comment]
I don't like the idea of debounce knowing anything about events or dom. I looked @ the source of debounce in v2 and it purely delays value change. So it operates only on value and both ways. So if value is changed in vm it'll also delay the update of UI. Am I right?

so there was a triggerUpdate as well.

but we want their child in here..
So we could fork the updates from view based on the event and it's arguments

What about `mousemove.delegate="boo() & debounce:{delay: 200, flushOn: ['Enter', 'Space']}"` eh?

**Comment by nenadvicentic** [comment]
My feeling is that this is overcomplication of `debounce` and would probably overcomplicated implementation as well.

What if I also need to flush `debounce` on a button click? Or, I'm expecting `Enter` to triggers button click on the form with multiple input fields, all flushed? Should  `propertyChanged` method be able to detect if it was called after normal `debounce` or after flush? What if my debounce time is much longer and I end up needing to flush 2 input field values?

To me something about this proposed feature smells pretty bad.

**Comment by avrahamcool** [comment]
> Specifying an event name to flush debounce/throttle may not be always appropriate, as view model parent child can also be throttled/debounced. Also, if we are throttling `updateTarget`/`updateSource`, there's no access to the event triggering the delayed update. Maybe we can combine with signals instead:
> 
> ```
> <input
>   value.bind="myValue & debounce:{delay: 200, flushOn: ['Enter-signal']}"
>   keydown.trigger="if key== enter then signal 'Enter signal'">
>   // pseudo code the line above
> ```

that should sufice.
