### ISSUE TITLE
delay parameter of `debounce` binding behavior is not bounded

### ISSUE THREAD

**Issue by avrahamcool** [aurelia/aurelia#1146]
# 🐛 Bug Report

the `delay` parameter that is provided to the binding behavior is evaluated only once.

the same bug occurs in AU1. (should I open a separate report for that?)

```<input value.bind="value & debounce:delay">```
changing the value of `delay` later on does not affect the `debounce`.

## 🤔 Expected Behavior
parameter should be bound (just like everything else in AU).
so changes in the parameter - need to update the delay time for typing that come afterwards.

## 😯 Current Behavior
the `delay` parameter that is provided to the binding behavior is evaluated only once.

## 💁 Possible Solution
react to changes on the parameter.

## 💻 Code Sample

**App.ts**
```typescript
export class App
{
  public value = "abc";
  public delay = 1000;
}
```
**App.html**
```html 
<input value.bind="value & debounce:delay">
<button click.delegate="delay = 5000 - delay">switch delay</button>
```

**Comment by bigopon** [comment]
It's intentional in v1 that we don't observe for changes for binding behavior parameters. I'm not sure the original motivation why, I'll search for it.

**Comment by bigopon** [comment]
A question I have is binding behavior are supposed to tape into the `bind`/`unbind` phases via `bind()`/`unbind` methods. If we are to observe, what method of the binding behavior should b invoked when there' changes in the dependencies?

**Comment by Alexander-Taran** [comment]
implementing this will lead to : "while waiting for debounce to happen, I changed the delay.. and it did not update the timer "

**Comment by Vheissu** [comment]
We have established this is related to v2 behaviour that is intended. I am closing this.

**Comment by bigopon** [comment]
@avrahamcool do you have a use case for this?

**Comment by avrahamcool** [comment]
I was fiddeling at the time with a admin panel where you could set all the variables that you wanted from inputs in the page and observe how the output behaviour reacted accordingly..
and I noticed that teaking the `delay` parameter wasn't working..

I don't think that I have a real-life scenario that actually need this feature.
and I agree with @Alexander-Taran comment, a feature like that will be very confusing.

I'm okay with closing this issue.
keep up the good work :)

**Comment by bigopon** [comment]
@avrahamcool thanks for the info. This can easily be supported, just it's the matter of should. And probably we can let it rest, I cant picture a good use case for this either.
