### ISSUE TITLE
working-with-form-elements needs section on handling "submit"

### ISSUE THREAD

**Issue by akircher** [aurelia/aurelia#1155]
Please add a section to "working-with-form-elements" on handling "submit".  Is best practice to put it on the `<form>` element?  On the `<button>` element?  Use `trigger` or `delegate`?

Because of the lacking documentation, I just caught a developer trying to use `onClick.bind`!

**Comment by bigopon** [comment]
Sounds like a very nice suggestion! Any interest in having a PR 👍 ?

**Comment by arjendeblok** [comment]
I think what misses is a **button** section. So how about handling a button on a form. And reference to the handling events part.

I personally use just event bindings on buttons themselves, but I do not know if there is also a case for putting an event binding on the form itself.
