### ISSUE TITLE
Aurelia is hijacking external links

### ISSUE THREAD

**Issue by wesfolz** [aurelia/aurelia#1158]
# 🐛 Bug Report

When using Aurelia without a build step external links are being hijacked by the router causing an exception to be thrown and preventing the link from being opened.

## 🤔 Expected Behavior

The router should ignore external links.

## 😯 Current Behavior

When an external link is clicked this exception is thrown:
```
route-expression.ts:56 Uncaught Error: Expected component name at index 7 of 'https://thinkster.io', but got: '/thinkster.io' (rest='/thinkster.io')
    at ParserState.expect (route-expression.ts:56)
    at Function.parse (route-expression.ts:523)
    at Function.parse (route-expression.ts:429)
    at Function.parse (route-expression.ts:398)
    at Function.parse (route-expression.ts:318)
    at Function.parse (route-expression.ts:321)
    at Function.parse (route-expression.ts:252)
    at Function.$parse (route-expression.ts:190)
    at Function.parse (route-expression.ts:130)
    at Function.create (instructions.ts:298)
```
I'm having to do something like this as a workaround:
```
<a click.trigger="clickLink()">Link</a>

export class ExternalLink {
  link = "https://thinkster.io";
  clickLink = () => window.open(this.link);
}
```

## 💻 Code Sample

Clicking the Thinkster link causes the above exception.
https://github.com/aurelia/aurelia/blob/f0095fdd7aff5cb86a383b00a9bf5e45b9a42330/examples/realworld-vanilla/index.html#L444

**Comment by bigopon** [comment]
@wesfolz thanks for the bug report.

A workaround that can be employed for now is to use `click.capture`:
```html
<a click.capture="goExternal(href)">
```
```ts
class {
  goExternal(link) {
    location.href = link
    // or
    // api https://developer.mozilla.org/en-US/docs/Web/API/Window/open
    window.open(link, '', 'noreferrer')
  }
}
```

**Comment by fkleuver** [comment]
Did you add the `external` attribute to the anchor?

**Comment by wesfolz** [comment]
> Did you add the `external` attribute to the anchor?

@fkleuver If the href is hardcoded, adding external fixes the issue, but if I bind the href attribute to a variable then the href attribute is not being set when the external attribute is present.
e.g. 
this works: `<a href="https://google.com" external>`
href attribute is missing during runtime: `<a href.bind="link" external>`
href attribute is present but link gets hijacked: `<a href.bind="link">`

**Comment by Vheissu** [comment]
@bigopon I am seeing this issue in one of my applications, I'm not sure if there was a regression or not, but it's the same issue. In my case, `href` disappears if I have `target="_blank"`
