### ISSUE TITLE
Missing query string parameters in load(params) and canLoad(params)

### ISSUE THREAD

**Issue by hanssens** [aurelia/aurelia#1160]
# 🐛 Bug Report

In the latest Aurelia 2.x any query string parameters can not be read out anymore from the `params` parameter in the component/page lifecycle.

It has been briefly [discussed on the Aurelia Discord channel](https://discord.com/channels/448698263508615178/605165485876707328/834415267198533633).

## 🤔 Expected Behavior

The `params` parameter in either `canLoad()` or `load()`, resp. through `lifecycleHooks()` and `IRouteViewModel` should contain query string parameters, if provided. Like when navigating to a url containing `?id=12345&foo=bar`.

## 😯 Current Behavior

The `params` object does not appear to have query/url parameter data embedded. 

## 💁 Possible Solution

Unknown. But current workaround is to ignore Aurelia and extract any query string parameters through vanilla Javascript, like so:

```    
    getQueryParam(name: string) {
        const params = new URLSearchParams(window.location.search);
        return params.get(name);
    }
```

## 🔦 Context

It is required to read these parameters for handling page calls originated from external events. Meaning not originating from the aurelia router. Like a login-callback?code=abc&token=123. 

## 💻 Code Sample

* Create a new, empty Aurelia app using `npx makes aurelia`
* Enable Routing, TypeScript, Webpack and NPM. Discard tests and css processing
* Add class `example.ts` as shown below
* Run the project and navigate to for example navigate to: http://localhost:9000/example?id=12345

```
// EXAMPLE.TS
import { lifecycleHooks } from "aurelia";

@lifecycleHooks()
export class Example {

    constructor() {
        console.log('Example.constructor()');
    }

    canLoad(params, next, current): boolean {
        console.log('Example.canLoad()', params);
        // [PROBLEM] Expect 'params' here to contain id=12345
        return true;
    }

    load(params, next, current) {
        console.log('Example.load()', params);
        // [PROBLEM] Expect 'params' here to contain id=12345
    }
}

```

![CleanShot_2021-04-21_at_15 45 30](https://user-images.githubusercontent.com/493382/115953516-3a29ff00-a4ec-11eb-9732-c47d73f354c3.png)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | "lastest" and "dev" (as of  — 04/22/2021)
| Language         | English
| Browser          | All
| Bundler          | Webpack
| Operating System | macOS
| NPM/Node/Yarn    | NPM

**Comment by bigopon** [comment]
On the first glance, it seems the usage of `Example` is incorrect. The first parameter of a `@lifecyclehooks` is a vm, so I think you should have had this:
```ts
// EXAMPLE.TS
import { lifecycleHooks } from "aurelia";

@lifecycleHooks()
export class Example {

    constructor() {
        console.log('Example.constructor()');
    }

    canLoad(vm, params, next, current): boolean {
        console.log('Example.canLoad()', params);
        // [PROBLEM] Expect 'params' here to contain id=12345
        return true;
    }

    load(vm, params, next, current) {
        console.log('Example.load()', params);
        // [PROBLEM] Expect 'params' here to contain id=12345
    }
}
```
Can you try this?

**Comment by hanssens** [comment]
Ugh... You're absolutely right @bigopon. Stupid on me, that was it! 

I guess I got confused by the signature at the [bottom of the lifecycleHooks docs](https://docs.aurelia.io/routing/lifecycle-hooks) which (assumingly) which only applies to IRouteViewModel. And doesn't appear to have vm as parameter.
