### ISSUE TITLE
Template binding does not recompute when its @computedFrom("foo", "bar") dependencies change sometimes when number of bindings to connect becomes large enough to spill to the ConnectQueue's deferred handling threshold (100)

### ISSUE THREAD

**Issue by alankila** [aurelia/aurelia#1162]
# 🐛 Bug Report

I have a HTML table component that works a lot like your run of the mill datatable, basically something like `console.table(array_of_objects)` but with flexible column setup, search feature, and paging. The search is implemented by iterating over all fields of the table and having a `<input type="text" value.bind="search[field.key]"/>` type of solution, where the `search` is just a JS object. I use `BindingEngine` to attach property observers to each of the fields in `search` and they fire the event that recalculates the datatable's rows by a signal. (As there can be multiple tables per view, the signal's name is generated to be unique to each table instance, and I call it `searchEvent`.)

So the main loop of the table's template looks something like this, with some elements elided for simplicity:

```html
    <tr>
      <td repeat.for="field of fields" click.delegate="setSort(field.key)" class="${sort == field.key ? 'sorted' : ''} ${reverse ? 'reversed' : ''}">${field.header}</td>
    </tr>
    <tr>
      <td repeat.for="field of fields">
        <input if.bind="field.type != 'boolean'" type="text" value.bind="search[field.key] & debounce:200" placeholder="Filter…" />
        <span if.bind="field.type == 'boolean'">
          <label class="prewrapped"><input type="radio" value="" checked.bind="search[field.key]" /> <span t="common.both"></span></label><br/>
          <label class="prewrapped"><input type="radio" value="✓" checked.bind="search[field.key]" /> <span t="common.true"></span></label><br/>
          <label class="prewrapped"><input type="radio" value=" " checked.bind="search[field.key]" /> <span t="common.false"></span></label>
        </span>
      </td>
    </tr>
    <tr repeat.for="row of rows & signal: searchEvent">
       <td repeat.for="field of fields">${row[field.key]}</td>
    </tr>
```

The rows property itself is a `@computedFrom('data', 'page', 'sort', 'reverse') get rows() { ... }` type of deal, where the current page of the result set, the sorting property and direction, and the data to be displayed all affect the window that is paged into view.

## 🤔 Expected Behavior

The idea is that if user writes something into search field, that field filters the table's rows, and this is achieved by having the search object's keys observed manually via `BindingEngine`. If user clicks page numbers in the table's header, the `page` is written to, and `get rows()` is supposed to recompute. Similarly, if user clicks on the header columns, `sort` and `reverse` are similarly changed, and should cause the table to update.

## 😯 Current Behavior

Today, I ran into issue where adding 14th column to a datatable caused the sorting and paging to stop working. Search still worked correctly. To my further puzzlement, I also noticed that it didn't even matter which columns were present on the table, only that there were more than 13 columns. Some random changes to the table's implementation seemed to make things working again, but it was not clear why, and thus I pressed on...

## 💁 Possible Solution

I determined that the removing the `signal:` fixed the issue at cost of breaking my search function. As the problem seemed to be a bug in the bindings, I studied source code of the `aurelia-binding` package and noticed that there exists a connect queue with default value of 100 entries. I suspected that some such arbitrary limit was the issue, and upon testing, I was able to correct the issue for good by exporting `disableConnectQueue()` from `aurelia-binding` and executing that as part of my `main.ts` setup.

I was also able to determine that my example table with 14 columns broke when `connectQueueThreshold = 102` (or less). My 13 column case broke when `connectQueueThreshold = 96` (or less). Thus, I conjecture that this deferral is broken in my case.

Furthermore, the problem seems also to require signaling bindings during the `attached()` component lifecycle event. I was doing something like:

```typescript
    for (let field of this.fields) {
      search[field.key] = "";
      const disposable = this.engine.propertyObserver(this.search, field.key).subscribe(() => {
        this.signaler.signal(this.searchEvent);
      });
      this.searchObserver.push(disposable);
    }
```
But really, the actual point of the rube goldberg machine above is that I change the search somehow, which through template has property observing going and somehow all this causes the `searchEvent` to fire through that observer, despite I change the value before I have attached the listener. (My guess is that the template binding influences the behavior somehow.) However, I can reproduce the problem by just doing this instead of the above, during `attached()`:

```typescript
    this.signaler.signal(this.searchEvent);
```
and I can fix the problem at will by increasing the connect queue's length. Apparently, my table has enough bindings inside related to the search function that somehow 100+ connect queue entries get created -- whatever they are -- and that, then triggers the deferral to a later time, which somehow breaks the `@computedFrom` observation rather than simply connects it up later as expected.

## 🔦 Context

The problem for me is that users can't use my data table correctly, e.g. their ability to page the result set is harmed, even though they can manually trigger re-rendering by changing a search field and then clearing it again, which triggers the signal that re-renders the table.

I'm posting this issue here mostly to develop documentation that indicates that there seems to be something wrong with ConnectQueue.

## 💻 Code Sample

I am unable to provide a code sample at this time. The application exposing the problem is rather large, though it can probably be pared down to a reasonably minimal test case with some effort. I suspect that a trivial test case can be created by reducing `connectQueueThreshold` to very low value such as 0, and creating a template binding that refers both to a computed property and some signal, and triggering that signal during the `attached` hook, which should force the deferred handling that doesn't seem to work in this specific case.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | 2.0.2 
| Language         | TypeScript
| Browser          | Firefox 88
| Bundler          | Webpack
| Operating System | Ubuntu 21.04
| NPM/Node/Yarn    | 7.10.0

**Comment by bigopon** [comment]
I think we recently have had the same q related to the connect queue as well. I think the connect queue can be disabled without any issues. In v2, we no longer employ such technique, and on startup, everything is as synchronous as possible.
