### ISSUE TITLE
ISanitizer should not have an insecure default implementation

### ISSUE THREAD

**Issue by dabide** [aurelia/aurelia#1165]
# 💬 RFC
## 🔦
@MedAziz1 yesterday [pointed out on the Aurelia Discord](https://discourse.aurelia.io/t/xss-vulnerability-in-htmlsanitizer-might-be-insufficiently-handled/4219/2?u=dabide) that Aurelia 2 has the same vulnerability in its default HTML sanitizer implementation that Aurelia 1 has: https://github.com/aurelia/aurelia/blob/master/packages/runtime-html/src/resources/value-converters/sanitize.ts

`ISanitizer` should either not have a default implementation, or have a secure one. Otherwise, the default implementation will create a false sense of security, and many will unwittingly use it without knowing that it only supplies a very basic level of protection.

Putting a warning in the documentation won't necessarily help much, because it might have been introduced into the codebase by somebody else, and the developer is just following pattern, or they just found it in some search result.

**Comment by bigopon** [comment]
I guess that's the right way to do it. Any interest on creating a PR @dabide ? We can throw in the default resolver of the interface I think.

**Comment by dabide** [comment]
I'll give it a go, @bigopon.

**Comment by Bart76** [comment]
Nice to see this picked up. I only hope that not too much effort is put into this and that only "quick fixes" will be implemented here. There are already way more sophisticated HTML sanitizers out there, and IMHO there's no point in reinventing the wheel in that regard. The documentation has always clearly stated that the built-in HTML sanitizer is unsuited for production usage anyway.

IMHO, there are other (more pressing) issues in Aurelia's roadmap that should get priority.

**Comment by dabide** [comment]
I agree, my take is to make the interface unimplemented, and add some documentation.

**Comment by Alexander-Taran** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Sanitizer

Can feature detect and use when available.
Future proof few (-:

**Comment by bigopon** [comment]
Throw by default now.
