### ISSUE TITLE
repeat.for with child components that have slots produces unexpected behavior

### ISSUE THREAD

**Issue by michaelnero** [aurelia/aurelia#1167]
# 🐛 Bug Report

I have an instance where using `repeat.for` in combination with child components that have slots produces behavior that I don't expect. I'm able to work around it by cloning the component definition in `define`. Here's a gist that reproduces the issue:
https://gist.dumber.app/?gist=47b4b854b00d9dd87ab5ccd95fb655c9

## 🤔 Expected Behavior

The correct value should show for each item.

## 😯 Current Behavior

I don't see the correct value for each item.

## 💻 Code Sample

https://gist.dumber.app/?gist=47b4b854b00d9dd87ab5ccd95fb655c9

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | 2.0.0-alpha.3
| Language         | typescript
| Browser          | Edge 90.0.818.62
| Bundler          | webpack 5.37.1
| Operating System | Windows 10
| NPM/Node/Yarn    | npm

**Comment by bigopon** [comment]
@michaelnero thank you. I happened to be looking at this currently as well. Will fix and publish.

**Comment by bigopon** [comment]
The issue is related to context cache retrieval based on definition. There' two different `<listbox/>`, but both of them have the same static definition and thus got the same cached render context. A workaround is to either have a `define` lifecycle returning a different definition, or an injectable token. Will fix

**Comment by michaelnero** [comment]
That's what I was assuming was happening, so you can see in my gist that I attempted to "fix" it by doing exactly what you suggested. The `assignee-fix` custom element is returning the cloned definition, and gives me the expected behavior.

I don't know enough about the code base yet to suggest a fix, but happy to help out in any other way.

**Comment by bigopon** [comment]
@michaelnero the gist description and the repro helped heap, in the end, there will be another test based on the gist you provided here as well. The one I got above is based on another repro I got earlier. For the fix, I'm not sure about a fix direction yet, but will update.
