### ISSUE TITLE
String interpolation and to-view binding have behavior inconsistent with docs

### ISSUE THREAD

**Issue by michaelnero** [aurelia/aurelia#1168]
# 🐛 Bug Report

The docs state that string interpolation-based bindings are an alternative to the `to-view` binding, but the two have inconsistent behavior. If the docs should be updated because this behavior is intended, I'm happy to submit a PR to update the docs.

I'm also not sure if this is two bugs or one, so I'll try to be as clear as I can here.

An example is in this gist:
https://gist.dumber.app/?gist=c1f20770b87217102fb53541c43d8060

**Example 1**
For `<input>` elements, `undefined` values:
1) render the string "undefined" for attributes using `to-view` binding explicitly
2) render an empty string when using string interpolation, which is consistent with what the docs say

**Example 2**
For `a` elements, `undefined` values:
1) don't render the attribute at all for attributes using `to-view` binding explicitly
2) render an empty string when using string interpolation, which is consistent with what the docs say

Again, I may have misinterpreted the docs and string interpolation and the `to-view` binding aren't supposed to have the same behavior. But, I think I would expect that the #1's in the example above to be consistent across elements, which is why maybe this is two bugs, not one. For what it's worth, I prefer how the `to-view` binding behaves with `a` elements, in that it removes the attribute altogether rather than render the string "undefined".

## 🤔 Expected Behavior

1) For string interpolation and the `to-view` binding to behave consistently if string interpolation is an alternative for the `to-view` binding --**or**-- to update the docs. Either one is fine!
2) Definitely that the `to-view` binding should behave consistently across different elements.

## 😯 Current Behavior

Described above.

## 💻 Code Sample

https://gist.dumber.app/?gist=c1f20770b87217102fb53541c43d8060

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | 2.0.0-alpha.3
| Language         | typescript
| Browser          | Edge 90.0.818.62
| Bundler          | webpack 5.37.1
| Operating System | Windows 10
| NPM/Node/Yarn    | npm

**Comment by bigopon** [comment]
@michaelnero thank you very much for this observation. This inconsistent behavior is intended, but not 100%.

For interpolation bindings, the expressions of the [part bindings](https://github.com/aurelia/aurelia/blob/9897eda88aa5e76501e5e67d34d993379db22c4b/packages/runtime-html/src/binding/interpolation-binding.ts#L134) are evaluated in non-strict mode, which means undefined is coerced into `''`

For property binding, strict mode is on, and undefined is `undefined`.

The above doesn't explain why the `min.to-view="undefined"` results in `min="undefined"`, while `href.to-view="undefined"` results in `href=""`.

For the doc, any help is really welcomed.

**Comment by akircher** [comment]
An idea: Under the hood, it might be nice to have a "(non)strict-mode" binding behavior.  That way in the docs you could describe `${example}` as the equivalent to `value.bind="example & nonstrict".  This makes the differences more explicit and potentially reusable.

**Comment by bigopon** [comment]
@akircher thanks for the suggestion. This is currently done under `isStrictBinding` option on the custom element options. The reason for this inconsistency is because `href` is treated as an attribute, while `min` is as a property. Probably `href` should be treated as property too.

**Comment by bigopon** [comment]
I just had a check, `href`/`src` are the behavior from v1 we are keeping. A slight change is that now they are both attribute on any element, unlike v1, which are only on `<a>` & `<img>` respectively. Probably we should update the docs instead.

**Comment by Vheissu** [comment]
Closing this as the docs for interpolation and other syntax have long been updated.
