### ISSUE TITLE
Should build with node.js LTS

### ISSUE THREAD

**Issue by timfish** [aurelia/aurelia#1169]
With the latest node.js LTS (v14.17.0) I get the following if I run `npm run init`:

![image](https://user-images.githubusercontent.com/1150298/119367309-b8272480-bca9-11eb-9e69-0b1d1bccff41.png)

Ideally, Aurelia should build on the latest LTS. If it cannot be made to work,  `engines`  should be updated in `package.json`!

**Comment by bigopon** [comment]
Thanks for this issue. This is an error of npm version < 7. Please refer to contributing doc here for now https://docs.aurelia.io/community-contribution/building-and-testing-aurelia
