### ISSUE TITLE
Unable to inject host element for top-level components in au-viewport

### ISSUE THREAD

**Issue by michaelnero** [aurelia/aurelia#1171]
# 🐛 Bug Report

An error is thrown if you try to inject the host element via the constructor of a view model if the custom component is the top-level component of an `au-viewport`. You are, however, able to inject services you've registered and the host element for all other custom components further down the hierarchy.

I can't repro this in gist.dumber.app since it blows up if you try to use routing -- it doesn't look like it supports URL fallbacks -- but you can try this locally:

https://gist.dumber.app/?gist=ffa1104721943effa44dc1802caa7427

## 🤔 Expected Behavior

Either:
1) I shouldn't get an error in this scenario or
2) The docs should be updated to indicate that this scenario is not supported -- I can help with this!

## 😯 Current Behavior

The follow error is thrown:

```
Uncaught (in promise) Error: Cannot call resolve ElementResolver before calling prepare or after calling dispose.
    at InstanceProvider.resolve (di.js?69b2:1114)
    at Container.get (di.js?69b2:797)
    at Container.containerGetKey (di.js?69b2:505)
    at Array.map (<anonymous>)
    at Factory.construct (di.js?69b2:520)
    at Resolver.resolve (di.js?69b2:479)
    at Container.get (di.js?69b2:797)
    at RouteContext.createComponentAgent (route-context.js?925d:308)
    at eval (viewport-agent.js?2195:216)
    at Batch.invoke (util.js?3815:32)
```

## 🔦 Context

This isn't a blocker since the workaround is to wrap your component with another component.

## 💻 Code Sample

https://gist.dumber.app/?gist=ffa1104721943effa44dc1802caa7427

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | 2.0.0-alpha.3
| Language         | typescript
| Browser          | Edge 90.0.818.62
| Bundler          | webpack 5.37.1
| Operating System | Windows 10
| NPM/Node/Yarn    | npm

**Comment by jwx** [comment]
@michaelnero @bigopon This is working with `@aurelia/router` https://gist.dumber.app/?gist=23c70bf5a1d08ab44e0dca88a5cc9f17
