### ISSUE TITLE
[RFC] migrate our decorators to latest JS decorator spec

### ISSUE THREAD

**Issue by 3cp** [aurelia/aurelia#1180]
# 💬 RFC

## 🔦 Context

Our decorators are currently in outdated legacy decorator API format.

The result is we still need legacy mode when transpiling the code.

In Babel, it's `[ "@babel/plugin-proposal-decorators", { "legacy": true } ]`.

In TypeScript, it's just `"experimentalDecorators": true`. TypeScript understands our decorators are in legacy mode because it knows the type definition of those decorators, so it smartly transpiling the code accordingly.

We probably need to switch our decorators to the APIs of latest spec. https://github.com/tc39/proposal-decorators
Then we can drop `"legacy": true` in babel config. The babel config will become `[ "@babel/plugin-proposal-decorators", { "decoratorsBeforeExport": true } ]` (For usability, we need that decoratorsBeforeExport to deviate from current spec, TypeScript silently supports that).

**Comment by bigopon** [comment]
Unless this proposal gets to stage 4, I think we should stay far away from it. I don't know how many hops we have to get through along the ride for a stage 2 proposal, especially this decorator one.

**Comment by Vheissu** [comment]
I agree this is very important @3cp but I agree with @bigopon that right now given how turbulent the decorator's specification has been and the fact they've been trying to get decorators to stage 3 for three years now, we should stick with legacy. As we can see in [this linked section](https://github.com/tc39/proposal-decorators#how-should-i-use-decorators-in-transpilers-today) in the README, they are recommending that everyone sticks with the legacy decorators for the time being.

**Comment by 3cp** [comment]
The state of decorator is so bad, if they can put decorator into ES spec, a lot of framework can use plain ESM code without transpiling.
It's insane to argue about the decorator design for so many years. It feels like no end.

**Comment by Vheissu** [comment]
@bigopon @3cp Given the decorator proposal has reached stage 3, are we more confident with the new design and migrating over?

**Comment by bigopon** [comment]
it's a massive move, we probably want to delay it until the last moment. If we were to do it now, any small changes from now would cause a lot of headache.
