### ISSUE TITLE
Validation I18n Internationalization doesn't work

### ISSUE THREAD

**Issue by rzasinets** [aurelia/aurelia#1182]
# 🐛 Bug Report

Trying to utilize localization of validation errors, but it seems doesn't work. It doesn't respect any translations from either default ValidationI18nConfiguration namespace nor ValidationI18nConfiguration default namespace. Have tried:
- used out-of-the-box validation rules and custom ones;
- different combinations of message keys (both defined by validations rule and explicit `.withMessageKey()` method call)

Looks like it works correctly for dev version 0.7.0, but with latest 2.0.0-alpha.5 nothing happends.

## 🤔 Expected Behavior

When I change locale language (`await this.i18N.setLocale(newLang);`) validation error messages must be appropriately translated.

## 😯 Current Behavior

If no explicit `.withMessage()` is applied to the rule only autogenerated message is returned.

 `.required()` rule without `.withMessage()`
![Without .withMessage()](https://i.imgur.com/Sq0yEE0.png)

Applied `.required().withMessage(i18N.tr('validation:required'))`
![Applied .withMessage(i18N.tr('validation:required'))](https://i.imgur.com/OG9Dpst.png)

As you can see I'm using default message key for out-of-the-box RequiredRule. 'validation' is set as default namespace for ValidationI18nConfiguration

    ValidationI18nConfiguration.customize(options => {
      options.DefaultNamespace = 'validation';
    })

## 💁 Possible Solution

-

## 🔦 Context

Context is pretty simple since I just started new little app giving Aurelia 2 a try. As for now only authentication/registration screens are implemented. But exactly this screens consumes validation the most (validate username/password requirements, server-side username uniqueness validation etc.)

## 💻 Code Sample

GitHub: https://github.com/rzasinets/au2-validation-internationalization-sample

main.ts

    Aurelia
    .register(RouterConfiguration, MainHeaderHook)
    .register(DialogDefaultConfiguration.customize(globalSettings => {
      globalSettings.startingZIndex = 2;
    }))
    .register(ValidationHtmlConfiguration.customize(options => {
      options.DefaultTrigger = ValidationTrigger.changeOrFocusout;
    }))
    .register(Loading)
    .register(DropdownCustomAttribute)
    .register(CollapserCustomAttribute)
    .register(
      c.customize(options => {
        options.initOptions = {
          resources: {
            en: { translation: en, validation: enVal },
            ru: { translation: ru, validation: ruVal }
          },
          fallbackLng: false
        };
      }),
      ValidationI18nConfiguration.customize(options => {
        options.DefaultNamespace = 'validation';
      })
    )
    .register()
    .app(App)
    .start();

login.ts

    constructor(@IRouter private router: IRouter,
                @newInstanceForScope(IValidationController) private validationController: IValidationController,
                @IValidationRules validationRules: IValidationRules,
                @I18N public i18N: I18N,
                private loading: LoadingManager, private authService: AuthService) {
      validationRules
        .on(this.model)
  
        .ensure((x: $inputs.Login) => x.username)
        .required().withMessage(i18N.tr('validation:required'))
  
        .ensure((x: $inputs.Login) => x.password)
        .required().withMessage(i18N.tr('validation:required'));
    }

en-validation.json

    {
      "required": "Required property.",
      "minLength": "Must have at least {{length}} characters.",
      "canOnlyContainLettersOrDigits": "Can only contain letters or digits.",
      "duplicateUsername": "Username is already taken.",
      "requiresDigit": "Must have at least one digit (0-9).",
      "requiresLowercase": "Must have at least one lowercase (a-z).",
      "requiresUppercase": "Must have at least one uppercase (A-Z).",
      "requiresUniqueChars": "Must use at least {{count}} different characters."
    }

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | 2.0.0-alpha.5
| Language         | Typescript@4.3.2
| Browser          | Chrome@91.0.4472.77
| Bundler          | webpack@5.27.2
| Operating System | Win10x64
| NPM/Node/Yarn    | npm@7.15.1 / node@16.0.0

**Comment by Vheissu** [comment]
@rzasinets Thank you for creating this issue and providing all of the information. Let us triage and then get back to you shortly on a possible solution.

**Comment by rzasinets** [comment]
If it help, added sample project to GitHub
https://github.com/rzasinets/au2-validation-internationalization-sample

**Comment by bigopon** [comment]
@Sayan751 should this line
```ts
    .required().withMessage(i18N.tr('validation:required'));
```
work at all? Shouldn't it be
```ts
    .required().withMessage(i18N.tr('validation:required'));
```

**Comment by Sayan751** [comment]
@rzasinets  There are couple of issues with the code.

Firstly, in order to leverage the localized validation messages, you need to use the `withMessageKey('i18n.key')` instead of `withMessage`.  Even though the dependencies are bit outdated this can be seen in action here: https://stackblitz.com/edit/au2-validation-localization-defaultnamespace

Also, the registrations for the validation is done twice here. Once in form of 

```ts
ValidationHtmlConfiguration.customize(options => {
  options.DefaultTrigger = ValidationTrigger.changeOrFocusout;
})
```

and then again as 

```ts
ValidationI18nConfiguration.customize(options => {
    options.DefaultNamespace = 'validation';
  })
```

Both can be combined as 

```ts
ValidationI18nConfiguration.customize(options => {
    options.DefaultTrigger = ValidationTrigger.changeOrFocusout;
    options.DefaultNamespace = 'validation';
  })
```

For more info refer the docs: https://docs.aurelia.io/validation/i18n-internationalization

**Comment by rzasinets** [comment]
@Sayan751 thank you for review, I'm near sure, that tried some of your suggestions with no success. And for sure I know about `.withMessageKey` but again it didn't work for me. Will check everything again later today or tomorrow, since I'm out of work machine right now.

**Comment by Sayan751** [comment]
@rzasinets Check this demo with latest dependencies: https://gist.dumber.app/?gist=b28ccdabce0c47a1d86d165a53376900

**Comment by rzasinets** [comment]
@Sayan751 It works! Fundamental mistake here was that I've registered validation twice, as you said) But I thought that ValidationI18nConfiguration is like an add-on over the default ValidationHtmlConfiguration. Now everything is perfect. Thank you very much!
