### ISSUE TITLE
Binding context methods are not called from au-slot

### ISSUE THREAD

**Issue by MaximBalaganskiy** [aurelia/aurelia#1203]
# 🐛 Bug Report

Consider the following
```html
    <mdc-tab-bar>
      <template au-slot>
        <mdc-tab label="Examples" class="viewer-tab" active="true" click.trigger="loadExamples()"></mdc-tab>
        <mdc-tab label="Api" class="viewer-tab" click.trigger="loadApi()"></mdc-tab>
      </template>
    </mdc-tab-bar>
```

## 🤔 Expected Behavior

Methods are called on the binding context

## 😯 Current Behavior
Error is thrown
```
Uncaught Error: Expected 'loadApi' to be a function
    at getFunction (ast.js:1155)
    at CallScopeExpression.evaluate (ast.js:623)
    at Listener.callSource (listener.js:28)
    at Listener.handleEvent (listener.js:36)
```
The methods are searched on `mdc-tab-bar` view model, thus not reaching higher binding context

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | alpha.9

**Comment by bigopon** [comment]
Thanks, somehow our tests didn't catch this during the refactoring. Repro here https://gist.dumber.app/?gist=8650a1a9ffb38be5a2825b7c906a881a

I happen to be enhancing au slot & compilation, will fix this as well.

**Comment by bigopon** [comment]
This works in alpha 8. Alpha 9 with the container timing fix probably introduced some regression here.

**Comment by bigopon** [comment]
Having both elements defined globally works as expect https://gist.dumber.app/?gist=7a43f0054ede284b8d32218e6cf72de9

**Comment by bigopon** [comment]
This is related to pass-through slot with CE. A more precise reproduction of the error is here https://gist.dumber.app/?gist=3a35edda2a0b5d073e883630e66cb711

**Comment by bigopon** [comment]
A better example that demonstrate how caching behavior of render context is affecting the scope resolution https://gist.dumber.app/?gist=b8fc67ea261f6897ae846b572dcaa184
3 layers of au-slot pass through and it fails, as top level one is cached

To fix this bug, we will need to tweak the way render context are constructed, and the way renders are invoked, as well as the way au slot determines and picks its factory
