### ISSUE TITLE
request(templating): gives more power to `processContent` hook

### ISSUE THREAD

**Issue by bigopon** [aurelia/aurelia#1204]
# 🙋 Feature Request

At the moment, the process content hooks is limited to only 2 parameters: `node` which is the host element of a custom element, and platform, which mostly provides features/functionality related to document/window. This probably is too limiting, as information about the hydration instruction and the compilation context is also needed. An example of this is `<au-slot/>` fallback content. At the moment, it's a hardcoded block of logic https://github.com/aurelia/aurelia/blob/2cbfe9240c7c1dc9a26e13d51f56dfff3d8e7736/packages/runtime-html/src/template-compiler.ts#L622-L657 
but it could totally reside in the `processContent` hooks of `<au-slot/>` itself.

Consider adding 2 parameters:
- Hydrate element instruction
- Compilation context
as 3rd and 4th parameters of the `processContent` hook, so that CE can optionally compile their content themselves.

cc @fkleuver @Sayan751

**Comment by bigopon** [comment]
We may want some more dynamic power, but at the same time, we probably don't want to overpower this hook, so maybe there could be a metadata property on the custom element instruction that can be use to hold an object from process content:
```ts
processContent(platform, node, data) {
  // add stuff to data here so instruction can use it later
}
```

**Comment by Sayan751** [comment]
I like the metadata approach. I think a primary use-case would be the ability to add bindable instructions and scope.

```ts
data[Symbol.for('au.bindables')] = { 
  'target1': 'source1',
  'target2': {mode: 'to-view', source: 'source2'}
}

data[Symbol.for('au:scope')] = {source1, source2};
```
