### ISSUE TITLE
request(au-slot): au-slot should work with `@children`, or an equivalent for slotting observation

### ISSUE THREAD

**Issue by bigopon** [aurelia/aurelia#1205]
# 🙋 Feature Request

At the moment, `<au-slot>` does not provides a way to toggle between its content coming from projection or fallback , when the content from projection has been deactivated (1), nor a way to react to whenever its content has been possibly changed (2). Consider adding an API to enable (2) as (1) isn't easy, or non-invasive to implement.

Also, there should be an event like `slotchange` event of native slot:
```html
<slot slotchange.trigger="onContentChange()">
```
so the API may look like this
```html
<au-slot slotchange.trigger="onContentChange()">
```

or a higher level decorator similar to `@children`, maybe `@auSlotChildren`

This could be implemented by either:
- Make `View` subscribe-able, so subscriber can at least know when a view is deactivated and react to.
- Use a mutation observer on the immediate parent of the au-slot comment marker location and observer changes of the nodes

**Comment by Sayan751** [comment]
@bigopon This seems to done. Can this be closed?
