### ISSUE TITLE
`ref` is assigned incorrectly for au-slotted elements with a child

### ISSUE THREAD

**Issue by MaximBalaganskiy** [aurelia/aurelia#1210]
# 🐛 Bug Report
Consider the following
```html
<mdc-expandable>
  <div au-slot="caption">Lorem ipsum dolor...</div>
  <template au-slot>
    <mdc-expandable>
      <div au-slot="caption">Lorem ipsum dolor...</div>
      <template au-slot>
        Lorem ipsum dolor sit amet, ad erat postea ullamcorper nec, veri veniam quo et. Diam phaedrum ei mea, quaeque
        voluptaria efficiantur duo no. Eu adhuc veritus civibus nec, sumo invidunt mel id, in vim dictas detraxit. Per
        an legere iriure blandit. Veri iisque accusamus an pri.
      </template>
    </mdc-expandable>
  </template>
</mdc-expandable>
```

## 🤔 Expected Behavior
Root `mdc-expandable` template sets a `ref` to its own internal container element https://github.com/aurelia-ui-toolkits/aurelia-mdc-web/blob/e9fc682fb9054102884ec45c8b594cb57c25af0d/packages/expandable/src/mdc-expandable.html#L22

## 😯 Current Behavior
The `ref` value  "leaks" to a child element which is located in a slot

## 💻 Code Sample
https://gist.dumber.app/?gist=4eb3cec7576f659936aedb56e8eaa5a6
Go to https://aurelia-mdc-web-au2.balaganskiy.pro/#/expandable Child section and inspect values of expandable view models

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | 2.1.0-dev.202106282211

**Comment by bigopon** [comment]
@MaximBalaganskiy can you help guide how to "inspect values of expandable view models" in more details? It doesn't obvious where to inspect in the UI.

**Comment by MaximBalaganskiy** [comment]
Dev tools... Sadly Aurelia inspector does not work

**Comment by bigopon** [comment]
Well, I guess let's stick to the old saying: one thing at a time.

**Comment by bigopon** [comment]
The binding shouldn't get out of the boundary like this.

A work around is to initialize `container` property explicitly https://gist.dumber.app/?gist=4c7f33e1bbf74fb5cac8b50e4e59e0b1

**Comment by bigopon** [comment]
This bug is related to scope picking around scope and host scope
