### ISSUE TITLE
request(templating): dynamic tag element

### ISSUE THREAD

**Issue by bigopon** [aurelia/aurelia#1219]
# 🙋 Feature Request

An uncommon, though not rare request we often got is the ability to dynamically switch the tag of some element. A most common example of this is a switch between a link/button. Consider the following example:

Render a link if there's a href, other wise, render a button.

This is doable with an if/else
```html
<a if.bind="href" href.bind="href">
  ${linkMessage}
</a>
<button else click.trigger="navigateSomewhere()">
  ${buttonMessage}
</button>
```
This isn't always great, as it's a bit noisy & boilerplate-y. Consider supporting condensed form of the above template with something like this
```html
<au-element tag.bind="href ? 'a' : 'button' href.bind="href" click.trigger="navigateSomewhere()">
  ${href ? linkMessage : buttonMessage}
</au-element>
```

A complication with the above template with `<au-element/>` is that it's not easy to distinguish what binding expressions should  go with what tag. For the above example. if the tag is `a`, then only needs a `href.bind`, and if the tag is `button`, only needs the `click.trigger`.

**Comment by hiaux0** [comment]
My issue with the initial proposal:
- when there are more attributes, could quickly get out of hand on what belongs where (as you mentioned)
- too many `?` operators?

Proposition:
- inner tags, that are controlled via `au-switch-elements` (name just for illustrative purposes)


```html
<au-switch-elements tag.bind="href ? 'a' : 'button'">
  <a href.bind="href">${linkMessage}</a>
  <button click.trigger="navigateSomewhere">${buttonMessage}</button>
</au-switch-elements>
```

**Comment by bigopon** [comment]
Interesting example! Even though it's quite close to `switch/case`, it's actually less boilerplate than that. Though, when it comes to the content of those tag, the boilerplates is there. An example is:
```ts
<au-switch-elements tag.bind="gridLayout ? 'div' : 'p'>
  <div role="paragraph" class="grid" data-layout="...">
    <div>My header</div>
    <div>My body</div>
  </div>
  <p class="card">
    <div>My header</div>
    <div>My body</div>
  </p>
</au-switch-elements>
```

**Comment by hiaux0** [comment]
> close to switch/case

Yeah true.
Now, I can better see what your initial proposal tried to solve.
 
### Next idea
#### "Local templates" - Magic

Inspired by "[Local templates](https://docs.aurelia.io/getting-to-know-aurelia/introduction/local-templates)"  and portal
**Aim:** 
- keep attributes clean (and know what relates to what)
- Reduce boilerplate

**Solution:**
- new "magic" tag, that inserts the resulting element as a tag for the "boilerplate"

**Con:**
- Yet another new concept

```html
<au-switch-elements tag.bind="gridLayout ? 'div' : 'p'">
  <div role="paragraph" class="grid" data-layout="..."/>
  <p class="card"/>

  <resulting-element>
    <!-- boilerplate -->
    <div>My header</div>
    <div>My body</div>
  </resulting-element>
</au-switch-elements>
```

#### "Local templates" - Normal
Pro: 
- Known concept

```html
<au-switch-elements tag.bind="gridLayout ? 'div' : 'p'">
  <template as-custom-element="boilerplate">
    <div>My header</div>
    <div>My body</div>
  </template>

  <div role="paragraph" class="grid" data-layout="...">
    <boilerplate/>
  </div>
  <p class="card">
    <boilerplate/>
  </p>
</au-switch-elements>
```

**Comment by bigopon** [comment]
The magic-tag looks likable. It's a new concept so it's unlikely to cause confusion. Also, the local - local template will probably causes some issues with our template compiler, as it will need to learn about some special elements that may ignore its no non-root local template rule. The name `<resulting-element>` and `<au-switch-elements` can probably be tweaked a bit, to make the concept "less new":

```html
<au-host tag.bind="gridLayout ? 'div' : 'p'">
  <div role="paragraph" class="grid" data-layout="..."/>
  <p class="card"/>

  <template>
    <!-- boilerplate -->
    <div>My header</div>
    <div>My body</div>
  </template>
</au-host>
```

**Comment by bigopon** [comment]
This is now doable via the `<au-compose>`:
```html
<au-compose tag.bind="gridLayout ? 'div' : 'p' template.bind="someHtml">
```
