### ISSUE TITLE
It should be possible to completely destroy component with if.bind=false

### ISSUE THREAD

**Issue by rzasinets** [aurelia/aurelia#1230]
# 🙋 Feature Request

It should be possible to completely destroy component with if.bind=false

## 🤔 Expected Behavior

With Aurelia1 we were able to extend if.bind usage with additional params (e.g. `if="condition.bind: condition; cache:false"`). But now looks like that syntax is not supported anymore.

## 😯 Current Behavior

As for now component's "construction" part is invoked once. Further switching only triggers everything after `created` lifecycle hook.

## 💁 Possible Solution

If possible, restore functionality from Aurelia1 to Aurelia2. Just passing cache control to if attribute would be perfect.

## 🔦 Context

I have a page, that renders different 'views' by user choice. All views are presented in page html and their appearance is controlled by `if.bind` clause (I understand, that it might be better to utilize routing, but page is included to the dialog where routing doesn't have sense). The 'tricky' part is that all this child views have validation included, which is initialized in "construction" of element lifecycle. So the first time user access any view everything works as expected, but if he switch to another view and then returns to already accessed - validation is not working anymore: validation controller misses all `bindings` attached. I believe, that if component wouldn't be cached (destroyed completely) and all lifecycle hooks would be invoked every time if might fix this issue.

## 💻 Examples

I've prepared sample [project](https://github.com/rzasinets/au2-validation-internationalization-sample). First time you access View 1 or View 2 validation work cool. But after switching back from View 2 to View 1 (and visa versa) `await this.validationController.validate()` is always considered valid.

**Comment by bigopon** [comment]
@rzasinets thanks for this issue. I'm thinking of adding cache control too.
