### ISSUE TITLE
.call binding behavior doesn't pass anything to $event

### ISSUE THREAD

**Issue by rzasinets** [aurelia/aurelia#1231]
# 🐛 Bug Report

Trying to bind component callback with `.call` binding behavior. Callback triggers as expected, but always have empty arguments

## 🤔 Expected Behavior

Just normally receive everything I pass from component into parent viewmodel

## 😯 Current Behavior

Looks like $event is resolved into empty string always

## 🔦 Context

Just added a simple component with simplest callback that should notify parent viewmodel with boolean argument. Was very unhappily surprised that widely used in Aurelia1 `.call` binding always return empty string. `.bind` works as expected.

## 💻 Code Sample

https://github.com/rzasinets/au2-validation-internationalization-sample

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | 2.0.0-alpha.5
| Language         | Typescript@4.3.2
| Browser          | Chrome@91.0.4472.77
| Bundler          | webpack@5.27.2
| Operating System | Win10x64
| NPM/Node/Yarn    | npm@7.15.1 / node@16.0.0

**Comment by bigopon** [comment]
@rzasinets thanks, I got a reproduction of the issue here https://gist.dumber.app/?gist=b99b96f61b75db753379e238f5be05e7
