### ISSUE TITLE
au-compose using view-model.bind

### ISSUE THREAD

**Issue by micmanar** [aurelia/aurelia#1233]
Hi, 
I'm trying to use multiple au-compose tags binded to a single already existing component instance with view-model.bind="viewModel". 

## 🤔 Expected Behavior
Binding an existing view-model to multiple au-compose tags should create different indipendent views with a shared state.

## 😯 Current Behavior
Only the first au-compose binding creates a new view and works correctly, the following ones all refer to the view, even if the view-model was previowsly unbinded. The first view is used again and again and showed in the previous parent.

## 💁 Possible Solution
I quote bigopon from a discord post: 
This is because of the difference in composition primitives in v1 and v2, and some caching behavior in v2 that we aren't sure about yet. At the moment, a view model instance is associated with a single controller, two way. Maybe we shouldn't need that and let the composition happen "transiently" like v1

## 💻 Code Sample

I've created a gist showing the behavior in aurelia v1:
https://gist.dumber.app/?gist=56422325ca9f9ff415fa5731599e897d
the buttons allows to bind and unbind at will the same view-model to different instances of au-compose, multiple views are created as needed and there are no errors.

This is the same gist ported to aurelia v2 alpha 0.8: 
https://gist.dumber.app/?gist=67cfba30df6e60f5177a377065d4e5c7

**Comment by bigopon** [comment]
Thanks @micmanar for this issue. This is because of the difference in the composition primitives between v1 and v2.
cc @fkleuver @Sayan751

**Comment by Sayan751** [comment]
@micmanar Very interesting usage of compose! The use-case however is not very clear from the example you have created in dumber gist. You have talked about shared state. I am interested in knowing how you intend to share the state among all those compose instances. There might be other ways to deal with shared state, rather than sharing view-model. For example, you can share the model among all those instances, or if your use case is complex, then you can have full-blown state management using the store plugin.

**Comment by micmanar** [comment]
@Sayan751 The gist with multiple instances in the same place is only for making the behavior more evident without needing to navigate in and out between different pages. The actual use-case is not about **sharing** state, but just to **keep** the state of the UI between successive activations when singleton view-models are not an option.
I'm porting an existing application using this tecnique and just wanted to mark the difference in behaviour of v1 and v2. Of course, should the new behavior remains as is, moving the UI state elsewhere is an easy and valid option.
