### ISSUE TITLE
regression(au-slot) alpha.5->alpha.10 context is not initialized on accessing slot holder second time

### ISSUE THREAD

**Issue by rzasinets** [aurelia/aurelia#1234]
# 🐛 Bug Report

Can't navigate to back to route content of which is rendered into `au-slot`. Works nice in alpha.5 but buggy in alpha.10

## 🤔 Expected Behavior

Routes should be just normally rendered :)

## 😯 Current Behavior

Got an error ![error snapshot](https://i.imgur.com/fXTeXzb.png) and application is broken

## 🔦 Context

Have a number of routes that render their content into a wrapper with `au-slot`. First time accessing all of this routes goes well, but I can't access any route second time. If I remove wrapper (and its slot) application works again

## 💻 Code Sample

https://github.com/rzasinets/au2-validation-internationalization-sample
Try navigate to alternative route and back to home

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | 2.0.0-alpha.10
| Language         | Typescript@4.3.2
| Browser          | Chrome@91.0.4472.77
| Bundler          | webpack@5.27.2
| Operating System | Win10x64
| NPM/Node/Yarn    | npm@7.15.1 / node@16.0.0

**Comment by jwx** [comment]
This bug doesn't seem to exist with the Aurelia Direct Router <https://github.com/rzasinets/au2-validation-internationalization-sample/pull/1/files> so it seems to be within the router.

**Comment by rzasinets** [comment]
@jwx really works. But your implementation of direct routing differs from the one, described in docs (which doesn't work, I checked). 
If you don't mind I'll not merge your pull request to ensure but is reproducible for further reference.
I didn't use use direct routing (the way it should be added according to docs) because hated this strange `home@default` fragment in url, added by the viewport. But looks like referencing `aurelia-direct-router` package directly fixes this issue.
As a conclusion: `au-slot` became broken with any routing configuration, except of direct routing, when we add direct router package directly. 
Thank you very much. Not a blocker anymore for me)

**Comment by bigopon** [comment]
Thanks @rzasinets @jwx . Direct router working helps narrow down what to guess where it fails. I'll probably start focusing more on the default router soon. In the mean time, glad the direct router works for you.

**Comment by rzasinets** [comment]
Can confirm, that after updating to 2.0.0-alpha.10 the issue is gone with classic router

**Comment by jwx** [comment]
@rzasinets @bigopon Can this be closed?
