### ISSUE TITLE
CSS extraction does not work with Webpack 5

### ISSUE THREAD

**Issue by Vheissu** [aurelia/aurelia#1244]
# 🐛 Bug Report

When attempting to extract CSS using the Mini CSS Extract plugin in Webpack, I get numerous warnings which I am assuming are coming from our Webpack plugin. I am using the default convention where styles are not being manually imported and defined on a `customElement` decorator (although I did try this to no avail).

Please note I am NOT using CSS Modules or Shadow DOM for styling.

**The error I am seeing is:**

```
WARNING in ./src/components/login.html 7:57-59
export 'default' (imported as 'd0') was not found in './login.scss' (module has no exports)
```

Before creating this issue, I tried quite a few things to see if I can fix this.  Now, the thing is, I see these warnings, but my styles are being loaded in Webpack. The issue appears to be that they are not chunked. All of my CSS is in an `entry.css` file instead.

So, the CSS is being found, but it's not extracting properly. It's almost as if the conventions plugin or loader (most likely loader) is trying to import the contents of my file incorrectly.

Relevant parts of my webpack configuration file:

```
const MiniCssExtractPlugin = require("mini-css-extract-plugin");

const cssLoader = {
  loader: 'css-loader',
  options: {
    // https://github.com/webpack-contrib/css-loader#importloaders
    importLoaders: 2,
    esModule: false,
  }
};

const sassLoader = {
  loader: 'sass-loader',
  options: {
    sassOptions: {
      includePaths: ['node_modules']
    }
  }
};

const postcssLoader = {
  loader: 'postcss-loader',
  options: {
    postcssOptions: {
      plugins: ['autoprefixer']
    }
  }
};
```

```
{ test: /\.html$/i, use: '@aurelia/webpack-loader', exclude: /node_modules/ }
{ test: /\.css$/i, use: [ MiniCssExtractPlugin.loader, cssLoader, postcssLoader ] },
{ test: /\.scss$/i, use: [ MiniCssExtractPlugin.loader, cssLoader, postcssLoader, sassLoader ] },
```

## 🤔 Expected Behavior

CSS should be extracted into named chunks as per the component.

## 😯 Current Behavior

CSS is not extracted into chunks.

## 💁 Possible Solution

Check loader to ensure any parsed resources from custom elements are being properly imported.

## 🌍 Your Environment

Latest dev version of Aurelia, TypeScript and Webpack.

**Comment by 3cp** [comment]
If not using shadowdom or css-modules, currently conventions write the html module with css import as following:
```js
import d0 from "./foo-bar.css";
export const dependencies = [ Registration.defer('.css', d0) ];
```

The mini-css-extract-plugin however hides all exports from the compiled css module, hence the warning from webpack.

The `Registration.defer('. css', d0)` is a noop as Aurelia 2 doesn't need to do anything here.

`Registration.defer('.ext', dep)` was designed to handled unknown resource type. Known resource types are js/ts, or any template file formats (.html, .md, .pug, .haml). We still use `Registration.defer` for all css resources (.css, .scss, .sass, .less, .styl).

I don't remember why we need to use `Registration.defer` on css resources. @EisenbergEffect ?

If we can remove `Registration.defer` wrapper on css resources, the fixed compiled code will be just:
```js
import "./foo-bar.css";
```

**Comment by Vheissu** [comment]
@3cp In your testing, does removing Registration.defer break anything? Because I've love to see this one fixed for an app I am porting over to Au2.

**Comment by 3cp** [comment]
It would not break anything, unless you use `<slot>` inside the template which forces Aurelia 2 to use shadowdom, that prevents global styles to be applied.

**Comment by Vheissu** [comment]
@3cp I guess in this instance if we restrict the change to be non-ShadowDOM (which my understanding is handled elsewhere anyway) we should just make the change. I'm not sure if Rob has the time to weigh in on this one.

**Comment by EisenbergEffect** [comment]
I don't remember the reason for this actually. It was a long time ago now...maybe even close to two years. Sorry I can't be of much help. Maybe @bigopon can investigate and see if it can be removed.

**Comment by 3cp** [comment]
Ok I will update conversations then. To see if anything breaks.
