### ISSUE TITLE
[RFC] Introduce on binding command

### ISSUE THREAD

**Issue by zewa666** [aurelia/aurelia#1255]
# 💬 RFC

While Aurelia settles on the `attribute.bind|delegate|trigger|call="bindable"` this RFC proposes the introduction of a secondary approach with an `on` binding command. 

## 🔦 Context

The purpose of this approach is to:

* Support of camelCase event names (e.g. custom events fired by the users app or e.g. consumed 3rd party web-components)
```html
<ion-input on="randoEvent: doSomething()">
```
* Multi event bindings
```html
// current
<div this.trigger="doSomething()" that.trigger="doMore()" bail.trigger="quit()">

// alternative with on
<div on="this: doSomething(); that: doMore(); bail: quit()">
```
* Allow custom expressions similar to i18n
```html
<div t="[html]...">
```

## 💻 Examples

The following examples would be open for debate:

* Dynamic composition with bind
```html
<div on.bind="bindable"></div>

// bindable -> randoEvent: doSomething()
```
* Binding to an object of type {[Key: EventName]: Callback}
```html
<div on="{ [myEventExpression1]: doThis(), [myEventNameExpression2]: doThat() }">
```
* Controlling initOptions of addEventListener
```html
<div on="this:{ passive: false, once: true }: doSomething(); that: doMore(); bail: quit()">
// leading to e.g.
<div on="drag:{ passive: false }: onDrag(); dragStart: $event.preventDefault(); dragover: $event.preventDefault()">
```
* Support Vue like key-specific event bindings `@keydown.esc="myfunction"`

**Comment by avrahamcool** [comment]
I can't really see new advantages to the new syntax, except that is more compact. but that come with a cost of a learning curve and a break from the traditional way of V1.

dynamically binding to an object is an obvious benefit - but I can't think of a use case where I'll need that.
can you provide some real life example where this will be beneficial?

how can we specify if we want to use `trigger`, `delegate` or `capture` when using `on`?

> Controlling initOptions of addEventListener
> Support Vue like key-specific event bindings @keydown.esc="myfunction"
those two are a very good addition. and in my opinion should be added to the regular binding commands as well.
(is there currently a way of doing that? in V1? or V2? - in the past, I created custom attributes and custom logic to do those two.)

**Comment by zewa666** [comment]
The learning curve with two competing approaches is definitely a thing.

Perhaps the most important example is the binding to camelCased event names which you cant really express otherwise.

Trigger/delegate as well as capture all relate to Event specifics like bubbling/intercepting. Take a look at the initOptions scenario. Perhaps that way like.

@keydown, not that I'd know

**Comment by Vheissu** [comment]
I love the proposed syntax. I think as long as we have the existing syntax for events, these new additions are just more powerful tools in an already powerful arsenal of features. It's really no different than having conventions and configuration options for creating components and attributes.

**Comment by MylesPenlington** [comment]
Like this for binding to html Events - very useful. Would save quite a bit of boiler plate code
 ```
<ion-input on="randoEvent: doSomething()">
```
Also clear benefits for the support of the mentioned syntax leading to code like
```
<div on="drag:{ passive: false }: onDrag(); dragStart: $event.preventDefault(); dragover: $event.preventDefault()">
```
Key bindings would be helpful too.

**Comment by bigopon** [comment]
I think one aspect of this we should ... bikeshed is syntax. What about using some special character to signal event, instead of `;`?
```html
<div on="@drag:{ passive: false }: onDrag() @dragStart: $event.preventDefault() @dragover: $event.preventDefault()">
```

**Comment by MylesPenlington** [comment]
I think I would prefer a more explicit syntax in preference than to add more "Special" characters with special meaning perhaps - easier on intellisense too?
```
<div onevent="
```
Then could also things like ontrigger, oncapture, ondelegate, onkeyup, onkeydown, or perhaps on.trigger, on.capture, on.event etc?? And maybe this is is easier to extend too

**Comment by bigopon** [comment]
```html
<div onevent="">
```
We will have to avoid any kind of `on...` attribute, because of the high chance of collision with standard `on` attribute:
```html
<div onclick="this.tagName === 'div'">
```

**Comment by MylesPenlington** [comment]
Which is sort I sort of threw in that additional syntax idea at the end
```
<div on.event="" on.trigger="" />
```
Kind of syntax instead

**Comment by avrahamcool** [comment]
> @keydown, not that I'd know, can you share a sample of your custom attributes?

sorry for the late response, I didn't notice your request until now.

for the `initOptions`, I wanted to use `once`. so I used the regular syntax but kept a `boolean` attribute on my VM - to indicate if I already clicked on button. (not very elegant).

for the `keydown` - I created a specific (too specific in my opinion) attribute, to handle "Enter" key.

usage:
```html
<input type="text" value.bind="myValue" enter-press.call="myFunc()">
```

custom-attribute:
```typescript
import {autoinject} from "aurelia-framework";

@autoinject()
export class EnterPressCustomAttribute
{
    enterPressed: (e: KeyboardEvent) => void;
    value: Function;
    _ENTER_KEY = 13;

    constructor(private element: Element)
    {
        this.element = element;
        // 'this' won't be changed so you have access to you VM properties in 'called' method
        this.enterPressed = e => ((e.which || e.keyCode) === this._ENTER_KEY) && this.value();
    }

    attached()
    {
        this.element.addEventListener("keydown", this.enterPressed);
    }

    detached()
    {
        this.element.removeEventListener("keydown", this.enterPressed);
    }
}

```

**Comment by PrinceLune** [comment]
Key-specific event bindings should be handled by the developer in my opinion. Setup a action handler and use a object literal to call the correct function just like how Redux uses combineReducers and useReducers makes the action go to the right function in this case the keyboardEvent. This will help performance. You can use KeyboardEvent.key key values and typescript to simplify your logic and make your key handling by splitting the reducers by the types of key values here: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values

Here is a example of what I'm talking about:
https://github.com/PrinceLune/Snippets/blob/master/KeyEventHandler.ts

also which is
_UIEvent.which
Non-standard: This feature is non-standard and is not on a standards track. Do not use it on production sites facing the Web: it will not work for every user. There may also be large incompatibilities between implementations and the behavior may change in the future._

**Comment by bigopon** [comment]
@PrinceLune I think this is where we need to find the balance. Leaving it handled by developers will create a hole in developer experience evident per the feature requests/questions around this for the last few years.

**Comment by PrinceLune** [comment]
@bigopon 

Yeah that is a tricky one. I only chime in on this because I had to write the Xbox one controller directive(your controller emits KeyboardEvents) for Xbox Assist(it's a headless web-view that protocols to a Angular App on console) on the Xbox One, it's used by Gamepass, Mixer and other apps on the console. I know Netflix wrote their own version for their React app on console, as I did as well because we refactored Assist to be a React app instead because of how much we had to fight Angular to do what we want. 

Some gotchas, Triggering change detection, causing the whole app to rerender causing huge performance dips when profiling(cute little bug we found, if you slapped around the joystick fast enough you could cause so many rerenders you would crash your Xbox). I haven't tested what Aurelia will do in that kind of situation or if you plan on being a framework that is used on console like environment.

**Comment by bigopon** [comment]
@PrinceLune Aurelia binding & observation system works by connecting only the relevant parts of views and view models together. For that, updating view model will result in a precise view update, and it's also easy to hack around stuff if there's something unforeseen.
With that principle, any environment will work just fine. An issue with this is it will require a bit more time at the application startup to setup all the necessary connections. How much slower & how noticeable a slow down is compared to others are hard to measure. (v1 has been doing really well in both benching and perceiving perf).
