### ISSUE TITLE
[RFC] Bindables built in attribute (Spread like)

### ISSUE THREAD

**Issue by brandonseydel** [aurelia/aurelia#1258]
# 💬 RFC
Aurelia could benefit in a syntax to leverage bindable multiple properties of an object to individual bindables rather than a state object.  This can be useful when dealing with UI libs and such.

# Examples
The purpose is to unlock the capability to send an object to a CE and let properties bind to bindables of that CE without having to use one state object.

```ts
export class PersonViewer {
  @bindable firstName:string;
  @bindable lastName:string;
}
```

Originally had to always go this route

```html
<person-view first-name.bind="person.firstName" last-name.bind="person.lastName" />
```
Proposed
```html
<person-view bindables.bind="person" />
```

Bindables will assign properties of the object to bindables of the CE matched by name.  This would include functions and such.

### Some talking points:
If there is a bindable say middle name and the object passed is not there should be create the property on the object?  If we do not do this then if another CE adds the property the current CE wouldnt be notified of the change.  So is auto creating properties on an object OK, optional, or no way?  

The most obvious use case of this is to be able to use UI libs without tons of bindables.
```html
<md-button bindables.bind="{ disabled:true, outline:true, small:true }" />
// compared to 
<md-button disabled.bind="true" outline.bind="true" small.bind="true" />
```

If we include both does order trump?

```html
<mb-button small.bind="false" bindables.bind="{small:true}" />
```
Is small bound to false or the objects true?

**Comment by bigopon** [comment]
> If there is a bindable say middle name and the object passed is not there should be create the property on the object? If we do not do this then if another CE adds the property the current CE wouldnt be notified of the change. So is auto creating properties on an object OK, optional, or no way?

Observing = creating property. And yes, maybe it can auto observe in advance. Say we have

```ts
class NameTag {
  @bindable first
  @bindable middle
  @bindable last
}
```
and the template

```html
<name-tag bindables.bind="contact">
```
`first`, `middle`, `last` should be all eagerly observed on `contact` object. I think it's more natural this way, and can avoid the issues of missing change notification from property addition.

Syntax wise, I'm not sure `bindables.bind` is the best though, can be bikeshed this a bit more?

**Comment by brandonseydel** [comment]
@bigopon what you think it should be named?  I think we can drop bind since these will all have to be an obj....cut the fat 

bindables="{}"
properties="{}"
observables="{}"
...="{}"

**Comment by bigopon** [comment]
Since we have `...$attrs` for everything else that is not bindables/template controller, maybe we can have `...$bindables`? It's a bit long though. What about `...$props`?
