### ISSUE TITLE
Keyed binding & assignment expression should work with array

### ISSUE THREAD

**Issue by bigopon** [aurelia/aurelia#1262]
# 💬 RFC

## 🔦 Context

Currently, for an expression like this
```html
<button click.trigger="myItems[0] = $event.target"></button>
```
When a click happens on the button, `myArray[0]` is assigned `event.target` value, similar to the following code:
```ts
myItems[0] = event.target
```
If `myItems` is a normal object, this will trigger change notification for the property `0`. But if `myItems` is an array, this mutation will go unnotified, as plain assignment to array index cannot be observed.

This could lead to the following confusing situations:

- Two way binding between an input and an array index only works one way: (`values` mutation notifies input to change, but input changes won't notify assignment to `values[$index]`
```html
<let values.bind="[]"></let>
<form repeat.for="i of items">
  <input value.bind="values[$index]" />
  <button>Commit</button>
</form>
```
- ref changes but no notification
```html
<div repeat.for="i of itemCount" ref="myDivs[$index]">
  
</div>
<button click.trigger="itemCount = itemCount + 1">More divs</button>
${myDivs.length}
```
Will only work one way: changes in the array via mutation methods (splice, push, pop, reverse, shift, unshift, sort) will notify the template, but changes from the button click won't notify `${myDivs.length}` binding.

## Changes:

In the access keyed expression, `assign` method:
```ts
  public assign(f: LF, s: Scope, l: IServiceLocator, val: unknown): unknown {
    const instance = this.object.evaluate(f, s, l, null) as IIndexable;
    const key = this.key.evaluate(f, s, l, null) as string;
    return instance[key] = val;
  }
```
change to
```ts
  public assign(f: LF, s: Scope, l: IServiceLocator, val: unknown): unknown {
    const instance = this.object.evaluate(f, s, l, null) as IIndexable;
    const key = this.key.evaluate(f, s, l, null) as string;
    if (instance instanceof Array && isArrayIndex(key)) {
      instance.splice(key, 1, 1);
      return val;
    }
    return instance[key] = val;
  }
  ```

**Comment by MaximBalaganskiy** [comment]
I think this is critical - there are a lot scenarios where inputs are bound to array elements
