### ISSUE TITLE
fetchAdvice has no param for `i`

### ISSUE THREAD

**Issue by dkent600** [aurelia/aurelia#1265]
Here: https://github.com/aurelia/aurelia/blob/master/docs/user-docs/getting-to-know-aurelia/introduction/built-in-template-features/promise.bind.md

The `fetchAdvice` function has no param for `i`.  Either don't pass it in, or use it, or declare it and explicitly ignore it while explaining why.

**Comment by bigopon** [comment]
@dkent600 thanks. I'll be declared ignore, with some explanation.
