### ISSUE TITLE
Repeater Contextual Properties do not work on custom attributes (not prefixed with data-)

### ISSUE THREAD

**Issue by brettdusek** [aurelia/aurelia#1275]
# 🐛 Bug Report

The Repeater's contextual properties are too opinionated on where they can be used. For example, we have a custom web component that is being repeated over that can set a 'layout' attribute for styling purposes and we want to set layout='odd' for each odd item. The contextual properties only work when set in 'class' or attributes starting with 'data-'. This seems like an unnecessary enforcement of web standards (while binding to custom attributes isn't this way for example) or too opinionated on how elements may be styled.

Update w/ example: https://gist.dumber.app/?gist=31ec9927a7810e6ab52e07405de0cb42

## 🤔 Expected Behavior

`<my-component repeat.for="item of data" layout="${ $odd ? 'odd': '' }">${item.id}</my-component>`

should render as:

```
<my-component layout="odd">1</my-component>
<my-component layout>2</my-component>
<my-component layout="odd">3</my-component>
```

## 😯 Current Behavior

`<my-component repeat.for="item of data" layout="${ $odd ? 'odd': '' }"></my-component>`

renders as:

```
<my-component layout></my-component>
<my-component layout></my-component>
<my-component layout></my-component>
```

...but this works...

`<my-component repeat.for="item of data" data-layout="${ $odd ? 'odd': '' }"></my-component>`

renders as:

```
<my-component data-layout="odd"></my-component>
<my-component data-layout></my-component>
<my-component data-layout="odd"></my-component>
```

## 🔦 Context

This may lead to interoperability issues with other 3rd party component libraries that are attribute-based instead of class-based for styling, and/or disregard prefixing custom attributes with 'data-' which, while not standard-compliant, is common.

Edit: Fixing formatting / typos, correcting repeat-for to repeat.for just for clarity

**Comment by bigopon** [comment]
@brettdusek the html
```html
<my-component repeat-for="item of data" layout="${ $odd ? 'odd': '' }">${item.id}</my-component>
```
should work just fine, unless it's `repeat-for` instead of `repeat.for`.

Can you help verify if the syntax is correct?

**Comment by brettdusek** [comment]
Sorry, repeat-for was a typo in my post; This issue does persist as stated. I'll correct my post to avoid misdiagnosis.

Just to reiterate.. using 'layout' does not work whereas 'data-layout' will. Same for any attribute... like 'hello' vs. 'data-hello'.

**Comment by brettdusek** [comment]
https://gist.dumber.app/?gist=31ec9927a7810e6ab52e07405de0cb42 

Here is an example demonstrating the issue.

**Comment by brettdusek** [comment]
Sorry, one other thing.. you'll notice in my example I use `${ $odd ? 'odd': '' }`. This outputs 'odd' on even items instead.

**Comment by bigopon** [comment]
@brettdusek I see, thanks for the example. Here's an example that works https://gist.dumber.app/?gist=435a70d5a3ccfbb87868854bd6ffb38b

The reason you are seeing that behavior is because the way Aurelia works: by default, it works with properties, except it looks like an attribute.

This means `layout="${$odd ? 'odd' : ''}"` will result in a binding with property `layout`, you can inspect the element and see this property on it.

Changing that to `layout.attr="$odd ? 'odd' : ''"` works as expected, as `.attr` forces this binding to be with an attribute.

**Comment by bigopon** [comment]
I think others may find this confusing as well, there'll be some more doc to make sure this behavior is more noticeable.

**Comment by brettdusek** [comment]
@bigopon Thanks for the tip on using "layout.attr", that works. I agree that a example in the docs or more explanation would be helpful there.

**Comment by Sayan751** [comment]
@bigopon Considering the [docs for attr](https://docs.aurelia.io/templates/overview/attribute-binding) binding is in place, I am closing this issue.
