### ISSUE TITLE
When removing component that has still running animation, exception is thrown; detaching() not respected

### ISSUE THREAD

**Issue by bojanv55** [aurelia/aurelia#1299]
# 🐛 Bug Report

I'm rendering component, component is animated on attach (btw animation only works in firefox and not in chrome - I guess because of this custom element name that is rendered in HTML), and If I remove component before animation is complete I get:

```
Uncaught Error: AUR0505:aurelia-demo>[repeat][view:unnamed-1] activating|released
    at Controller.deactivate (index.js:3579)
    at Repeat.di (index.js:8199)
```

## 🤔 Expected Behavior

Component is removed from the screen without exception (and detaching() is called, since now immediately removed)

## 😯 Current Behavior

Exception above is thrown, and component is immediately removed, not respecting detaching() method.

## 💻 Code Sample

This is how I render component, and I have a button with which I add/remove component to components array:

```
<template repeat.for="component of components">
    <au-compose containerless view-model.bind="component"></au-compose>
  </template>
```

and thiese are methods from component that is problematic:

```
  attaching = () => {
    const animation = this.host.animate(
        [{ opacity: 0 }, { opacity: 1 }],
        { duration: 5000 },
    );
    return animation.finished;
  }

  detaching = () => {
    const animation = this.host.animate(
        [{ opacity: 1 }, { opacity: 0 }],
        { duration: 5000 },
    );
    return animation.finished;
  }
```

So, If I wait 5 seconds and then remove component from `components` array it is OK related to exception (component is removed from the screen without exception), but it is not waiting for `detaching()` animation to complete. If I do not wait for promise returned in attaching to complete, there is an exception.

This is animation in Firefox (notice that my component element occupies some space on inspect):

![animationFirefox](https://user-images.githubusercontent.com/1422698/131182711-4b7ec011-6236-4061-ad7d-4d10a7362a09.gif)

and in Chrome - no animation and my component has no screen space:

![animationChrome](https://user-images.githubusercontent.com/1422698/131182718-4592f057-32df-497b-8a13-0e944e2688b3.gif)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | ^2.0.0-alpha.18
| Language         |
| Browser          | Any
| Bundler          | Webpack
| Operating System | Windows
| NPM/Node/Yarn    | NPM

**Comment by bigopon** [comment]
@bojanv55 thanks for the issue and gist.

The reason animation doesn't play on Chrome is that Chrome does not animate non-block element, as the element created by au-compose is `<some-demo2/>`, which has inline display by default. Simply change it template from
```html
<div class="some-demo">
  This is some demo2 a kazemo iz pogleda
</div>
```
to
```html
<template style="display:block">
  <div class="some-demo">
    This is some demo2 a kazemo iz pogleda
  </div>
</template>
```
will fix that.

For the detaching without proper animation and the bug, It's a known issue in the repeater with race condition. It'll be prioritized but a bit time to get fixed.

**Comment by bojanv55** [comment]
@bigopon Thanks. I thought that removing that some-demo2 would solve it actually, but did not know how to remove it inside au-compose.

**Comment by Sayan751** [comment]
@bigopon Moving this to v2.x.

**Comment by bigopon** [comment]
This is already fixed via partial deactivation/activation work from @jwx and @Sayan751 . Stackblitz updated demo here https://stackblitz.com/edit/au2-conventions-usssia?file=src%2Fmy-app.html

@3cp when I went to the dumber repo link https://gist.dumber.app/?gist=2ff71b60ccbcdc62a4dd9295bf0d710d
I got the old decorator based compiled code. How do we reset the cache for that compilation? It's probably from a long time back.

**Comment by 3cp** [comment]
I will update dumber-gist with latest au2 plugin. I might hard coded au2 config to use legacy decorator in the app.

**Comment by bigopon** [comment]
Cool thanks @3cp 🙏

**Comment by bigopon** [comment]
Thanks @3cp for updating gist dumber. It's working now at https://gist.dumber.app/?gist=66e738715f3d7750f150f213db58bb5f

Though the animation doesn't seem to run like in Stackblitz when clicking on render button. I'm quite confused why 🤔

**Comment by 3cp** [comment]
@bigopon your demo2 file has a missing ")" in `constructor(private host = resolve(INode)) {`

Once fixed, animation is running. For me the remove only happens after animation finished. Not sure is that a bug. There is an error about unhandled promise.

**Comment by bigopon** [comment]
Aaahh thanks @3cp . Some how the app still worked and it got me quite confused.

For the error, I didnt encountered any, even when waited all the way to the end and start again, it seems
