### ISSUE TITLE
Allow for the use of this inside of views to align with the usage inside of view models

### ISSUE THREAD

**Issue by brandonseydel** [aurelia/aurelia#1310]
# 💬 RFC

Throughout the years and developers introduced to Aurelia I constantly see the hang up on inside the class using this. and in the view omitting it.  I think the class mindset should permeate into the views as well.  This would allow copy/paste back and forth from html -> ts without any effort, allow some string interpolation things to work easier (strongly typed templates), and follow the standard class this. accessor (optionally)

**Comment by Vheissu** [comment]
This is actually brilliant. We should keep the default behaviour of mapping class properties and methods to the view, but I can't see the harm in also adding this.

**Comment by bigopon** [comment]
We currently have `$this` pointing at the current context. Allowing `this` could introduce some confusion, but I think its not without merit. How will "this" play together with our current syntax?
