### ISSUE TITLE
Allow for invoking functions with default parameter when not ()

### ISSUE THREAD

**Issue by brandonseydel** [aurelia/aurelia#1311]
# 💬 RFC

I always seem to be running into the same behavior with trigger and delegate where all I want to do is call the event with default parameters from the func without having to invoke it in-line.

e.g.

```html
<button click.trigger="click" >Click Me</button>
Vs
<button click.trigger="click($event)">Click Me</button>
```

```ts
class ButtonViewModel {
  click(event:MouseEvent){
  // event will have value in both cases
  }
}
```

**Comment by Vheissu** [comment]
Another good suggestion @brandonseydel I think a default for these types of event makes a lot of sense. It's rare for a lot of the click events stuff I do especially, that I need more than the event object.

**Comment by brandonseydel** [comment]
@bigopon - I think handler, handle, or invoke.

**Comment by bigopon** [comment]
> ...evaluate the expression and if the result is a function, invoke it...

This'll give surprises, as if this behavior was here, we would need to be very careful of what the expression evaluates to.

It's more ambiguous because we want to make sure we only call some function only once, and call the right function.

**Comment by jwx** [comment]
> > ...evaluate the expression and if the result is a function, invoke it...
> 
> This'll give surprises, as if this behavior was here, we would need to be very careful of what the expression evaluates to.

How so? (Sorry for not getting it!) 

> It's more ambiguous because we want to make sure we only call some function only once, and call the right function.

**Comment by bigopon** [comment]
> (Sorry for not getting it!)

No worries, just it felt hard for an example so I didn't try to go further, though thanks, I think I have one:

Let's take this as an example:
```html
<button click.trigger="onClick($event)">
```
If we are to `evaluate the expression and if the result is a function, invoke it`, then if `onClick($events)` evaluates to a function, we are gonna call that function too. I think this is a surprise, since the intention is to only call `onClick`.

**Comment by jwx** [comment]
Yeah, that's what I would call an additional feature. But in any case, I don't really see it as a problem. Especially if the documentation mentions this along with the `true`/`false` feature. Also, if someone would return a function from `onClick($events)` in your example, I'd assume their intention is for the returned function to be called.

**Comment by bigopon** [comment]
> that's what I would call an additional feature

I'm tempted to say this could be just that, though this would make the meaning of an event handler no longer just "event handler". I'm hesitant on this. Though it could be toggled via something like this
```ts
aurelia.register(ListenerBindingOptions.create({
  invokeIfFunction: true
}))
```
cc @Sayan751

**Comment by Sayan751** [comment]
I agree on the point of ambiguity. IMO that's additional work we might want to avoid. Because it is possible to return function that is nested infinitely. Then the question is where to draw the line.

Also I have a question with the original proposal. I gather that the intention is to reduce the verbosity. To that end, if the `EVENT.handler` is a new binding command then it the cleanest. We can additionally go further and restrict it as an alias to `EVENT.trigger($event)`.  But if we go further to implement the `EVENT.delegate|trigger|call.handler` variants then the original intention of reducing verbosity is not met. On the other hand, once we create the alias, there will invariably expectations for other variants. That's why I am skeptical about the value added by implementing this feature.

I think this whole thing can be tackled by documentation showing how to create such aliases on userland.

**Comment by jwx** [comment]
> Because it is possible to return function that is nested infinitely. Then the question is where to draw the line.

We don't draw the line. If the dev does that, it'll be a bug in their code.

I've assumed this change has also had the intention of making `click.trigger` more similar to the equivalent to (for example) Vue, who already supports this. (I know at least a couple of Vue devs who got a bit frustrated by this when transitioning to Aurelia.)

**Comment by brandonseydel** [comment]
> > Because it is possible to return function that is nested infinitely. Then the question is where to draw the line.
> 
> We don't draw the line. If the dev does that, it'll be a bug in their code.
> 
> I've assumed this change has also had the intention of making `click.trigger` more similar to the equivalent to (for example) Vue, who already supports this. (I know at least a couple of Vue devs who got a bit frustrated by this when transitioning to Aurelia.)

Basically yes....most other frameworks are offering the ability to pass the function and it will be invoked with all parameters without having to specify each individual one.  Many of my suggestions are peaked from other developers heartaches with the framework (most are ergonomics).  I couple of bad run ins when they pick up the framework is enough for people to set it down.  I am trying to remove every possibility of a gotcha or lack of feature.

**Comment by Sayan751** [comment]
I think instead of adding this to the core framework, we can make the proposed aliases/redirects via a "toolbox" package. Or those can even be part of the core package, but are effective only when opted-in (registered with DI).

**Comment by jwx** [comment]
If I understand @brandonseydel correctly, having things opt-in doesn't prevent the run ins he's trying to eliminate.

I don't think that we can add everything and the kitchen sink to the core, but (with my very limited knowledge of the relevant code) this seems like pretty low hanging fruit.

**Comment by brandonseydel** [comment]
> If I understand @brandonseydel correctly, having things opt-in doesn't prevent the run ins he's trying to eliminate.
> 
> I don't think that we can add everything and the kitchen sink to the core, but (with my very limited knowledge of the relevant code) this seems like pretty low hanging fruit.

I feel like it is fairly simple and has a representation in almost all frameworks.  Evaluate the expression if the expression result is a function invoke that function with ALL the parameters from the caller.  This will introduce even neater features as well as unlocking really nice curried function capabilities. I think I explained it very verbose to @bigopon on discord so hopefully he has some insight.

**Comment by bigopon** [comment]
We have 2 ways to do this:
1. opt-out: By default, it'll evaluate the expression, and if the result is a function, then treat it as a handler. This introduces a breaking change behavior. I don't know how big the impact would be. Also, it's quite weird that event handler isn't really a handler in this case.
2. opt-in: by default, it'll behave like v1, and if an applications wants to make it `if it evaluates to a function, call it` then it needs to add the following:
```ts
aurelia.register(ListenerBehavior({ callHandler: true })
```

I'm quite not sure what we should go for in this case. opt-out (1) is both intuitive and weird. opt-in (2) is good, though a bit of boiler plate. Maybe we can just group it in our `aurelia` package, or the `extended` package.

**Comment by Sayan751** [comment]
>  opt-in (2) is good, though a bit of boiler plate.

Which is why I suggest for a toolbox/utility package for such ease-of-use features.
