### ISSUE TITLE
Make it easier to access the composed view-model inside of the au-compose element

### ISSUE THREAD

**Issue by Vheissu** [aurelia/aurelia#1314]
# 🙋 Feature Request

In Aurelia 1, we would create a reference to the composed view-model inside of `<compose>` using this approach `<compose view-model.ref="myCompose"></compose>` and then referencing the `currentViewModel` property. In Aurelia 2, we still have `view-model.ref` for the newer `au-compose` element, but because of the way components are passed as constructable components, `view-model.ref` doesn't function the same way.

## 🤔 Expected Behavior

The `view-model.ref` binding used on `<au-compose>` should allow the composed view-model to be accessible, not the constructible instance.

## 😯 Current Behavior

When you attempt to access the view-model using `view-model.ref="myCompose"` and then `myCompose.viewModel` you can see the value is showing the definition of the class `class SomeCustomElement {}` but it's not instantiated yet, so you can't access properties or methods on it.

## 💁 Possible Solution

The composed view-model is already accessible inside of `au-compose` and accessible from the reference.

```
this.stepViewModel = this.composeRef.composition.controller.viewModel;
```

The CompositionController has a `viewModel` property which acts like the `currentViewModel` property in Aurelia 1. We could either keep it like it currently works and document this quirk. Or, we could change the behaviour of the `au-compose` element to make the `viewModel` property on the reference the instantiated class.

## 🔦 Context

I have a step-based wizard built with Aurelia 1. In my attempt to port this over, I needed to be able to query the children and access their view models.

**Comment by bigopon** [comment]
Accessing `myCompose.viewModel` means accessing the **bindable** property `viewModel`, which normally is a constructor. I guess this is a documentation issue, where it is not clear how to access the the view model of the current composition. It is as you noted:
```ts
composition.controller.viewModel;
```
One thing we can do is to define a `viewModel` property on `composition`, so that it can just be
```ts
composition.viewModel;
```
so that `controller` can stay out of the application code since it's not commonly needed.
```ts
composition.controller.viewModel === composition.viewModel
```

Though this could create some unnecessary confusion/questions. I guess we should just doc it with
```ts
composition.controller.viewModel;
```
first and see how it goes.

Can you help with a doc PR for this area @Vheissu ?

**Comment by Vheissu** [comment]
@bigopon I agree, it's definitely a documentation issue. I think the ideal solution would be to document this and it's not a problem. It saves having to modify the `au-compose` element and it also saves having to modify test cases and other work. Once I worked out where the instantiated component viewModel lived, it all made sense to me. I'll get a PR sorted out for this.

**Comment by Alexander-Taran** [comment]
ping @Vheissu (-:

**Comment by Vheissu** [comment]
Looking at this today.

**Comment by Vheissu** [comment]
@bigopon @Alexander-Taran This is now documented. This issue can be closed: https://docs.aurelia.io/getting-to-know-aurelia/components/dynamic-composition#accessing-the-view-model
