### ISSUE TITLE
[$50] Aurelia browser extension does not work on Au2 sites

### ISSUE THREAD

**Issue by MaximBalaganskiy** [aurelia/aurelia#1315]
# 🐛 Bug Report

Aurelia browser extension does not work on Au2 sites.
![image](https://user-images.githubusercontent.com/3712700/141868768-f4b21856-1f25-4761-8303-db1538fd1ed2.png)

Reinstall does not help.
At the same time, the extension works for Au1 sites displaying duplicate properties.
![image](https://user-images.githubusercontent.com/3712700/141868866-a4358ca3-9478-42b2-9462-299bb4661c06.png)
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Browser          | Chrome 95.0.4638.69, Edge 95.0.1020.53 
| Operating System | Windows 10, Windows 11

**Comment by bigopon** [comment]
@brandonseydel are you aware of any issues like this?

**Comment by brandonseydel** [comment]
Let me look into this.

**Comment by hiaux0** [comment]
This issue was selected to be a bounty 
https://discourse.aurelia.io/t/bounties-for-smaller-aurelia-tasks/4510

**Comment by MaximBalaganskiy** [comment]
The proposed PR still has issues
* `$au` usage
* if a component has a binding which value is current `window` for example, DevTool crashes with an exception `Object reference chain is too long`
