### ISSUE TITLE
Optional ShadowDom per component

### ISSUE THREAD

**Issue by AStoker** [aurelia/aurelia#1320]
# 🙋 Feature Request
We need the ability to specify particular components to NOT use Shadow Dom. Currently, by convention, everything is using shadow dom, but we have a plugin that (unfortunately) does not play well within a shadow node. We want to keep the convention the same of having everything use shadow dom by default, but have the ability to specify certain components to not use it.

Right now to achieve this result we have to manually add the `@customElement` decorator and fully specify all dependencies, resources, and template. While feasible, this causes us to break the pattern of importing other custom elements in the html (as we have to list them under dependencies instead).

There is already a decorator called `@useShadowDom`, but it's set up for configuring a particular shadow option (open or closed). Perhaps we could also add a "false" option to disabled the shadow dom without having to completely break out of the convention of defining elements.

## 🤔 Expected Behavior
We should be able to use some kind of new or existing decorator to not use shadow dom while still keeping the other conventions intact.

## 😯 Current Behavior
The only way to specify a custom element to not use shadow dom is to manually create a custom element with the `@customElement` decorator and respecify all the defaults, minus the shadow dom option.

## 💁 Possible Solution
Right now to achieve this result we have to manually add the `@customElement` decorator and fully specify all dependencies, resources, and template. While feasible, this causes us to break the pattern of importing other custom elements in the html (as we have to list them under dependencies instead). 

A desirable approach would be to either reuse an existing decorator (such as `@useShadowDom`) or create a new decorator (such as `@noShadowDom`) to allow the developer to keep the conventions but specifically disable shadow dom on this component.

## 🔦 Context
We are trying to use a WYSIWYG editor (RoosterJS specifically), but unfortunately all the editors we've come across rely on some kind of `getSelection`, which does not translate over shadow dom currently. The result is that cursor positions get screwed up and placed incorrectly.
The solution (currently) is to not have our editor placed inside shadow elements. That means the app root as well as the custom element that shows the editor need to not be within a shadow dom.

## 💻 Examples

Here is a sample project with shadow dom disabled, which enables the RoosterJS editor: https://github.com/AStoker/aurelia-roosterjs

**Comment by bigopon** [comment]
At the moment, the ways containerless and shadow DOM work are quite similar, they are predetermined early and quite impossible to change after the definition construction. Sometimes this make it inflexible to develop higher level feature/refactor/optimize the code around this part of the `controller.ts`. I've been always thinking that it needs to be refactored a bit, so I'll have a look to see how a per instance configuration mode can work properly & ergonomically.

**Comment by bigopon** [comment]
For this, I think we should extend our discussion to: ability to override `shadowDom` per usage. It has 2 cases of overriding like this:

1. custom element has `shadowOptions` in `@customElement` decorator, and `shadow-dom="false"` on the element usage
```ts
@customElement({ shadowOptions: 'open' })
export class MyElement {}
```

```html
<my-element shadow-dom="false">
```

2. custom element does NOT have `shadowOptions` in `@customElement` decorator and `shadow-dom="open"` or `shadow-dom="closed"` on the element usage:
```ts
@customElement()
export class MyElement {}
```

```html
<my-element shadow-dom="open">
<my-element shadow-dom="closed">
```

This behavior also be extended to `containerless` probably.

cc @fkleuver @Sayan751 @zewa666

**Comment by bigopon** [comment]
I think I've understood the motivation of this feature request more. I believe this should achieve it:
in template `my-component.html`
```html
<use-shadow-dom mode="open">
or
<use-shadow-dom mode="closed">
```
For my comment above https://github.com/aurelia/aurelia/issues/1320#issuecomment-1110869315, I think we may need to consider more, since if it was enabled, there will be messy situation where css encapsulation no longer works.

**Comment by bigopon** [comment]
I'll close this for now, since I believe the request can be resolved already with the current convention. We can continue the discussion in another issue if that's not the case.
