### ISSUE TITLE
Docs: How to build a plugin

### ISSUE THREAD

**Issue by Vheissu** [aurelia/aurelia#1330]
Aurelia 2 made it considerably easier and more powerful to create your own plugins. We need to document how you can create plugins that cover simple use cases as well as documenting how to create plugins that accept configuration options upon instantiation.

* Dealing with dependency injection
* Working with start up tasks to delay calling and registering parts of your code
* Global resources (plugins that create resources to be used in apps already registered with DI)
* Plugins that accept configuration options (UI libraries)

**Comment by LloydNicholson** [comment]
Hey @Vheissu. I hope you are well. This would be a really useful section to have included in the docs. Thank you. I am currently struggling a bit with this as I am not a typescript wiz.

**Comment by Vheissu** [comment]
We have a section on building plugins here and I am now closing this: https://docs.aurelia.io/developer-guides/building-plugins
