### ISSUE TITLE
Router: Binding using params.bind is broken on the load attribute

### ISSUE THREAD

**Issue by Vheissu** [aurelia/aurelia#1338]
The load attribute supports supplying a component/path as well as any parameters to be bound using `params.bind` in the router, `params.bind` is broken. In the example app, you can see that the URL for the "View Profile" tab resolves to `http://localhost:9000/profile(name=rob)` which appears to be using a form of direct routing syntax. This URL should match that of the defined path in `my-app.ts` and look like this: `http://localhost:9000/profile/rob`

**Comment by Sayan751** [comment]
@Vheissu I think there is a configuration mistake for the routes.

The routes for the `profile` is defined as follows:

```ts
    {
      path: 'profile/:name',
      component: ViewProfile,
      title: 'View Profile'
    },
```

Note that there is a `id` property in the routing configuration option, and when that is absent, the `path` is used as fallback for `id`. When you use the `load` custom attribute like this: `<a load="route:profile; params.bind:{name: 'rob'}">View Profile</a>`, the value bound to the `route` property is used as the `id` to search among the configured routes. When none found, the direct routing variant is used as fallback. So with this situation can be corrected by adding a `id` property to the routing configuration:

```ts
    {
      id: 'profile',
      path: 'profile/:name',
      component: ViewProfile,
      title: 'View Profile'
    },
```

Contextually, it can be noted that with the previous configuration in place, `<a load="route:profile/:name; params.bind:{name: 'rob'}">View Profile</a>` will also work. However, adding a `id` property might be more ergonomic.

I think we can update the docs accordingly, and this issue can be closed.
