### ISSUE TITLE
Router: Fallback value does not work on au-viewport

### ISSUE THREAD

**Issue by Vheissu** [aurelia/aurelia#1343]
Quite a common scenario in an application with routing is a fallback for when someone attempts to visit a route that does not exist. We are supposed to have a `fallback` attribute on the `au-viewport` custom element. In fact, the default `npx makes aurelia` application with routing adds in a viewport element with the fallback attribute: `<au-viewport fallback="missing-page"></au-viewport>`

In the provided example application, attempt to visit a URL that does not exist. Just type some gibberish into the URL: `http://localhost:9000/fkjsdfkjlsd8798` you'll get a console error saying the route doesn't exist, but the `fallback` property of `missing-page` 

Furthermore, I attempted to create this fallback value as a route inside of my-app.ts (you'll see it commented out) to no avail.

I think the current fallback approach is actually quite flawed. The fallback behaviour should be consistent with Aurelia 1 where we had a method called `config.mapUnknownRoutes('not-found');` which allowed us to redirect missing routes to another route. I think this should be similar in v2 where we specify what the fallback route looks like.

**Comment by Sayan751** [comment]
This can be closed once the PR #1387 is merged. The fallback specified in `au-viewport` works as expected. Moreover, a global `fallback` is added to avoid specifying a `fallback` property in every `au-viewport`. You can refer the [tests](https://github.com/aurelia/aurelia/blob/d82474cdd444b79399a4921f88c9297ff4241042/packages/__tests__/router-lite/smoke-tests.spec.ts#L790-L1094) for this.
