### ISSUE TITLE
Custom elements do not appear in local templates.

### ISSUE THREAD

**Issue by michaelnero** [aurelia/aurelia#1373]
# 🐛 Bug Report

I'm not able to use custom elements in local templates. This is easily reproducible; you can check out the gist here: https://gist.dumber.app/?gist=018dd79b7b043b8f99403c735dcaa04f

Note in the linked gist that using `<import>` inside the local template doesn't seems to have any affect.

## 🤔 Expected Behavior

Custom elements should work in local templates as well.

**Comment by Sayan751** [comment]
Note that You need to register the custom element as follows:

```ts
import Aurelia from 'aurelia';
import { MyApp } from './my-app';
import { SolidIcon } from './solid-icon';

Aurelia
  .register(SolidIcon) //<-- custom element registration
  .app(MyApp)
  .start();
```

Then it should work. With the custom element registered, you can also remove the imports from the HTML.

```html
<!--<import from="./solid-icon"></import>-->

<h1>${message}</h1>
<solid-icon></solid-icon>
<person-info></person-info>

<template as-custom-element="person-info">
  <!-- I added the following import to attempt to fix this, but removing it has no affect -->
  <!-- <import from="./solid-icon"></import>  -->
  <p>Hello from a custom template</p>
  <solid-icon></solid-icon>
</template>
```

**Comment by michaelnero** [comment]
Hm, I might be a bit confused by how to create and use components. The [documentation](https://docs.aurelia.io/getting-to-know-aurelia/components#registering-your-components) does show registering a component in that way, but the way I interpreted the docs is that you can either register your component globally (like you showed), or within the template by using `import`.

Do I need to globally register _all_ of my components? Or just in this specific scenario when trying to use a component within a local template?
