### ISSUE TITLE
Cannot use colon in html class name (CSS Modules)

### ISSUE THREAD

**Issue by aegenet** [aurelia/aurelia#1386]
# 🐛 Bug Report

When using CSS modules, if an html class contains a colon ':' in its name, an exception is thrown.

```html
<div class="md:left-0"></div>
```

## 🤔 Expected Behavior

Use the html class name as expected.

## 😯 Current Behavior

Aurelia tries to bind the `md` property into `class` :

```typescript
'AUR0707:class.md'
```

```typescript
'Uncaught Error: Bindable md not found on class.'
```

## 💁 Possible Solution

Don't use the colon ? If you are using Tailwind CSS, you can change the separator by configuration:

```javascript
// `tailwind.config.js`
module.exports = {
  separator: '_', // : by default
  /* ... */
}
```

Or, simply, don't use CSS modules.

## 🔦 Context

Tailwind CSS cannot be used without changing the default separator.

## 💻 Code Sample

**Repository**: https://github.com/aegenet/au2-issue-css-colon

```bash
git clone git@github.com:aegenet/au2-issue-css-colon.git
cd ./au2-issue-css-colon
yarn run test
```

**Snippet**

```css
.md\:message {
  background-color: lightblue;
}
```

```html
<div class="md:message">${message}</div>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | 2.0.0-alpha.27
| Language         | TypeScript
| Browser          | Chrome/Firefox
| Bundler          | Webpack (`CSS Modules`)
| Operating System | Windows 11
| NPM/Node/Yarn    | Yarn 1.22.17

**Comment by bigopon** [comment]
Thanks for this bug, I'll investigate. It's an interesting case, and certainly the stance won't be "don't use colon", at least for now.

**Comment by Sayan751** [comment]
I have only seen usage of colon in CSS selectors limited to pseudo class. If you really want to use colon as the class name then you might want to escape it with `\:` or `\3A`.

Refer: 
- https://mathiasbynens.be/notes/css-escapes
- https://mothereff.in/css-escapes#0search%5fform%3Aexpression

**Comment by aegenet** [comment]
Thanks for your comment. Unfortunately, the issue is not in the declaration (css/scss side), but when we use the class name.
If you look at the [repo](https://github.com/aegenet/au2-issue-css-colon/blob/master/src/my-app.scss#:~:text=.md-,%5C%3A,-message%20%7B), I have already, like Tailwind CSS, escaped the colon.

We can't escape the ':' in HTML: we bypass the error and... nothing. The class name is not the same in css (`xx:yyy` VS `xx\:yyyy`).

**Comment by Sayan751** [comment]
@bigopon Although the reason for the error is clear, the solution might be to unescape the colon can treat that as attribute value. That is when I use `class="foo\:bar"` then it works fine, but the class applied is "foo\:bar" instead of "foo:bar". Therefore, a general rule can be to unescape the colon when found in an attribute value of string literal. That way it doesn't need to be specific to class attribute, and rather can be part of the generic template compiler. What do you think?

**Comment by Sayan751** [comment]
On a second thought, it might easier and wiser to unescape the value in the class attribute itself. That should have less ripple effect. We can also add this in the doc that a colon in a string literal must be escaped, and the corresponding CA should take the responsibility to unescape that.

**Comment by bigopon** [comment]
At the moment, this is only an issue when shadowDOM is used, because it hijack `class` attribute with a `class` custom attribute. I think we can find a way to do it, especially when there' many way of hooking into the pipeline: `compiling` hook from the compiler, binding command, attr syntax.

**Comment by Sayan751** [comment]
> attr syntax

Awesome would be to create a plugin for Tailwind CSS to support something like `class.tw.md="foo-bar"` 😁
