### ISSUE TITLE
@parcel/core: Failed to resolve component

### ISSUE THREAD

**Issue by nenadvicentic** [aurelia/aurelia#1408]
# 🐛 Bug Report

I've created new, barebone Aurelia project using `npx make aurelia`.
Project uses:
TypeScript, SCSS and Parcel.

Following the tutorial for router-configuration, I modified/added following files
`main.ts`
```typescript
import { RouterConfiguration } from '@aurelia/router-lite';
import Aurelia from 'aurelia';
import { MyApp } from './my-app';

Aurelia
  .register(RouterConfiguration)
  .app(MyApp)
  .start();
```
`my-app.ts`
```typescript
import { IRouteViewModel, route } from "aurelia";

@route({
  routes: [
    {
      path: ['', 'home'],
      component: import('./components/home-page'),
      title: 'Home',
    }
  ]
})
export class MyApp implements IRouteViewModel {
  public message = 'Hello World!';
}
```
`my-app.html`
```html
<div class="message">${message}</div>
<au-viewport></au-viewport>
```
`components/home-page.html`
```html
<h1>This is the home-page</h1>
```
`components/home-page.ts`
```typescript
export class HomePage {
    
}
```
`tsconfig.json`
```json
{
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "module": "ES2022",
    "moduleResolution": "node",
    "skipLibCheck": true,
    "target": "ES2017",
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "sourceMap": true
  },
  "include": [
    "test",
    "src"
  ],
  "files": [
    "src/resource.d.ts"
  ]
}
```
## 🤔 Expected Behavior

I'm expecting site to run on `http://localhost:9000` and to show content from `home-page.html` after the "Hello World!" message.

## 😯 Current Behavior

Parcel shows error in command line:
```cmd
> au-project-1@0.1.0 start
> parcel -p 9000

Server running at http://localhost:9000
× Build failed.

@parcel/core: Failed to resolve 'b8fed70fb39c8137' from './src/my-app.ts'

  C:\Users\nvicentic\source\repos\aurelia2-projects\au-project-1\src\my-app.ts:7:25
    6 |       path: ['', 'home'],
  > 7 |       component: import('./components/home-page'),
  >   |                         ^^^^^^^^^^^^^^^^^^^^^^^^^
    8 |       title: 'Home',
    9 |     }

```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | 2.0.0-alpha.29
| Language         | TypeScript
| Browser          | Any
| Bundler : Parcel         | 2.5.0
| Operating System | Windows 11
| NPM/Node/Yarn    |  v16.14.0/8.3.1/1.22.18

**Comment by bigopon** [comment]
it also errs when doing
```diff
- component: import('./components/home-page')
+ component: () => import('./components/home-page')
```

This seems weird, since it' just some normal standard JS import. @3cp

**Comment by 3cp** [comment]
Parcel should support dynamic import by default.
https://parceljs.org/features/code-splitting/#using-dynamic-imports

I will do some tests, to see what's missing.

**Comment by 3cp** [comment]
It's indeed caused by our customised parcelrc. But I don't understand why at the moment.

**Comment by nenadvicentic** [comment]
@3cp I had to add in `tsconfig.json` additional entry for my project's TypeScript compiler to stop complaining:
`"module": "ES2022"`

Is it possible that you're simply missing this in configuration that parcel plugin is using for Aurelia?

It would be also great if missing entry above can be added to the Aurelia project template by default, because, as soon as someone uses dynamic import, they will run into issues. The entry is present when using `WebPack` or `Dumber` template (altough it's `"module": "esnext"`).

**Comment by 3cp** [comment]
Our parcel plugin doesn't play or use the tsconfig.

The config means after our plugin, continue to apply all default transformers for ts file.
```
"*.ts": ["@aurelia/parcel-transformer", "..."],
```

I think the minimum "target" for tsc to retain `import()` is ES2020. But I am not sure do we want to set that as default, as we don't want to assume users only want to support latest browsers.

Even with "module" and "target" in tsconfig, it didn't fix this issue.
Another interesting fact is this issue doesn't apply to parcel+babel setup.

There is something funny going on for the TypeScript setup.

**Comment by nenadvicentic** [comment]
It's not about `target` property. It's about `module` property.

[module](https://www.typescriptlang.org/tsconfig#module) affects `moduleResolution` by compiler. Since, in order to [create a route](https://docs.aurelia.io/developer-guides/routing/creating-routes), we have to use `import(...)`, it immediately creates compiler error. Therefore, as soon as we try to configure route in a new project, we get compiler error  in the IDE. Of course, compilation fails as well.

If you check my `tsconfig.json` I used `"module": "ES2022"`, while still using `"target": "ES2017"`. Your own `WebPack` and `Dumber` templates to exactly that. This is Webpack:
```json
{
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "module": "ES2020",
    "moduleResolution": "node",
    "skipLibCheck": true,
    "target": "ES2017",
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "sourceMap": true
  },
  "include": [
    "test",
    "src"
  ],
  "files": [
    "src/resource.d.ts"
  ]
}
```

**Comment by 3cp** [comment]
Oh, thx. Will update the skeleton for that warning.

**Comment by 3cp** [comment]
Our skeleton is already use `"module": "esnext",` which is always on latest es spec.

But we didn't turn it on when using jest. Jest (at least v27) needs to use `"module": "CommonJS"` which is the default.
```
{
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    // @if !jest
    "module": "esnext",
    // @endif
```

**Comment by nenadvicentic** [comment]
@3cp I'm talking from the top of my head, but think that correct solution would be to to have child `tsconfig.json` in `/tests` folder, which overrides `module` property only for tests, if needed.

Current solution, that you described, basically, breaks routing, when `jest` is used for tests.

**Comment by 3cp** [comment]
Just found out ts-jest will force commonjs regardless the setting in tsconfig.
It's probably a change in ts-jest after I created the au2 skeleton repo 2 yrs ago.

I removed the condition check in our skeleton.

**Comment by nenadvicentic** [comment]
Are there any news about fix in `@aurelia/parcel-transformer`?

I have tried version `2.0.1-dev.202207260540` and having exactly the same problem.

I looked at the code of `@aurelia/parcel-transformer` and there is nothing there that is Typescript specific. I won't pretend that I understand what the plugin does exactly, but to my mind, it seems that issue is configuration of Typescript compiler that is triggered by `preprocess` function (`import { preprocess } from '@aurelia/plugin-conventions';`).

**Comment by 3cp** [comment]
It's not tsc, the error is from parcel internal (likely this [resolver](https://parceljs.org/features/plugins/#resolvers)) we didn't quite understand.

It didn't affect babel setup, but only ts. That fact is really strange.

**Comment by 3cp** [comment]
Found a strange fix.

update `.parcelrc` from

```
"*.ts": ["@aurelia/parcel-transformer", "..."],
```

to 

```
"*.ts": ["@aurelia/parcel-transformer", "@parcel/transformer-typescript-tsc"],
```

Could be related to this: https://parceljs.org/languages/typescript/#tsc

I will test more and update our skeleton.

**Comment by nenadvicentic** [comment]
@3cp  Thanks a lot man. This works.

> Could be related to this: https://parceljs.org/languages/typescript/#tsc

Yes, it completely makes sense:
*"you may need to use TSC if you are using some configuration in `tsconfig.json` that Parcel doesn't support"* -  so probably the same configuration option `module: "2020"`, that we discussed, is missing on parcel built-in transformer.

> I will test more and update our skeleton.

I tested a bit more myself. Page in the browser is not reloading, when project files are changed (both `*.ts` and `*.html`) even though in the console, it's clear that parcel rebuilds the project.

In addition this issue #1485 is present in both Parcel and Webpack. It's not limited only to Dumber as I initially thought.

**Comment by 3cp** [comment]
There is another issue. We added some HMR support in our plugin, but never tested on parcel.

Now parcel saw there is some HMR api in our code, and try to do HMR and failed.
You have to manually reload the page for now.

**Comment by nenadvicentic** [comment]
@3cp No problem for reloading manually, just wanted to document the behavior.

> We added some HMR support in our plugin, but never tested on parcel.

Also, as I wrote, it's same behavior in WebPack and Dumber as well. Probably due to the same HML module.

**Comment by 3cp** [comment]
I will update the config in our skeletons to explicitly turn off hmr except webpack for now.
In few days.

**Comment by 3cp** [comment]
aurelia/new#84
