### ISSUE TITLE
Repeater bug with a race condition

### ISSUE THREAD

**Issue by Alexander-Taran** [aurelia/aurelia#1425]
# 🐛 Bug Report

Having a tree structure rendered recursively twice, when altering nested arrays, exception happens

## 🤔 Expected Behavior

No exception and modified structure is rendered correctly both times.

## 😯 Current Behavior

![image](https://user-images.githubusercontent.com/1029452/169155512-97b6a372-31b2-465a-9920-87ad810bcf6b.png)

## 🔦 Context

I want to render a tree and a control hierarchy of the same tree using `compose`

## 💻 Code Sample

Full repro attached in archive.
[observation-repro.zip](https://github.com/aurelia/aurelia/files/8749493/observation-repro.zip)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | 2.alpha.31
| Language         | TS
| Browser          | Chrome
| Bundler            | Parcel
| Operating System | Windows 10 / Wsl
| NPM/Node/Yarn    | node 18

**Comment by bigopon** [comment]
this is a bug related to the repeater not detecting the state of corresponding collection properly, it's probably not an observation bug.

**Comment by Alexander-Taran** [comment]
@bigopon 

I could not track yet where synthetic view in repeater becomes undefined.. 
What if we just add `continue` if `view === undefined` ?

```ts
    for (; i >= 0; --i) {
      view = views[i];
      if(!view) continue;
      next = views[i + 1];

      view.nodes.link(next?.nodes ?? location);
```

**Comment by Alexander-Taran** [comment]
Ok even weirder.. after drag'n'drop operation (while both copies of the tree are rendered) one of the checkboxes stops working as well

**Comment by bigopon** [comment]
For the checkbox that stopped working, it's probably because of the uncaught error?
For the main issue and the suggested fix, we probably cannot do that, as it would make the logic flaky, since we can't tell why something in the control could go `undefined`. There should be a way to fix it without compromising its robustness.

**Comment by Alexander-Taran** [comment]
@bigopon updated the repro archive with a button to reproduce the issue (-:


![repro](https://user-images.githubusercontent.com/1029452/169697271-a5fae4ed-eb47-4c1e-b73d-203f8921d720.gif)

**Comment by Alexander-Taran** [comment]
@bigopon 

My hero!!! ❤
