### ISSUE TITLE
RFC: Change dist target to es2020

### ISSUE THREAD

**Issue by bigopon** [aurelia/aurelia#1427]
# 💬 RFC

At the moment, we are compiling to es2018 for the dist files. One of the pros of this is that es2018 is a good middle ground between features and complexity in end application tooling. One of the cons of having dist files in es2018 is that it results in more unideal code, because we employ quite a bit of optional chaining and Nullish coalescing syntaxes. The following code, for example:
```ts
obs = (pd.get?.getObserver ?? pd.set?.getObserver)?.(obj, this)
```
will be compiled into something like this
```js
obs = (_d = ((_b = (_a = pd.get) === null || _a === void 0 ? void 0 : _a.getObserver) !== null && _b !== void 0 ? _b : (_c = pd.set) === null || _c === void 0 ? void 0 : _c.getObserver)) === null || _d === void 0 ?
```
The compiled code is bigger, probably slower and harder to follow when debugging without sourcemap.

If we are to change our dist format to es2020, the compiled code will be exactly the same with the source. One of the cons of compiling to es2020 is that it results in complexity in compilation for end application tooling, if they are to target browsers that aren't supporting es2020 features yet.

Can I use: https://caniuse.com/mdn-javascript_operators_optional_chaining
![image](https://user-images.githubusercontent.com/9994529/169673573-16e92b46-1f54-41e5-889d-b9e1ff62114c.png)

Browsers market share statistics: https://www.stetic.com/market-share/browser/

A few questions we can look at in details:
- Aurelia applications end users statistics: are users of Aurelia applications on Safari older than `13.3.4`? What are the percentages of those users.
- Can we provide a guide to help application configure the compilation of es2020 to es2018 and older easier.

**Comment by 3cp** [comment]
Why not keep the default dist cutting-edge?

We planned to ship another dist with IE11 compatible. Since IE11 is EOL this June, maybe we can readjust the coming compatible dist target to somewhere between ES5 to ES2018?

If we say default dist is -2yr, then it's ES2020. Compatible dist is -5yr, then it's ES2017. I think we don't need any additional polyfill to support ES2017 which is much nicer than IE11.

**Comment by bigopon** [comment]
Nice comment/reminder @3cp , thank!

Indeed with IE11 entering EOL this June, and v1 support not getting deprecated, I think it's undesirable to have a compat dist to support IE11. The strategy of -2/-5 seems pretty reasonable, maybe we can follow it this way/make it our policy.

**Comment by Alexander-Taran** [comment]
![finish-him](https://user-images.githubusercontent.com/1029452/169701401-06281f25-37f8-45eb-b5f1-812d4f482acb.gif)
