### ISSUE TITLE
Webpack loader having an issue when using a named component and shadow dom

### ISSUE THREAD

**Issue by brandonseydel** [aurelia/aurelia#1434]
# 🐛 Bug Report

## 🤔 Expected Behavior
Shadow dom is allowed

## 😯 Current Behavior

Shadow dom is turned off with console warning

## 💁 Possible Solution

Use the name defined on the CE instead of the file name from the unit to determine if it is valid.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          |
| Language         |
| Browser          |
| Bundler          |
| Operating System |
| NPM/Node/Yarn    |

**Comment by brandonseydel** [comment]
@3cp - see above

**Comment by 3cp** [comment]
Can you show me the warning message?

**Comment by 3cp** [comment]
Oh, I think I got what you mean now. :-) will fix.

**Comment by 3cp** [comment]
This is actually troublesome.
When we process `foo.js` (or .ts) and `foo.html`, the two files are processed almost independently (at least without peeking each other's content).

The shadow mode is one line of config in compiled `foo.html` js code.
```js
export const shadowOptions = { mode: 'open' };
```

The warning was printed while we process `foo.html` without knowing the content of `foo.js`. So `foo.html` didn't know where is another manual `@customElement` decorator in `foo.js`.

I propose:
1. skip the tag-name check in our preprocessor. Don't warn at compile time.
2. warn at runtime if the real tag-name is not acceptable for shadow dom.

This is probably needed, as user can even use variable as the tag-name.
```js
import * as viewDef from "./foo.html";
@customElement({ ...viewDef, name: some_composed_name })
export class Foo {}
```

cc @bigopon

**Comment by bigopon** [comment]
We can have it as 2 step compilation. First assemble the parts (view/ view model) and then do verification. Would that be better?

**Comment by 3cp** [comment]
As my example code above, the element name can be a variable which is not statically analysable.

**Comment by brandonseydel** [comment]
> As my example code above, the element name can be a variable which is not statically analysable.
> 
> 

I actually am using a configurable prefix to make this argument hold more water.

**Comment by bigopon** [comment]
> As my example code above, the element name can be a variable which is not statically analysable.

We can make an assumption that if the element name is not analyzable, devs know what they are doing. Leave it to runtime to throw if inappropriate. Same way can be applied to some other areas probably: when it's hard, assume.

**Comment by 3cp** [comment]
If runtime is (going to) throwing the error, I think we can keep preprocessor simple by not doing any check.

**Comment by brandonseydel** [comment]
@3cp you want to remove the check then?  I can take care of that?

**Comment by 3cp** [comment]
It's a decision for @bigopon :-)

**Comment by bigopon** [comment]
Yeah sure lets let runtime handle that for now. Please help with a PR if you are already ready @brandonseydel
