### ISSUE TITLE
Difficulty using UMD

### ISSUE THREAD

**Issue by bigopon** [aurelia/aurelia#145]
I have had some difficulty using UMD with webpack, both via my local setup and stackblitz / codesandbox, though it theoretically shouldn't cause any issue. I think we should switch it to either commonjs or es2015 and let consumer decide what they want to do with it. Note that it happens when i'm using JS, not TS

@EisenbergEffect @fkleuver

**Comment by bigopon** [comment]
Having a look at umd output, it is easy to conclude that the format is not for distributing plugin / lib without concatenation or module hoisting.

**Comment by fkleuver** [comment]
Have you tried with a different format? I had the same issue with commonjs in the examples with Parcel. I believe this is due to semver issue. The modules get duplicated.

**Comment by bigopon** [comment]
Resolved by @fkleuver
