### ISSUE TITLE
[Router lite] ability to have local navigation

### ISSUE THREAD

**Issue by bigopon** [aurelia/aurelia#1461]
Assume that we have the following hierarchy of routes:
```
a /
  b /
    c /
      c1
      c2
    d /
      d1
      d2
```
and we are at `a/b/c/c1`, we want to programmatically navigate to `a/b/c/c2` without touching anything else. Pseudo code:
```ts
router.navigate('c2')
```

In v1, this can be done by injecting `Router` at `c` and call
```ts
router.navigate('c2')
```

In v2, with child router concept being replaced by `route context`, we can do it similarly via the global router of an application:
```ts
router.navigate(routeContext, 'c2')
```

The pros of v1 way is it's local, thus simple to learn & teach. Consider having the same capability on the route context in v2 router.

cc @Sayan751 @jwx

**Comment by Sayan751** [comment]
With `router-lite` it looks as follows: `roueter.load('path-relative-torouting-context', {context: routingContext})`. From that perspective, the new API can be `RoutingContext#load('path-relative-to-this')`. Note that this might not replace the existing router API, as the `context` there, is polymorphic:
https://github.com/aurelia/aurelia/blob/ffacade3eb6eb8158aad5105a5c6e84dd2830554/packages/router-lite/src/router.ts#L137-L146

**Comment by jwx** [comment]
In `router` you do
```html
<a load="relative-path">Description</a>
```
and
```ts
this.router.load(relativePath, { context: this });
```
in `custom-element.html` and `custom-element.ts` respectively and navigation will be in the context of the appropriate routing scope. There's  no need for the dev to get or know the actual routing scope. Relative path also supports routing scope traversal with `../`. In `router`, relative/local navigations are fundamental (and encouraged).

**Comment by Sayan751** [comment]
> In `router` you do
> 
> ```
> <a load="relative-path">Description</a>
> ```
> 
> and
> 
> ```ts
> this.router.load(relativePath, { context: this });
> ```
> 
> in `custom-element.html` and `custom-element.ts` respectively and navigation will be in the context of the appropriate routing scope. There's no need for the dev to get or know the actual routing scope. Relative path also supports routing scope traversal with `../`. In `router`, relative/local navigations are fundamental (and encouraged).

This is also possible in `router-lite`.
