### ISSUE TITLE
Lifecycle detached, and unbind not working with if.bind

### ISSUE THREAD

**Issue by gustavnilsson14** [aurelia/aurelia#1468]
# 🐛 Bug Report

When using if.bind to toggle component attachment to the DOM, when the condition evaluates as false, detached, and unbind is not fired on the removed component. Using latest aurelia npm package, and typescript

## 🤔 Expected Behavior

I expect that when the test: boolean is changed to false in the containing component, the testcomponent should be removed from the DOM (which happens), and also both detached, and unbind should run on my testcomponent (these functions do not fire)

## 😯 Current Behavior

There is no error, completely silent, and the functions do not run (i have tried both debugger; and console.log inside the functions)

## 🔦 Context

So, in one of my components, i send subscriptions (which are based on properties bound from the parent component) to my server when they are attached, and i need to be able to unsubscribe when the component detaches

## 💻 Code Sample

Containing component html looks like:

<require from="./components/pages/if-test/if-test"></require>
<div>
  <button click.delegate="iftest = !iftest">toggle</button>
  <if-test if.bind="iftest"></if-test>
</div>

The containing component has an iftest: boolean property

And in ./components/pages/if-test/if-test

export class IFTest {
  constructor() {
    console.log("constructor(){");
  }
  created(owningView: any, myView: any) {
    console.log("created(owningView: View, myView: View) {");
  }
  attached() {
    console.log("attached() {");
  }
  bind(bindingContext: Object, overrideContext: Object) {
    console.log("bind(bindingContext: Object,overrideContext: Object) {");
  }
  detached() {
    console.log("detached() {");
  }
  unbind() {
    console.log("unbind() {");
  }
}

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | latest
| Language         | typescript
| Browser          | edge and chrome
| Bundler          | webpack
| Operating System | win 11
| NPM/Node/Yarn    | NPM

**Comment by bigopon** [comment]
@gustavnilsson14 can you give a repro? Also, is this v2 or v1?

**Comment by gustavnilsson14** [comment]
this is v2
repro, or repo? in the case of the latter, https://github.com/gustavnilsson14/apoc-vtt
sorry for the file size, i have been working solo locally, and i didnt bother with a .gitignore :P
the example is in myapp.ts, and frontend\src\components\pages\if-test... there is a button there which toggles a component, and which should fire the detached/ unbind (and also bind, but thats not the problem i have atm) as the component is toggled off
i was thinking first that it was because im making it as a one page app, without routing (for now at least), but then i saw in the docs it should fire in this case
thank you for the quick response :)

**Comment by Sayan751** [comment]
@gustavnilsson14 Note that the lifecycle hook names have been changed in Au2; for your case, it needs to be `detaching` (instead of `detached`) and `unbinding` (instead of `unbind`). You can find the details here: https://docs.aurelia.io/getting-to-know-aurelia/components/component-lifecycles. 

Here is also an SB example that shows that the `if.bind` does work correctly: https://stackblitz.com/edit/au2-if-bind-gh-issue-1468

I am closing this issue, however, in case of any further questions, feel free to continue the discussion. ✌️

**Comment by gustavnilsson14** [comment]
Alright m8, big thanks for the help!
Honestly i was searching about for hours but never managed to come by that info :p
Next time i will clone the repo for a closer look
Keep up the good work ^^
