### ISSUE TITLE
`ValidationTrigger.changeOrFocusout` doesn't clear the errors when refocusing an input and writing into it

### ISSUE THREAD

**Issue by IonelLupu** [aurelia/aurelia#1470]
# 🐛 Bug Report

When using the `ValidationTrigger.changeOrFocusout` trigger, refocusing an input after it's invalid and writing in it, won't make the error go away

Replicate steps:
- open the Stackblitz link
- click Submit. The errors should display under each input
- write less that 10 characters in the last input. All the errors should still be there
- click on the second input (or any other input) and **add something to it**
- click on the last input again and add more characters until you have more than 10. Watch the error not disappearing. It should go away.

PS. focus out and now the error should disappear. 

(This is not the same behavior as in AU1)

## 🤔 Expected Behavior

Expecting the error message to go away.

## 😯 Current Behavior

The error message is still visible

## 💻 Code Sample

[Stackblitz](https://stackblitz.com/edit/au2-validation-validation-validationresultpresent-wxisnc?file=index.ts,src%2Fmy-app.ts)

## 🌍 Your Environment

(refer to Stackblitz)
| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          |
| Language         |
| Browser          |
| Bundler          |
| Operating System |
| NPM/Node/Yarn    |

**Comment by IonelLupu** [comment]
@Sayan751  You are right. I copied the wrong validation rules from my code. I updated the stackblitz link above. Retry the steps again pls. You will now see the error better

**Comment by Sayan751** [comment]
@IonelLupu I have corrected another inapplicable validation rule for `age`; there `.min` is expected, as it is of `number` data type. But I cannot still reproduce the error and just to ensure that we are not trying different steps, here is GIF of my steps. 

![au2-validation-gh-1470](https://user-images.githubusercontent.com/3128881/174876647-7a516d22-7af0-4ff1-8f4d-1fb10287fa91.gif)

**Comment by IonelLupu** [comment]
hey @Sayan751 . My steps were actually wrong. I updated them now above. In the steps where it says "click on some other input" it should also have been "and add something to that input".
