### ISSUE TITLE
Need to exclude some attributes from transferring.

### ISSUE THREAD

**Issue by brandonseydel** [aurelia/aurelia#1471]
# 🙋 Feature Request

There is no way to exclude attributes from transferring.

## 🤔 Expected Behavior

Ability to exclude attributes or any custom attributes maybe?

## 😯 Current Behavior

Doesn't exist 

## 💁 Possible Solution

@capture({exclude: [] | regex})

## 🔦 Context

Slot doesn't work
Validation-error attribute doesn't work
Seems like any CAs might need to be left alone for an option?

**Comment by bigopon** [comment]
> Seems like any CAs might need to be left alone for an option?

can you give an example?

**Comment by brandonseydel** [comment]
@bigopon - Maybe an option on the attribute to allow transferring?

**Comment by zewa666** [comment]
i think what we said is that order matters. if you spread first, Attributes defined afterwards will overwrite te spreaded ones.

**Comment by brandonseydel** [comment]
> > Seems like any CAs might need to be left alone for an option?
> 
> can you give an example?

I was just saying because of the validation-error attribute that others would arise since usually an end user would be applying a CA to the element rather than passing down.
