### ISSUE TITLE
ValidationController doesn't update the results when trigger is `changeOrFocusOut`

### ISSUE THREAD

**Issue by IonelLupu** [aurelia/aurelia#1476]
# 🐛 Bug Report

When having `DefaultTrigger = ValidationTrigger.changeOrFocusout` config for `ValidationHtmlConfiguration`:
```ts
.register(ValidationHtmlConfiguration.customize((options) => {
      options.DefaultTrigger = ValidationTrigger.changeOrFocusout;
    }))
```
and when I use .ensureObject() to add validation rules on my object:

```ts
  public constructor(
    @newInstanceForScope(IValidationController)
    private validationController: IValidationController,
    @IValidationRules validationRules: IValidationRules
  ) {
    this.person = new Person('bar', 41);
    validationRules
      .on(this.person)
      .ensureObject()
      .satisfies((p) => p.name === 'foo' && Number(p.age) === 42)
      .withMessage('Not foo@42');
    validationController.addObject(this.person);
  }
```
the errors displayed in the page don't show up after writing invalid values unless I click a button that does `.validate()` on the validationController. It looks like `change` or `focus out` don't trigger the validation of the rules.

## 🤔 Expected Behavior

I am expecting to see the errors show up after I write something in the input that makes it invalid
## 😯 Current Behavior

No errors. The current behavior is that it does nothing.

## 💁 Possible Solution

There are two possible solutions:
1. Make the `validationController.results` automatically update when any input changes.
2. Offer an `.onChange` event or callback on the validationController so decs can implement anything they want in there (in this case, they will call `.validate()` in the callback)

## 🔦 Context

I am trying to automatically display all the errors of `.ensureObject()` in my page without having to click a button. 

## 💻 Code Sample
[Stackblitz](https://stackblitz.com/edit/au2-validation-validating-object-bbme9u?file=src%2Fmy-app.ts,src%2Fmy-app.html,index.ts)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | dev
| Language         | TS 4.7.3
| Browser          | chrome 103.0.5060.66 
| Bundler          | webpack 5.73.0
| Operating System | Windows 10
| NPM/Node/Yarn    | v14.16.0

**Comment by Sayan751** [comment]
@IonelLupu I have made some changes in your SB sample, and this here is working as you are expecting: https://stackblitz.com/edit/au2-validation-validating-object-gh1476?file=src%2Fmy-app.ts,src%2Fmy-app.html,package.json

The main changes are applying the `@watch` decorator. Note that as the `person` is created inside `MyApp` and the instance is **not** changed inside the `PersonEditor`. Thus, there is no `change` event on the `person` object in itself when you edit the name and age properties inside the `PersonEditor`. However, as you want to trigger the validation once the internal properties of the `Person` instance changes, you need to apply observers and that is done by using the `@watch` decorator. There were a couple of `validate` binding behaviours missing in your example; I added those, and it should now be working as per your expectation.

**Comment by IonelLupu** [comment]
hey @Sayan751 thank you for the solution. I really appreciate your investigation 😄 . Didn't know about this trick with @watch. Works as excepted in the example above.

But, in my case, the @watch formula is not that simple. Take a look at [this example](https://stackblitz.com/edit/au2-validation-validating-object-gh1476-n9icss?file=src%2Fmy-app.ts,src%2Fmy-app.html,package.json). When you click "activate addresses", ALL of the other properties of the `person` are evaluated even if the `name` and the `age` have the same values. Of course, this is because `.validate()` validates everything.

I kinda fixed this by using validation tags [like so](https://stackblitz.com/edit/au2-validation-validating-object-gh1476-jukvnn?file=src%2Fmy-app.ts,src%2Fmy-app.html,package.json) (let me know if there is a better approach). But still, this is not 100% correct because the error message ("addresses percentage must add up to exactly 100%") should show up after you focus out from the Percentage input that has an invalid value (excepting this because of `changeOrFocusout`). Another problem with this approach is that now, the Submit button that calls `validationController.validate()` doesn't validate the `.ensureObject()` rules anymore because they now have a special tag attached to it. So I guess I have to manually add the validation rules somehow (and I don't know how. I was expecting the rules in this code: `.validate({ rules: [..here..]})`  to be easier to add like in AUv1). 

Any idea on how to make this work beautifully?

**Comment by Sayan751** [comment]
@IonelLupu Your use-case is not completely clear to me. However, I am assuming that you are expecting something like this:
https://stackblitz.com/edit/au2-validation-validating-object-gh1476-collection?file=src%2Fmy-app.ts,src%2Fmy-app.html,package.json.

If I am misinterpreting, then please try to explain your objective first. You have tried to explain what you have tried, which is helpful, but it is difficult to follow without understanding the end-goal first.

**Comment by Sayan751** [comment]
Closing this issue, as IMO no bug has been reported, and on contrary OP merely asked a question. Feel free to continue the discussion, if needed.
