### ISSUE TITLE
@aurelia/router silently fails if ShadowDOM is enabled and component file names are not kebab cased

### ISSUE THREAD

**Issue by Vheissu** [aurelia/aurelia#1481]
# 🐛 Bug Report

When using the `@aurelia/router` package in an application with ShadowDOM enabled globally, if routed components are not kebab-cased to be in line with the web specification, the router silently fails (empty au-viewport element).

In my situation, I had a component called `home.ts` and `home.html` the class name for `home.ts` was `HomeComponent`. However, due to the fact the filename was `home` without a hyphen to kebab case it, my route (defined below) failed.

```typescript
import { IRouteableComponent, IRoute } from "@aurelia/router";

export class MyApp implements IRouteableComponent {

    static routes: IRoute[] = [
        {
            component: () => import("./components/home/home"),
            path: ["", "home"],
            title: 'Home'
        }
    ];

}

```

## 🤔 Expected Behavior

An error should be thrown if you attempt to load a component that doesn't adhere to the Web Component specification on element naming.

## 😯 Current Behavior

The route won't load. No error messages in the console are thrown either (unless I was meant to have a debug mode on).

## 💁 Possible Solution

There appears to be code by the looks of it checking as the routed component is not loaded. So, I assume just throwing an error would be sufficient to guide developers.

## 🔦 Context

Routing to components.

**Comment by netcitylife** [comment]
It is related not only to this possible error, but any error that happens inside a loaded page is suspended by router exception handler. That initial exception should be displayed to developers console

**Comment by Vheissu** [comment]
This issue appears to have resolved itself in the latest release. Closing. I will reopen if I encounter this again.

**Comment by netcitylife** [comment]
I dont think it is. Fallback works differently now, but component error, that caused fallback is still hidden from developer. So no one can see WHY fallback happened.

**Comment by Vheissu** [comment]
@netcitylife This issue was related to shadow Dom components failing if the names were wrong. However, the issue you are describing is detailed in a separate issue to this one.

**Comment by netcitylife** [comment]
> @netcitylife This issue was related to shadow Dom components failing if the names were wrong. However, the issue you are describing is detailed in a separate issue to this one.

Could you point to that issue, please?

**Comment by Vheissu** [comment]
I was thinking of this issue: https://github.com/aurelia/aurelia/issues/1519 — but I don't think there is a specific issue related to swallowing errors. It very much should be its own separate issue.
