### ISSUE TITLE
Capturing attribute with filter function in convention 

### ISSUE THREAD

**Issue by bigopon** [aurelia/aurelia#1488]
With the PR #1487 merged, we can now specify a function to filter what attribute **should be capture**:
```ts
capture: attr => attr !== 'class'
```

An issue with this is it's not straight forward how to do it with convention. Maybe we can allow function parsing?
```html
<capture>(attr) => attr !== 'class'</capture>
```
it looks weird.

Another options is to support RegExp, but it would be quite hard to express filtering with RegExp, it's probably not worth it.

Will keep this a discussion for now.

cc @3cp @brandonseydel @Sayan751 thoughts?

**Comment by 3cp** [comment]
Yes, expression in html supposes to be simple and readable. Putting function there looks weird.

Beside RegExp, there is also widely used glob pattern format, which is easier to support. An array of glob pattern (with negative parts) should work for our case.

-----

Also, if we want, parsing RegExp can be cheap. The key is to utilise native JS engine to try the the RegExp.
That's basically how meriyah does it, only a little bit stat parsing for something like escaping and grouping. The heavy lifting is done by native JS engine.

https://github.com/meriyah/meriyah/blob/master/src/lexer/regexp.ts

**Comment by bigopon** [comment]
What about the concern related to regexp above:
> it would be quite hard to express filtering with RegExp

Say we want to capture all attribute except `class` and `validation-error` in RegExp. I don't expect writing this regexp is a pleasant experience.

**Comment by 3cp** [comment]
Agree, might try glob pattern.

**Comment by Vheissu** [comment]
Are we still considering this line of thinking? @bigopon

**Comment by bigopon** [comment]
This is done-ish. If we have any other request here for a higher level/more flexible API around this, it can be a new issue.
