### ISSUE TITLE
[RFC] Auto recognize commonly used global objects

### ISSUE THREAD

**Issue by bigopon** [aurelia/aurelia#1490]
## Context

Currently, in the template, if one wants to acces `JSON`/`Date`/`Math` (commonly used global properties), the dev needs to have the property available in either:
- binding context (view model) via assigning those global objects to properties on the view model instance or
- the overridecontext (view) via assigning those global objects to properties on the override context on controller scope

Assigning those global objects can be done either via lifecycle hooks or directly in view model code.

This has a few cons:
- Bad ergonomics: have to set it up
- Unnecessary overhead: accessing those property in normal templating expression will cause overhead. Even small, it's still a waste

Another way to do this is via value converter. Some example would be
```
JSON.stringify ---> | json
Math.ceil      ---> | ceil
```
Though value converter is commonly used to express the conversion of a value, not the creation of a value. So it'll be inappropriate to express `Date.Now()`/`Math.PI` etc...
Also, value converters add noises to the template, which sometimes is more desirable to avoid.

## Proposal

Introduce a special treatment for those known properties (`Date`/`JSON`/`Math`) in our AST so that the above issue can be solved:

- An `AccessJsonExpression` that will return `JSON` object on global, without observing if the property to be accessed on the scope is `JSON`, similarly done for other properties like `Date`, `Math` etc... This will cost more at expression parsing time, and less at runtime/evaluation-time.

## Potential issues

This is a breaking change (though practically not) for existing app, if there' properties on the view model that have the same names with those global properties. Though if those properties are used to express something other than those global objects, it'll probably be something we don't want to encourage anyway. If an application wants to do it this way, it can still be done via `$this` access:
```html
// JSON on the global object
<div>${JSON.stringify(text)</div>
// JSON on the view model
<div>${$this.JSON.stringify(text)</div>
```

## Alternative solution

We can provide a set of commonly used value converter, like `stringify` etc, A pros of this approach is it doesn't require any special treatment for some properties, though it requires each method used have an equivalent value converter. This is also boilerplate.

**Comment by roemhildtg** [comment]
Just something to add - you could also do this via value convertors, rather than using the binding context. Would this offer any additional benefits over using value convertors?

**Comment by simonfox** [comment]
Personally wouldn't use it, and prefer not to put that sort of thing in our templates.

**Comment by bigopon** [comment]
> Personally wouldn't use it, and prefer not to put that sort of thing in our templates.

Do you meant you don't ever want to have `JSON.stringify(...)`/`Math.something(...)` in your template?

> you could also do this via value convertors, rather than using the binding context. Would this offer any additional benefits over using value convertors?

Thanks for the reminder, I forgot this "normal way" when crafting the RFC. Will add it in. The cons of a value converter is it adds an additional dependency, and a concept that is only in Aurelia. Says to get the ceiling of a number, without `Math`, you'll have to create a value converter for ceiling it, or doing it in the view model. Either of those two ways results in a different mental with the most basic function calls in normal JavaScript, I think it's not necessary to require those extra steps.

**Comment by Vheissu** [comment]
I use value converters I have written for convenience wrappers around JSON in many of my projects. JSON.stringify, Date.now and so forth. I can't see many downsides to adding support for these into templates. It would immensely clean up some of my applications by removing value converters which are a couple of lines.

**Comment by simonfox** [comment]
> Do you meant you prefer not to have JSON.stringify(...)/Math.something(...) in your template?

Yes. Just our preference to stick to properties in the template - we'd do anything like this in either the view model or a value converter.

**Comment by bigopon** [comment]
@simonfox thanks. Keeping the template simple is a nice way of doing thing to stick to. I think this proposal will not affect simplicity of templates while removing the boilerplate. We will be only enabling a handful of global properties. Maybe only JSON/Date/Math, which are quite commonly used.

**Comment by zewa666** [comment]
the problem is where this starts and where it ends. JSON as a helper itself might be okayish, but any non-trivial and i18n based app wont do it with native Date/Math due to formatting/parsing reasons as an example. Besides I'm with @simonfox in that this typically pollutes your template with things that are better kept in the VM. but thats a preference thing and no one forces you to use em.

**Comment by Sayan751** [comment]
In general, I also agree to the opposing argumentations presented previously. Sometimes it makes more sense to perform such actions in the view models.

On the other hand, I think some global APIs might be useful to have in template. For example, having the `Math` API available in the template might not be such a bad idea. IMO, it will be straightforward by introducing a special keyword for this. Also, I think it makes more sense to limit the access to the global (static) APIs under a new `$global` (referring to `globalThis`) keyword. For example:

```html
<!-- points to the global Math API -->
${$global.Math.ceil(x)}

<!-- points to the scope (binding and overriding context) -->
${Math.ceil(x)}
```

With that in place, the scope selection for that innermost expression (will be `globalThis` in this case) will be easy, we just need to discount that we don't need any change observations on the `globalThis` "properties".

**Comment by netcitylife** [comment]
This may be implemented as some kind of configurable global context, like in underscore templates. It may be disabled by default completely for migration stability

**Comment by m-gallesio** [comment]
If (and only if) this is implemented, I too think "some kind of configurable global object" would be the safest choice.
This seems similar in concept to `globalResources` in v1 (not sure whether it exists in v2).

**Comment by Vheissu** [comment]
I agree that this feature, like other Aurelia features, should be configurable on a global scope. Let developers choose what properties are exposed in their templates to prevent misuse and better conciseness. @bigopon, I think it's worth implementing this, as long as the configuration is an option.

**Comment by bigopon** [comment]
Configuration may sounds good, but it'll be weird since configuration may need to be enabled at both app and component level, and component may want to enable different globals compared to what the owning app provides. Imagine a plugin wanting to have their own global, conflicting with the main app provides.
I think if we are to enable this, it should be non configurable finite list of known & commonly use language global.
cc @fkleuver @Sayan751

**Comment by Sayan751** [comment]
@bigopon I agree. This is why it makes sense to me to introduce a new `$global` token/keyword. Behind that, we can also allow only a finite list of operations (also possibly static and synchronous).

**Comment by bigopon** [comment]
if we are to enable a limited set of globals only, does it make sense to introduce a `$global` keyword? It'll be different with standard way of writing script too much. Imo we can just keep it simple and make it look like normal scripting.

**Comment by Sayan751** [comment]
I think the parsing would be easier with that, and also the scope evaluation down the line.

**Comment by bigopon** [comment]
> I think the parsing would be easier with that, and also the scope evaluation down the line.

I see the concerns, Thanks for pointing that out. To me, it sounds pretty simple with a new AST type: `AccessGlobal`
```ts
class AccessGlobal {
  name: string;
  evaluate() {
    return globalThis[this.name]
  }
  assign() {
    // do nothing
  }
}
```
then in our parser, in place of `AccessScope`, we just need to check the name against the list of global properties:
```ts
const expr = globalNames.includes(name) ? new AccessGlobal() : new AccessScope()
```

**Comment by Sayan751** [comment]
I still think having an explicit keyword makes it easier to differentiate between the following two cases:

```html
<!-- points to the global Math API -->
${$global.Math.ceil(x)}

<!-- points to the scope (binding and overriding context) -->
${Math.ceil(x)}
```

Might be a bit of contrived example, but we would like to handle that formally.

**Comment by bigopon** [comment]
By enforcing `$global` it's impossible to have code that is short and looks like normal script, while without `$global`, it's still possible to reference own view model override via `$this`:
```html
$this.Math.ceil(x)
```
You are right that there's a scope behavior that should be considered when looking at the template code, but I quite don't think anyone would wants to write `$global.Math` to mean `Math`, normally when I see `Math`, I immediately think of the global Math.

Not to mention introducing a `$global` keywords has implicit ramification in the future where we want to enable more language syntaxes, that is ever growing. (dynamic import, switch expression, using, piping etc...)
