### ISSUE TITLE
Aurelia Router - Infinite loop with deep invalid path

### ISSUE THREAD

**Issue by aegenet** [aurelia/aurelia#1492]
# 🐛 Bug Report

With `@aurelia/router`, if we specify a deep path in a configured route ({ path: '/page/x' }), and a user goes to /page/y, the missing page appears, but with an infinite loop.

## 🤔 Expected Behavior

Just the missing page.

## 😯 Current Behavior

Missing page and infinite loop.

## 🔦 Context

I am using `@aurelia/router` and configured routes with sub paths.

## 💻 Code Sample

Here: [Project](https://gist.dumber.app/?gist=34ca8e1c17beaeda594e4a673bd78554)

1. Go to #/page/3
2. Then, #/page/8

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | 2.0.0-alpha.37
| Language         | TypeScript
| Browser          | Chrome 104.0.5112.81, Firefox 103.0.1
| Bundler          | Dumber / Webpack
| Operating System | Windows 11
| NPM/Node/Yarn    |

**Comment by aegenet** [comment]
I tried the .39 version as it was supposed to fix the above issues.
Unfortunately, the router on the alpha.39 version does not seem to work (on all our projects).

Before (alpha.38): https://gist.dumber.app/?gist=34ca8e1c17beaeda594e4a673bd78554
After (alpha.39): https://gist.dumber.app/?gist=93ba7c8415e501935dd6411f10ef23b8

I don't know if it's related to #1532 (router lite).

**Comment by jwx** [comment]
The original issue is fixed in alpha.39 and a PR is merged (https://github.com/aurelia/aurelia/pull/1534) for the new issue mentioned in the comment above. As soon as alpha.40 is out both of these should be resolved.
