### ISSUE TITLE
Allow arrow functions inside HTML

### ISSUE THREAD

**Issue by brandonseydel** [aurelia/aurelia#1503]
# 🙋 Feature Request

The ability to allow arrow functions to reside inside views.

## 🤔 Expected Behavior

It works when using something like a filter arrow function on array

## 😯 Current Behavior

Blows up with parsing error

## 💁 Possible Solution

Allow the parser to correctly extract and run the JS

## 🔦 Context

When using an HTML only view it is impossible for this to work without brining in a backing store.  Array filter expression is one example which is widely used.

## 💻 Examples

```html
<div repeat.for="users of users.filter(y=>y.online)" >
```

**Comment by bigopon** [comment]
There' multiple category of functions that the parser has to deal with correctly (to throw unsupported error if we want to enable this. Example are async, generator, IIFE, classic function etc...).
Maybe this is supportable if we limit the scope of this to only allow synchronous arrow function with simple return expression. That will be simpler on both parser and AST level.

Valid:
```
.filter(y => y.value)
.filter((y, i) => y.value[i])
.filter(y => y.value.deep.value)
.filter(y => y.condition ? y.yes : y.no)

repeat.for="x of _"
    .filter(y => y.condition ? x.yes : x.no)
```

I'm not sure if it's really desirable though, if we can have a lambda based template.

cc @Sayan751 @fkleuver

**Comment by Sayan751** [comment]
IMO, it will be a bit difficult to implement and might even be a slippery slope. Implementing this even in the simplest form would open up the door to more complex use cases. That would mean that we need to be prepared to support every kind of JS/TS syntaxes. Mind that we are currently supporting a subset of expression in the template.

However, what might be more confusing than implementing the expression parser, would be to deal with the scopes, the various element in the expression deals with. When dealing with Arrow function, handling the scope is also paramount. We need to keep that in mind, how we are going to handle that.

If we still want to implement that, then we need to properly outline what we are going to support and most importantly what not. To that end, probably turn this issue into RFC and discuss more formally. For example, if it is only needed for the `repeat.for` TC then we can add a second bindable called `predicate`, which is an expression, evaluated to `boolean`. An example can be 

```html
repeat.for="items.bind: x of items; predicate.bind=x.someFlag && somBcFlag"
```

We can employ the same scope traversing to evaluate the predicate. That way the footprint will be limited to `repeat.for` and we don't need explicitly bother about bringing the scope-complexity, that's inherently related to the arrow functions, to template.

However, whatever the decision might be, I would suggest postponing this activity till we release the beta, especially as this not a really blocking issue without no workaround.

**Comment by fkleuver** [comment]
I agree with @Sayan751 about the slippery slope so we should be very explicit about the scope, that is, describe not just what we *will* support but perhaps more importantly what we *won't*.

There is something in the spec that gives us an already well-defined description of exactly what "simple" means. It excludes rest/spread, object/array binding patterns and initializers.
https://tc39.es/ecma262/#sec-static-semantics-issimpleparameterlist

As for what sort of expressions to support, we can also go with something already (fairly) well-defined, that is, the existing Aurelia syntax we use which is the subset of [AssignmentExpression](https://tc39.es/ecma262/#prod-AssignmentExpression) (the `ExpressionBody` part of `ConciseBody`) without yield/await and a few other things. But would then include arrows (which means nested arrows).

**Comment by bigopon** [comment]
> just start with a "whitelist" of what an arrow can be initiatated from ...

Currently we perform "track on evaluate", which means we probably should be able to observe any property access from expressions within an arrow function.

This is some pseudo code that I think can demonstrate that observation can be done quite easily
```ts
class LambdaExpression {
  public constructor(
    public parameters: string[],
    public body: IsLeftHandSide,
  ) {}

  public evaluate(f: LF, s: Scope, l: IServiceLocator, c: IConnectable | null): unknown {
    const func = (...args: unknown[]) => {
      const functionScope = Scope.create({
        // build the parameters in the scope of the arrow function
       // on a scope before evaluating the body expression of the arrow fn
        ...this.parameters.reduce((map: IIndexable, name, i) => {
          map[name] = args[i];
          return map;
        }, {})
      });
      return this.body.evaluate(f, functionScope, l, c);
    };
    return func;
  }
}
```

What will fallshort, to me is the array mutation sensitive calls (`.filter`, `.map` etc...) may not yield proper observation, but I think we can adjust our `CallMember` AST to detect this.

For the syntax, we can say we only support clearly defined parameters, without default value or destructuring. This also means that rest syntax isn't supported. Then everything will be quite observable & simple.

@brandonseydel , can you update this RFC to make it into a more formal format? There's at least an alternative solution such as a value converter to deal with filtering, so the saying
> When using an HTML only view it is impossible for this to work without brining in a backing store. Array filter expression is one example which is widely used.

isn't always correct.
