### ISSUE TITLE
[RFC] Rename routing lifecycle hooks

### ISSUE THREAD

**Issue by jwx** [aurelia/aurelia#1509]
# 💬 RFC

## Context

Currently, the component lifecycle hooks have a naming convention that specifies whether the lifecycle step is happen*ing* (`attaching`) or has happen*ed* (`attached`). The router component hooks, however, does not follow this naming convention and are instead named `canLoad`, `load`, `canUnload` and `unload`. 

The hooks `canLoad` and `canUnload` are for a functionality that doesn't exist in the component lifecycle hooks so they can decide the naming convention themselves. (And it makes sense. To the degree that if the functionality were ever to appear in lifecycle hooks the naming convention would work well for that as well (`canAttach`)). 

The hooks `load` and `unload` do have clear equivalents among lifecycle hooks but don't follow the naming convention of those. By the names themselves, it's also unclear whether the step is happening or has happened when the hooks are called. 

## Proposal

Rename the `load` and `unload` hooks to `loading` and `unloading` respectively. That way they'd have the expected names of component hooks and they'd also clearly indicate that they are at the start of the load/unload step.

## Benefits

Consistent naming among the component hooks will make them easier to understand and remember. It will also open up for the possibility to add routing hooks at the end of the load/unload process; `loaded` and `unloaded`. (There are use cases for both `loading/unloading` and `loaded/unloaded` component hooks when using multiple viewports.)

## Potential issues

It would be a breaking change for existing apps. But the fix is hopefully quite quick to do. And these kind of changes are in a way not to be unexpected as long as we're in alpha.

## Alternative solution

We could support both names, `load/loading` and `unload/unloading`.

**Comment by Sayan751** [comment]
>  It will also open up for the possibility to add routing hooks at the end of the load/unload process; loaded and unloaded. (There are use cases for both loading/unloading and loaded/unloaded component hooks.)

Can you please give some example of such use-cases? I am intrigued as such hooks were not there in V1, and sincerely I never faced a need to have that. To me, the `attached` is practically that `loaded` hook.

As a side remark, we should be cautious about introducing too many hooks or even renaming the existing ones, as that will bring (probably needless) breaking changes.

**Comment by Vheissu** [comment]
I think the way the Lifecycle methods are currently named makes more sense than those presented in this RFC. I understand the intent, but I like how the router isn't the same as core methods. Hooks like the current canLoad just make sense.

**Comment by jwx** [comment]
> Hooks like the current canLoad just make sense.

I agree and I don't propose we change `canLoad` or `canUnload`. The only change I'm proposing is that `load` is changed to `loading` and `unload` is changed to `unloading`.

**Comment by jwx** [comment]
> Can you please give some example of such use-cases? I am intrigued as such hooks were not there in V1, and sincerely I never faced a need to have that. To me, the `attached` is practically that `loaded` hook.

If one is using only one viewport, which I recall (hopefully accurately) you saying you prefer, a `loaded` hook will indeed serve the same purpose as the `attached` hook. I've updated the RFC to mention multiple viewports. (Also, to be clear, this proposal isn't including adding the `loaded/unloaded` hooks.)

> As a side remark, we should be cautious about introducing too many hooks or even renaming the existing ones, as that will bring (probably needless) breaking changes.

I agree, but I think this change is worth it. At least as long as we're in alpha.

**Comment by bigopon** [comment]
On one hand, renaming
```
load -> loading
unload -> unloading
```
makes those hook themselves much clearer, and same naming pattern with the core hooks should aid understandability/learnability.

On the other hand, `loading` and `canLoad` or `unloading`/`canUnload` combos feel somewhat weird, but maybe that's not an issue.

To me, I think we should go for this since the existing lifecycle names give a feeling that router is a different framework.

**Comment by Sayan751** [comment]
> On the other hand, loading and canLoad or unloading/canUnload combos feel somewhat weird

It does sound weird. 

On the other hand, the `load`, `unload` has been the names since v1. I am not sure if it is justified to well-accepted names just for the sake of it, considering it does not bring any other additional changes.

**Comment by bigopon** [comment]
> On the other hand, the load, unload has been the names since v1

I guess by `v1` you meant "the start of v2"?

If we have `load`/`unload`, maybe we should have `bind`/`attach`/`detach`/`unbind` + `-ed` versions of them instead.

**Comment by Sayan751** [comment]
> I guess by `v1` you meant "the start of v2"?

Sorry, v1 is a poor choice of words. You are right. 

> If we have `load`/`unload`, maybe we should have `bind`/`attach`/`detach`/`unbind` + `-ed` versions of them instead.

Nah, that would be more unwarranted changes. In that case, I think we can move forward with the renaming, if we are keen on aligning the names.
