### ISSUE TITLE
Router fallback behaviour breaks for routes with multiple parts

### ISSUE THREAD

**Issue by Vheissu** [aurelia/aurelia#1519]
# 🐛 Bug Report

The current `fallback` behaviour in `@aurelia/router` assumes that the route will only have one segment and will break for routes with multiple parts.

### Non-existent route where fallback works

http://localhost:9000/#/FSDF

### Non-existent route where fallback fails (and app breaks)

http://localhost:9000/#/FSDF/TEST

What will happen here is the application will get into an infinite loop and completely break. After a few seconds, the tab will need to be forced closed.

```
Error: 1 remaining instructions after 100 iterations; there is likely an infinite loop.
    at createUnresolvedinstructionsError (index.dev.mjs?4dc9:5146:1)
    at Router.unresolvedInstructionsError (index.dev.mjs?4dc9:5001:1)
    at RoutingScope.processInstructions (index.dev.mjs?4dc9:3564:1)
    at async Promise.all (:9000/index 0)
    at async RoutingScope.processInstructions (index.dev.mjs?4dc9:3656:1)
    at async Router.processNavigation (index.dev.mjs?4dc9:4781:1)
```

## 🤔 Expected Behavior

For fallbacks, multiple URL segments should work.

## 😯 Current Behavior

The current fallback behaviour isn't working for configured routes like v1.

## 💁 Possible Solution

Fix the `fallback` attribute, but also implement a solution that can be implemented in code similar to how it worked in v1 routing.

**Comment by jwx** [comment]
Resolved via https://github.com/aurelia/aurelia/pull/1507 and https://github.com/aurelia/aurelia/pull/1524.
