### ISSUE TITLE
Router: Redirecting from lifecycle and hook methods requires component to be registered

### ISSUE THREAD

**Issue by Vheissu** [aurelia/aurelia#1521]
# 🐛 Bug Report

Redirecting from within hooks and lifecycle methods is currently restricted. We currently need to return the name of a component, which doesn't work for configured routing because it assumes the component name is registered. Furthermore, we cannot redirect with parameters (to my knowledge). 

The way the redirection currently works appears to be from the direct routing days where it is assumed we're registering components with DI (which is not the case with configured routing).

## 🤔 Expected Behavior

Similar to v1 routing, we should be able to redirect from within a component Lifecycle like canLoad elsewhere, with support for routes with parameters. All this without the need to register the component (in configured routing this happens on a route.

Maybe the introduction of a v1-like `Redirect` object could be a solution?

```
import { Redirect } from '@aurelia/router';

export class MyComponent {
    canLoad() {
        return new Redirect('/products');
    }
}
```

This would also allow us to redirect with route parameter values. Handy in situations where you might redirect to a page that has result and page number values.

```
import { Redirect } from '@aurelia/router';

export class MyComponent {
    canLoad() {
        return new Redirect('/products/25/1'); // /products/:results/:page
    }
}
```

## 😯 Current Behavior

Returning a string value to redirect only takes a component name and assumes its registered with DI. We can sort of hack a redirect by injecting the router and calling load on the router, but it feels wrong and requires injecting the router to do a simple task.

Currently, we can only return component names, but they need to be registered:

```
export class MyComponent {
    canLoad() {
        return 'products'; // Will error if no component called products has been registered first
    }
}
```

**Comment by bigopon** [comment]
Rather than having to import `Redirect` from an aurelia package to have this
```ts
import { Redirect } from '@aurelia/router';

export class MyComponent {
    canLoad() {
        return new Redirect('/products/25/1'); // /products/:results/:page
    }
}
```
We can enable literal object syntax pattern so that it can be:
```ts
import { Redirect } from '@aurelia/router';

export class MyComponent {
    canLoad() {
        return { redirect: '/products/25/1' }; // /products/:results/:page
    }
}
```

**Comment by Vheissu** [comment]
@bigopon A much better solution.
