### ISSUE TITLE
Configured router issue with alpha 39

### ISSUE THREAD

**Issue by haserver** [aurelia/aurelia#1532]
# 🐛 Bug Report

Not sure if bug or configuration error but here the issue I am facing with alpha 39 configured router.

1. Create alpha 39 app using npx makes: custom typescript app with dumber, plain css, no shadow dom, no testing, with basic routing and npm install

2. Configure three routes like

**my-app.ts**

```ts
import { IRouter } from "aurelia";
export class MyApp {
  static routes = [
    {
      path: ["", "welcome"],
      component: () => import("./welcome-page"),
      title: "Home",
    },
    {
      path: "about",
      component: () => import("./about-page"),
      title: "About",
    },
    {
      path: "about2",
      component: () => import("./about-page2"),
      title: "About2",
    },
  ];
  constructor(@IRouter private router: IRouter) {}
```

**my-app.html**

```html
<nav>
  <button click.delegate="goto('welcome')">Welcome</button>
  <button click.delegate="goto('about')">About</button>
  <button click.delegate="goto('about2')">About2</button>
</nav>

<au-viewport></au-viewport>
```

4. Run the app and notice following console log error

<img width="810" alt="Screenshot 2022-09-02 at 13 26 52" src="https://user-images.githubusercontent.com/65811121/188129790-32f41149-8b65-46a3-a634-848f9662c7ac.png">

When one route removed, `about` or `about2`, no error is shown and routing and app work fine. Full source/example attached.

[au39-router.zip](https://github.com/aurelia/aurelia/files/9477519/au39-router.zip)

**Comment by bigopon** [comment]
@haserver thanks for reporting the issue. can you create a repro based on our basic setup here https://stackblitz.com/edit/au2-conventions?file=src%2Fmy-app.html

**Comment by haserver** [comment]
here it is https://stackblitz.com/edit/au2-conventions-vuyga8?file=src/my-app.html

**Comment by Sayan751** [comment]
@bigopon @jwx I think this issue has been closed by mistake. Reopening this.
