### ISSUE TITLE
if.bind always execute content

### ISSUE THREAD

**Issue by miniben-90** [aurelia/aurelia#1533]
# 🐛 Bug Report

I have an array of data that could be empty and inside my element I have some calculations with data.
I'm using `if.bind` with a `repeat.for` on my element. After upgrade I have an error with the parser (AUR0167 in my local project and AUR0162 when I reproduced the bug withdumbergist).

## 🤔 Expected Behavior

Not executing the content when if.bind is false.

## 😯 Current Behavior

Crash with error AUR0167.

## 💻 Code Sample

```html
<div if.bind="data.length" repeat.for="value of data">
  <let calc.bind="value.val1 / value.val2"></let>
  ${calc}
</div>
```

Example here: [https://gist.dumber.app/?gist=5dc43ea77422d5fd1d0f2cd03b529d34](https://gist.dumber.app/?gist=5dc43ea77422d5fd1d0f2cd03b529d34)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | 2.0.0-alpha.39
| Language         | TypeScript
| Browser          | Chrome 104.0.5112.81, Firefox 103.0.1
| Bundler          | Dumber / Webpack
| Operating System | Windows 11
| NPM/Node/Yarn    |

**Comment by bigopon** [comment]
Thanks for reporting this issue @miniben-90
I don't think there's any content being executed. This is an issue with the parser due to some recent refactoring. 
cc @fkleuver 
Somehow this slipped through our parser tests.

**Comment by fkleuver** [comment]
I've reproduced the issue and am working on a fix, thanks for reporting this
