### ISSUE TITLE
Platform taskQueue multiple instances all use the same delay value

### ISSUE THREAD

**Issue by alexgustafson** [aurelia/aurelia#1542]
# 🐛 Bug Report

When using multiple instances of PLATFORM.taskQueue.queueTask as a replacement for setTimeout. It appears that the longest delay value is used for all instances.

Repro link https://github.com/alexgustafson/multiple-queuetask-timing

## 🤔 Expected Behavior

I would expect that each instance of queueTask would repeat at its own set delay time.

## 😯 Current Behavior

All instances use the same delay time. Its seems that the longest ( largest ) value wins.
There is no error.

## 💁 Possible Solution

I am using native setTimeout instead.

## 💻 Code Sample
Here is a link to an example Aurelia v2 project. There are three components, typing text into the view. Each should be typing at a different speed. 

https://github.com/alexgustafson/multiple-queuetask-timing

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          |   v2 2.alpha 39 |
| Language         | typescript |
| Browser          |
| Bundler          |
| Operating System |
| NPM/Node/Yarn    |

**Comment by superspartak** [comment]
I can confirm that as of March 2024, it still persists

**Comment by bigopon** [comment]
The `PLATFORM.taskQueue` is uses `setTimeout` under the hood so it sounds weird for what we are seeing. Are you able to reproduce the issue with just setTimeout instead of the taskQueue @alexgustafson @superspartak?

**Comment by superspartak** [comment]
Switching to setTimeout seems to fix the issue. as @alexgustafson mentioned, initially, all events run on their expected time if the delay for the earlier tasks are shorter than the later once. In the next iterations, whatever delay is the maximum, it seems to be the same for all tasks.
