### ISSUE TITLE
Native HTML elements binding problems

### ISSUE THREAD

**Issue by netcitylife** [aurelia/aurelia#1543]
# 🐛 Bug Report

Binding to HTML &lt;input&gt;/etc elements works unexpectedly for undefined ViewModel property values

Repro link https://stackblitz.com/edit/aurelia-2-typescript-iskzhw?file=my-app.ts

## 🤔 Expected Behavior

Undefined properties do not produce invalid html attributes, or produce empty values, not "undefined" (for strings) or 0 (for numbers)

## 😯 Current Behavior

Resutling HTML is: &lt;input class="au" type="undefined" minlength="0" maxlength="0" placeholder="undefined"&gt;

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | 2.0.0-alpha.39
| Language         |
| Browser          | Firefox
| Bundler          |
| Operating System | MacOS
| NPM/Node/Yarn    |

**Comment by bigopon** [comment]
When it's undefined/null, we probably should remove the attribute.

**Comment by netcitylife** [comment]
Its worth considering this task when working on it: #75

**Comment by netcitylife** [comment]
@bigopon 
Hm, I see now that you just manually set a list of properties which will use attr accessor, so it is the same as: type.bind="type & attr" , am i right?
If so, the list should be longer:
id, name, min, max, step, pattern, accept, title.

And this list may be longer. May be it would be useful to make some configuration callback, which would be passed element name and attribute name, and return an appropriate accessor. So one may extend this behavior if needed.

**Comment by bigopon** [comment]
@netcitylife yes a proper condiguration like other parts of the API will come.

**Comment by bigopon** [comment]
For atrributes that have matching props and are automatically reflected, we shouldnt have to do anything. Just there some special attribute like the one in this issue will break the element functionality with null/undefined so it needs to be done

**Comment by netcitylife** [comment]
@bigopon I updated my stackblitz example and it shows that then setting id.bind="<undefined>" it also becomes id="undefined" and we are able to query element by this "undefined" id, which id not correct, as i think

**Comment by netcitylife** [comment]
> @netcitylife yes a proper condiguration like other parts of the API will come.

May be it should be done in 2.1 ?) Its really time to stick with some +/- current functionality and make a stable release...
While trying to create something perfect, you will end up with nothing :(

**Comment by bigopon** [comment]
Yes, but `undefined` on `id` is a user preventable error, and recoverable, while `undefined/null` on `size`/`maxLength` min length could corrupt some state. Ideally we will by default take care of "dangerous" properties.
