### ISSUE TITLE
propertyChanged() callback is not documented

### ISSUE THREAD

**Issue by netcitylife** [aurelia/aurelia#1551]
propertyChanged() is totally missing in new documentation. Also, valueChanged()/propertyChanged() currentry do not fire for the first time (initial) assignment, this is different from v1 and (if correct), should be mentioned in docs and migration guide.

**Comment by Vheissu** [comment]
Documented pending release.

**Comment by Vheissu** [comment]
This is documented here: https://docs.aurelia.io/components/bindable-properties#calling-a-change-function-when-bindable-is-modified
