### ISSUE TITLE
Empty path in child routers stopped working since alpha40

### ISSUE THREAD

**Issue by netcitylife** [aurelia/aurelia#1568]
# 🐛 Bug Report

When child router route has an empty path (path: ''), router fails navigating to it. Example of child router configuration:
```js
static routes: IRoute[] = [
        {
            path: '',
            redirectTo: 'api',
        },
        {
            path: 'api',
            component: import('./pages/api/api-list'),
            title: 'Api list',
        }
];
```
When navigating to <parent_path> or <parent_path>/ - it fails, but when navigating to <parent_path>/api - it works OK. The same is when route has a 'component' prop, not 'redirectTo'.

## 🤔 Expected Behavior

It should work as in <= alpha38

## 😯 Current Behavior

Router fails navigating with an error:
`Uncaught (in promise) Error: 'null' did not match any configured route or registered component name - did you forget to add the component 'null' to the dependencies or to register it as a global dependency?`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | 40
| Language         |
| Browser          |
| Bundler          |
| Operating System |
| NPM/Node/Yarn    |

**Comment by jwx** [comment]
This should be resolved in the next release.

**Comment by netcitylife** [comment]
Ok, thanks

**Comment by jwx** [comment]
You can check this now by installing `dev` version if you want.

**Comment by netcitylife** [comment]
Yes, fixed in alpha 41. Closing issue, thanks
