### ISSUE TITLE
Error on defining-routes-using-the-route-decorator documentation page?

### ISSUE THREAD

**Issue by ivanbacher** [aurelia/aurelia#1585]
On t[his page](https://docs.aurelia.io/developer-guides/routing/creating-routes#defining-routes-using-the-route-decorator):

routing
  creating-routes
     defining-routes-using-the-route-decorator

```
import { IRouteableComponent } from "@aurelia/router";

@route({
    routes: [
      {
        path: ['', 'home'],
        component: import('./components/home-page'),
        title: 'Home',
      }
    ]
})
export class MyApp implements IRouteableComponent {

}
```

I get an error that `route` is not defined. When trying to import `route` from `@aurelia/router`, I get an error that it does not exist.

Should it not be:

```
import { routes } from "@aurelia/router";

@routes([
      {
        path: ['', 'home'],
        component: import('./components/home-page'),
        title: 'Home',
      }
])

export class MyApp {

}
```

**Comment by Vheissu** [comment]
@ivanbacher Good catch. Thank you. With the router changing a bit over the last few months, little things like these went under the radar. It's a docs issue and you were correct.

@bigopon Documentation issue. This was the older syntax for using the route decorator. I have fixed this up now.
