### ISSUE TITLE
Change load Router hook to loading in documentation 

### ISSUE THREAD

**Issue by ivanbacher** [aurelia/aurelia#1587]
Documentation includes this:

[The load method](https://docs.aurelia.io/developer-guides/routing/routing-lifecycle#load) is called when your component is navigated to. If your route has any parameters supplied, they will be provided to the load method as an object with one or more parameters as the first argument ...

When using `load`, browser console outputs this:
```
Deprecated] Found deprecated hook name "load" in live. Please use the new name "loading" instead.
```

**Comment by Vheissu** [comment]
@ivanbacher Sorry. I had these changes in a separate branch and forgot I hadn't merged them in yet. I was waiting on the router changes to be released and then forgot. All fixed now. Thank you.
