### ISSUE TITLE
Navigating to child routes -  route did not match any configured route or registered component name

### ISSUE THREAD

**Issue by ivanbacher** [aurelia/aurelia#1613]
# 🐛 Bug Report

I have the following routing structure:
- child-01
  - home
  - dashboard
 - child-02
   - home
   - dashboard
   
`child-01` and `child-02` get rendered into the main viewport and both have their own viewports to render the corresponding `home` and `dashboard` views. 

![image](https://user-images.githubusercontent.com/5493114/199424429-e08af1ad-46b8-4f7f-9528-3ef015edfa10.png)

If the app is loaded for the first time then all routes will work
- child-01/home
- child-01/dashboard
- child-02/home
- child-02/dashboard

However, If you navigate to `child-01/home` then only `child-01/dashboard` will work. Trying to navigate to `child-02/home` and `child-02/dashboard`, will throw an error.

E.g. current route is `child-01/home` and attempting to navigate to `child-02/home`

```
Uncaught (in promise) Error: 'home' did not match any configured route or registered component name - did you forget to add the component 'home' to the dependencies or to register it as a global dependency?

```
Discourse link: https://discourse.aurelia.io/t/router-scopes-and-child-routes/4955
Repro link https://stackblitz.com/edit/au2-router-p1wmzl-fqweny?file=src/my-app.css

For the repro link. Open up the web dev console and try to navigate to the different routes.

## 🤔 Expected Behavior

You should be able to navigate to any route from any route.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          |  2.0.0-alpha.41 |
| Language         | JS and TS |
| Browser          |  Chrome, Firefox |
| Bundler          |  Webpack |
| Operating System | Mac |

**Comment by Lakerfield** [comment]
In the latest version 2.1.0-dev.202302082041 a @aurelia/router-lite version of the setup of above is working.  (see https://stackblitz.com/edit/au2-router-p1wmzl-cyjhcr )

When using the @aurelia/router version the error is changed to: "Error: AUR0011: Invalid resolver returned from the static register method" Which is occurring when the Home of Dashboard route is loaded for the second time from the other child route

**Comment by ivanbacher** [comment]
Cool. Thanks for the update.

I can also confirm that it is now working with `@aurelia-router`. In order to fix the error you were getting all the components needed to be remained to have a unique name.

```
Child-01
    Home
    Dashboard

Child-02
    Home
    Dashboard
```

Was renamed to 


```
Child-01
    Child-01-Home
    Child-01-Dashboard

Child-02
    Child-02-Home
    Child-02-Dashboard
```

You can find a working example here: https://stackblitz.com/edit/au2-router-p1wmzl-nwhlxf

**Comment by Sayan751** [comment]
@ivanbacher It seems that the problem is resolved with the latest version. Can this be closed now?

**Comment by ivanbacher** [comment]
@Sayan751 Yes, I think so. Thank you.
