### ISSUE TITLE
i18n interpolation causes infinite getter calls because of proxy on getter

### ISSUE THREAD

**Issue by brandonseydel** [aurelia/aurelia#1614]
# 🐛 Bug Report

When i18n has a interpolation and used in getters it calls resetRegex forcing the proxy to invoke the getters on every call.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          |
| Language         |
| Browser          |
| Bundler          |
| Operating System |
| NPM/Node/Yarn    |

**Comment by Sayan751** [comment]
@brandonseydel Please provide a minimal reproduction of the problem.

**Comment by bigopon** [comment]
This is probably because i18next is trying to cache while doing a translation causing bindings to run infinitely. We can introduce a way for proxy observation to ignore some properties so that 3rd lib can be left alone during dependency collection round.
