### ISSUE TITLE
async getRouteConfig()

### ISSUE THREAD

**Issue by elitastic** [aurelia/aurelia#1615]
# 🙋 Feature Request

In Aurelia v1 it was possible to create routes in an async function like:

```
async configureRouter(config: RouterConfiguration, router: Router)
{
    const routes = [] as RouteConfig[];

    const xy = await doingAsyncWork()
      
    config.map(...);
}
```

In Aurelia v2, there is the `getRouteConfig()` hook, but it's only possible to use this in a synchronous way.

`async getRouteConfig()` is not working.

## 🤔 Expected Behavior

getRouteConfig() should be awaited.

## 😯 Current Behavior

getRouteConfig() is not being awaited

## 💁 Possible Solution

await the getRouteConfig() hook

## 🔦 Context

I'm using this to be able to make routes dependent on data loaded from the server.

**Comment by Sayan751** [comment]
Hi @elitastic! Sorry for the delayed response. Thank you for opening the issue.

The router API currently does not support a `async getRouteConfig` hook. That will take some time, and unfortunately can't be prioritized at this moment.

However, especially in the light of the `async` `AppTask`. Using something like the following, you can work around this shortcoming for now.

```typescript
import { IContainer } from '@aurelia/kernel';
import { AppTask } from '@aurelia/runtime-html';

new Aurelia()
  .register(
    AppTask.hydrating(
      IContainer /*or any other injection symbol as per your need*/, 
      /*an instance of the injection symbol will be passed on to the lambda*/
      container => doYourAsyncWork()
    )
  );
```

For more details, refer to the [documentation](https://docs.aurelia.io/getting-to-know-aurelia/app-tasks).

**Comment by elitastic** [comment]
OK, thanks for your help!
