### ISSUE TITLE
Class bindings not working when using debounce

### ISSUE THREAD

**Issue by elitastic** [aurelia/aurelia#1616]
# 🐛 Bug Report

Class binding is not working when combined with debounce, could you please have a look to the following repro:

[Repro link https://stackblitz.com/edit/au2-conventions?file=src%2Fmy-app.html](https://stackblitz.com/edit/au2-conventions-p1b96a?file=src/my-app.html)

## 🤔 Expected Behavior

class name should be set

## 😯 Current Behavior

class name is set to "undefined" instead of the correct class name

## 💻 Code Sample

[Repro link https://stackblitz.com/edit/au2-conventions?file=src%2Fmy-app.html](https://stackblitz.com/edit/au2-conventions-p1b96a?file=src/my-app.html)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | 2.0.0-alpha.41
| Language         | English
| Browser          | Brave
| Bundler          | Webpack
| Operating System | Windows
| NPM/Node/Yarn    | NPM

**Comment by bigopon** [comment]
It seems this repro is using an old version. By deleting the package lock and installing the latest, I was able to see both divs toggled correctly.
![gh-1616](https://user-images.githubusercontent.com/9994529/215428761-c0884f74-db64-4348-a1c3-b1cbde45627c.gif)

**Comment by elitastic** [comment]
Oh I'm sorry, my mistake, thanks for checking this!
