### ISSUE TITLE
Binding to value of select element throws error in macOS Safari

### ISSUE THREAD

**Issue by akesser** [aurelia/aurelia#1618]
# 🐛 Bug Report

When I try to bind to the selected value of a `<select>` element via something like `<select value.bind="selectedValue">` Safari throws an error:

```
Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'new this._obj.ownerDocument.defaultView.MutationObserver')
```

The `defaultView` is null. I am using Safari version 16.1 on macOS Monterey 12.5.1. In brave the binding works without an error.

The `ownerDocument` in Safari looks like a reference to a blank page, as `URL`  is `about:blank` whereas in Brave, `URL` is the correct `http://localhost:9000/` 

## 🤔 Expected Behavior

Safari should not throw an error and should bind the variable to the selected value of the `<select>` element as Brave does

## 😯 Current Behavior

Error Message in Safari:
Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'new this._obj.ownerDocument.defaultView.MutationObserver')

Stacktrace in Safari:
_start (index.dev.mjs:8003)
subscribe (index.dev.mjs:8042)
$bind (index.dev.mjs:1874)
bind (index.dev.mjs:3685)
activate (index.dev.mjs:3665)
(anonyme Funktion) (index.dev.mjs:8829)
onResolve (index.dev.mjs:263)
attaching (index.dev.mjs:8810)
_attach (index.dev.mjs:3775)
bind (index.dev.mjs:3712)
activate (index.dev.mjs:3665)
_attach (index.dev.mjs:3788)
bind (index.dev.mjs:3712)
activate (index.dev.mjs:3665)
(anonyme Funktion) (index.dev.mjs:1933)
process (index.dev.mjs:997)
(anonyme Funktion) (index.dev.mjs:1011)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | 2.0.0-alpha.41
| Language         | typescript
| Browser          | safari 16.1
| Bundler          | web pack
| Operating System | macOS Monterey 12.5.1
| NPM   |  8.19.2
| node | v18.12.1

**Comment by Vheissu** [comment]
This is the bug I mentioned to you in Discord @bigopon it effectively breaks apps in Safari and is a bit of a show stopper. I think we need to address this one with high priority (if not already).

**Comment by bigopon** [comment]
Thanks @Vheissu
The bug boils down to the following test
```ts
var div = document.createElement('div')
div.innerHTML = '<template><select></select>'
var select1 = div.firstChild.content.cloneNode(true).firstChild
// ---------------
var tpl = document.createElement('template')
tpl.innerHTML = '<select>'
var select2 = tpl.content.firstChild;
// ---------------
var tpl2 = document.createElement('template')
tpl2.innerHTML = '<select>';
var select3 = document.importNode(tpl2.content);
// ---------------
var tpl3 = document.createElement('template');
tpl3.innerHTML = '<select>';
var select4 = document.adoptNode(tpl3.content);
[
    select.ownerDocument === document,
    select2.ownerDocument === document,
    select3.ownerDocument === document,
    select4.ownerDocument === document,
];
```
It had always been false/false/true/true but for Safari 16, it should now be false/false/true/false

A fix for this should not be hard, just want to confirm whether this replicates in Safari 16.
