### ISSUE TITLE
Examples linked in documentation use Aurelia v1

### ISSUE THREAD

**Issue by akesser** [aurelia/aurelia#1619]
The links to CodeSandbox examples in the documentation of Aurelia v2 use Aurelia v1

E.g.: 
https://docs.aurelia.io/templates/forms?q=Selen#select-number
The link to the examples: https://codesandbox.io/embed/5j0zxp7rk?autoresize=1&fontsize=18&hidenavigation=1&module=%2Fsrc%2Fapp.html&view=preview

**Comment by Vheissu** [comment]
Thank you @akesser this has been resolved pending next docs update release.
