### ISSUE TITLE
view duplicated after router `back()` from child route

### ISSUE THREAD

**Issue by bsrdjan** [aurelia/aurelia#1624]
# 🐛 Bug Report

The parent page view is duplicated after router `back()` from child route

To reproduce

1. Start the app
2. Click on `User`, click on `Dashboard`, click on `My Account`
3. Click `Back` button

Before step 3

<img width="315" alt="before" src="https://user-images.githubusercontent.com/1697847/206202070-803f8c7b-0773-4beb-8a88-ca609de69e33.png">

After step 3

<img width="381" alt="after" src="https://user-images.githubusercontent.com/1697847/206202112-7d445a16-ba74-42fa-a78b-961820a41ac8.png">

:exclamation: Error is stackblitz is different, there is no duplication but no route change either, nothing happens after Back` button click. 

Repro link https://stackblitz.com/edit/au2-conventions-6kyroj?file=src/my-app.html

## 🤔 Expected Behavior

The previous page should be shown (dashboard)

## 😯 Current Behavior

No errors in console log
## 💻 Code Sample

https://stackblitz.com/edit/au2-conventions-6kyroj?file=src/my-app.html

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | 2.0.0-alpha.41 |
| Language         | English |
| Browser          | Chrome 108.0.5359.94 |
| Bundler          | webpack@5.74.0 | 
| Operating System | OSX |
| NPM/Node/Yarn    | node 16.18.1 npm 8.19.2 |

**Comment by bigopon** [comment]
This is not replicable in latest version. Closing but pls feel free to open a new one if the behavior still persists.
