### ISSUE TITLE
Change queryParams to parameters in specifying load options documentation for router

### ISSUE THREAD

**Issue by ivanbacher** [aurelia/aurelia#1625]
In the [Specifying load options](https://github.com/aurelia/aurelia/blob/182254d901106db8a6145524b8f82dc271b55c7d/docs/user-docs/developer-guides/routing/navigating.md#specifying-load-options) documentation `queryParams` is mentioned. This did not work for me. I had to use `parameters` instead.

### Old version:

Specifying load options
The router instance load method allows you to specify different properties on a per-use basis. The most common one being the title property to allow you to modify the title as you navigate to your route.

A list of available load options can be found below:

title — Sets the title of the component being loaded
queryParams — Specify an object to be serialized to a query string, and then set to the query string of the new URL.
fragment — Specify the hash fragment for the new URL.
These option values can be specified as follows and when needed:

```
import { IRouter, IRouteableComponent } from '@aurelia/router';

export class MyComponent implements IRouteableComponent {
    constructor(@IRouter private router: IRouter) {

    }

    async viewProduct() {
        await this.router.load('products', {
            title: 'My product',
            queryParams: {
                prop1: 'val',
                tracking: 'asdasdjaks232'
            },
            fragment: 'jfjdjf'
        });
    }
}
```

### New version

Specifying load options
The router instance load method allows you to specify different properties on a per-use basis. The most common one being the title property to allow you to modify the title as you navigate to your route.

A list of available load options can be found below:

title — Sets the title of the component being loaded
parameters — Specify an object to be serialized to a query string, and then set to the query string of the new URL.
fragment — Specify the hash fragment for the new URL.
These option values can be specified as follows and when needed:

```
import { IRouter, IRouteableComponent } from '@aurelia/router';

export class MyComponent implements IRouteableComponent {
    constructor(@IRouter private router: IRouter) {

    }

    async viewProduct() {
        await this.router.load('products', {
            title: 'My product',
            parameters: {
                prop1: 'val',
                tracking: 'asdasdjaks232'
            },
            fragment: 'jfjdjf'
        });
    }
}

**Comment by bigopon** [comment]
Resolved by #1706
