### ISSUE TITLE
configuring-the-same-url-strategy missing from router configuration documentation

### ISSUE THREAD

**Issue by ivanbacher** [aurelia/aurelia#1626]
Searching for `sameUrlStrategy` brings up the following:

![Screenshot 2022-12-14 at 10 17 08](https://user-images.githubusercontent.com/5493114/207555622-148bef00-7d32-411c-bf5d-0d4877ba8b43.png)

However, `Configuring the same URL strategy` seems to be missing from the `router-configuration` page, although it's shown in the search results.

https://docs.aurelia.io/developer-guides/routing/router-configuration#configuring-the-same-url-strategy

**Comment by Sayan751** [comment]
I am closing this, as the `sameUrlStrategy` is dropped from router-lite, and thus also from the docs. One need to use the [transition plan](https://docs.aurelia.io/getting-to-know-aurelia/routing/aurelia-router-lite/transition-plans) instead.
