### ISSUE TITLE
Add releases to github

### ISSUE THREAD

**Issue by rmja** [aurelia/aurelia#1648]
Hi,

I am so happy that aurelia 2 finally has reached beta quality and I would really like a way to express this. One such way is to maintain the github releases. It currently states that the most recent version is 0.6 from back in 2019 (https://github.com/aurelia/aurelia/releases). It should really be updated/maintained such that it is possible to express e.g. 💯 or 🚀 etc.

**Comment by bigopon** [comment]
We now put release for all beta ones. thanks @rmja
