### ISSUE TITLE
View compiler extension point

### ISSUE THREAD

**Issue by bigopon** [aurelia/aurelia#165]
At the moment, we have very nice view compilation model, thanks to binding command resource from @fkleuver . However, there is something still lacking: a way to handle an arbitrary unknown binding command - attribute combination.

```html
<div
  background-color.style='bgColor'
  style.color='color'
  selected.class='selected'
  class.selected='selected'
  ref='div'></div>
```

With the above usage, declaring new binding command does not always give the ability to handle the scenario. I think we may want to introduce `inspectAttribute`, that will be called before anything else to give a chance to have those highly dynamic usage a solution. Our default implementation will be a noop function, or a function that handle `ref` only

@fkleuver @EisenbergEffect

**Comment by fkleuver** [comment]
Keep in mind we're completely parsing every attribute and attribute value. This has a huge impact on larger applications with a lot of css classes and whatnot, and is a non-negligible contributor to vCurrent's startup time.
And of course when people start intercepting `inspectAttribute` this can easily go wrong in all sorts of ways via little mistakes.

What I'd like to try instead is allow user to define custom patterns in a similar way to how they can define routes, using a NFA of sorts (similar to `route-recognizer`). Not entirely sure about the pattern syntax yet but I thought about [re2](https://github.com/google/re2/wiki/Syntax) (or a subset thereof) which is basically a subset of regex that is faster/easier to parse than normal regex.

I'd propose doing it via `@bindingSyntax` decorators, and it would look roughly like this:

```ts
@bindingSyntax('([^\.]+)\.([^\.]+)') // vCurrent dot binding syntax - generic

@bindingSyntax('([^\.]+).*\.([^\.]+)') // vNext binding syntax - generic
```

```ts
export interface IAttributeInspector {
    inspectAttribute(resources: IResourceDescriptions, ...parts: string[]); InspectedAttribute | null;
}

@attributeInspector('([a-zA-Z0-9\.\-_])\.([a-z\-]+))')
export class DefaultAttributeInspector implements IAttributeInspector {
    public inspectAttribute(resources: IResourceDescriptions, target: string, command: string); InspectedAttribute | null {
       // return null if the command is unknown, and let the next inspector try
    }
}
```

Registering more than one inspector would essentially merge the patterns. Priority would be determined based on most specific to least specific match, etc.

Such that:

```ts
@attributeInspector('style\.([a-z\-]+))')
```

Will take precedence over the default:

```ts
@attributeInspector('([a-zA-Z0-9\.\-_])\.([a-z\-]+))')
```

**Comment by bigopon** [comment]
> Keep in mind we're completely parsing every attribute and attribute value. This has a huge impact on larger applications with a lot of css classes and whatnot, and is a non-negligible contributor to vCurrent's startup time.

I'm aware of that. For app that uses JIT, it's always splitted if it's large, so there would never be too many templates to parse upfront, the perf here will not be too bad. From Krauset benchmark, it suggests starting up time is very fast, which means our current compiler is doing it just fine. So it's probably the bundle size that slow things down. Maybe I can create a compiler benchmark to compare between the two if needed.

> What I'd like to try instead is allow user to define ....

Again, I like your ideas 👍 . Looks very nice to me. It should also aid AOT since the expression is much friendly to parse than an arbitrary block of code.

**Comment by fkleuver** [comment]
> Maybe I can create a compiler benchmark to compare between the two if needed.

We basically have this already. Look at the `packages/examples/benchmark`. It does fairly detailed logging on startup time and the time spent between various parts of it. All we need to do is add some big fat overloaded-with-css-classes html files (maybe in a sibling test, but can live in the same one for the time being) and run that thing.

You can run it locally (by looking at circle.yml file and running same commands) or let ci run it.
CircleCI build logs will report on the times. It also outputs and stores the raw json performance measurements which has more detail.

#118 or PR #160 is basically what needs to get tackled asap for this to work well. My intent was to tidy up krausest a bit and have our own clean version of it running on a daily basis. Then it would post a report with performance data over time, comparing vcurrent to vnext.

If you want to take over that PR be my guest lol. Otherwise I'll pick it up again after finishing #149

**Comment by bigopon** [comment]
I'll be patient 👯‍♂️

**Comment by EisenbergEffect** [comment]
Implemented.
