### ISSUE TITLE
parcel-transformer import requires .js/.ts extension in pathname

### ISSUE THREAD

**Issue by mahlonsmith** [aurelia/aurelia#1657]
# 🐛 Bug Report

ViewModels that are imported within a view are not instanced when using the parcel/transformer, though their view is.

(This was confirmed when using `npx makes aurelia [project] -s parcel`, some discussion [here](https://discourse.aurelia.io/t/new-aurelia-user-silly-behavioral-question).)

## 🤔 Expected Behavior

Importing a component with parcel should behave in the same fashion as webpack.

## 💁 Possible Solution

As a workaround, you can import the component with an explicit file extension:

`<import from="./sub-component.js"></import>`

This correctly instances the viewModel.

## 💻 Code Sample

my-app.html

```html
<import from="./sub-component"></import>
<div class="message">${message}</div>
<sub-component></sub-component>
```

sub-component.js

```javascript
export class SubComponent {

        constructor() {
                console.log( "LOADED!" );
        }
}
```

The "LOADED!" message is never fired, unless importing with the .js extension - this appears to be the case with typescript as well.  The contents of `sub-component.html` are rendered.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | 2.0.0-beta.1 |
| Language         | ESNext |
| Browser          | N/A |
| Bundler          | Parcel |
| Operating System | Linux |

**Comment by bigopon** [comment]
@3cp @brandonseydel has this been fixed? I remember we were discussing this.

**Comment by 3cp** [comment]
I tried something before, but it seems not in our (our parcel plugin) control.

The `<import>` line is translated simply as an import statement in generated js code.

Parcel uses different way to resolve a dependency for the import with or without file extension. This is probably because our js/ts files are also transpiled by our plugin (to support conventions), not just html files. The extra touch on js/ts files messed up some dep resolution.

I did not dig enough in parcel to understand this behavior. I will have another look when I got time.

**Comment by 3cp** [comment]
https://parceljs.org/features/dependency-resolution/#file-extensions

> Note that these may only be omitted when importing from a JavaScript or TypeScript file. File extensions are always required for dependencies defined in other file types like HTML and CSS.

That's probably the reason, those deps (imports) are from your html file (compiled into js code). Parcel seems disallow omitting file extension in deos from html file.

**Comment by bigopon** [comment]
Maybe we can add an option in our plugin convention to enable the ability to transform import specifiers encountered in template. The Parcel plugin then can provide the callback for this with proper transformation for the bundler.
Let's close this for now, and open a new issue to track that if that is actually requested.

**Comment by ged** [comment]
> Maybe we can add an option in our plugin convention to enable the ability to transform import specifiers encountered in template. The Parcel plugin then can provide the callback for this with proper transformation for the bundler.
> Let's close this for now, and open a new issue to track that if that is actually requested.

I would like to request that functionality. Is this the right way to do that or is there a better way?

**Comment by bigopon** [comment]
For me, the ability to hook into different phases of the template convention based compilation is a good feature. Though @3cp may have some other ideas.

**Comment by 3cp** [comment]
I think it's a good idea and doable.

May not need to be configurable. All bundlers can support import with file extensions.

**Comment by 3cp** [comment]
I will work against this one ticket.

**Comment by ged** [comment]
> Maybe help create a formal featute request @ged ?

I am happy to help out in whatever way I can. I don't mean to speak for the OP, but my main motivation is just to have Aurelia components under Parcel behave as the documentation says they should. Alternatively, I suppose just clarifying somewhere that the component conventions don't apply if you're using Parcel would work as well.

**Comment by 3cp** [comment]
Parcel skeleton has been updated. https://github.com/aurelia/new
