### ISSUE TITLE
Usage of ObserverLocator is poorly described in docs

### ISSUE THREAD

**Issue by ekzobrain** [aurelia/aurelia#1659]
ObserverLocator is described just as an internal api of @observable decorator, while it is not just that. It is a single replacement for Aurelia 1 observers for different kinds of objects. It should mostly be used directly for complex scenarios, so that scenarios should be described in docs: usage out of custom elements (services for example), observing arrays, observing objects/maps/sets, observing collections (arrays of objects), etc.

**Comment by Sayan751** [comment]
With the introduction of the [`@watch` decorator](https://docs.aurelia.io/getting-to-know-aurelia/watching-data), the expectation is that the majority of the data observation use-cases will be covered by that. 

However, you are right that the docs in this area is a bit sparse. We will be happy to accept a PR, if you feel like adding more exciting examples to the docs.

**Comment by bigopon** [comment]
The current doc at https://docs.aurelia.io/getting-to-know-aurelia/observation looks good enough to me. For the observer locator doc itself, it's just the essence of what is useful. This doc will be updated once we solidify the observer locator APIs and observation generally a bit more.
