### ISSUE TITLE
Are the binding behavior bind and unbind arguments in the wrong order in docs?

### ISSUE THREAD

**Issue by ivanbacher** [aurelia/aurelia#1663]
Looking at [binding-behaviors/debounce.ts](https://github.com/aurelia/aurelia/tree/f13be8c440412f6294aa7d28a0f0799cc8c82ec1/packages/runtime-html/src/resources/binding-behaviors) 

```
public bind(scope: Scope, binding: IBinding, delay?: number) 
```

However in the [docs](https://docs.aurelia.io/templates/binding-behaviors#custom-binding-behaviors)

```
bind(binding, scope, interceptor) {
```

Do `binding` and `scope` need to be switched in the docs?

**Comment by bigopon** [comment]
Thanks @ivanbacher
