### ISSUE TITLE
.trigger binding command does not support event names with >1 dot

### ISSUE THREAD

**Issue by ekzobrain** [aurelia/aurelia#1693]
# 🐛 Bug Report

When event name contains more than one dot (eg "show.bs.modal") - no listener is setup on an element (bug, multiple dots should be supported)

Repro link https://stackblitz.com/edit/au2-conventions-n8sl8n?file=src%2Fmy-app.html

## 🤔 Expected Behavior

Events with multiple dots in name should be handled correctly

## 😯 Current Behavior

Developer tools show no event handler on an element

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | 2.0.0-beta.1
| Language         |
| Browser          |
| Bundler          |
| Operating System |
| NPM/Node/Yarn    |

**Comment by ekzobrain** [comment]
@bigopon https://discord.com/channels/448698263508615178/545423969642217474/1073580365039542293

**Comment by bigopon** [comment]
We can only support a fixed number of dot at the moment when parsing our attribute name. Example:
```
PART.PART                -> supports bs-modal.trigger
PART.PART.PART       -> supports bs.modal.trigger
```
If we want to support `PART.PART.PART.PART` as in your example, then maybe it's a BYO:
```ts
@attributePattern(
  { pattern: 'PART.PART.PART.PART', symbols: '.' },
)
export class DotSeparatedAttributePattern {

  public 'PART.PART.PART.PART'(rawName: string, rawValue: string, parts: string[]): AttrSyntax {
    return new AttrSyntax(rawName, rawValue, `${parts[0]}.${parts[1]}.${parts[2}`, parts[3]);
  }
}
```
Or alternatively, we can also implement a way to express repeated parts:
```ts
@attributePattern(
  { pattern: 'PART+.PART', symbols: '.' },
)
export class DotSeparatedAttributePattern {
  public 'PART+.PART'(rawName: string, rawValue: string, parts: string[]): AttrSyntax {
    return ...
  }
}
```
cc @fkleuver @Sayan751

**Comment by Sayan751** [comment]
@bigopon @ekzobrain I think the [docs on this](https://docs.aurelia.io/developer-guides/scenarios/attributepattern) has plenty of examples. Hence, I am inclined towards closing this issue in favour of the docs.

**Comment by Sayan751** [comment]
I was looking into this issue. One can create a custom binding command to extend the Au2 binding language. Here is a working example <https://stackblitz.com/edit/aurelia2-custom-binding-command?file=src%2Fmy-app.ts&file=src%2Fmain.ts>. If you combine that with a custom attribute pattern, then you can extend it further by increasing the number of PARTs.

I will try to add an article to the docs, and then we can close this issue.
