### ISSUE TITLE
Fix inconsistency in passing component and template to routes/dialog/<au-compose>

### ISSUE THREAD

**Issue by ekzobrain** [aurelia/aurelia#1695]
# 🙋 Feature Request

Router, Dialog plugin and au-compose CE all implement dynamic composition. But all of them handle `component` and `template` parameters a bit differently:
1. Router supports (router/router-light may also have some differences)
```ts
component: SomeComponent
component: () => SomeComponent
component: import('./some-component')
component: () => import('./some-component')
component: string // custom element name as i understand?? not described in docs
component: viewModel instance
```
`template` is not supported

2. Dialog supports:
```ts
component: () => SomeComponent | viewModel instance,
component: () => Promise<SomeComponent | viewModel instance>
template: string | Element,
template: Promise<string | Element>
```
a poor set of options comparing to router, but supports `template`, no dynamic imports, no direct assignment for `component` (only callback)

3. au-compose supports:
```ts
viewModel: SomeComponent | viewModel instance
viewModel: Promise<SomeComponent | viewModel instance>  // but no import()
view: string
view: Promise<string>
```
parameter names differ: component - viewModel, template - view. no dynamic imports, no `template` as Element

## 🤔 Expected Behavior

1. Component/template resolving should be extracted to @aurelia/kernel (or @aurelia/runtime) as a set of common methods and interfaces that would be reused by all dynamic composition implementations.
2. May be change au-compose parameter names to `component` and `template` accordinally?
3. Available options to pass component and template framework-wide could be:
```ts
component: SomeComponent | viewModel instance // directly passed Constructable or object instance
component: Promise<SomeComponent | viewModel instance> // promise resolved to a Constructable or object instance
component: import('./some-component') // dynamic import that returns a Constructable
component: () => import('./some-component') // callback returns dynamic import that returns a Constructable, lazy loading
template: string
template: Promise<string>
template: import('./some-template.html') // dynamic import that returns a string
template: () => import('./some-template.html') // callback returns dynamic import that returns a string, lazy loading
```
4. Add `template` support to the router?

So there may be a single interface like this:
```ts
interface IDynamicCompositionComponent {
  component?: Constructable | object | Promise<Constructable | object | IModule> | () => Promise<IModule>;
  template?: string | Element | Promise<string | Element | IModule> | () => Promise<IModule>;
}
```

Then it could be used like this:
```ts
interface IRoute extends IDynamicCompositionComponent {
  ...
}

interface IDialogSettings extends IDynamicCompositionComponent {
  ...
}

export class AuCompose implements IDynamicCompositionComponent {
  @bindable
  public component; // instead of viewModel

  @bindable
  public template; // instead of view
}
```

Also kernel/runtime packages could expose common methods that will be used to resolve `component` to `Constructable`/`object` and `template` to `string` framework-wide.

## 😯 Current Behavior

Different framework parts handle dynamic composition in their own way, support differet options and have their own interfaces

**Comment by ekzobrain** [comment]
@bigopon @Sayan751

**Comment by bigopon** [comment]
this is concerning the router so cc @jwx  as well

**Comment by bigopon** [comment]
Thanks @ekzobrain , one immediate actionable item is to sync `<au-compose/>` `viewModel` and `view` to `component`/`template` respectively. Then we can support `viewModel`/`view` with the `compat-v1` package.

**Comment by ekzobrain** [comment]
Yes, generally this is the most backward-incompatible change (in terms of v2), so it should be in as early as possible.

**Comment by Sayan751** [comment]
I would like to point that these 3 things have different context. Hence, the difference in API is only natural, and it is not an inconsistency. Hence, the value addition is not clear to me, and we should probably don't attempt to achieve this so-called consistency that is devoid of usage-context.

Let me give you an example. Even though it might make sense to rename the `viewModel` to `component` and the `view` to `template` for the `<au-compose>`, the same might not be true if a `template` is added to the route configuration. Because, as per my experience, the routed view models are often heavy on the view model side; for example, they fetch from backend services and so on. Which might be difficult to achieve with template alone.

**Comment by Sayan751** [comment]
Closing this as the au-compose is made consistent.
