### ISSUE TITLE
Html select multipe binding throws "AUR0654: Only null or Array instances can be bound to a multi-select"

### ISSUE THREAD

**Issue by ekzobrain** [aurelia/aurelia#1724]
# 🐛 Bug Report

When using template like this:
```html
<select value.bind="[]" multiple.bind="true">
```
binding engine that setups observer on value array checks that select element has multiple=true property. But it does not have it because is is not yet bound, so error appears. https://github.com/aurelia/aurelia/blob/master/packages/runtime-html/src/observation/select-value-observer.ts#L266
Currently this may be fixed by changing attribute order:
```html
<select multiple.bind="true" value.bind="[]">
```
but this is not obvious... Also text error is a bit confusing considering it's context. I think it would better be: "Array value can be bound only to a multi-select"

## 🤔 Expected Behavior

No error

## 😯 Current Behavior

Error :)

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | 2.0.0.beta-1
| Language         |
| Browser          |
| Bundler          |
| Operating System |
| NPM/Node/Yarn    |

**Comment by bigopon** [comment]
In some scenarios, we probably will say order matters, though for this built-in select element, we can handle since it's a known.
