### ISSUE TITLE
Consumable enums should not be const enum - support TypeScript `verbatimModuleSyntax` (and JS projects)

### ISSUE THREAD

**Issue by josundt** [aurelia/aurelia#1736]
# Background
When evaluating imports/exports, the TypeScript compiler needs to distinguish _type-only_ from _runtime_ imports/exports.
The compiler's default import elision strategy can not always evaluate this 100% correctly, and the compiled JS may end up with import/export statements of modules - even when only types from that module were actually referenced. 
When explicitly using the `type` keyword with imports/exports in the source code, the TypeScript compiler will evaluate this more correctly.

TypeScript 5.0 introduces a new compiler option `verbatimModuleSyntax` (that merges/deprecates some earlier options).
The idea of this flag is to require/enforce using the `type` keyword for __type-only__ imports and exports.
[Reference](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#verbatimmodulesyntax)

I expect `verbatimModuleSyntax` to be the preferred/recommended compiler for TypeScript moving forward, since it more correctly can distinguish types from runtime entities, and avoid unwanted imports/exports in the compiled JS. And with this setting switched on, the TypeScript auto-import refactoring feature automatically includes the `type` keyword correctly when applicable.

# 🐛 Bug Report

When enabling this compiler option in a Aurelia2 project, I get the following compile error whenever a `const enum` from any Aurelia2 package is imported:

_`error TS2748: Cannot access ambient const enums when 'verbatimModuleSyntax' is enabled`_.

The problem is that `const enum` in TypeScript is a type-only enum - the enum itself is not emitted to the JS output and has no runtime representation. A `const enum` can only be used internally within a TypeScript project - since it "exists" at compile-time, but cannot be used by external consumers (f.ex. @aurelia/* package ) as the enums are not defined at runtime.
[Reference](https://www.typescriptlang.org/docs/handbook/enums.html#const-enums)

I therefore suggest that all enums meant to be accessible for @aurelia/* package consumers are turned into regular `enum` instead of `const enum`. (This should not be a too big job, a simple search for "const enum" in the aurelia source gave a manageable number of results.)

I understand that "regular" enums come with a minor size implication. Still; if consumers cannot switch `verbatimModuleSyntax` on, this may have greater bundle size implications for Aurelia2 TypeScript projects. And I guess the enums are not available at all for Aurelia2 JS projects, unless the compiler option `preserveConstEnums` is set to true.

Using "regular" enums is a better option than using const enums with the `preserveConstEnums` compiler option set to true - which I have seen that some packages tsconfig.json files use (i18n/runtime).

FYI: The enums that caused problems for me at this point are:
* LogLevel (packages/kernel/src/logger.ts)
* ColorOptions (packages/kernel/src/logger.ts)
* Signals (packages/i18n/src/utils.ts)

**Comment by bigopon** [comment]
Thanks @josundt . I think we will move away from enum, and using const type instead probably. I'll explore this.

cc @fkleuver @Sayan751

**Comment by josundt** [comment]
> Thanks @josundt . I think we will move away from **public** enum/const enum, and using const type instead probably. I'll explore this.
> 
> cc @fkleuver @Sayan751

In my opinion, standard TS enums should work fine as long as the const keyword is omitted. Then they are also available as simple JS objects at run-time👍

**Comment by Sayan751** [comment]
@bigopon Added this to beta milestone. If you have not already started on this, I can take a dig if you want.

**Comment by bigopon** [comment]
Thanks @Sayan751 please have a go if you like.
