### ISSUE TITLE
RFC - Field level injection via added get function to the inject

### ISSUE THREAD

**Issue by brandonseydel** [aurelia/aurelia#1742]
# 💬 RFC

While injecting via constructor is great, there is a problem when base classing or trying to use in generic functions to construct a result.

## 🔦 Context

Ctor is getting messy when injecting lots of parameters, hard to get an instance from the container in a generic function, and not having to call super with the parent injections would be beneficial for lib auths.

## 💻 Examples

```ts
class AbcNew {
  a = inject.get(A);
  b = inject.get(B);
}

class AbcOld {
  constructor(private readonly a:A, private readonly b:B,}{}
}


// new
class Def extends AbcNew {
 c = inject.get(C);
}

// old
class Def extends AbcOld {
  constructor(a:A, b:B, private readonly c:C}{
  super(a,b);
  }
}

class CrazyStuff {
  a = doSomethingCrazy();
}


doSomethingCrazy(){
const service= inject.get(Service);
const result = service.findAKey('sdfsd');
return inject.get(result);
}
```

@zewa666 @bigopon

**Comment by bigopon** [comment]
I think we need to mention where we have seen this approach and express thanks to their ideas/exploration. Particularly Angular and Vue.

Personally, I think this is not bad, and works well with native class field to avoid having to have constructor as well. One point of discussion could be the function call to inject. Should it be a separate export or a property on the `inject` export itself:
```ts
class Abc {
  a = injected(A)
  // vs
  a = inject.get(A)
  // vs
  a = fromDI(A)
  // vs
  a = di(A)
  // ... etc names
}
```

**Comment by brandonseydel** [comment]
You can see Angular implementation 
https://angular.io/api/core/inject

While this idea is very old they helped flush out the use cases and make it more standard. :)  You can see community contribution for au1 here
https://github.com/devaur/aurelia-property-injection

**Comment by zewa666** [comment]
while at it we could improve the dx via array destructuring to inject multiple keys at once

```ts
const [aa, bb, cc] = inject(a, b, c)
```
```
