### ISSUE TITLE
refactor: extract template compiler into a separate package

### ISSUE THREAD

**Issue by bigopon** [aurelia/aurelia#1746]
## 🔦 Context

As part of the pre compilation work, the template compiler, and likely the expression parsing will need to be extracted into a separate package so that it can be reused by both applications and build tools.

Maybe we can have like this
```diff
+ @aurelia/expression-parser
  @aurelia/runtime
+ @aurelia/template-compiler
  @aurelia/runtime-html
```

One challenge could be around the typings & instructions exports, though they shouldn't be difficult to work out.

**Comment by Sayan751** [comment]
@bigopon This is a great idea! Do you think this can be prioritized for RC?

**Comment by bigopon** [comment]
@fkleuver is assigned this, and im working with him as well. I do want this before rc.

**Comment by bigopon** [comment]
The expression parser has been extracted to its own package in #1943, we just need to do the same work to the template compiler.
