### ISSUE TITLE
Value not set on HTMLInputElement under JSDOM using `value.bind`

### ISSUE THREAD

**Issue by tomtomau** [aurelia/aurelia#1758]
# 🐛 Bug Report

Given a simple binding, the below works as expected in the browser:
```typescript
<input type="text" value.bind="value">
```

When testing under jsdom (per the stock standard install from `npx makes aurelia`, Typescript variant):
```typescript
 expect(input.value).toBe('some value');
 ```
 
Will fail because `input.value` returns an empty string instead of a bound value.

Refer to reproduction link created using `npx makes aurelia`:

https://github.com/tomtomau/jsdom-au2-repro/pull/1

## 🤔 Expected Behavior

The tests in the reproduction should pass.

## 😯 Current Behavior

```
<!-- ✅ Passes test, but not practical (hardcoded value) - just for debugging -->
<div>
    <p>This uses a hardcoded string, so it sets the value initially, but it won't have two way binding. It's mostly here for debugging.</p>
    <input id="optionA" type="text" value="Hello World!">
</div>

<!-- ❌ Fails test -->
<div>
    <p>This one sets the value in the browser, but in tests it returns empty string?</p>
    <input id="optionB" type="text" value.bind="value">
</div>

<!-- ❌ Fails test -->
<div>
    <p>This one doesn't get the value bound in the browser (?) and doesn't get set in tests.</p>
    <input id="optionC" type="text" value.bind>
</div>

<!-- ✅ Passes test, but not practical (no two-way binding) -->
<div>
    <p>This use string interpolation, so it won't have two way binding. The tests pass because it sets the value initially though. It's mostly here for debugging.</p>
    <input id="optionD" type="text" value="${value}">
</div>
```

## 💁 Possible Solution

My best guess is this is something related to how `value.bind` works on HTMLInputElements and the possible limitations of the jsdom API.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | 2.0.0-beta.5   
| Language         |
| Browser          |
| Bundler          |
| Operating System |
| NPM/Node/Yarn    |

**Comment by bigopon** [comment]
```html
    <input id="optionB" type="text" value.bind="value">
```
With `render` setup like in the repro, the observer locator will be using a noop node observer locator, which doesn't know that it should have two way binding for `value.bind` on input. We should be using `createFixture` from `@aurelia/testing` to ensure all basic registrations are in place, or you can do this
```ts
import { NodeObserverLocator } from 'aurelia'

```

**Comment by bigopon** [comment]
For the option C
```html
<!-- ❌ Fails test -->
<div>
    <p>This one doesn't get the value bound in the browser (?) and doesn't get set in tests.</p>
    <input id="optionC" type="text" value.bind>
</div>
```
The reason it doesn't work, is because it's not yet been implemented. I think @brandonseydel was requesting it but we were still in the discussion what the final details should be. It's here #1259

**Comment by tomtomau** [comment]
Thanks for your help with this @bigopon ❤️ 

The solution here really was to use createFixture().

Separately - has there been any talk about supporting `happy-dom` instead of `jsdom`? We're battling a few setup issues that `globalize()` from `aurelia-pal-nodejs` in v1 supported

**Comment by bigopon** [comment]
@tomtomau our testing fixture doesn't care about what the underlying dom environment is. We have a platform layer for this.
The following is how jsdom is setup in this repo:
```ts
import { BrowserPlatform } from '@aurelia/platform-browser';
import { setPlatform } from '@aurelia/testing';
import { JSDOM } from 'jsdom';

const jsdom = new JSDOM(`<!DOCTYPE html><html><head></head><body></body></html>`, { pretendToBeVisual: true });

const platform = new BrowserPlatform(jsdom.window as unknown as Window & typeof globalThis, {
  // ... overrides here
  fetch: () => Promise.resolve({})
});
setPlatform(platform)

console.log(`Node JSDOM test context initialized`);
```
You can just replace the jsdom instance with happy dom, and use `window` object returned from it and we'll be as good.

For this issue, I'll close this for now, thanks for reporting.

**Comment by bigopon** [comment]
The `value.bind` part is done in #1963
