### ISSUE TITLE
@newInstanceOf decorator doesn't work properly on IHttpClient

### ISSUE THREAD

**Issue by mt-mshorrosh** [aurelia/aurelia#1765]
In the following snippet of code, `config` here seems to be a singleton so whichever service registers last overwrites the config on any previous ones. It could just be that a new instance of `IHttpClient` is never created thus the entire client instance is a singleton.  I've discussed this with @bigopon on discord and even though the examples at https://docs.aurelia.io/aurelia-packages/fetch-client#configuring-the-fetch-client show this as being the proper usage, it simply doesn't work.  If I switch to use `HttpClient` instead, all is well. 

![image](https://github.com/aurelia/aurelia/assets/104581968/430e190b-bd2a-4a5e-b2fc-f3a4c277a837)

You can see in the following screenshot that upon service 2 being registered, it has service 1's base URL.  As soon as service 2 sets its base URL, service 1's will be incorrect.  

![image](https://github.com/aurelia/aurelia/assets/104581968/5b3c06a1-c424-4139-9804-d4c031a7b818)
        
I have created a repo to demonstrate this located at https://stackblitz.com/edit/au2-conventions-pphynj?file=src%2Fmy-app.ts.

**Comment by bigopon** [comment]
Thanks @mt-mshorrosh . This is because the newInstance resolvers dont try to resolve the interface, but only construct it. It should try to resolve the interface first probably.
