### ISSUE TITLE
[Feature Request] Support Nullish coalescing in templating

### ISSUE THREAD

**Issue by CollinHerber** [aurelia/aurelia#1769]
# 🙋 Feature Request

Support Nullish coalescing (??) within templates.

## 🤔 Expected Behavior
When label is null, show "Enter Label"
>${label ?? "Enter Label"}

## 😯 Current Behavior

>${label ?? "Enter Label"}

When label is null "Enter Label" is not shown

>${label ? label : "Enter Label"}

This currently works

**Comment by Vheissu** [comment]
This should be supported, as we document this syntax and other newer forms of syntax are supported. In the meantime while I get an answer for this, you can do this as a workaround if you want cleaner syntax:

```html
${label || "Enter Label"}
```

**Comment by CollinHerber** [comment]
> This should be supported, as we document this syntax and other newer forms of syntax are supported. In the meantime while I get an answer for this, you can do this as a workaround if you want cleaner syntax:
> 
> ```
> ${label || "Enter Label"}
> ```

It is not supported.
Sample here https://stackblitz.com/edit/au2-conventions-ttzm2n?file=src%2Fmy-app.html

|| works though. However ?? should work as well.

**Comment by bigopon** [comment]
`??` works, and exactly as expected. Though in text binding like in your example, `null`/`undefined` get converted to an empty string because text binding expressions are eval'd in non strict mode.
Here's an example to illustrate it https://stackblitz.com/edit/au2-conventions-cbmca3?file=src%2Fmy-app.html,src%2Fmy-app.ts

Maybe we should also make text binding strict by default.

cc @fkleuver @Sayan751 @jwx @brandonseydel @Vheissu

**Comment by CollinHerber** [comment]
I don't understand. It does not appear as I would expect it to. Here is an updated example. https://stackblitz.com/edit/au2-conventions-zj2zf8?file=src%2Fmy-app.html,src%2Fmy-app.ts
I created a getter, and then inside the templating example the same code. One presents the message, the other does not.

**Comment by brandonseydel** [comment]
> `??` works, and exactly as expected. Though in text binding like in your example, `null`/`undefined` get converted to an empty string because text binding expressions are eval'd in non strict mode. Here's an example to illustrate it https://stackblitz.com/edit/au2-conventions-cbmca3?file=src%2Fmy-app.html,src%2Fmy-app.ts
> 
> Maybe we should also make text binding strict by default.
> 
> cc @fkleuver @Sayan751 @jwx @brandonseydel @Vheissu

The output of the expression should be strict or not and not the individual expressions inside imo.

**Comment by bigopon** [comment]
> I don't understand. It does not appear as I would expect it to ...
> ... I created a getter, and then inside the templating example the same code. One presents the message, the other does not.

I was not clear enough. What I meant is if we have
```ts
<div>${message ?? 'default'}</div>
```
it's treated as
```ts
<div>${(message ?? '') ?? 'default'}</div>
```
This behavior of `message` -> `message ?? ''` is a behavior from v1 that we are keeping, we call this a non-strict mode.

I think for v2, we shouldn't support this anymore, and encourage folk to use optional syntax instead.

**Comment by bigopon** [comment]
Note that it's only in non strict mode for text interpolation, other bindings are in strict mode by default
```ts
<div textcontent.bind="message ?? 'default'"></div>
```
