### ISSUE TITLE
[router-lite] Open in new tab does not grab correct url

### ISSUE THREAD

**Issue by CollinHerber** [aurelia/aurelia#1776]
# 🐛 Bug Report

On Aurelia 2 opening a link in a new tab results in the url only containing what in the load area.
IE if I am on the route /something/foo
and I have a <a load="bar">
If I just click on it I am properly navigated to /something/foo/bar
However if you open it in a new tab you are navigated to /bar

Repro link https://stackblitz.com/edit/au2-conventions?file=src%2Fmy-app.html

## 🤔 Expected Behavior

I am properly navigated to /something/foo/bar

## 😯 Current Behavior

if you open it in a new tab you are navigated to /bar

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          |
| Language         |
| Browser          |
| Bundler          |
| Operating System |
| NPM/Node/Yarn    |

**Comment by CollinHerber** [comment]
I just pulled the latest dev and not seeing this work yet, does dev have these changes?

**Comment by Sayan751** [comment]
This is not yet realesed. However I think we might be closer to cut the next beta release.

**Comment by Sayan751** [comment]
This is now fixed in v2.0.0-beta.7.

**Comment by Sayan751** [comment]
@CollinHerber I think you might be missing the `<base href="/">` in index.html. For more refer https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base. I am closing this again. If you still face the issue, please consider opening a new issue with a reproduction.

**Comment by CollinHerber** [comment]
> @CollinHerber I think you might be missing the `<base href="/">` in index.html. For more refer https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base. I am closing this again. If you still face the issue, please consider opening a new issue with a reproduction.

I am not missing this in my index.html.
