### ISSUE TITLE
Synthetic views cannot hydrate custom elements registered locally to ancestor

### ISSUE THREAD

**Issue by Sayan751** [aurelia/aurelia#1785]
# 🐛 Bug Report

Repro link https://stackblitz.com/edit/synthetic-view?file=src%2Fmy-app.ts,src%2Fmain.ts

If you check out the repro, there is a `ValueText` CE registered to the root `MyApp`. The root uses the `FooBar` and packs the `ValueText` as a child. The `FooBar` processes The child fragment via `processContent` hook and subsequently create a view factory. The view factory is later hydrated by a template controller.

## 🤔 Expected Behavior

The `ValueText` is hydrated.

## 😯 Current Behavior

The `ValueText` is not hydrated. It works iff the `ValueText` is registered to the root container.

## 💁 Possible Solution

This is an artefact of how the resources are resolved. Either we need to copy the resources from parent when creating a child container, or pass on a flag from `Controller.$view` to instruct that the container chain needs to be traversed.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          |
| Language         |
| Browser          |
| Bundler          |
| Operating System |
| NPM/Node/Yarn    |

**Comment by bigopon** [comment]
It is as you mentioned in the possible solution part. This is the problematic part with the approach:
```ts
    this.factory = new ViewFactory(controller.container, definition);
```
we are assuming the `controller` of the template controller owner has all the resources required in the template but it doesn't. We can solve this by creating a container with inherited resources from the hydration context like this example https://stackblitz.com/edit/synthetic-view-55p3ap?file=src%2Fmy-app.ts,src%2Fmain.ts

**Comment by Sayan751** [comment]
@bigopon Thanks! That's a great solution!

**Comment by Sayan751** [comment]
@bigopon I think I have spoken too early 😝 What I have overlooked is that your solution disregards any dependency resources registered to the custom element performing the `processContent`. I think we need a general API to merge container resources. Think about template controllers registered internally only for a particular CE inside a package.

**Comment by Sayan751** [comment]
Never mind 😄  The following works. Overlooked the `definition` in the `define` hook 😛 

```ts
const container = hydrationContext!
  .controller
  .container
  .createChild({ inheritParentResources: true })
  .register(definition.dependencies);
```

**Comment by Sayan751** [comment]
Closing this, as I have a working solution.
