### ISSUE TITLE
[Feature request] Enhance should call app tasks

### ISSUE THREAD

**Issue by Vheissu** [aurelia/aurelia#1787]
# 🙋 Feature Request

Currently, the enhance functionality does not fire app tasks, which means you cannot use the router with enhance (possibly other things that rely on app tasks).

## 🤔 Expected Behavior

App tasks should be called regardless of whether you're starting an entire instance or using enhance.

## 😯 Current Behavior

App tasks are not fired.

**Comment by Sayan751** [comment]
Sounds like a 2nd instance of an Aurelia app 😃

**Comment by Sayan751** [comment]
@Vheissu I have created a simple [working solution](https://stackblitz.com/edit/gh1787-apptasks-and-enhance?file=src%2Fmy-app.ts,index.ejs,src%2Fmain.ts,package.json) based on i18n, as that involves invoking AppTasks.

Is your use-case more complex than this? If that suffices for your use-case as well, then consider closing this issue.
