### ISSUE TITLE
DI resolving for value converters works incorrecty within slotted content

### ISSUE THREAD

**Issue by ekzobrain** [aurelia/aurelia#1797]
# 🐛 Bug Report

Cause might be this PR: https://github.com/aurelia/aurelia/pull/1735

Example:

```typescript
class SomeCustomElementWithSlot {}
```

```html
<template>
  <au-slot></au-slot>
</template>
```

```typescript
class SomeCustomElement {
  static dependencies = [SomeCustomElementWithSlot, SomeValueConverter];
}
```

```html
<some-custom-element-with-slot>
  <input value.bind="value | someValueConverter">
</some-custom-element-with-slot>
```

## 🤔 Expected Behavior

works

## 😯 Current Behavior

Throws exception:
```Error: AUR0009: Attempted to jitRegister something that is not a constructor: 'au:resource:value-converter:someValueConverter'. Did you forget to register this resource?```
Seems like the wrong container is invoked, but only for evaluated expressions (value converters, binding behaviors), because custom elements are resolved correctly.

## 💁 Possible Solution

Register value converter in the root container.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | 2.0.0-beta.7
| Language         |
| Browser          |
| Bundler          |
| Operating System |
| NPM/Node/Yarn    |

**Comment by bigopon** [comment]
Resolved by #1802
