### ISSUE TITLE
Binding to checkbox with array works wrongly when using model.bind="undefined" and value.bind

### ISSUE THREAD

**Issue by ekzobrain** [aurelia/aurelia#1804]
# 🐛 Bug Report

When using both value.bind (with any correct string value) and model.bind with `undefined` value on input element, array binding (https://docs.aurelia.io/templates/forms#array-of-strings) breaks.
I have such template because I have a custom element which wraps input and thus has `value` and `model` bindings.

Repro link: https://stackblitz.com/edit/au2-conventions-fygzff?file=src%2Fmy-app.ts,src%2Fmy-app.html

## 🤔 Expected Behavior

model.bind="undefined" works as if it was not used at all

## 😯 Current Behavior

array binding does not work

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | 2.0.0-beta.7
| Language         |
| Browser          |
| Bundler          |
| Operating System |
| NPM/Node/Yarn    |

**Comment by bigopon** [comment]
Technically speaking there's not a reliable way to tell whether `undefined` is a valid value or not, thus it's not safe to fallback to `value` when `model` value is `undefined`. I'm not sure we can support such feature.
What if `model.bind` is undefined and there's no value binding either? it would give wrong value all the times. (some string).

**Comment by Sayan751** [comment]
The [docs](https://docs.aurelia.io/templates/forms#array-of-numbers) do not cite any similar examples, as shown in this issue. Hence, I would assume that this is not supported.

Here is a working example: https://stackblitz.com/edit/au2-conventions-kryzmq?file=src%2Fmy-app.html

I am closing this issue for now. Feel free to reopen if there are real-life use-cases that are not satisfied with the documented way to binding checkboxes.
