### ISSUE TITLE
templating engine drops attributes from au-compose tag

### ISSUE THREAD

**Issue by ekzobrain** [aurelia/aurelia#1806]
# 🐛 Bug Report

When using au-compose with additional html attributes (like style for example) in template - they are dropped in output HTML.
It worked in earlier versions.

Repro link https://stackblitz.com/edit/au2-conventions-peynua?file=src%2Fmy-app.html,src%2Fmy-app.ts,src%2Fmy-app.css

## 🤔 Expected Behavior

output html is like this:
```html
<au-compose style="width: 20%"></au-compose>
<au-compose style="width: 30%"></au-compose>
```

## 😯 Current Behavior

output html is like this:
```html
<au-compose></au-compose>
<au-compose></au-compose>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | 2.0.0-beta.8
| Language         |
| Browser          |
| Bundler          |
| Operating System |
| NPM/Node/Yarn    |

**Comment by bigopon** [comment]
Thanks @ekzobrain , the style attribute should also be transferred to the host element of the composed custom element. This is unintentional.

**Comment by ekzobrain** [comment]
Yes, in case of rendering a custom element - it works. But does not work with `containerless` feature (in this case i think attributes whould remain on `au-compose`, but they just disappear).
`au-compose` also seems not to work with non-custom element (with convensions) at all. Nothing gets renderer in this case

**Comment by bigopon** [comment]
> non-custom element at all. Nothing gets renderer in this case.

Non custom elements don't get the same treatment with custom elements, so the `static template` part wasn't used. Were you expecting it to work as if it was a custom element?

> attributes should remain on au-compose, as with non-custom element composition

We could, but this will make it incredibly complex I think. Shouldn't it be simpler for apps to have
```html
<au-compose containerless ...>
```
?

**Comment by ekzobrain** [comment]
I think you need an RFC about dynamic composition behavior, which will be transferred to docs afterwards :) The first thing to note is that all dynamic composition parts (au-compose, dialog, au-viewport) should work the same regarding:
1. explicit custom elements / custom elements with convensions / non-custom elements / etc (in fact I do not know exact differences between those)
2. containerless support
3. attribute transferring support

This issue is also relative #1695 

I would try to extract a general dynamic composition function to the core, and then reuse it where applicable. This will result in:
1. more reliable code
2. more convinient overall behavior
3. less code
4. better framework extension capaibilities for plugin authors

About containerless - I suspect that it is better to use the `containerless` option of a composed custom element, while only element itself knowns it's capabilities to work without the host. But if it is hard to detect this while transferring attributes, then it should be pointed out by RFC. This could be solved by another option `au-compose` option which will allow to switch off attribute transferring at all.

**Comment by bigopon** [comment]
> I would try to extract a general dynamic composition function to the core, 

It likely will be like this, thanks for the suggestion.

> But if it is hard to detect this while transferring attributes

It's not hard to decide to whether transfer or not, but it's unclear what happens when we transition from a containerless to a non-containerless custom element. All bindings that resulted in attributes on `<au-compose>` elements will need to be dealt with, or left alone? For example, in your code of this issue, what happens when we compose another element that is not containerless afterwards. But yeah, maybe an RFC is better so that the behaviors can be properly doc'd.

**Comment by bigopon** [comment]
I think a solution for a better consistency/meeting expectation would be to:
- have `<au-compose>` always create host element for the composition
  - if the view model is a custom element, an element with corresponding name will be created
  - if the view model is not a custom element, a `<div/>` will  be created. This `<div/>` is configurable via a bindable on the au-compose:
      ```html
      <au-compose tag="p" view-model.bind="{ content: 'some text' }">
      ```
      This would result in the following html
      ```html
      <p>...</p>
      ```

**Comment by bigopon** [comment]
> May be replace au-compose element with rendered host element instead of appending host to it?

This is what its doing, as au compose itself is now containerless.

And au compose supports containerless custom element composition

**Comment by ekzobrain** [comment]
That's great. Are additional attributes like style/class transferred from au-compose to rendered component host element now?

**Comment by bigopon** [comment]
@ekzobrain it should work like that, yes. We have tests for both scenarios in au compose test file. Maybe we can add another like above for solidness.

Im think au compose can also be enhance to work with string as custom element name. Itll be similar to current router rendering mode, so itll be on parity.

Any thoughts @fkleuver @Sayan751 @jwx ?

**Comment by bigopon** [comment]
@ekzobrain these two tests should demonstrate the case you mentioned
https://github.com/aurelia/aurelia/blob/309a1308e5af99f977543afc60680003d88b5707/packages/__tests__/src/3-runtime-html/au-compose.spec.ts#L1347-L1392

**Comment by bigopon** [comment]
@ekzobrain you can test the scenario using latest dev version, together with the new feature string as component name.

**Comment by ekzobrain** [comment]
Sounds great, can't wait for it to be released! Providing a component as element name seems useful for application-level configurable dynamic composition.

**Comment by ekzobrain** [comment]
@bigopon does au-compose support au-slot? Will this example work?
'''html
<au-compose component.bind="xxx">
 <some-projected-markup/>
</au-compose>
'''
Considering "xxx" component uses au-slot projection?

**Comment by bigopon** [comment]
@ekzobrain yes au slot works as expected. Shadow dom only works with direct usage, we can make it work too but it'll feel very different, I'll prefer leave it out. You can see it in this example https://stackblitz.com/edit/au2-conventions-ugq2up?file=src%2Fmy-app.html,src%2Fmy-app.ts
