### ISSUE TITLE
router: popstate events are broken with empty routes ('')

### ISSUE THREAD

**Issue by MercinaM** [aurelia/aurelia#1812]
# 🐛 Bug Report

When navigating back to the default route, the router does not correctly load the component associated with the empty route, but instead either leaves the viewport empty (root viewport), or keeps the component associated with the previous route (nested viewport).

Repro link https://stackblitz.com/edit/au2-conventions-kpnr9p, but the error can also be reproduced in the official routing example at https://simple-routing.vercel.app

## 🤔 Expected Behavior

When I navigate from the default route to another route, then return back with the browser's back button, the home component should be displayed.

When I navigate to the route with nested sub-routes, then to nested page 2, then go back with the browser's back button, the nested page 1 should be displayed.

## 😯 Current Behavior

When I navigate from the default route to another route, and return back with the browser's back button, nothing is displayed.

When I navigate to the route with nested sub-routes, then to nested page 2, then go back with the browser's back button, the nested page 2 is still displayed.

## 💁 Possible Solution

Right now, the only way I know to avoid the error is to not use default routes.

**Comment by aegenet** [comment]
Hello, until a fix is released, you can apply a "dirty" patch to Aurelia 2 using `patch-package` if you'd like. Use the following patch file:

./patches/@aurelia+router+2.0.0-beta.8.patch
```diff
diff --git a/node_modules/@aurelia/router/dist/esm/index.dev.mjs b/node_modules/@aurelia/router/dist/esm/index.dev.mjs
index 4d4a3b6..718e4e4 100644
--- a/node_modules/@aurelia/router/dist/esm/index.dev.mjs
+++ b/node_modules/@aurelia/router/dist/esm/index.dev.mjs
@@ -4978,6 +4978,10 @@ let Navigator = class Navigator {
         storeable.instruction = RoutingInstruction.stringify(this.container, storeable.instruction);
         // Make sure full state instruction is a string
         storeable.fullStateInstruction = RoutingInstruction.stringify(this.container, storeable.fullStateInstruction, false, true);
+        if (storeable.fullStateInstruction === '-' && (typeof navigation.fullStateInstruction === 'string' ? navigation.fullStateInstruction === '' : navigation.fullStateInstruction?.find(f => f.route?.matching === ''))) {
+            // '-' is ignored in the lifecycle...
+            storeable.fullStateInstruction = '';
+        }
         // Only string scopes can be stored
         if (typeof storeable.scope !== 'string') {
             storeable.scope = null;
diff --git a/node_modules/@aurelia/router/dist/esm/index.mjs b/node_modules/@aurelia/router/dist/esm/index.mjs
index cb8937c..809f965 100644
--- a/node_modules/@aurelia/router/dist/esm/index.mjs
+++ b/node_modules/@aurelia/router/dist/esm/index.mjs
@@ -3163,6 +3163,10 @@ let k = class Navigator {
         const i = t instanceof Navigation ? t.toStoredNavigation() : t;
         i.instruction = RoutingInstruction.stringify(this.container, i.instruction);
         i.fullStateInstruction = RoutingInstruction.stringify(this.container, i.fullStateInstruction, false, true);
+        if (i.fullStateInstruction === '-' && (typeof t.fullStateInstruction === 'string' ? t.fullStateInstruction === '' : t.fullStateInstruction?.find(f => f.route?.matching === ''))) {
+            // '-' is ignored in the lifecycle...
+            i.fullStateInstruction = '';
+        }
         if (typeof i.scope !== "string") {
             i.scope = null;
         }
```

**Comment by Sayan751** [comment]
@aegenet Would you be interested in submitting a PR with the fix?
