### ISSUE TITLE
Bug: redirectTo in navigationModel

### ISSUE THREAD

**Issue by elitastic** [aurelia/aurelia#1815]
# 🐛 Bug Report

`redirectTo` route should be excluded from navigationModel in router-lite:

https://stackblitz.com/edit/au2-conventions-gt6vkx

I also cannot exclude the redirectTo route from navigationModel as `nav: false` ist not a valid property of a `redirectTo` route.

## 🤔 Expected Behavior

A `redirect` route should be excluded from navigationModel

## 😯 Current Behavior

A `redirect` route is included in navigationModel

**Comment by Sayan751** [comment]
I like this idea. Having this in place, might make the router-lite code a lot cleaner. I think the only case where removing it might cause a problem is where there is a `redirectTo` configuration with title. I think that in that case, the assumption is to include it in the nav-model. 

Even though I am inclined towards removing it from the nav-model in favour of cleaner code. My assumption here is that it is unlikely to encounter numerous routes with `redirectTo` in a real app. Thus, if those routes are removed from the nav model in router-lite, it might not be too hard for dev to create those navigational links manually.

What do you think @bigopon?

**Comment by Sayan751** [comment]
I have prepared the PR. However, I think we should not merge that in a haste. First, let us iron out any remaining issues/question etc.

**Comment by elitastic** [comment]
@Sayan751, unfortunately, it's not possible to deactivate a redirect route in the nav model, as `nav` is not a valid option of a redirect route:

`Error: AUR3557: Unknown redirect route config property: "welcome.routes[0].nav". Only 'path' and 'redirectTo' should be specified for redirects.`

That's why it looks more like a bug to me than an interesting idea ;-)

**Comment by bigopon** [comment]
> I think the only case where removing it might cause a problem is where there is a redirectTo configuration with title. I think that in that case, the assumption is to include it in the nav-model.

Maybe we can also say that it's weird that there are 2 titles for the same route, it'll confuse either the devs or users.

> Even though I am inclined towards removing it from the nav-model in favour of cleaner code. My assumption here is that it is unlikely to encounter numerous routes with redirectTo in a real app. Thus, if those routes are removed from the nav model in router-lite, it might not be too hard for dev to create those navigational links manually.

👍
