### ISSUE TITLE
Rollup Generation Fails on @containerless and @capture decorators

### ISSUE THREAD

**Issue by CollinHerber** [aurelia/aurelia#1828]
# 🐛 Bug Report

So I was working with @brandonseydel and was working on https://github.com/Betsy-Bot/betsy-web-components and through some discovery Brandon said that the decorators `@capture` and `@containerless` were causing the generated components to not generate properly. I'm not sure exactly what went wrong I'm just kinda playing telephone here as I wasn't the one that made the discovery.

A known workaround was by adding `static containerless = true` or `static capture = true` within the class scope to get the same behavior. So there is a workaround. 

The exact setup can be found here https://github.com/Betsy-Bot/betsy-web-components/commits/new-dist

I would ask @brandonseydel for more information on the issue as he can better articulate the problem.

## 🤔 Expected Behavior

Rollup generation for components should work with decorators

## 😯 Current Behavior

Need to use static definiton to get the decorator behavior.

## 🔦 Context

Trying to make a Material Web 3 Component library for Aurelia 2

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | Beta 8
| Language         |
| Browser          |
| Bundler          | Rollup & Vite
| Operating System | Mac OS
| NPM/Node/Yarn    | Node 20 * PNPM 8

**Comment by bigopon** [comment]
With the new code generation done in #1960 , we don't have this issue any more. Let's reopen it when we change our code back to decorator.
