### ISSUE TITLE
Rollup Generation Fails when using Conventions

### ISSUE THREAD

**Issue by CollinHerber** [aurelia/aurelia#1831]
# 🐛 Bug Report

Same context as https://github.com/aurelia/aurelia/issues/1828
Check out that ticket for a bit more context

But basically I was using Conventions for my custom elements and the rollup generation would not work correctly.
I need to swap all components to use `@customElement` decorators

I also needed to add a plugin to my vite config: Code courtesy of @brandonseydel 
```ts
export const rawHtml = () => {
  const filter = rollupPluginutils.createFilter('*/.ts', undefined);
  return {
    name: 'raw',
    transform: function transform(code: string, id: string) {
      if (!filter(id)) return;
      if (code.includes('__au2ViewDef')) return;
      code = code.replaceAll(/(import .* from .*).html/g, '$1.html?raw');
      return { code };
    },
  };
};
```
Brandon will be able to provide more insight if needed. I am just creating the ticket per his request.

## 🤔 Expected Behavior

Conventions when using Rollup should work as intended. Configuration approach should not be forced.

## 😯 Current Behavior

Conventions do not work and configuration is forced.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | Beta 8
| Language         |
| Browser          |
| Bundler          | Vite
| Operating System |
| NPM/Node/Yarn    | PNPM 8 Node 20

**Comment by bigopon** [comment]
With the new code generation in #1960 , we won't have this issue anymore. Let's re-create this when we have a code generation.

**Comment by dkent600** [comment]
I am still having this problem with and without `enableConventions` being set on the aurelia-vite-plugin.

Using @aurelia/vite-plugin@2.0.0-beta.18
