### ISSUE TITLE
HTML attribute removed on binding/templating

### ISSUE THREAD

**Issue by Robbendebiene** [aurelia/aurelia#1832]
Thanks a lot for this framework, it is so delightful working with it!

# 🐛 Bug Report

```ts
export class Example {
  label = 'Test';
}
```
```html
<template>
  <div id="${label}" popovertarget="${label}"></div>
</template>
```

Repro link https://stackblitz.com/edit/au2-conventions-nqkrrr?file=src%2Fmy-app.html
## 🤔 Expected Behavior

Attribute `popovertarget` should be set with the substituted value.

```html
<div id="Test" popovertarget="Test"></div>
```

## 😯 Current Behavior

Attribute `popovertarget` is removed/missing.

```html
<div id="Test"></div>
```

## 💁 Possible Solution

So far it seems like aurelia somewhere explicitly defines attribute names/types for which templating works. I would expect that it is mostly agnostic to the actual attribute name since web standards are constantly evolving.

## 🔦 Context

I wanted to try out the new [Popover API](https://developer.mozilla.org/en-US/docs/Web/API/Popover_API) in one of my projects.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | 2.0.0-beta.8
| TypeScript         | 
| Firefox          |  119
| Chrome          | 119
| Fedora Linux  | 38
| NPM    | 10.2.0

**Comment by bigopon** [comment]
Thanks @Robbendebiene , this happens because `popovertarget` is not considered a property instead of an attribute. If you check the `<div/>`, you'll see it has a property `popovertarget` with value `Hello world!`. This'll be a simple fix. It'll be an additional value for the list here https://github.com/aurelia/aurelia/blob/35f5d70f9b6c090cb84eead3ae5c50f58e8c56f1/packages/runtime-html/src/observation/observer-locator.ts#L244-L252

**Comment by Robbendebiene** [comment]
Thanks for the explanation.

Other new attributes that are related to this and need to be added as well are:
- `popovertargetaction`
- `anchor` (see https://developer.chrome.com/blog/tether-elements-to-each-other-with-css-anchor-positioning/)

Out of interest, why isn't there something like a  `FusedAccessor` that tries to use `PropertyAccessor` with a fallback to the `DataAttributeAccessor`?

**Comment by bigopon** [comment]
For the main popover APIs, they have been resolved. For `anchor` attribute, probably it's better, for now, to avoid since it's not official enough yet. We will be adding it as soon as it makes it way to mdn.
