### ISSUE TITLE
Inconsistencies in Router Documentation 

### ISSUE THREAD

**Issue by ivanbacher** [aurelia/aurelia#1834]
I might have found some inconsistencies in the router/route-lite documentation. Should all of the below not have the same parameters or the same naming conventions?

```
canLoad(
  params: Params, 
  next: RouteNode, 
  current: RouteNode | null
)
```

[Router/Lifecycles](https://docs.aurelia.io/routing/routing-lifecycle)
```js
canLoad(
	params: Parameters, 
	instruction: RoutingInstruction, 
	navigation: Navigation
)
```

[Router/Hooks](https://docs.aurelia.io/routing/router-hooks)
```js
canLoad(
	viewModel, 
	params: Parameters, 
	instruction: RoutingInstruction, 
	navigation: Navigation)
```

[Router-lite](https://docs.aurelia.io/router-lite/routing-lifecycle)
```js
canLoad(
	params: Params, 
	next: RouteNode, 
	current: RouteNode | null
)
```

[Router-lite/hooks](https://docs.aurelia.io/router-lite/router-hooks)
```js
canLoad(
  viewModel: IRouteViewModel,
  params: Params,
  next: RouteNode,
  current: RouteNode | null
)
```

**Comment by Sayan751** [comment]
@ivanbacher Note that the underlaying implementations of router and router-lite are very different from one another. Thus, even though we can use the same hook names for both the routers, the parameters passed on to those hooks are of different data-structures/types. Probably, those types cannot be reconciled. Like @Vheissu, I am also of the opinion that the docs need to mention this somehow better. Do you have an idea, as to how to improve the docs? If so, please feel free to submit a PR.
