### ISSUE TITLE
Replace sass-lint to get rid of critical vulnerabilities

### ISSUE THREAD

**Issue by Eagle94T** [aurelia/aurelia#1836]
# 🙋 Feature Request

When installing the latest version of aurelia2 with `npx makes aurelia` a dependency to sass-lint is used. However, sass-lint is not maintained anymore, and should thus be replaced e.g. with stylelint.

## 🤔 Expected Behavior

A fresh installation of aurelia does not contain unmaintained dependencies or dependencies with critical vulnerabilities.

## 😯 Current Behavior

Currently a fresh installation of aurelia already contains 8 vulnerabilities due to the unmaintained sass-lint dependency

## 💁 Possible Solution

Instead of using sass-lint, I suggest usin [stylelint](https://www.npmjs.com/package/stylelint#stylelint) with [stylelint-config-standard-scss](https://www.npmjs.com/package/stylelint-config-standard-scss#stylelint-config-standard-scss) and additionaly [stylelint-config-css-modules](https://www.npmjs.com/package/stylelint-config-css-modules#stylelint-config-css-modules).

## 🔦 Context

Used configuration for reproducing the behavior:

![image](https://github.com/aurelia/aurelia/assets/14317524/68d02b87-2070-4dab-8ab3-169da6bf4699)

## 💻 Examples
```
# npm audit report

ajv  <6.12.3
Severity: moderate
Prototype Pollution in Ajv - https://github.com/advisories/GHSA-v88g-cgmw-v5xw
fix available via `npm audit fix`
node_modules/table/node_modules/ajv
  table  3.7.10 - 4.0.2
  Depends on vulnerable versions of ajv
  node_modules/table

merge  <2.1.1
Severity: high
Prototype Pollution in merge - https://github.com/advisories/GHSA-7wpw-2hjm-89gp
No fix available
node_modules/merge
  sass-lint  *
  Depends on vulnerable versions of eslint
  Depends on vulnerable versions of gonzales-pe-sl
  Depends on vulnerable versions of merge
  node_modules/sass-lint

minimist  1.0.0 - 1.2.5
Severity: critical
Prototype Pollution in minimist - https://github.com/advisories/GHSA-vh95-rmgr-6w4m
Prototype Pollution in minimist - https://github.com/advisories/GHSA-xvch-5gv4-984h
No fix available
node_modules/minimist
  gonzales-pe-sl  *
  Depends on vulnerable versions of minimist
  node_modules/gonzales-pe-sl

shelljs  <=0.8.4
Severity: high
Improper Privilege Management in shelljs - https://github.com/advisories/GHSA-64g7-mvw6-v9qj
Improper Privilege Management in shelljs - https://github.com/advisories/GHSA-4rq4-32rv-6wp6
No fix available
node_modules/shelljs
  eslint  1.4.0 - 4.0.0-rc.0
  Depends on vulnerable versions of shelljs
  node_modules/sass-lint/node_modules/eslint

8 vulnerabilities (3 moderate, 2 high, 3 critical)
```

**Comment by bigopon** [comment]
Thanks @Eagle94T 
Cc @3cp

**Comment by 3cp** [comment]
Thx! Will update.
