### ISSUE TITLE
package "exports" field prevents importing dev builds without a bundler

### ISSUE THREAD

**Issue by mxjp** [aurelia/aurelia#1856]
# 🐛 Bug Report
The **exports** field in all package.json files seems to be used wrongly and prevents importing dev builds directly in NodeJS without using a bundler.

The exports field in `packages/runtime/package.json` currently looks like this:
```js
// package.json
{
  "exports": {
    "types": "./dist/types/index.d.ts",
    "require": "./dist/cjs/index.cjs",
    "import": "./dist/esm/index.mjs",
    "development": "./dist/esm/index.dev.mjs"
  },
}
```
Usually, the exports field may contain conditional **or** subpath imports, but not both in the same object. See https://nodejs.org/api/packages.html#exports for more info.

## 🤔 Expected Behavior
There should be a simple way to directly import the dev build without using a bundler:
```js
// This should work:
import { ... } from "@aurelia/runtime/development";
```

## 😯 Current Behavior
In the current package json, the **development** field shown above is a conditional export which prevents directly importing it. So all of the imports below will result in an error:
```js
// Doesn't work because "development" is
// specified as a condition, not a sub path:
import { ... } from "@aurelia/runtime/development";

// Doesn't work because "dist/esm/index.dev.mjs"
// is not specified as a subpath:
import { ... } from "@aurelia/runtime/dist/esm/index.dev.mjs";
```

There is currently a workaround with absolute or relative paths, but can get very complicated when using npm workspaces:
```js
import { ... } "./node_modules/@aurelia/runtime/dist/esm/index.dev.mjs";
```

## 💁 Possible Solution
Changing the development field in all packages to a subpath export as shown below should work:
```js
// package.json
{
  "exports": {
    ".": {
      "types": "./dist/types/index.d.ts",
      "require": "./dist/cjs/index.cjs",
      "import": "./dist/esm/index.mjs"
    },
    "./development": {
      "types": "./dist/types/index.d.ts",
      "require": "./dist/cjs/index.dev.cjs",
      "import": "./dist/esm/index.dev.mjs"
    }
  },
}
```
This change would still allow aliases for the dev builds when using a bundler, but also allows directly importing a dev build in NodeJS.

## 🔦 Context
Some resources on package exports:
+ Conditions supported by webpack: https://webpack.js.org/guides/package-exports/#conditions
+ Conditions supported by nodejs: https://nodejs.org/api/packages.html#conditional-exports
+ Conditions supported by rollup: https://www.npmjs.com/package/@rollup/plugin-node-resolve#exportconditions
+ Typescript "types" condition and subpaths: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html#packagejson-exports-imports-and-self-referencing

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Bundler          | None
| NPM/Node/Yarn    | Node 16, 18 LTS, 20 LTS

**Comment by bigopon** [comment]
Thanks @mxjp i think your suggestion works better, though maybe we can have a development condition for `.` too, like this:
```json
// package.json
{
  "exports": {
    ".": {
      "types": "./dist/types/index.d.ts",
      "require": "./dist/cjs/index.cjs",
      "import": "./dist/esm/index.mjs",
      "development": "..."
    },
    "./development": {
      "types": "./dist/types/index.d.ts",
      "require": "./dist/cjs/index.dev.cjs",
      "import": "./dist/esm/index.dev.mjs"
    }
  },
}
```
Ill create a PR soon. If you are interested, a PR will be really welcomed.

**Comment by mxjp** [comment]
I will make a PR now that also includes the "development" condition in "."

**Comment by mxjp** [comment]
@bigopon Should I make the change for all packages under /packages?
