### ISSUE TITLE
OPEN COLLECTIVE FUNDS

### ISSUE THREAD

**Issue by weagle08** [aurelia/aurelia#1879]
Why is Fred Kleuver invoicing $1560/week yet has hardly any commits? I would like to make sure that backers are not being cheated out of money here and that individuals that are actually doing the work are getting the benefit of the collective.

Ben

**Comment by bigopon** [comment]
@weagle08 thanks for creating the issue, @fkleuver is being tasked with working on a few tasks, hence the payment for his work. For the issue of not having appropriate amount of work being checked in, it's partly the nature of the work he's doing: it's a big piece, but I think we've also have had a discussion about this and he'll be making other improvements along the way so it doesn't appear as no work.

**Comment by weagle08** [comment]
As a long time user and backer I appreciate the feedback. Thanks!
