### ISSUE TITLE
[refactor] remove define life cycle

### ISSUE THREAD

**Issue by bigopon** [aurelia/aurelia#1898]
## 🔦 Context

Currently the `define` lifecycle provides the ability to alter the definition of a custom element dynamically. This feels too ambitious and powerful, and likely will cause unexpected behavior/hard to support cases, or even create fiction against static analysis during build time compilation.

We will be moving forward without this lifecycle. 

## ❔ Existing usages

If there are applications relying on the behavior of this lifecycle, we can reconsider adding it back in the worst case scenario, but will first try to provide a better alternative.

cc @fkleuver @Sayan751

**Comment by Sayan751** [comment]
@bigopon I am all for this. I have personally seen no use-case so far to change the definition on runtime. AFAIR the define hook was a hack to disable cache, by returning a new definition instance every time the hook is invoked. Personally, I have used this hook to grab stuffs from the hydration context, and managing registered resources in container. As long as the hydration context stays injectable, which is the case as of now, I think we can remove the hook.
