### ISSUE TITLE
Router swallows DI errors

### ISSUE THREAD

**Issue by ekzobrain** [aurelia/aurelia#1910]
# 🐛 Bug Report

When navigating to a component that produces DI errors - those errors are swallowed by the router and not shown in console. The only error shown is: `Error: 'xxx' did not match any configured route or registered component name - did you forget to add the component 'xxx' to the dependencies or to register it as a global dependency?`
Previously the same happend with errors produced by routed component lifecycle, but it was fixed in one of the latest releases.

Repro link https://stackblitz.com/edit/au2-conventions-pj6kbd?file=src%2Fpage2.ts,src%2Fendpoint.ts

Reproduction steps: click on link "Page with error", look at the console.

## 🤔 Expected Behavior

Error about invalid resolver is displayed in the console.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          |
| Language         |
| Browser          |
| Bundler          |
| Operating System |
| NPM/Node/Yarn    |

**Comment by 3cp** [comment]
What's wrong with my stackblitz? I tried to install the missing webpack-dev-server but it rejects it.

```
> webpack serve

[webpack-cli] You need to install 'webpack-dev-server' for running 'webpack serve'.
TypeError: callSite.getFileName is not a function. (In 'callSite.getFileName()', 'callSite.getFileName' is undefined)

~/projects/au2-conventions-pj6kbd 7s
❯ npm i -D webpack-dev-server
npm ERR! code ERR_INVALID_PROTOCOL
npm ERR! Protocol "https:" not supported. Expected "http:"
```

**Comment by ekzobrain** [comment]
Strange, for me the provided link works OK without any issues. webpack-dev-server is already listed in package-lock.json

**Comment by 3cp** [comment]
I managed to reproduce the error locally.
The endpoint is a resolver which right now our conventions plugin doesn't cover. Before we covers it, user needs to use explicit decorator on this resource. cc @Sayan751 

https://github.com/aurelia/aurelia/blob/efe208c512897a29ff15ce659b25bde0866bbecf/packages-tooling/plugin-conventions/src/options.ts#L1

**Comment by 3cp** [comment]
OK, I also saw that `$isResolver: true` fixes the issue. I don't know what's the design, use that meta flag, or there is a special decorator for resolver. cc @Sayan751

**Comment by ekzobrain** [comment]
$isResolver: true must be used for a valid resolver, a resolver interface requires it. I commented it out intentionally to show that an error thrown by DI system is caugth and swallowed by the router. It should not do it, so that developer may see what's the source of the problem.

**Comment by 3cp** [comment]
The doc asks you to write `$isResolver: true`. Why skip it?

https://docs.aurelia.io/getting-to-know-aurelia/overview/resolvers#example-of-a-custom-resolver

**Comment by ekzobrain** [comment]
I think any other DI resolving error (for example if some token cannot be injected) would behave the same.
