### ISSUE TITLE
Restrict behavior of custom attribute single value binding and primary bindable

### ISSUE THREAD

**Issue by ekzobrain** [aurelia/aurelia#1911]
# 🙋 Feature Request

Current single value binding always sets CA's value to the first defined class property. But it is not always desirable. I have some CA's that have one property and that property needs to have a default value, for example. But Aurelia always sets it's value to empty string, even if I provide no value when using that CA. That's because DOM attributes always have an empty value, even when not set at all (`<div some-attribute/>`). A suggest to restrict single value binding a bit: use not the first CA property, but a property named `value`. If CA has such property and there is no other bindable with `primary: true` option, only then HTML attributes's value will be assigned to it.

The second proposal (not so critical, just for convinience) is to move `primary` option from `bindable` definition to `customAttribute` definition. This will solve a confusion that single value binding may work with or without `bindable` decorator (currently it's required to add it just for observation of `value` property to work). When defining primary property on a CA, we may say that CA's always have a default primary property named `value`, and it works with or without conventions. Also primary property (even by conventions) is always observable (fires change callbacks). If one wants to use another property as primary - he may change it's name via `customAttribute` decorator (or with a static property).
This way we will also avoid confusion errors when `primary` may be set on multiple bindables.
And the concept of "single value binding" will disapear in favor of "default primary property", that will be more straightforward and convinient.

## 🤔 Expected Behavior

1. For:
    ```javascript
    class SomeCustomAttribute {
      value: string;
    }
    ```
    ```html
    <div some/>
    ```
    this way `value` will be set to an empty string (or any other value if set to an attribute)

2. For:
    ```javascript
    class SomeCustomAttribute {
      @bindable()
      prop = 1;
    }
    ```
    ```html
    <div some/>
    ```
    this way `prop` will be `1`

3. For:
    ```javascript
    @customAttribute({ name: 'some', primaryProperty: 'prop' })
    class SomeCustomAttribute {
      prop;
    }
    ```
    ```html
    <div some="val"/>
    ```
    this way `prop` will be `val`

4. For:
    ```javascript
    @customAttribute({ name: 'some', primaryProperty: null })
    class SomeCustomAttribute {
      prop;
    }
    ```
    ```html
    <div some="val"/>
    ```
    nothing will be set, primary property is disabled

## 😯 Current Behavior

HTML attribute's value is always set to the first CA class property, thus does not allow that property to have a default value of be of any type other than `string`. It's especially annoying when CA has just one property, and I don't want it to be

**Comment by bigopon** [comment]
Thanks for the issue @ekzobrain , just to clarify: the current behavior is if theres no bindable defined, then we target the `value` property on the custom attribute instances. Otherwise the primary bindable will be targeted in the single binding mode.
A bindable is considered primary if its one of the following:
- the only bindable, or
- the bindable with `primary: true` in is config, or
- the first bindable when there is no primary defined

I think your case should work by default, or maybe can you provide a repro so its clearer whats missing?

**Comment by ekzobrain** [comment]
My major case is when I have a single bindable and don't want it to be assigned with attribute value. But I have no way to do this now. And the overall approach seems too complicated and inconvinient. There are too many if/else in this logic :)
I suggest a simpler approach:
define `primaryProperty` on `customAttribute` definition, not on bindable. Then, by default, it would be `value`, but may be changed to any other property name, or disabled completely with `null` value (see my last two examples).

**Comment by ekzobrain** [comment]
This repro highlights my issue: https://stackblitz.com/edit/au2-conventions-u5ygqi?file=src%2Fsome-attribute.ts,src%2Fmy-app.ts,src%2Fmy-app.html

**Comment by bigopon** [comment]
@ekzobrain I think the idea of moving primary to the custom attribute definition sounds good. We can make it backward compatible by checking whether `primaryProperty` is defined or not.

If it's not defined (backward compat), then it'll automatically pick the one with the rules mentioned:
```
the only bindable, or
the bindable with primary: true in is config, or
the first bindable when there is no primary defined
```

If it's defined then it'll take over the process of defining primary bindable.

Thoughts @fkleuver @Sayan751 @jwx @brandonseydel @Vheissu ?

**Comment by Sayan751** [comment]
I also like the idea of moving the primary bindable information to the custom attribute. That might take some burden off the bindable definition. 

> Though I think this is also related to a more general issue: what to do when the initial binding value is undefined from the parent.

I think if a value is bound (identifiable from the compiled instructions, I guess), then that value will be assigned, even if it is `undefined`. One can always employ setters in `@bindable`, if that does not suffice.

**Comment by bigopon** [comment]
After some moment of aha, I think we can at least partially address this issue by making empty binding as no binding. For custom attributes, empty binding mean an empty string as expression, for example:
```html
<div my-attribute>
```
I don't think anyone would want to say: create a custom attribute `my-attribute`, and let it have an empty string as value.
With this change, the default value should be able to be retained when there's no actual binding.

For when there's actual binding, but empty values (`undefined`/`null`/`""`), it's the actual value so I think we can leave it alone.

**Comment by bigopon** [comment]
I created a PR here https://github.com/aurelia/aurelia/pull/1930
It should address the issue with the cases you mentioned @ekzobrain 
For the template
```html
<div my-attr="val">
```
I think the intention is too clear that the attribute wants to bind to the primary bindable with a value `val` literal string, we probably shouldn't change that.

**Comment by ekzobrain** [comment]
I agree with this partial solution. At least it solves the main issue when attribute is used without any intentional value
