### ISSUE TITLE
Tweak aurelia package reexports

### ISSUE THREAD

**Issue by ekzobrain** [aurelia/aurelia#1915]
# 🐛 Bug Report

The main package should only reexport public api functions/interfaces from core packages, but not plugins.
Currently @aurelia/fetch-client is reexported here: https://github.com/aurelia/aurelia/blob/master/packages/aurelia/src/index.ts#L60

## 🤔 Expected Behavior

Plugin packages are not reexported

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | 2.0.0-beta.11
| Language         |
| Browser          |
| Bundler          |
| Operating System |
| NPM/Node/Yarn    |

**Comment by bigopon** [comment]
Im not entirely sure about why. I think the motivation was to have it all in one and we will just encourage devs to import from the `aurelia` for simplicity. Maybe it shouldnt be this way, some times it feels weird to me.
Cc @brandonseydel @Vheissu @3cp @Sayan751 @jwx

**Comment by ekzobrain** [comment]
Fetch client docs (https://docs.aurelia.io/aurelia-packages/overview/setting-up) examples import from '@aurelia/fetch-client'.

Currently `fetch-client` is the only package that is positioned as a plugin, but required and reexported by `aurelia`. Why not `dialog` / `validation` / etc then?

**Comment by bigopon** [comment]
Fetch client being far more used than the rest is the reason I believe.

**Comment by ekzobrain** [comment]
Router is used not less, but it is not reexported...

**Comment by bigopon** [comment]
It used to be reexported as well, but we removed it. Maybe let's cleanup the fetch plugin and let aurelia just be the core modules.

**Comment by Sayan751** [comment]
We can remove the reexports from the plugins. I see no conflict with that.

**Comment by Vheissu** [comment]
I think removing the exports is fine. I will admit our exports situation is weird anyways. For example, the watch decorator isnt in the main Aurelia package as an export, so you have to get it from runtime/html.

**Comment by ekzobrain** [comment]
> I think removing the exports is fine. I will admit our exports situation is weird anyways. For example, the watch decorator isnt in the main Aurelia package as an export, so you have to get it from runtime/html.

watch is there already

**Comment by bigopon** [comment]
Resolved by #1926
