### ISSUE TITLE
Define `ts-jest` config under `globals` is deprecated

### ISSUE THREAD

**Issue by nuxy** [aurelia/aurelia#1940]
# 🐛 Bug Report

Running `test` on a new project results with the warning:

```
# npm run test

> my-app@0.0.1 test
> jest

ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
transform: {
    <transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
},
```

## 🤔 Expected Behavior

No warnings should occur.

## 💁 Possible Solution

Update `@aurelia/ts-jest` to support recommented transform format, or default to `ts-jest`.

## 🔦 Context

Deprecated configuration option. Will eventually be ignored altogether.

## 🌍 Your Environment

| Software               | Version(s)        |
|-------------------------|---------------------|
| Aurelia                  |  2.0.0-beta.14  |
| Language             | TypeScript       |
| Browser                | N/A                  |
| Bundler                 | Webpack         |
| Operating System | Ubuntu 22.04  |
| NPM/Node/Yarn   | NPM 10.2.3     |

**Comment by bigopon** [comment]
Thanks @nuxy , cc @3cp

**Comment by 3cp** [comment]
User could not just move the config from global to the location in transformer because we have hard coded creation of ts-jest instance with no passed in options.

https://github.com/aurelia/aurelia/blob/877a385ee18d89f8a8adef935e81047ba9b5137a/packages-tooling/ts-jest/src/index.ts#L19
