### ISSUE TITLE
2.0.0-beta.15 - using @inject is throwing errors

### ISSUE THREAD

**Issue by ivanbacher** [aurelia/aurelia#1946]
Just updated to `2.0.0-beta.15` and using @inject decorator is now throwing an error:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'kind')
```

The change log states that there are some breaking changes when moving to `2.0.0-beta.15` however I don't think any of the documentation has be updated to reflect this?

## How to reproduce:

```
npx make aurelia // choose default app option
```

In `my-app.js` add:

```
import {inject} from 'aurelia'

@inject(Element)

```

**Comment by ivanbacher** [comment]
I think I figured it out. Changing the `babel.config.json` file to this:

```
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "loose": true,
        "exclude": [
          "@babel/plugin-proposal-dynamic-import"
        ]
      }
    ]
  ],
  "plugins": [
    "@babel/plugin-transform-class-static-block",
    [
      "@babel/plugin-proposal-decorators",
      {
        "version": "2023-11",
      }
    ],
    [
      "@babel/plugin-proposal-class-properties",
      {
        "loose": true
      }
    ],
    "@babel/plugin-syntax-dynamic-import"
  ]
}
```

Seems to fix the issue.

**Comment by ivanbacher** [comment]
@3cp Can you please confirm if the above is correct?

This issue: https://github.com/aurelia/aurelia/issues/1180 also mentions something about changing babel options.

**Comment by 3cp** [comment]
Yes, decorator is changed to latest spec. Have to remove the legacy option in babel config.
