### ISSUE TITLE
Type is not a constructor, for unregistered compiler resources

### ISSUE THREAD

**Issue by fkleuver** [aurelia/aurelia#198]
For one reason or another the template compiler may try to get resources like `binding-command:null`, causing DI to JitRegister this as a string instance which results to a non constructable type.
See also: https://github.com/aurelia-contrib/aurelia-vnext-starter/issues/1
We should probably guard against this sort of thing a bit deeper into DI so that it just returns null (or throws a more descriptive error) if it gets a non-function, rather than trying to construct whatever it gets.

**Comment by EisenbergEffect** [comment]
Seems like the fix might be as simple as not allowing auto-registration when the key is a string? If that makes sense, I can pick this up and add a test. Is my understanding correct?

**Comment by fkleuver** [comment]
Yeah that makes sense actually. I don't think auto-registering a string would ever be intuitive behavior, and if you really need to you can still register a string explicitly. Maybe disallow auto-registration for anything that's not an `instanceof Object`?

**Comment by bigopon** [comment]
In this PR #194 , it's fixed by specifically telling container to not `autoRegister`. I think it should be sufficient to guard against this?

**Comment by fkleuver** [comment]
I overlooked that but you're right @bigopon that does look like a very elegant fix for this

**Comment by EisenbergEffect** [comment]
Closing this as fixed via #194
