### ISSUE TITLE
Router-lite duplicates url on page reload

### ISSUE THREAD

**Issue by ivanbacher** [aurelia/aurelia#2003]
This is probably a weird use-case. I am trying to incorporate an Aurelia app into a Wordpress admin page.

More info here: https://discourse.aurelia.io/t/integrating-aurelia-with-wordpress-backend/5474

Seem to be working, however when I reload the page. The route is duplicated within the url bar of the browser.

e.g. on first load:

`http://localhost:8888/wp-admin/admin.php?page=page-01/#/database?page=page-01`

`/#/database?page=page-01` is added by the `router-lite`. Then when the page is reloaded the new url is: `http://localhost:8888/wp-admin/admin.php?page=page-01%2F#/database?page=page-01/#/database?page=page-01`

I have tried to play around with the `basePath` config option, but have not had any success. If I set the basePath to this:
```
basePath: '/wp-admin'
```

I get this error

```
Error: AUR3501: Unexpected '.php' at index 6 of '/admin.php'
```

Any suggestions?

Is is possible to use the route with a type of in-memory url system rather then modifying the main url of the page?

**Comment by Sayan751** [comment]
@ivanbacher I think you are looking for the `none` `historyStrategy`.

```ts
    RouterConfiguration.customize({
      historyStrategy: 'none',
    })
```

References:
- [Documentation](https://docs.aurelia.io/getting-to-know-aurelia/routing/aurelia-router-lite/router-configuration#none)
- [Example](https://stackblitz.com/edit/router-lite-historystrategy-none?ctl=1&embed=1&file=src/main.ts)

**Comment by ivanbacher** [comment]
@Sayan751 Thank you so much. I missed that when reading through the docs.

Anyways, I gave it a shot. But still am getting a weird url in when the app first loads. Looks like `?page=page-01` might be causing the issue?

```
import Aurelia from 'aurelia'
import { StyleConfiguration } from 'aurelia'
import { RouterConfiguration } from '@aurelia/router-lite'
import { MyApp } from './my-app'

import bootstrap from './resources/scss/bootstrap.scss'

Aurelia
  .register(StyleConfiguration.shadowDOM({
    sharedStyles: [bootstrap]
  }))
  .register(RouterConfiguration.customize({
    activeClass: 'active',
    historyStrategy: 'none'
  }))
  .app(MyApp)
  .start()
```



```
@route({
  routes: [
    {
      path: ['', 'database'],
      component: DatabaseRoute,
      title: 'Database',
    },
    {
      path: 'upload',
      component: UploadRoute,
      title: 'Upload',
    },
    {
      path: 'settings',
      component: SettingsRoute,
      title: 'Settings',
    },
  ],
  fallback: 'database'
})
```

```
http://localhost:8888/wp-admin/admin.php?page=page-01/?page=page-01
```

```
@route({
  routes: [
    { path: '', redirectTo: 'database' },
    {
      path: 'database',
      component: DatabaseRoute,
      title: 'Database',
    },
    {
      path: 'upload',
      component: UploadRoute,
      title: 'Upload',
    },
    {
      path: 'settings',
      component: SettingsRoute,
      title: 'Settings',
    },
  ],
  fallback: 'database'
})
```
```
http://localhost:8888/wp-admin/admin.php?page=page-01/database?page=page-01
```

**Comment by Sayan751** [comment]
@ivanbacher It is a bit difficult to say what is going wrong, without seeing a reproduction. Can you please arrange a reproduction?

**Comment by ivanbacher** [comment]
Of course

Here is a basic working example: https://stackblitz.com/edit/aurelia-2-router-lite-test-1

Here is an example where the url of the page is set to `wp-admin/admin.php?page=Page-01` and the aurelai app is then initialised: https://stackblitz.com/edit/aurelia-2-router-lite-test-2

I hope these makes sense and thank your for taking a look. Example 2 is where I am currently stuck on

**Comment by ivanbacher** [comment]
Sorry the above Stackblitz examples are not quite right. I have having trouble setting them up so they are the same as the my dev environment. 

I might lack some understanding here, but this is way I am trying to do:

The URL of the page when the aurelia app is loaded is this: `/wp-admin/admin.php?page=Page-01`. This url should stay the same once the app is loaded, so if the user chooses to refresh the page, then they are just brought to the same place.

The issue I am facing is that the url before the aurelia app is loaded is `http://localhost/wp-admin/admin.php?page=one`. Once the aurelia app loads then the router-lite changes the url to this: `http://localhost/wp-admin/admin.php?page=one/?page=one`

So the router is somehow adding this `/?page=one` to the existing url. If ?page=one is not present I think the router only adds `/`.

I have found a hacky workaround for now. Once the router has completed navigation for the first time, then just remove the unneeded part from the url.

```
export class MyApp {
  private ea
  private subs = []
  private hasLoaded = false

  constructor(ea) {
    this.ea = ea

    const s1 = this.ea.subscribe('au:router:navigation-end', async () => { 
      if(!this.hasLoaded) {
        this.hasLoaded = true
        fixURL()
      }
    })

    this.subs.push(s1)
  }

  detached() {
    this.subs.forEach(sub => sub.dispose())
    this.subs = []
  }
}


function fixURL() {
  // Get the current URL
  const currentUrl = window.location.href
  
  // Define the part of the URL you want to remove
  const removePart = '/?page=one'

  // Remove the part from the URL
  const newUrl = currentUrl.slice(0, -removePart.length);
      
  // Update the URL in the browser's address bar without reloading the page
  history.replaceState(null, null, newUrl);
}
```

**Comment by Sayan751** [comment]
@ivanbacher I can replicate the issue: https://stackblitz.com/edit/router-lite-historystrategy-none-gh2003?file=package.json,src%2Fmy-app.ts,src%2Fmain.ts. I will dig deeper. Thanks for reporting this.

**Comment by ivanbacher** [comment]
Super. Thank you very much. Feel free to let me know if you need me to test anything.
