### ISSUE TITLE
Lifecycle hooks promise from binding() is not awaited by au-compose

### ISSUE THREAD

**Issue by ekzobrain** [aurelia/aurelia#2041]
# 🐛 Bug Report

Discussed here: https://discord.com/channels/448698263508615178/1275063951255928872/1275064485060677725

Repro link: https://stackblitz.com/edit/au2-conventions-djfavb?file=src%2Fcompose-component.ts,src%2Fmy-app.html,src%2Fmain.ts

## 🤔 Expected Behavior

Promise returned from binding() lifecycle hook is awaited as with regular component activation

## 😯 Current Behavior

binding() promise is not awaited and parent component attaches too early

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | latest beta
| Language         |
| Browser          |
| Bundler          |
| Operating System |
| NPM/Node/Yarn    |

**Comment by bigopon** [comment]
This is an intentional behavior.
If we had the following structure: parent -> child, then lifecycle will be something like this
```
parent.binding
parent.bound
parent.attaching
child.binding
child.bound
child.attaching
child.attached
parent.attached
```
binding and bound are meant for own component, and is only guaranteed that the parent lifecycles will run before the ones from child.

**Comment by bigopon** [comment]
Closed but please feel free to reopen/open a new issue if you want to discuss related issues further @ekzobrain
