### ISSUE TITLE
Dialog are not really modal

### ISSUE THREAD

**Issue by Stopi** [aurelia/aurelia#2052]
Hi, first: thanks to all of you guys for your hard work.

### Here's my issue:

In https://github.com/aurelia/aurelia/blob/master/docs/user-docs/aurelia-packages/dialog.md,
it is said that dialog plugin is going to provide what is called a modal dialog box.

But this isn't true, or at least it's partially wrong since the dialog opened _**isn't modal**_.
The "modal" term means you cannot interact with the background while the dialog is opened.

Currently, it sure has a visual overlay to cover the background, but if you use the [TAB] key, you can still reach everything behind that overlay.

In Aurelia V1, the dialog plugin was making use of the html <dialog> element (see https://github.com/aurelia/dialog/issues/335), which provides true modals.

Why the dialog from Aurelia V2 doesn't just do that?

I think this limitation should be mentioned in the doc, so people don't loose time implementing something that doesn't behave as expected.

**Comment by Stopi** [comment]
I just posted a feature request for using the \<dialog> HTML element in this package.

**Comment by bigopon** [comment]
Tracked in #2053
