### ISSUE TITLE
Bound value of select element is set after change event

### ISSUE THREAD

**Issue by ivanbacher** [aurelia/aurelia#2054]
# 🐛 Bug Report
I noticed this functionality:

Say I have this template
```
<template>
  <label>
    Select product:<br>
    <select value.bind="selectedProductId">
      <option model.bind="null">Choose...</option>
      <option repeat.for="product of products"
              model.bind="product.id">
        ${product.id} - ${product.name}
      </option>
    </select>
  </label>
  Selected product ID: ${selectedProductId}
</template>
```
and add this to it:

```
<select value.bind="selectedProductId" change.trigger="onChange()">

...

onChange() {
    console.log(this.selectedProductId)
}
```

The output of the `console.log` in the `onChange()` function will be called before the new value is set. 

E.g.
- selectedProductId is null
- user selects first option
- onChange is called
- null is printed to console
- user selects second option
- onChange is called
- value of first option is printed

Repro link: None yet, but happy to make one if needed

## 🤔 Expected Behavior

`selectedProductId` value shoudl be set before `onChange` is called

**Comment by ivanbacher** [comment]
Current solution is to use something like this in the `onChange()` function:

```
const element = this.host.querySelector('select')
console.log(element.value)
```

**Comment by bigopon** [comment]
This is a test in my local
![image](https://github.com/user-attachments/assets/b36d8058-5fae-4d95-a17c-c0b54ecd99d6)
and it logs
```
null
['0']
```
It seems to be working as expected, can you help with a repro?

**Comment by ivanbacher** [comment]
Thanks for taking a look @bigopon. Here is a repo replicating the issue: https://stackblitz.com/edit/au2-select-bug



https://github.com/user-attachments/assets/0ec726ec-187f-4c02-880f-99b97efd9ca4

**Comment by bigopon** [comment]
I see, thanks @ivanbacher . This is considered working as expected, since bindings are evaluated in order. Because listener binding is specified before value binding, so its handler is called before, and thus will react before the value is updated. If you move the listener binding after the value binding, you'll see its working as expected.

**Comment by ivanbacher** [comment]
Haha, I see. Thank you for clarifying @bigopon. I must have missed this when reading the docs. Sorry about that. Keep up the great work 😊

**Comment by bigopon** [comment]
thanks @ivanbacher
