### ISSUE TITLE
Returning false from canLoad breaks navigation

### ISSUE THREAD

**Issue by superspartak** [aurelia/aurelia#2064]
# 🐛 Bug Report

When I return a `false` value from canLoad hook in either the route component or globally registered lifecycle hook, the navigation breaks. Trying to route to another route after that point leads to the second route being instantiated under the existing route. So inside the same au-viewport element, we end up with multiple different routes being loaded.

Repro link:

https://stackblitz.com/edit/au2-conventions-waf2jy?file=src%2Fmy-app.html

1. Go to Recipes
2. Click on any recipe link
3. It won't happen because recipe-details has a canLoad that returns false.
4. Click on Home at top
5. The recipe list won't disappear but Home component will be rendered below it, which can be scrolled down to.

## 🤔 Expected Behavior

After false is returned from canLoad and navigation is cancelled, router should keep behaving normally.

## 😯 Current Behavior

After false is returned from canLoad and navigation is cancelled, attempts to route elsewhere leads to the former Routable component to get "stuck" and other component to be rendered below the former.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | multiple versions (as new as beta 22)
| Language         |
| Browser          | Chrome / Firefox
| Bundler          |  Webpack
| Operating System | Windows
| NPM/Node/Yarn    |

**Comment by ivanbacher** [comment]
https://github.com/user-attachments/assets/68a6077f-be73-4590-a782-878ebf8e9935

**Comment by superspartak** [comment]
@ivanbacher Thanks for the response.

> Is this not expected behaviour?

Most definitely not. This leads to different routes being present on the screen at the same time on top of each other. Or am I missing something?

> returning a string instead of false would fix your issue:

No it would not. I don't necessarily want to redirect the user. I might want to handle the situation in a different way.

I did not get the purpose of the video because it clearly displays the problem 🙂 If you look closely at seconds 12 to 14, recipe list is rendered twice, on top of each other and normal navigation is broken (you can't go back to Home, if you click any of the recipe details links)

**Comment by ivanbacher** [comment]
@superspartak Yes correct, I misunderstood the issue, that's also why I deleted the previous comment 😅. I added the video just to make it clear what the issue is for anyone viewing ☺️

**Comment by superspartak** [comment]
@ivanbacher Thanks for the support in that case 😄

**Comment by superspartak** [comment]
#2067 Seems to be fixing it. Thanks guys!
