### ISSUE TITLE
Create test placeholders / instructions for testing

### ISSUE THREAD

**Issue by bigopon** [aurelia/aurelia#210]
So I thought about our tests, and decided to create this. Things are working and looking good, but we need way more tests. One way to solve it is to ask @fkleuver to do everything, but it will probably be too much and take long time for him to finish everything alone, so I think I'll walk through every missing tests and create placeholder for them, together with some specs, such as what should be tested, what scenarios should be validated. Then we can easily split them up into individual issues and label `test + help-wanted`. That way, we can invite community members to share fun building Aurelia. Thoughts ? @EisenbergEffect @fkleuver

**Comment by fkleuver** [comment]
Love the idea! I'm very happy that you're proposing this :)

**Comment by EisenbergEffect** [comment]
Sounds like a great idea to me too!

**Comment by fkleuver** [comment]
Just so I don't forget (and others know what's still to-do), some notes on which things I believe need significantly more test coverage:
### Kernel
- DI jitRegister
- DI interpret
- DI childContainers

### Runtime - Binding
- ComputedObserver (this also still needs to be fixed)
- LengthObserver
- DirtyChecker
- **all** binding resources (complex integration test combinations with other binding and templating resources)
- AST (specifically BindingBehavior and ValueConverter)
- Call
- EventManager
- ExpressionParser (the runtime one)
- LetBinding
- Listener
- Ref

### Runtime - Templating
- Compose (complex integration test combinations with other resources and specifically async)
- Replaceable
- With (complex scope situations such as replace-parts)
- createElement (complex combinations of inputs)
- Lifecycle (exotic usage of hooks with/without async task registrations, flush/bind/others getting queued from within hooks, verifying the only-detach-roots behavior with mocks)
- Aurelia (unit tests that verify the various non-obvious task/start/stop combinations)
