### ISSUE TITLE
Context traversal not working inside custom elements

### ISSUE THREAD

**Issue by fkleuver** [aurelia/aurelia#218]
# 🐛 Bug Report

A custom element does not have access to `$parent` via the `parentOverrideContext`, at least not when there's a repeater / template controller on it.

## 🤔 Expected Behavior

`@customElement`'s `$hydrate` should create its scope based on the parentScope so that the bindingContext inside it can traverse upwards

## 😯 Current Behavior

It does this: `this.$scope = BindingContext.createScope(this);` (line 148, custom-element.ts)

Consequently, `@customElement` has no access to parent context

## 💁 Possible Solution

The `$scope` somehow needs to be passed down from parent to child during hydration because currently there seems to be no direct way to access it.

We could either directly register/store it via the `renderingEngine` or `renderContext`, or somehow let child resources access their parents and get the parent scope that way. I'm hesitant on either approach.

We could also make the scope a first-class citizen during the rendering process, as an extra argument in addition to `renderable` / `target` / `instruction`. It doesn't necessarily seem wrong to be because the scope is the same level of granularity of the `target`, which the renderer also explicitly passes around.

I have not looked at or considered how vCurrent solves this. These are just my initial thoughts.

I can also be completely and utterly wrong and this could be an issue with how the template compiler processes bindable attributes on custom elements after wrapping them. I haven't debugged it yet.

## 🔦 Context

Template controllers will wrap custom elements in a new context and thereby they lose access to the properties they're bound to, meaning nothing will work with a repeater+custom element unless all the bindable properties come first.

## 💻 Code Sample

See this [integration test](https://github.com/aurelia/aurelia/pull/217/files#diff-76aa27f7a7be71f350f6b7644b522cc3R636)

## 🌍 Your Environment

N/A

**Comment by EisenbergEffect** [comment]
I don't think that the internal view of a custom element should have access to the parent scope (the scope outside of the custom element). If we did that then anything from anywhere could bind all the way up to the root of the app and there would be no encapsulation. Am I understanding correctly?

**Comment by fkleuver** [comment]
> I can also be completely and utterly wrong and this could be an issue with how the template compiler processes bindable attributes on custom elements after wrapping them. I haven't debugged it yet.

There are no unit tests for this particular area in the template compiler yet, I realized later.

I did mix something up. I looked at the wrong place and concluded that this was the issue. But the bug I ran into is not caused by the custom element's internal view not having access to the parent scope,

It could be a problem in `SemanticModel.lift()`. I need to look further into it unless @bigopon already found the culprit. 

Anyway, just to clarify, consider this custom element (a few things shortened for brevity):

```ts
@customElement({
  name: 'foo',
  template: '<template>${msg}</template>'
})
class Foo { @bindable msg; }
```

The app below will render:
```html
hello
```

```ts
@customElement({
  name: 'app',
  template: '<template><foo msg.bind="message" repeat.for="i of 1"></foo></template>'
})
class App {
  message = 'hello';
}
```

Whereas this app will render:
```html
undefined
```

```ts
@customElement({
  name: 'app',
  template: '<template><foo repeat.for="i of 1" msg.bind="message"></foo></template>'
})
class App {
  message = 'hello';
}
```

**Comment by fkleuver** [comment]
So given this template:

```html
<template><foo text.bind="text" repeat.for="i of 3"></foo></template>
```

This is what the runtime looks like:

![image](https://user-images.githubusercontent.com/9655331/46838002-ae31ab00-cdb7-11e8-97ca-cee8c857f669.png)

Now swap it around:

```html
<template><foo repeat.for="i of 3" text.bind="text"></foo></template>
```

And you get this (notice 1 less bindable):

![image](https://user-images.githubusercontent.com/9655331/46838047-d8836880-cdb7-11e8-9058-2b5c8a06614d.png)

However that bindable is located in the views that the repeater owns and it seems like it can get up to the app context just fine: 

![image](https://user-images.githubusercontent.com/9655331/46838134-33b55b00-cdb8-11e8-96c4-44c61bae7b13.png)

So for some reason it just chooses not to traverse upwards and stops at an intermediate OverrideContext.

**Comment by fkleuver** [comment]
Looks like it's yet another case of property defined too late. False alarm @EisenbergEffect
