### ISSUE TITLE
Wrong nodes referenced with multiple sibling/child template controllers on surrogate elements

### ISSUE THREAD

**Issue by fkleuver** [aurelia/aurelia#219]
# 🐛 Bug Report

Having a `repeat` and an `if`/`else` (this applies to various combinations and placements) on template elements results in the wrong nodes (namely the `<au-loc>` nodes) being removed.

 my initial impression is that this is a problem in the rendering process, not in the template compiler, because the compiled instructions appear to be correct as per the unit tests (and rendering has very low coverage)

## 🤔 Expected Behavior

For example: `<template repeat.for="item of items" if.bind="show">${item}</template>`
Let's say we assign `[1, 2, 3]` as the items. and `show=true` It renders `123`, terrific.
Then we assign a smaller array `[1, 2]`. it stays `123`

## 😯 Current Behavior

Continuing on the above, after assigning `[1, 2]` it should render `12`

## 💁 Possible Solution

I'm pretty sure it's going wrong somewhere in the rendering process. The test coverage here is low, and in my various earlier debugging sessions some of it felt somewhat happypath-coded. 

Unless @EisenbergEffect has some immediate ideas, I suggest we systematically work up the test coverage in the rendering process especially around render locations and node adding/removal.

## 🔦 Context

I'm trying to get integration tests up and running for just about every thinkable combination of template controllers in various sibling and/or parent/child placements, on normal elements, template elements, and so forth. All of it needs to work 100%. This is step 1.

## 💻 Code Sample

See this commented out [integration test](https://github.com/aurelia/aurelia/pull/217/files#diff-76aa27f7a7be71f350f6b7644b522cc3R437)

## 🌍 Your Environment

N/A

**Comment by ghiscoding** [comment]
@fkleuver 
Could that be a binding issue with a mutation (assignment) that Aurelia cannot see? I had a similar issue and asked on SO [here](https://stackoverflow.com/questions/36394399/how-to-force-binding-re-evaluate-or-re-rendering-in-aurelia) in which Jeremy Danyow replied:

> Aurelia observes changes to the contents of an array by overriding the array's mutator methods (push, pop, splice, shift, etc). This works well for most use-cases and performs really well (no dirty-checking, extremely lightweight in terms of memory and cpu). Unfortunately this leaves one way of mutating an array that aurelia can't "see": indexed assignment... eg myArray[6] = 'foo'. Since no array methods were called, the binding system doesn't know the array changed.
