### ISSUE TITLE
Only create `$children` observer if the property is defined?

### ISSUE THREAD

**Issue by fkleuver** [aurelia/aurelia#229]
# 💬 RFC

Currently every single component is initialized with this:

![image](https://user-images.githubusercontent.com/9655331/46923546-817cce00-d019-11e8-81e4-4c1f3da9077c.png)

Seems rather wasteful to have an extra array and observer object for each and every element when they're only used in very specific cases.

Do these need to be declared and instantiated for any particular reason or can this change?

**Comment by EisenbergEffect** [comment]
Closing this out since we switch back to using a decorator.
