### ISSUE TITLE
[WIP] Router Use Cases [RFC]

### ISSUE THREAD

**Issue by davismj** [aurelia/aurelia#239]
- [x] [Dynamic Redirect](https://github.com/aurelia/router/issues/585)
- [ ] [Router Passthrough](https://github.com/aurelia/router/issues/527) ([also](https://github.com/aurelia/router/issues/428))
- [ ] [View Caching](https://github.com/aurelia/router/issues/173)
- [ ] [Prevent Exit](https://github.com/aurelia/router/issues/564)
- [x] [Custom Titles](https://github.com/aurelia/router/issues/218)

## Dynamic Redirect

```javascript
const redirect = (from, to, next) => next({ redirect: 'new' });
router.mapRoutes([ { route: 'old', before: redirect } ]);
```

## Prevent Exit

```javascript
const preventExit = (from, to, next) => next(??? ? null : 'home')
router.mapRoutes([ { route: '', name: 'home' ]);
router.before = [preventExit];
```

## Custom Titles

```javascript
router.buildTitle = (instructions) => instructions.reverse().map(i => i.title).join(' | ');
```

**Comment by Alexander-Taran** [comment]
Use case:
A dynamically loaded component has `configureRouter` and `router-view`

**Comment by Alexander-Taran** [comment]
some developers would like to generate events on child routers
https://github.com/aurelia/router/issues/293

**Comment by Alexander-Taran** [comment]
a case to look and test for 
https://github.com/aurelia/router/issues/66

**Comment by Alexander-Taran** [comment]
Use case
generate route to a sibling router
https://github.com/aurelia/router/issues/89

**Comment by Alexander-Taran** [comment]
Cancelling a navigation instruction with a redirect raises inconsistent navigation events
https://github.com/aurelia/router/issues/177

**Comment by Alexander-Taran** [comment]
Load route viewModel module from external location or via alternative resolve strategy
https://github.com/aurelia/router/issues/379

**Comment by krisdages** [comment]
Re https://github.com/aurelia/router/issues/379
Commenting here because that issue was closed, but it would be a wishlist item for a backport...

Similar to how globalResources lets you pass the constructor for a resource now instead of the module path,

It would be great if you could pass an async function to the route config that resolves to the viewmodel constructor (ie container key?) to use for the route.

We are trying to avoid things breaking due to moved or renamed modules, and this is one of the last areas in our app where a string is still required. 

Being able to pass a function that returns `(await import ("module-path")).ViewModelX` would allow the build to catch errors (or the IDE to do the refactoring).

**Comment by davismj** [comment]
That's a wonderful idea, thank you for the note.

**Comment by Alexander-Taran** [comment]
excessive activation of a parent router when navigated back from inner router
https://github.com/aurelia/router/issues/155

**Comment by Alexander-Taran** [comment]
warn about duplicate names
https://github.com/aurelia/router/issues/366

**Comment by bigopon** [comment]
Thanks @Alexander-Taran , I think we have resolved all of the use cases here, except for
> Use case
> generate route to a sibling router
> https://github.com/aurelia/router/issues/89

However, it's possible in v2 with a little tweak.

Supposed we have the following routing structure:
```
root
  - A
     - A1
     - A2
  - B
     - B1
     - B2
```
It's not possible for `A1`/`A2` to know about `B1`/`B2`, as the route configuration are lazily evaluated and they are only known once `B` has been loaded, and normally we only don't load `B` when we are loading A.

Though in v2, we have a "`cd`" like syntax for navigation, to load `B1` or `B2` from inside `A1` or `A2`, we can do

For `router`:
```ts
router.load('../../B/B1')
```

For `router-lite`:
```ts
router.load('../../B/B1')
```
doc https://docs.aurelia.io/getting-to-know-aurelia/routing/aurelia-router-lite/navigating#navigate-in-current-and-ancestor-routing-context

I think we can close this issue, we can open a new one for any unaddressed ones.
cc @Sayan751 @jwx
