### ISSUE TITLE
[RFC] [Feature] switch (/ case) template controller

### ISSUE THREAD

**Issue by fkleuver** [aurelia/aurelia#303]
TODO

**Comment by Sayan751** [comment]
# RFC

This RFC proposes the syntaxes for the `switch`/`case` template controller.
At this point, there are `if`/`else` template controllers to facilitate the conditional attach/detach of elements to/from the DOM.
However, the semantics of switch-case is missing.
Let's look at some examples.

## Examples

### Example#1: enum
A typical use-case for switch is to deal with `enum`s.
The following `OrderStatus` `enum` is given.

```typescript
const enum Status {
  received = 'received',
  processing = 'processing',
  dispatched = 'dispatched',
  delivered = 'delivered',
}
```

If we are tasked with showing a status text according to the `status: Status`, then with `if` template controller we might end up with the following markup.

```html
<span if.bind="status === 'received'">Order received.</span>
<span if.bind="status === 'processing'">Processing your order.</span>
<span if.bind="status === 'dispatched'">On the way.</span>
<span if.bind="status === 'delivered'">Delivered.</span>
```

> Note that the markup is kept simplistic for the ease of discussion.
> And yes, you can use i18n to have contextualize the text, but that is out of scope of this discussion.

The markup above will produce the desired result.
However, apart from having a bit cumbersome syntax, the semantic is somewhat lost.
With the proposed `switch`/`case` template controller, the above can be rewritten as the following.

```html
<au-switch expression.bind="status">
  <span case="received">Order received.</span>
  <span case="processing">Processing your order.</span>
  <span case="dispatched">On the way.</span>
  <span case="delivered">Delivered.</span>
</au-switch>
```

The goal is to render the first element that matches the `[expression]` of `au-switch`.
The rendered output should be same as the one with `if` template controllers.

There is one important difference between the two examples.
With the `switch`/`case` example, we have one dynamic expression (`status`), and four literal expressions for for `case`s.
As the literal expression does not change, we don't need to observe/connect to those, rather connecting to the `[expression]` of the `switch` should suffice.
Moreover, as with the switch syntax the first matched element is rendered, reevaluation of all four `cases` might not always be necessary when `status` changes.
That is not the case for the markup with `if` template controllers, as in that case when `status` changes, all four bindings are reevaluated.

### Example#2: another comparison with `if`/`else`

Sometimes we end up with a if-else ladder like the following.

```html
<some-el1 if.bind="expr1"></some-el1>
<template else>
  <some-el2 if.bind="expr2"></some-el2>
  <template else>
    <some-el3 if.bind="expr3"></some-el3>
    ...
  </template>
</template>
```

With the introduction of `switch` this can be flattened.

```html
<au-switch expression.bind="true">
  <some-el1 case.bind="expr1"></some-el1>
  <some-el2 case.bind="expr2"></some-el2>
  <some-el3 case.bind="expr3"></some-el3>
</au-switch>
```

### Example#3: support for expressions

Expressions can be freely used either in `[expression]` or `[case]`; i.e. the `[case]` expressions need not to be limited to constant literals.

```html
<au-switch expression.bind="foo.bar">
  <some-element1 case.bind="caseExpression1">...</some-element1>
  <some-element2 case.bind="caseExpression2">...</some-element2>
  <some-element3 case.bind="caseExpression3">...</some-element3>
</au-switch>
```

When `foo.bar === caseExpression2` the rendered output is as follows.

```html
<some-element2 case.bind="caseExpression2">...</some-element2>
```

As any of the expressions change, the `[case]` expressions will be reevaluated in the order to determine whether to attach/detach those to/from the DOM.
Of course there is some room for optimization here.
For example, reevaluation of all cases are justified if the `[expression]` changes, but if one of the `[case]` changes, then reevaluation of other `[case]`s might be avoided.

### Example#4: first match

The `[case]` evaluation stops at the first match.

```html
<au-switch expression.bind="true">
  <span id="1" case.bind="2 === 3"> Not matched </span>
  <span id="2" case.bind="2 === 2"> Matched </span>
  <span id="3" case.bind="1 === 1"> Ignored </span>
</au-switch>
```

Although the last 2 cases match, the `span#2` will be shown ignoring the `span#3`.
This let us avoid reevaluating all expressions.

However, there might be some use cases, where both `span`s desired to be attached to DOM.
This an open question.

### Example#5: default case

Being self explanatory, this is the fallback case, if nothing is matched.

```html
<au-switch expression.bind="status">
  <span case="received">Order received.</span>
  <span case="processing">Processing your order.</span>
  <span case="dispatched">On the way.</span>
  <span case="delivered">Delivered.</span>
  <span default-case>Not found.</span>
</au-switch>
```

### Example#6: multi-case

Multiple expressions for a single case should be supported.
The proposed syntax for that looks as follows.

```html
<au-switch expression.bind="status">
  <span case.bind="'received'; 'processing'">Not dispatched.</span>
  <span case="dispatched">On the way.</span>
  <span case="delivered">Delivered.</span>
</au-switch>
```

This is analogous with the following JavaScript code.

```js
switch(status) {
  case Status.received:
  case Status.processing:
    return 'Not dispatched.';

  case Status.dispatched:
    return 'On the way.';

  case Status.delivered:
    return 'Delivered.';
}
```

## Loose specs and implementation notes

This section tries to summarize the examples above with occasional implementation notes.

1. The custom element `au-switch` is used to apply switch behavior.
   1. The switch expression is bound using the `expression` attribute on the `au-switch` element.
   2. The absence of `[expression]` on `au-switch` should result in JIT compilation error.
   3. The `au-switch` needs to be `containerless`.
2. The cases are defined using the `[case]` or `[default-case]` attribute on the direct children of the `au-switch` element.
   1. The multi-`[case]` syntax is as follows: `case.bind="case.expression1; case.expression2"`.
   2. The usage of `[case]` on a non-children element of `au-switch` should result in JIT compilation error.
3. Any kind of expressions can be used be used for both `[expression]` and `[case]`.
4. Evaluation:
   1. The cases are evaluated in order.
   2. The match is determined with strict equality (`===`).
   3. The evaluation of the expression should stop after the first match (?; refer example #4). This is sort of an optimization step to prevent evaluation of every expressions. Implicitly, it also disallows the possibility of fallthrough (in JS this is a `case` without `break`).
5. Reevaluation:
   1. If the `[expression]` is changed, then invoke the same workflow as "evaluation" (previous point).
   2. Else: one of the `[case]` expression is changed. In that case reevaluate the currently active `[case]` as well as the changed `[case]`. The `[case]` with the lower ordinal wins.

**Comment by HamedFathi** [comment]
@Sayan751 

Why are you suggesting `default-case` instead of `default`?

**Comment by Sayan751** [comment]
@HamedFathi Sadly there is a native HTML attribute named `default`. Refer this: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/track#Attributes.

Open for any lesser verbose alternative.

**Comment by zewa666** [comment]
Let me preamble my reply with that I'm not really a fan of adding too much logic into markup and a switch/case in my opinion goes already too far. Heck I don't even use `else` :)

But nevertheless, looking at the samples it seems your switch/case implementation focuses on classic Java/C#/PHP approaches. As an alternative for default-case how about going with Ruby's idea of case/when + else?

```html
<au-switch expression.bind="status">
  <span when="received">Order received.</span>
  <span when="processing">Processing your order.</span>
  <span when="dispatched">On the way.</span>
  <span when="delivered">Delivered.</span>
  <span else>Not found.</span>
</au-switch>
```

Moreover Rubys approach supports a wide range of other nice features maybe more suitable in the markup scenario:

* ranges: `when 1..20`
* regex: when /^foo/

### Questions
* is case bindable? --> `<span case.bind="states[0]">Order received.</span>`
  the multi-case example (#6) indicates for me bind is being used for something else, or is that just an additional parser?
* correlated to bindable, can I use binding behaviors or value converters?

**Comment by zewa666** [comment]
Also with regards to fall-through vs first-match, I get that later makes more sense performance-wise and also it is most often used this way. So my first thinking of `case` + `case-break` would be actually most often unnecessary work. But perhaps something along these lines with varying names to indicate the behavior could be an idea.

**Comment by Sayan751** [comment]
@zewa666 Thanks for the feedback. The `switch`/`when`/`else` looks good to me syntactically. I was using the `switch`/`case`/`default` borrowing from JavaScript. I think that might have more familiarity. On a side note for `else`: it might already be coupled with the `if`, and for right reason. Not sure `else` should be refactored only to support switch.

This examples look exciting:

> ranges: when="1..20"
> regex: when="/^foo/"

Those can be supported with `case` as well. To support that, the specs and syntax needs to be clear though. For the first draft, it might be easier to focus on simple strict equality, IMO.

> is case bindable?

Yes.

> the multi-case example (#6) indicates for me bind is being used for something else, or is that just an additional parser?

There we need additional parsing logic (if not already there), and handle that during symbol creation.

> correlated to bindable, can I use binding behaviors or value converters?

Yes, that should also be possible, considering it is an expression after all.


Regarding fall-through, I am not sure how the syntax will look :(

**Comment by bigopon** [comment]
Looks great to me, probably there will be a few points for optimization for the steps listed by this RFC, but the core of it I think is good to go. 👍

**Comment by zewa666** [comment]
@Sayan751 thanks for the clarification. The fall-through use case is essentially the only thing I see here missing, since that really might come in handy and right now the RFC doesn't propose a solution/workaround for that. I have no idea either how to do it if break is the default. Otherwise things like a Valueconverter or other parseable symbol might could have been used. I'll give you a few samples below of potential ideas to handle it

```html
<!-- define a global fallthrough or break option (default is false) for the entire switch statement -->
<au-switch expression.bind="true" break/fallthrough="true">
  <!-- if fallthrough is default use break to signal breaks -->
  <span id="1" case.bind="2 === 3 & break"> Not matched </span>
  <!-- if break is default use fallthrough to signal the opposite -->
  <span id="2" case.bind="2 === 2 & fallthrough"> Matched </span>
  <!-- define break or fallthrough via boolean as a collocated attribute -->
  <span id="3" case.bind="1 === 1" break/fallthrough="false"> Ignored </span>
</au-switch>
```

The last one would be similar to how i18n makes use of collocation of t and t-params attributes.

**Comment by Sayan751** [comment]
IMO since fall-through might end up being a rarely used feature in this case, I propose a bit more verbose (possibly non-elegant), but easy to implement syntax.

```html
<span case="value.bind:'foobar'; fall-through.bind:true">foobar</span>
<span case="fizbaz">fizbaz</span>
<span case="dnc">dnc</span>
```

The default is always `fallThrough = false`, thus if in the above markup the evaluated switch expression is matched with `foobar`, the output will be `<span>foobar</span><span>fizbaz</span>`.

On a different note, I think for multi-case scenario, it will might be lot better to have the following simpler syntax instead.

```html
<span case.bind="['awesome', 'possum']"></span>
```

This feels more of natural syntax for this case, saving us potential refactoring effort in parsing which was the case for the original proposal.

cc: @zewa666 @bigopon @fkleuver @EisenbergEffect

**Comment by zewa666** [comment]
I'm personally not a fan of the first example, it feels really verbose and starts to mix lots of different things.

Bindingmode for fallthrough one time makes sense since that's not really gonna change.

The later sample, would that render the span ones if any of the arrays items hit? Like:

```ts
switch(foo): {
  case "bar":
  case "baz":
    console.log("foo ba[r|z]");
}
```

**Comment by fkleuver** [comment]
I like this, I'm just a bit concerned about consistency. Why not an ordinary template controller? Is there any technical reason for not doing something like this?
```html
<template au-switch.bind="expr">
  <div au-case="1"></div>
  <div au-case="2"></div>
  <div au-case="3"></div>
  <div au-default></div>
</template>
<template au-switch.bind="expr">
  <div au-case.bind="val1"></div>
  <div au-case.bind="val2"></div>
  <div au-case.bind="val3"></div>
  <div au-default></div>
</template>
```

As for taking liberties on the syntax and functionality, I'd prefer a more conservative approach here for the time being. The fancier we get, the more trouble we'll have if new language features are added by either TS or JS.

**Comment by Sayan751** [comment]
@fkleuver  I have nothing against `au-switch` being a simple template controller, as making it a CE it does not bring any added advantage to the table. If there is nothing else against that, I can convert the `au-switch` to a template controller.

However, I would like to keep the cases as `case` as compared to `au-case`. Same goes for default case. I am ok with either `case-default` or `default-case`; I find `au-default` to be very ambiguous.

@zewa666
> I'm personally not a fan of the first example, it feels really verbose and starts to mix lots of different things.

Actually that is formal syntax for binding multiple `@bindable`s in custom attribute. Considering the `fall-through` might be a rare use-case in devland, I think for the first draft, we can use that syntax. We can always go fancier (read 'internally complicated' :P) if the devs complaint about it in alpha.

> The later sample, would that render the span ones if any of the arrays items hit?

Yes.

**Comment by bigopon** [comment]
If we are to go with consistency, it should be consistent with the rest of our system maybe? we have `with` `if` `else` `repeat`, maybe we should have `switch`/`case` instead?

**Comment by Sayan751** [comment]
@bigopon Unfortunately, there is a native `<switch>` element: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/switch.

**Comment by bigopon** [comment]
I meant if we went with template controller, we could go with `switch` instead of `au-switch`

**Comment by Sayan751** [comment]
I ended up implementing the `switch/case` as template controllers, as opposed to what was indicated originally in this RFC. After the PR is merged, the docs will be available under https://docs.aurelia.io/getting-started/conditional-rendering#switch.
