### ISSUE TITLE
[Doc] More introduction on the README

### ISSUE THREAD

**Issue by RomkeVdMeulen** [aurelia/aurelia#318]
It's always surprised me that there's very little introduction in the READMEs of Aurelia projects. The standard boiler plate lists of a bunch of resources that people can go to, but it does nothing to establish the context of the project they're currently looking at. Oftentimes, it takes me a while and some research to find out what a component like [templating-resources](https://github.com/aurelia/templating-resources) actually does.

A lot of developers first come into contact with a framework through the README. See e.g. [Best of JavaScript](https://bestofjs.org/projects/aurelia). Now compare to [React](https://bestofjs.org/projects/react), [Preact](https://bestofjs.org/projects/preact), [Vue](https://bestofjs.org/projects/vuejs), [Ember](https://bestofjs.org/projects/ember), and others.

Now that all the projects are being collapsed into one repo, I'd say this is the ideal time to improve a bit. Add some introduction for new people, explaining Aurelia's purpose and philosophy, and add some unique selling points. Content could be copied from [https://aurelia.io/](https://aurelia.io/) and slighly rewritten. I could do a PR for this, if the team agrees this is worthwhile.

**Comment by fkleuver** [comment]
There is no reason for the lack of docs other than the lack of time on our part. Some help in this area would be most welcome :)

**Comment by EisenbergEffect** [comment]
@RomkeVdMeulen Thanks for the feedback. We were having a discussion on this topic on discourse recently and I agree that having a better baseline readme in each repo is a good idea. As @fkleuver mentioned, it's a matter of time. Things like readmes can sometimes go stale over time and are easy to go into disrepair, esp. when we've got so many repos. @RomkeVdMeulen Would you be interested in contributing by helping us to improve our READMEs?

**Comment by freshcutdevelopment** [comment]
I think this would definitely help with regards to the getting started story. I'm happy to put my hand up to assist on this front as well.

**Comment by EisenbergEffect** [comment]
Yay! @freshcutdevelopment I think we should start with two repos then. the `@aurelia/framework` repo and the `@aurelia/aurelia` repo. If you want to take a look there and open some starter PRs, we can go back and forth to get it where we like. @RomkeVdMeulen would be happy to provide feedback on the specific PRs as well. Once we're happy and we get those two merged in, we can work to propagate the pattern across more repos.

Here are a few things I think we'll want in each readme:

* A solid description of the repo.
* A status (production/beta/alpha)
* Relevant badges
* Probably keep the paragraph we have on communication channels
* Links to the docs related to the repo. This probably includes deep links to relevant locations in the site docs and the equivalent on GitHub itself.
* Links to any relevant demos, skeletons, tools.
* Link to license

Anything else we need?

**Comment by freshcutdevelopment** [comment]
Great, that sounds good to me. I'd probably add a small snippet of what it looks like to create a component with Aurelia, not something as comprehensive as our getting started from the docs, but just enough to see what the framework is all about without needing to jump off onto a separate page. 

For example, it may be good to include this just after the repo description, with a link out to code sandbox to see it in action.

I'll have a go at these PRs and submit for review.

**Comment by EisenbergEffect** [comment]
Sounds good. If you want to include a code sample, maybe base those off of the new sandboxes we added to the home page?

**Comment by freshcutdevelopment** [comment]
That sounds like a great idea. Will do.

**Comment by freshcutdevelopment** [comment]
Thanks @RomkeVdMeulen , will do.

**Comment by EisenbergEffect** [comment]
It was so much better than what we had that I merged it right away :) I think we can continue to work on it a bit more. Let me ponder it for a bit, make a few minor changes, and then see what our next steps should be.

**Comment by freshcutdevelopment** [comment]
Sounds great, thanks @EisenbergEffect!

**Comment by freshcutdevelopment** [comment]
Thanks @EisenbergEffect , sounds like a plan.

**Comment by RomkeVdMeulen** [comment]
Excellent work! This is a huge improvement.

There's one thing I think could be even further improved. The currect readme does a great job of explaining what Aurelia is. However, there are dozens of similar component-building JS frameworks. The readme could say a bit more on Aurelia's philosophy, and what sets it apart from other similar frameworks. Emphasize the convention-over-configuration aspect, and its close alignment to the latest standards, and explain briefly why this is a huge advantage to developers considering using Aurelia.

> * I haven't included a section on installation yet. Do you think we need one here?

I think showing a couple of console commands for installing the CLI and generating a new project is pretty standard for readmes, and a good way to encourage new developers to try out Aurelia and see for themselves what a typical Aurelia project might look like.

**Comment by RomkeVdMeulen** [comment]
ALso: the code example show here is perhaps a bit too simple. That makes it very easy to understand, and shows the elegance of Aurelia view models very well. I suspect though, that its too much of a toybox example to be compelling to developers reading this. Perhaps in addition to the straight-forward template binding, the sample should also demonstrate some more powerful features. Perhaps a value converter or binding behavior? Of course, you don't want to show too much code right away either... It's a difficult balancing act.

**Comment by fkleuver** [comment]
@RomkeVdMeulen A few examples with increasing complexity (like on the homepage) should be fine I think.
I agree a value converter is an amazing piece to show off since this sort of thing tends to be more tedious in just about any other framework.
Also showing different binding commands (`.trigger`, `.two-way` on a custom element, `repeat.for`) would help emphasize the simplicity and consistency.

**Comment by EisenbergEffect** [comment]
I'm just not sure how much content we want to duplicate from our homepage, and docs into this readme. I already know that when I update the docs, I've got to check our ToC in this readme to make sure it's in sync. Adding too much more could become an issue. There's a balance. Maybe we're still under where we need to be, but I wouldn't want too much more.

**Comment by fkleuver** [comment]
Well, the repo is one of our two home pages. What's fundamentally against keeping them in sync? You update one, you update the other. 10-20% overhead at most I'd say

**Comment by RomkeVdMeulen** [comment]
@EisenbergEffect I expect that even with some more complex examples and a bit more detailed text, the readme will hardly ever need updating. The core philosophy of Aurelia, the unique selling points, an example that shows a value converter: these are all things that haven't changed in years.

**Comment by EisenbergEffect** [comment]
Please go ahead and submit a PR and we can talk through it. Since I usually am the one who ends up doing a lot of this maintenance, I reserve the right to veto 😏 But, you all are probably right and it's probably only for the good of the project, so if you can put something together, let's take a look.

**Comment by RomkeVdMeulen** [comment]
@freshcutdevelopment Should I assume you'll consider this with the rest of the feedback, or would you like me to make a PR?

**Comment by EisenbergEffect** [comment]
There hasn't been much additional feedback. I think what we've got here is the important bit. So, @RomkeVdMeulen if you want to submit a PR, that would be great. Meanwhile, I also think we've got enough to start propagating to other repos @freshcutdevelopment are you still interested and available to help with that?

**Comment by freshcutdevelopment** [comment]
Thanks @RomkeVdMeulen & @EisenbergEffect , yes I think that'd be a great way to approach it. I can start on the other repos. Once PRs come in from @RomkeVdMeulen I can incorporate that feedback into the work I'm doing as well. Will begin with the aurelia/aurelia repo and work my way out from there.

**Comment by RomkeVdMeulen** [comment]
Sorry, I lost track of this for a bit. I'll see about getting that PR ready.

**Comment by EisenbergEffect** [comment]
Actually, I finished this a month or two ago, by bringing over similar content from au1. I don't think we can do much more until more core docs are written. But, the readme now gives examples and explains hot to get started.
