### ISSUE TITLE
Mother issue of all vcurrents "planned" for vnext

### ISSUE THREAD

**Issue by Alexander-Taran** [aurelia/aurelia#325]
# 💬 RFC

Will link here past issues in vcurrent that are candidates to be solved/implemented in vNext
That later could be sorted out to separate relevant rfcs

## Debugging
* [ ] Sourcemap issue with jspm
https://github.com/aurelia/framework/issues/225

* [x] DI interceptors/logging/debugging
https://github.com/aurelia/dependency-injection/issues/124

## So opinionated
* [ ] Configurable AccessMember Creation
https://github.com/aurelia/binding/issues/205

* [ ] Named templates inside templates
https://github.com/aurelia/templating/issues/473

* [x] Strict mode for templates
should warn on binding expressions errors
https://github.com/aurelia/templating/issues/500

* [x] Events for repeaters
https://github.com/aurelia/templating/issues/534

* [ ] Router shalt not make bluebird angry!!!
https://github.com/aurelia/router/issues/480

## Routing
* [ ] ensure proper life-cycle dependencies for nested router-views
https://github.com/aurelia/templating-router/issues/26

### Http (if we are going to have one)

* [x] Better http headers support as per RFC
https://github.com/aurelia/http-client/issues/77

* [ ] Correct typings for cancel-able requests
https://github.com/aurelia/http-client/issues/120
https://github.com/aurelia/http-client/issues/176

### Ui virtualization 
* [ ] detect map mutations
https://github.com/aurelia/ui-virtualization/issues/55

## Documentation
* [ ] Improve docs accessibility
print stylesheet or more printer friendly format for docs
https://github.com/aurelia/documentation/issues/196

## Binding behaviors
* [ ] debounce on input but not on blur
https://github.com/aurelia/templating-resources/issues/228

* [ ] would be also nice to have behaviors usable in code (at least debounce)

**Comment by Alexander-Taran** [comment]
## Architecture
`setRoot()` does not execute activation lifecycle
https://github.com/aurelia/router/issues/566

Composition cancelation
https://github.com/aurelia/templating/issues/612

Surrogate behaviors on compose/router-view
https://github.com/aurelia/templating/issues/513

Inheritance `super(...injected)`
https://github.com/aurelia/dependency-injection/issues/171

customElement as "templateController"
https://github.com/aurelia/templating/issues/171

hooks into framework configuration
i.e. viewStrategy viewLocator
https://github.com/aurelia/framework/issues/415

**Comment by Alexander-Taran** [comment]
## Binding
`class` and `style` binding enhancements
https://github.com/aurelia/binding/issues/294

Observation strategy for files on `input[type=file]`
https://github.com/aurelia/binding/issues/314

Typed binding to input value
https://github.com/aurelia/binding/issues/347

Testing: two-way binding
https://github.com/aurelia/testing/issues/85

Write log when binding to nonexistant properties
https://github.com/aurelia/binding/issues/30

Binding css/style to object with obseving new/removed properties
https://github.com/aurelia/templating-binding/issues/23

`disabled.bind`  and events are still delegated inside the element children
trove of info here:
https://github.com/aurelia/binding/issues/163#issuecomment-243223015

@bindable and getters/setters
https://github.com/aurelia/templating/issues/551
https://github.com/aurelia/templating/issues/579

`style.bind` to object. How Aurelia should unset previously bound values when they are not present anymore
https://github.com/aurelia/binding/issues/715

ValueConverters as a first class citizen in any part of binding expression (binding behaviors to.. while we are at it )
https://github.com/aurelia/binding/issues/718

two-way attribute binding
https://github.com/aurelia/templating/issues/283

**Comment by bigopon** [comment]
[ ] delegate should support cross boundaries, for shadow DOM scenarios

**Comment by fkleuver** [comment]
Adding v1 router base path issue here so we don't forget: <https://github.com/aurelia/templating-router/issues/57>

**Comment by Sayan751** [comment]
@Alexander-Taran @bigopon do we still need to track this for v2? Can we close it and create separate issues when needed? Some issues from V1 might be already too old and have lost relevance.

**Comment by bigopon** [comment]
We can close this, may have been implemented/rectified. If any thing is still of issues, we can address them later.
