### ISSUE TITLE
[RFC] Better support for view-model.ref with repeat.for

### ISSUE THREAD

**Issue by davismj** [aurelia/aurelia#329]
# 💬 RFC

This RFC proposes solutions to a common case where you want to reference the view-model underlying a custom element for a repeated set of sealed objects, e.g. models.

## 🔦 Context

Custom elements often expose a programatic API. I am building a Map element, with Markers, each Marker with a Popup. Marker has a `showPopup()` method which is called programatically by consumers. To call this method, I need a reference to the Marker view-model. This becomes difficult in vCurrent.

```html
<map>
  <marker repeat.for="item of items" view-model.ref="???">
    <popup>This is a popup.</popup>
  </marker>
</map>
```

One solution would be to write `view-model.ref="item.marker"`. However, when the repeated item, `item`, is sealed (e.g., if `item` is a *model*) this is not possible and additional workarounds are required. A good solution allows the consumer to associate the view-model with the the repeated item without modifying the repeated item.

## Examples

**Array-valued `refs` binding**

Where the `element.ref` binding sets a property to an `Element`, the `refs` binding sets a property to an `Array` of `Element`s.

```html
<map click.delegate="findNearestMarker($event)">
  <marker repeat.for="item of items" view-model.refs="markers">
    <popup>This is a popup.</popup>
  </marker>
</map>
```

```ts
class MapViewModel {
  markers: MarkerCustomElement[];
  findNearestMarker(event) {
    const { x, y } = event.detail;
    const closestMarker = null;
    const closestDistance = Infinity;
    this.markers.forEach((marker) => {
      const distance = marker.distanceTo(x, y);
      if (distance < closestDistance) {
        closestMarker = marker;
        closestDistance = distance;
      }
    });
    closestMarker.highlight();  
}
```

Nested repeats will continue to populate the same array.

```html
<map click.delegate="findNearestMarker($event)">
  <marker repeat.for="item of items" view-model.refs="markers">
    <popup repeat.for="popup of item.popups" view-model.refs="popups">This is a popup.</popup>
  </marker>
</map>
```

```ts
class MapViewModel {
  popup: PopupCustomElement[];
}
```

**Map-valued binding**

TODO

**Comment by matthewcorven** [comment]
@davismj filter (value converter) would the on the `item of items`, and our viewmodel array would be filled with the appropriate vms.

**Comment by fkleuver** [comment]
What about using `$children` and getting the correct view model based on the index of the items?

```html
<map>
  <marker repeat.for="item of items">
  </marker>
</map>
```

```ts
export class MapCustomElement {
    $children: MarkerCustomElement[];
    items: MarkerModel[];

    doStuffWithItem(item: MarkerModel) {
        const vm = this.$children.find(c => c.item === item);
        vm.doStuff();
    }
}
```

**Comment by bigopon** [comment]
An issue with this is we can never get the correct order of the view models without position information (`$index` in this case). It's better to have a `children` attribute/binding command, or something similar to take care of collecting the view model instead.
```html
<div click.delegate="findNearestMarker($event)" children="value.bind: popups; selector: div">
  <marker repeat.for="item of items" view-model.refs="markers">
    <popup repeat.for="popup of item.popups">This is a popup.</popup>
  </marker>
</div>
```

if it's the slotted element, then apps need to query the elements themselves via `@slotted()` feature
```html
<map>
  <marker repeat.for="item of items" view-model.refs="markers">
    <popup repeat.for="popup of item.popups">This is a popup.</popup>
```
```ts
class Map {
  @slotted('marker') markers: Marker[]

  markersChanged(markers) {
    const popups = markers.map(marker => marker.popups)
  }
}

class MarkerElement {
  @slotted('popup') popups: Popup[]
}
```

We can open a new issue for shortcut oriented features if necessary. Closing this for now.
