### ISSUE TITLE
[RFC][WIP] Layouts

### ISSUE THREAD

**Issue by davismj** [aurelia/aurelia#345]
# 💬 RFC

**Comment by Sayan751** [comment]
@davismj @bigopon @Vheissu Can you guys provide some details on this? Do we still need this? If not, then please consider closing it.

**Comment by Sayan751** [comment]
Closing this as layout or master page has nothing to do with routing. IMO, this is a pre-slot-era artefact, which can now easily be implemented in the dev land. A similar discussion can be found here: https://discourse.aurelia.io/t/aurelia-2-router-layout/5144. In case of any additional arguments for this feature, please feel free to reopen and/or continue the discussion.
