### ISSUE TITLE
Aurelia composed/ready event

### ISSUE THREAD

**Issue by zewa666** [aurelia/aurelia#360]
# 💬 RFC

vCurrent fires an aurelia-composed dom event once the app is ready. This, amongst others was used and awaited by the [protractor-plugin](https://github.com/aurelia/protractor-plugin/blob/master/index.js#L67) 

## 🔦 Context

Although vNext might be sync with its bootstrapping phase, given the context of an E2E test it would be beneficial to detect when the app is in a "ready-to-test" state. Since the apps `au.start()` might be delayed on purpose and/or manual bootstrapping performed it thus is not safe to expect the app to be loaded synchronously given an E2E context and not having access to the global Aurelia object.

Events are the most basic form of implementing an async kick-off thus I think this should be added to vNext as well.

**Comment by thomas-darling** [comment]
This is not just needed in context of E2E testing.
We also need it to enable reliable pre-rendering, using services such as http://prerender.io, where this event would indicate when the DOM is complete, and a snapshow can be taken.

**Comment by EisenbergEffect** [comment]
Makes perfect sense. I think this should be pretty easy to add to vNext and it should be more reliable in vNext as well due to the improved lifecycle.  We can keep the exact same event name as vCurrent, so it's not a breaking change. What do you think @fkleuver ? Any concerns?

**Comment by zewa666** [comment]
I've recently found one more use-case. In our Electron based app the main BrowserWindow is an Aurelia app. But that hosts another webview, which again is an Aurelia app. So making sure to properly wait for it to finish before firing ipcRenderer calls at it is crucial here

**Comment by fkleuver** [comment]
Fixed by https://github.com/aurelia/aurelia/pull/485
