### ISSUE TITLE
Router demos

### ISSUE THREAD

**Issue by jwx** [aurelia/aurelia#367]
# 💬 Demo

An issue for various router demos. Question, thoughts and opinions are always welcome.

**Comment by jwx** [comment]
Following up on the demo in the [Router parameters PR](https://github.com/aurelia/aurelia/pull/362) I've made a small addition to demonstrate one of the ways to alter the "url syntax".

![navigation example - customized syntax](https://user-images.githubusercontent.com/3307996/50804279-8b972b80-12ed-11e9-85c0-6af4d708d05b.gif)

The links in the files have now changed to
`app`
```html
<li><a href="authors/about">Authors</a></li>
<li><a href="books/about">Books</a></li>
<li><a href="about">About</a></li>
```
`authors` (and `books` is the same)
```html
<a href="author/${author.id}">${author.name}</a>
```
`author` (and `book` is the same)
```html
<li repeat.for="book of author.books"><a href="book/${book.id}">${book.title}</a></li>
```
There's still no route configuration, but the custom syntax has been hooked into the router like this
`app`
```typescript
    this.router.activate({
      transformFromUrl: (path, router) => {
        if (!path.length) {
          return path;
        }
        if (path.startsWith('/')) {
          path = path.slice(1);
        }
        // Fetch components for the "lists" viewport
        const listsComponents = router.rootScope.viewports.lists.options.usedBy.split(',');
        const states = [];
        const parts = path.split('/');
        while (parts.length) {
          const component = parts.shift();
          const state: IComponentViewportParameters = { component: component };
          // Components in "lists" viewport can't have parameters so continue
          if (listsComponents.indexOf(component) >= 0) {
            states.push(state);
            continue;
          }
          // It can have parameters, but does it?
          if (parts.length > 0) {
            state.parameters = { id: parts.shift() };
          }
          states.push(state);
        }
        return states;
      },
      transformToUrl: (states: IComponentViewportParameters[], router) => {
        const parts = [];
        for (const state of states) {
          parts.push(state.component);
          if (state.parameters) {
            parts.push(state.parameters.id);
          }
        }
        return parts.join('/');
      }
    });
```
Now, this is _example code_ to customize this _specific example app_, it's _not_ intended as a generic syntax transformer. It's to illustrate _one_ of the ways to customize. This code is _not_ intended to be a part of the router. @fkleuver#1873 has since long expressed his wish to do the traditional route recognizer (which could be hooked in like this) and a route table lookup could also easily be thrown into the mix here (or at some other connection point).

**Comment by jwx** [comment]
In this demo I've updated the example app to have default components in the viewports and also added a child viewport, with a default component, in the Book component. Manual `nav` elements have been replaced with the `au-nav` and the `addNav` api.

![viewports - defaults and nav](https://user-images.githubusercontent.com/3307996/50804531-a28a4d80-12ee-11e9-8390-31a327b32e38.gif)

With the help of the `au-nav` there's almost less code even though there's more features:
`app`
```html
<template>
  <au-nav name="app-menu"></au-nav>
  <au-viewport name="lists" used-by="authors,books" default="authors"></au-viewport>
  <au-viewport name="content" default="about"></au-viewport>
</template>
```
```typescript
@inject(Router)
export class App {
  constructor(private router: Router) {
    this.router.activate({});
    this.router.addNav('app-menu', [
      {
        title: 'Authors',
        components: [Authors, About],
        consideredActive: [Authors],
      },
      {
        title: 'Books',
        components: [Books, About],
        consideredActive: Books,
      },
      {
        components: 'about',
        title: 'About',
      },
    ]);
  }
}
```
`books`
```html
<template>
<h3>Books</h3>
<ul>
  <li repeat.for="book of books">
    <a href="book=${book.id}">${book.title}</a>
    <ul><li repeat.for="author of book.authors">${author.name}</li></ul>
  </li>
</ul>
</template>
```
```typescript
@inject(BooksRepository)
export class Books {
  constructor(private booksRepository: BooksRepository) { }

  get books() { return this.booksRepository.books(); }
}
```
`book`
```html
<template>
<h3>${book.title}</h3>
<div>Published: ${book.year}</div>
<div>Author(s):
  <ul>
    <li repeat.for="author of book.authors"><a href="author=${author.id}">${author.name}</a></li>
  </ul>
</div>
<au-nav name="book-menu"></au-nav>
<au-viewport name="book-tabs" default="book-details=${book.id}" used-by="about-books,book-details"></au-viewport>
</template>
```
```typescript
@inject(Router, BooksRepository)
export class Book {
  public static parameters = ['id'];

  public book: {id: number};

  constructor(private router: Router, private booksRepository: BooksRepository) { }

  public enter(parameters) {
    if (parameters.id) {
      this.book = this.booksRepository.book(+parameters.id);
    }
    this.router.setNav('book-menu', [
      {
        title: 'Details',
        components: `book-details=${this.book.id}`
      },
      {
        title: 'About books',
        components: 'about-books'
      },
    ]);
  }
}
```
`book-details`
```html
<template>
<h3>Details about the book</h3>
<p>Here's details about <strong>${book.title}</strong>...</p>
</template>
```
```typescript
export class BookDetails {
  public static parameters = ['id'];

  public book = {};
  constructor(private booksRepository: BooksRepository) { }

  public enter(parameters) {
    if (parameters.id) {
      this.book = this.booksRepository.book(+parameters.id);
    }
  }
}
```
And that's all. I think that's quite a lot of nice functionality for a small amount of code/work. Any questions or thoughts?

**Comment by shahabganji** [comment]
Dear @jwx ,

That looks quite great an effort has been don on routing, well done :+1: and keep up the good work :crossed_fingers: 

In Aurelia **vCurrent** we can have multiple named `router-view` as described [here](https://aurelia.io/docs/routing/configuration#rendering-view-ports), however, they are in sync with one another via route configuration. What I want to know is that whether it's possible to have routes like `secondary-routes` of angular or not; for AFAIK, in an angular app one can optionally switch secondary routes off and on, on demand.

I have somehow explained a usecase [here](https://github.com/aurelia/aurelia/issues/67#issuecomment-418402102)

Thanks and well done again.

**Comment by jwx** [comment]
Thanks, @shahabganji!

The routing demonstrated above doesn't used configured routes at all. Instead, each navigation contain a set of viewport states that form a navigation instruction. Sync is maintained within a navigation instruction so a navigation that contains three viewports will keep those three in sync while a navigation with a single viewport state will be totally independent from all other viewports. This means that while using the router like this doesn't support `secondary-routes` (since there are no configured routes) it doesn't need them: what's achieved with secondary routes is already a part of the router's core behavior.

The use case you referred to could be achieved in quite a few ways, but for example:

`app`
```html
<au-viewport name="main" used-by="announcements" default="announcements"></au-viewport>
<au-viewport name="details"></au-viewport>

<!-- Styling should make this viewport floating -->
<au-viewport name="chat" used-by="chat" default="chat"></au-viewport>
```
`chat`
```html
<au-viewport name="chat-main" used-by="chat-users" default="chat-users"></au-viewport>
<au-viewport name="chat-details" used-by="chat-user"></au-viewport>
```
With these two components handling viewports, you could have the following links:
```html
<a href="2-aurelia-routing+chat+chat-user=davismj">This sets up the entire first image you referred to</>
<a href="3-advanced-aurelia">Changes the details component and leaves everything else as it is</>
<a href="chat-user=jwx">Changes the chat user to jwx and leaves everything else as it is</>
<a href="-@chat">Clears the content of the chat viewport (making it possible to hide with css) and leaves everything else as it is</>
<a href="chat">Shows the chat viewport with the chat users list and leaves everything else as it is</>
```
And just to be clear: the above html is everything you'd need to do when it comes to routing for your use case. There's no additional configuration, of routes or anything else, to get this working.

If you want to read more about the basic principles, I've put up my first document as an RFC [here](https://github.com/aurelia/aurelia/issues/369).

I hope I understood your use case correctly. Did that answer your questions? If not, or you have more questions or opinions, please do let me know!

**Comment by shahabganji** [comment]
Thanks @jwx ,

You understood my use case correctly, and I knew this is different than configured routes. I still have some questions, yet not sure to ask them on this thread or on some RFC on the routing. anyway I'll ask them here and if you think we can move them into an appropriate thread.

1. Is `au-viewport` a replacement for `router-view`, or just another way to configure routes fast and simple? Can I use `compose` instead like what is suggested [here](https://github.com/aurelia/aurelia/issues/164#issuecomment-434547741)?
2. Is this approach suitable for simpler scenarios that we require to setup without the complexities of routing or we can utilize that for enterprise applications too? ( Kinda, intuitively I think this approach is better for the former scenario, am I right?  )
3. How does these routes get along with routing **steps(route guards)**, such a Authorize step?
```html
<au-viewport name="chat" used-by="chat" default="chat" steps="Authorize"></au-viewport>
```
or 
```html
<au-viewport name="chat" used-by="chat" default="chat" steps="Authorize,IsAdmin"></au-viewport>
```

**Comment by jwx** [comment]
@shahabganji First of all, let me point out that none of this is completely set yet. A lot of these posts express ideas and opinions from members of the team and community as a part of the development process, not documentation on how it will actually be in vNext. Having said that
1. My view is that `au-viewport` will replace `router-view`, containing the functionality necessary for both the traditional routes (`router-view`) and these convention-based ones. This also does track with vCurrent in the sense that in a route you configure which viewport the content should go to (if you have more than one `router-view`). The post you refer to about `compose` is primarily about using `compose` for the vCurrent `layout` feature, but we have talked about using `compose` for routing as well. However, since routing among other things involves navigation history, I think we'll end up with a separate `au-viewport` element for it.
2. I think the answer here is very subjective. My ambition is to get this into such a state that it can be used in any kind of application. If it had existed when I made my last enterprise application, I would've used it for it.
3. Routing steps/route guards will definitely be supported with the convention-based routing as well. While work on it hasn't started yet, [here's](https://github.com/aurelia/aurelia/issues/307#issuecomment-446936774) what I'm thinking.

Thanks for taking an interest and providing questions and feedback!

**Comment by shahabganji** [comment]
@jwx thanks for your prompt answer. The direction of touring sounds promising and that's awesome. Keep up the good work :+1: 

As the last question is it possible to have access to routes and their children before navigation to them as some sort of meta data to generate menus of site maps based on them? any work on that? both for when one uses convention-based routes and configured routes.

**Comment by jwx** [comment]
@shahabganji There's been talk about "going through" all the components of an application for that kind of meta data, but as far as I know it's not been specified exactly how that would be implemented.

The only thing I've done with relation to menues is the `addNav`, `setNav` and `au-nav` in the demo above. In most projects I've worked, menu structure and contents are decided by someone (who's not implementing the actual components) saying things like "and under the (menu) item 'Administration' we want the items 'Authors and 'Books' that shows their lists" so it just made sense to me to start an implementation from that point of view.

**Comment by jwx** [comment]
@shahabganji Since it's such a small amount of work, I added your chat use case to the previous demo.

**The resulting demo is [here](https://dist-73cbi2thx.now.sh).**

To get the this functionality, I simply added three small components:

`chat`
```html
<template>
  <h3>Chat <a href="-@chat" class="close">X</a></h3>
  <au-viewport name="chat-main" used-by="chat-users" default="chat-users"></au-viewport>
  <au-viewport name="chat-details" used-by="chat-user"></au-viewport>
</template>
```
```typescript
export class Chat { }
```
`chat-users`
```html
<template>
  <ul>
    <li repeat.for="user of users">
      <a href="chat-user=${user.id}">${user.id} (${user.name})</a>
    </li>
  </ul>
</template>
```
```typescript
@inject(UsersRepository)
export class ChatUsers {
  constructor(private usersRepository: UsersRepository) { }

  get users() { return this.usersRepository.users(); }
}
```
`chat-user`
```html
<template>
  <p>Chatting with <strong>${user.id} (${user.name})</strong><p>
  <p>You: Hello!</p>
  <p><input></p>
</template>
```
```typescript
@inject(UsersRepository)
export class ChatUser {
  public static parameters = ['id'];

  public user = {};
  constructor(private usersRepository: UsersRepository) { }

  public enter(parameters) {
    if (parameters.id) {
      this.user = this.usersRepository.user(parameters.id);
    }
  }
}
```
and added the Chat link to the `addNav`:

`app`
```typescript
    this.router.addNav('app-menu', [
      {
        title: 'Authors',
        components: [Authors, About],
        consideredActive: [Authors],
      },
      {
        title: 'Books',
        components: [Books, About],
        consideredActive: Books,
      },
      {
        components: About,
        title: 'About',
      },
      {
        components: 'chat',
        title: 'Chat',
      },
    ]);
```
And that's it! Any questions or thoughts?

**Comment by shahabganji** [comment]
@jwx 

Sounds easy to bootstrap, Is there any way that we cant test the above-mentioned sample online by ourselves, such as code sandbox or stackblitz?

**Comment by jwx** [comment]
## Local components

So far the demos have contained globally registered (unique) components, but of course Aurelia gives you the option to specify locally registered components. And the router will play along. Let's expand our previous demo with the following structure
![image](https://user-images.githubusercontent.com/3307996/51396256-09a1d080-1b3f-11e9-8ec8-c78942f55598.png)
so that the `book` component and the `author` component should have their own local `information` component. 

Let's first look at how you'd declare that dependency. We've got the html `require` way

`book`
```html
<require from="./information"></require>
```
or the code way

`book`
```typescript
import { Information } from './information';

@customElement({ dependencies: [Information] }) // This api might change but principle will remain
export class Book { ... }
```

Once the `Information` component (which is just an `export class Information {}` with some html) has been registered in any of the above ways it's now available for navigation for `book` and anything in the `au-viewport` within `book`. However, since that viewport in `book` is specifying `used-by` (which it doesn't need to, it's just to limit the components that can be loaded into it) we need to add the component to the list of accepted components

`book`
```html
<au-viewport name="book-tabs" used-by="about-books,book-details,information" default="book-details=${book.id}"></au-viewport>
```

Now `information` is available for us in links
```html
<a href="information">Book information</a>
```
or code
```typescript
this.router.goto("information");
```

and we can also add it to our already existing `nav`

```typescript
this.router.setNav('book-menu', [
  { title: 'Details', components: `book-details=${this.book.id}` },
  { title: 'About books', components: 'about-books' },
  { title: 'Book information', components: 'information' },
]);
```

And when we do exactly the same thing for the `author` component and its own `information` component, we end up with this

![router - local components](https://user-images.githubusercontent.com/3307996/51398678-82575b80-1b44-11e9-914b-ace97fb2439d.gif)

**The demo can be found [here](https://dist-iy8ffamwe.now.sh).**

Questions and opinions are highly appreciated!

**Comment by jwx** [comment]
> Is there any way that we cant test the above-mentioned sample online by ourselves, such as code sandbox or stackblitz?

Sorry for not replying sooner, @shahabganji. (I honestly thought I already had replied.) Unfortunately, as far as I know vNext isn't up on either code sandbox or stackblitz. You can always clone the repo, though, and play around with the test/demo application.

**Comment by shahabganji** [comment]
@jwx Not a problem at all, there's no rush.

**Comment by HamedFathi** [comment]
@jwx 
I have some idea about a document generator for Aurelia so I checked [Compodoc](https://compodoc.app/).

Please see Routes section in [here](https://compodoc.github.io/compodoc-demo-todomvc-angular/routes.html)

![image](https://user-images.githubusercontent.com/8418700/51690155-6143ae80-200d-11e9-86fa-591198683ceb.png)


How to get some info/meta info about current routing status? (like the above picture.) Is it possible in vNext?

**Comment by HamedFathi** [comment]
> The vNext router already has an api for listing all currently active components and their viewports.

Does it work in compile time? A document generator should gather the information from your app so I want to access the information in compile time. Is it possible?

Suppose I have an Aurelia project. I should pass the project path to a document generator and get the result. How to access the router information in this mode?

**Comment by shahabganji** [comment]
@jwx I think @HamedFathi requires the information of routes even when they are not yet **active**, if we forget about compile time he mentioned, at run time AFAIK the vCurrent does not provide you with a list of all routes available in your application until you hit them, am I right? Will that be kinda resolved in vNext? if so, then generating many stuff would be handy, ranging from documents to site maps and menus.

**Comment by jwx** [comment]
@HamedFathi @shahabganji Sorry, I misunderstood. If you're using this new dynamic routing, there aren't any routes configured in the router to ask for. What would be needed to get such a list is going through all application files (preferably at compile time) and gathering routable components/files and the links to them. While a nice feature, I think it'd be best kept out of the core of the router and possibly added as some kind of plugin. I've made a note of it and will get back to it when I've come further with the remaining core functionality of the router.

**Comment by shahabganji** [comment]
Is writing a plugin for compile time way different than regular plugins we write for Aurelia vCurrent?

And, I have seen a [plugin](https://github.com/jagonalez/aurelia-navigation-menu) before for routing, but not sure will it be helpful or not, for vNext?

**Comment by fkleuver** [comment]
@jwx @shahabganji  I think the whole point of dynamic routing is that there is no predefined deterministic set of routes. With configured routes (normal way with static props and/or decorators) it would obviously not be a problem to walk the tree, but with dynamic routes you need some user input to scope things.
With AOT it should be a different story. But building a navigation based on existing routes, if you need the whole route tree - configured routes is still a legitimate use case, this would be a good one such case imo.

**Comment by shahabganji** [comment]
@fkleuver Most of the time an enterprise application starts with a wealth of predefined routes via the `configureRouter` method in **vCurrent** and/or `@decorator` or other approaches in **vNext**. I think @HamedFathi's most concern is with predefined routes, am I right? 

> Requesting this info at runtime would be like trying to get all the values from a datepicker.

Couldn't be agree more. and I think they could be useful only to update menus, not generating a tree for documentation, or sitemap. Yet, not sure, maybe I couldn't get the use case.

**Comment by fkleuver** [comment]
I think there is a slight misunderstanding here. The new router can be used in **two** ways.

### Dynamic routing

This is what @jwx is currently working on: routing without the need for *any* configuration. A simplified way of putting it (ignoring all the various ways things can be overridden and whatnot), is the (default) convention that when you enter a url `/foo`, it will look for a custom element named `foo`.

This has no equivalent in vCurrent because in vCurrent (and as far as I know any other SPA framework) you *always* need to configure your routes in some way. in vCurrent that would be `configureRouter`. This is *not* a replacement for `configureRouter`; it is an *alternative* to it.

Its purpose is to significantly reduce the necessary boilerplate for those who just want straightforward routing without boilerplate. Most of the configured routing features are also available in dynamic routing, but not all of them - which features precisely, we don't know yet. It's a new thing so we have yet to discover its limitations (if any)

### Configured routing

This is not yet implemented, we still need to port the `route-recognizer` from vCurrent and make a few tweaks/adjustments, hook things up, implement @davismj 's specs with the decorators, static properties and other ways to statically define routes before components are even loaded.
This mechanism of using the router will be the most flexible in terms of retrieving (and manipulating) the configuration during app startup, for purposes such as the one you were talking about.

This is going to be the replacement for vCurren't `configureRouter` and it will largely work the same way, but will be a bit simpler to use. 

In fact, we'll have a backward compat package that can make the translation for `configureRouter` and we don't expect folks using all but the most low-level api's would have to change anything to get their vCurrent route configs to work in vNext.

**Comment by Sayan751** [comment]
@jwx Can this be closed?
