### ISSUE TITLE
Content Projection with Multiple Slots

### ISSUE THREAD

**Issue by shahabganji** [aurelia/aurelia#399]
# 🙋 Feature Request

There are times you need to let the user of your component to inject its customized contents to the templates of your component, this is when content projection comes into play; that being said, I think some times we want that content to be rendered in multiple places but one of them will be shown, or even all, the surrounding HTML tags are different though, with vCurrent it is kinda impossible to have multiple slots without **name attribute**, multiple default slots :see_no_evil: 

## 🤔 Expected Behavior

consider I have `some-component`:

```html
<template>
  <button if.bind="someConditions">
     <slot></slot>
</button>
<a if.bind="someOtherConditions">
     <slot></slot>
</a>
</template>
```

and when I use this component, I expected: 

```html
<some-component some-conditions.bind="true"></some-component>
<some-component some-other-conditions.bind="true"></some-component>
<some-component some-other-conditions.bind="true" some-conditions.bind="true"></some-component>
```

I expect the first component to render a **`button`**, the second one to render an **anchor** tag, and the last one to render **both a button and an anchor** .

## 😯 Current Behavior

* The aurelia templating engine throws an exception when observing multiple `slot` tags without name.

## 💁 Possible Solution

No Idea! :see_no_evil:  replace all the slots if the conditions met? :eyes: 

## 🔦 Context

A real world scenario would be bootstrap's **`list-group`** to implement all of its variants via a single component, consider [this](https://getbootstrap.com/docs/4.2/components/list-group/#basic-example) variant and [this](https://getbootstrap.com/docs/4.2/components/list-group/#links-and-buttons) one for instance.

## 💻 Examples

a `list-group` component

```html
<template>
    <ul class="list-group" show.bind="someCondition">
        <slot></slot>
    </ul>
    <div class="list-group" show.bind="!someCondition">
        <slot></slot>
    </div>
</template>
```

the `list-group-item` component

```html
<template>
    <li if.bind="someCondition">
        <slot></slot>
    </li>
    <a if.bind="!someCondition">
        <slot></slot>
    </a>
</template>
```

and the usage: 

```html
<list-group someCondition.bind="true">
    <list-group-item someCondition.bind="true">First</list-group-item>
    <list-group-item someCondition.bind="true">Second</list-group-item>
</list-group>
```

**Comment by fkleuver** [comment]
What you are looking for should be possible with `replaceable part` / `replace-part` although they need to be named:

```html
<template>
    <li if.bind="someCondition" replaceable part="list-item1">
    </li>
    <a if.bind="!someCondition" replaceable part="list-item2">
    </a>
</template>
```

```html
<list-group someCondition.bind="true">
    <list-group-item someCondition.bind="true" replace-part="list-item1">First</list-group-item>
    <list-group-item someCondition.bind="true" replace-part="list-item2">Second</list-group-item>
</list-group>
```

You can still put `@useShadowDOM` on top of the custom elements if you also need the encapsulation. In many cases it's the best of both worlds.

You're deliberately not using a repeater though? And would this sort of solution work for you or is there a particular reason they cannot be named?

**Comment by shahabganji** [comment]
@fkleuver

There are some concerns when using `replaceable part / replace-part`, one of which is that the injected template is bound to the inner context as such it has access to all private and public fields and APIs of the component, that violates  the encapsulation rule which in most cases is not what you want. That being said,  **`namings`** are preferable when they make parts of your component distinguishable just like `named-slots` not for what it is a default content of a component.

ASFAIK, the `replaceable / part` and `replace-part` should be applied on a `template / as-element="template"` tag, correct me if I am wrong, so the above-mentioned sample is looking abstract to me, therefore I tried to implement the sample with replaceables, please mention any mistakes I have.

* ## Implementations:

* ### list-group component

```html
<template>
  <ul if.bind="list">
    <li as-element="template" replaceable part="item-li">
    </li>
  </ul>

  <div if.bind="!list">
    <template replaceable part="item-a">
    </template>
  </div>
</template>
```

```ts
import { bindable } from "aurelia-framework";

export class ListGroupCustomElement {

  @bindable() list: boolean = true;

  private another_private_field = "I am another private field";
}
```

* ### list-group-item component

```html
<template>
  <li if.bind="list">
    <template replaceable part="item-li" replace-part="item-li">
    </template>
  </li>

  <a replace-part="item-a" if.bind="!list">
    <template replaceable part="item-a">
    </template>
  </a>
</template>
```

```ts
import { bindable } from "aurelia-framework";

export class ListGroupItemCustomElement {
  @bindable() list: boolean = false;

  private some_property: string = "I am a private field";
}
```

* ## Usage:

```html
<template>

  <require from="./list-group"></require>
  <require from="./list-group-item"></require>

  <list-group list.bind="false">
    <template replace-part="item-a">
<!-- can access a private field -->
      <p>${another_private_field}</p>
      <!-- ************************** -->
      <list-group-item repeat.for="s of names" list.bind="false">
        <template replace-part="item-a">
          <br />${s} - ${list}
        </template>
      </list-group-item>
    </template>
  </list-group>

  <hr />

  <list-group list.bind="true">
    <template replace-part="item-li">
      <list-group-item repeat.for="s of names" list.bind="true">
        <template replace-part="item-li">
          ${s} - ${list} - ${some_property}
        </template>
      </list-group-item>
    </template>
  </list-group>

</template>
```

The usage complexity of replaceable templates, and the fact that using strings is something that is intrinsically error prone especially when there's paucity of intellisense in some parts, will pale in comparison with `slot`s.

**Comment by fkleuver** [comment]
It will be possible to configure `replaceable` in such a manner that they do not have access to the outer scope though. In vCurrent this is hard-coded but in vNext this boundary traversal is controlled with a simple flag.

You have good points otherwise though and I agree. But template controllers + slots.. don't mix very well :(
I can try to think of another way. Perhaps replaceable can be given another attribute that tells it to automatically match by position.

**Comment by shahabganji** [comment]
@fkleuver 
One of the main differences of the `template` and `slot` is exactly their scope, while slot is bound to the outer scope before injection and do not have access to the internals, which in component design is a desired behavior in most cases, the template can have access to the both worlds since it is bound to the context after injection, moreover I am aware of the limitations of template controllers and slot when working in conjunction with one another.  I personally do not complain about them. @bigopon, I know slot is designed to inject a single blob, I do not want to have the blob in multiple destinations simultaneously, may be my sample was a bit misleading, and I am not deliberately copying the slot, the situation is a matter of `if/else` or `switch/case` which decides only a single valid destination, however in `Vue` there is not even this limitation, I am not saying that is good or bad, for I am not eligible to say. I just think having this feature would make component design and usage more friendly in some cases.

Maybe, maybe a better sample might look like this: 

```html
<template>
    <ul class="list-group" if.bind="someCondition">
        <slot></slot>
    </ul>
    <div class="list-group" else>
        <slot></slot>
    </div>
</template>
```

**Comment by EisenbergEffect** [comment]
We definitely can't allow more than one default slot as that would break with web standards. Such a thing would not work in the DOM without crazy hacks. The if/else scenario as above might actually work today in vNext though. I'm not sure. We'd have to tests, but I think it might be supported by native shadow dom.

**Comment by bigopon** [comment]
> however in Vue there is not even this limitation

Can you help show how it's done in Vue?

@shahabganji I think i understand what you feel, but I don't know if we ever want to fight against standard, we can submit a proposal if we have strong/concrete enough use case(s) though.

**Comment by EisenbergEffect** [comment]
Confirmed that the if/else scenario with slot from above works with native shadow DOM. So, supported in vNext already.

**Comment by shahabganji** [comment]
> We definitely can't allow more than one default slot as that would break with web standards. 

This was also my concern in first place, however I decided to open the feature request :roll_eyes: 

> The if/else scenario as above might actually work today in vNext though

If it works, that will tackle my concern, will it then allow me to have one slot in each block? like the above example?

> Can you help show how it's done in Vue?

Should I create a repository, if not the following is an example I just checked before opening the feature request. If you want a repo just let me know to update it somewhere.

* Vue sample:

```vue
<template>

  <div class="hello">
    <slot></slot>
    <hr />
    <slot></slot>
    <hr />
    <slot></slot>
  </div>

</template>

<script lang="ts">
import Vue from 'vue';

export default Vue.extend({
  name: 'HelloWorld',
  props: {
    msg: String,
  },
});
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
h3 {
  margin: 40px 0 0;
}
ul {
  list-style-type: none;
  padding: 0;
}
li {
  display: inline-block;
  margin: 0 10px;
}
a {
  color: #42b983;
}
</style>

```

* the usage: 

```vue
<template>
  <div id="app">
    <HelloWorld>
      <p>Hello world</p>
    </HelloWorld>
  </div>
</template>

```

![image](https://user-images.githubusercontent.com/4405518/51515344-8cb97400-1e28-11e9-9056-2f77fbd5edac.png)

However, as tou guys  said, adhering to the standards is also essential, looking for a trade off though.

**Comment by bigopon** [comment]
I see, what you described isn't really shadowDOM projection, it's replacement. Maybe we can have a flag to let the templating behave in that replacing way, instead of projecting way. Defer to @EisenbergEffect @fkleuver

**Comment by EisenbergEffect** [comment]
In ShadowDOM, adding three default slots will result in the browser ignoring the 2nd and 3rd slots entirely. I don't think we want to hack that to try to make things work contrary to the standard.

However, as @bigopon points out, this is like replacement. And the good news is that in vNext (just tested) and maybe in vCurrent (haven't tested) you can use the same name for multiple parts. For example:

#### slot-test.html

```xml
<template>
  <div replaceable part="copy">
  </div>

  <div replaceable part="copy">
  </div>

  <div replaceable part="copy">
  </div>
</template>
```

And then use it like this:

```xml
<slot-test>
  <span replace-part="copy">This is some duplicated text.</span>
</slot-test>
```

**Comment by davismj** [comment]
For what it is worth, the vCurrent solution to this is to use `@processContent`.

**Comment by fkleuver** [comment]
Well yeah, if we're going down the road of low level API's, which is indeed probably the better solution in the first place, `createElement` and the `render` hook are going to be your friends in vNext. We'll also add `@processContent` for backwards compat but the former two are much more powerful.

**Comment by shahabganji** [comment]
@EisenbergEffect I do no really want to copy a single blob in multiple parts, what I thought was to have a single destination which it's wrapper can be decided dynamically, just like the `if/else` conditioned that you said is working in vNext, which is awesome. I am profoundly supporting the idea of sticking to the standards, since it is what separates Aurelia from others. 🤞 👍

**Comment by fkleuver** [comment]
@shahabganji We're trying to keep that to a bare minimum. In certain areas we started from scratch so as the API's currently stand they are breaking, but for the most part they are translatable to vCurrent api's via a compat layer. We just need to choose carefully which things to focus on for backward compat.
Hooks are definitely a priority there, so problems with those should be minimal once things are done.

**Comment by Sayan751** [comment]
@shahabganji In my earlier conversation with @HamedFathi, we found out that this use-case is supported by the `au-slot`. The `au-slot` PR is merged. You can find the basic examples in the au-slot PR itself, but the docs PR will follow. Can you verify if this issue can be closed?

**Comment by shahabganji** [comment]
@Sayan751 sure I'll take a look.

**Comment by bigopon** [comment]
This is now supported per @Sayan751 's comment. Please refer to our au-slot doc for more details.
