### ISSUE TITLE
[RFC] Remove Binding Attributes from Templates During Compilation

### ISSUE THREAD

**Issue by EisenbergEffect** [aurelia/aurelia#420]
# 🐛 Bug Report

When a template is compiled, the bound attributes should be removed from the template so that when it's cloned as part of the instantiation process, they don't appear in the dom.

## 🤔 Expected Behavior

If we have some HTML as follows:

```XML
<input type="text" value.bind="firstName">
```

Then after compilation, the clonable template should look like this:

```XML
<input type="text" class="au">
```

There should be no `value.bind` attribute. Additionally, the following short-hand HTML syntax should produce the same output:

```XML
<input type="text" :value="firstName">
```

## 😯 Current Behavior

Currently, the above template, after compilation, still contains the `value.bind` attribute, which would then be present in the DOM when the template was cloned. This does not cause any buggy behavior (that I know of) but the DOM is less clean than we'd like it to be.

## 💁 Possible Solution

We could have the compiler remove all attributes for which there is a binding command of any sort.

## 🔦 Context

Again, this doesn't appear to result in bugs but would help in ensuring a cleaner DOM.

**Comment by bigopon** [comment]
I think this should be a toggle-able feature, as sometimes I do want to see my templates in the output, for debugging purposes. When views start to get complex, it's needed often.

**Comment by bigopon** [comment]
To clarify, interpolation should be removed, but attributes with binding commands don't suffer the same thing, so they can be safely ignored.

**Comment by EisenbergEffect** [comment]
Perhaps it's a debug feature that the attributes stay in the DOM, but when not in debug mode, they get removed? (I've tracked the interpolation issue separately from this.)

**Comment by bigopon** [comment]
Yes, I've always having them during development, sometimes they help greatly.

**Comment by fkleuver** [comment]
@EisenbergEffect vCurrent also doesn't remove them and since this doesn't cause anything to break I think this should be labeled feature / RFC. Makes it less distracting and not feel like high prio (which I don't think it is)

**Comment by EisenbergEffect** [comment]
Good point!

**Comment by bigopon** [comment]
After sometime, well, I think we should get started with just removing everything, and wait for an actual request before adding the ability to keep the attributes with binding expressions for debugging purposes.
