### ISSUE TITLE
Cannot nest a custom element in a slot

### ISSUE THREAD

**Issue by davismj** [aurelia/aurelia#446]
# 🐛 Bug Report

A custom element cannot be added to the slot of a custom element.

## 🤔 Expected Behavior

A custom element should be able to be added to a slot.

## 😯 Current Behavior

A custom element cannot be added to the slot of a custom element.

> reporter.ts:46 Uncaught (in promise) Error: There are more targets than there are target instructions.
    at Object.error (reporter.ts:46)
    at Renderer.render (renderer.ts:115)
    at Container.context.render (rendering-engine.ts:314)
    at CompiledTemplate.render (rendering-engine.ts:106)
    at ShellComponent.$hydrateElement [as $hydrate] (lifecycle-render.ts:108)
    at startTask (aurelia.ts:69)
    at Aurelia.start (aurelia.ts:98)
    at Object.parcelRequire.src/main.ts.@aurelia/debug (main.ts:12)
    at newRequire (main.b0a109ad.js:49)
    at localRequire (main.b0a109ad.js:55)

## 💻 Code Sample

```ts
import { customElement } from '@aurelia/runtime';
import template from './basic.html';

@customElement({ name: 'basic', template })
export class BasicCustomElement {
}
```

```html
<template>
  <span>Basic</span>
  <slot></slot>
</template>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | 0.3.0
| Language         | TypeScript
| Browser          | Chrome, Firefox
| Bundler          | Parcel
| Operating System | Windows
| NPM/Node/Yarn    | Node 10

**Comment by EisenbergEffect** [comment]
Currently, you would at least need to turn Shadow DOM on for the element with the `slot`. There's a setting in the `customElement` configuration object for that. Let me know if that fixes it for you.

**Comment by EisenbergEffect** [comment]
We aren't emulating shadow dom at all ourselves in vNext. We require native shadow dom or a pollyfill to be present. If you want to use slots or style encapsulation, you need shadow dom turned on for your element. Right now the default is that it's not turned on. Based on my recent work on a real app, I think we should make it turned on by default. This would be a breaking change against vCurrent, but I don't know any better way to handle it.

**Comment by davismj** [comment]
Tagging both elements with `@useShadowDOM` had no effect.

**Comment by fkleuver** [comment]
@davismj this is fixed by https://github.com/aurelia/aurelia/pull/485
