### ISSUE TITLE
Checkbox / Radio Bindings [RFC]

### ISSUE THREAD

**Issue by davismj** [aurelia/aurelia#447]
# 💬 RFC

Most input bindings are pretty straightforward, but checkboxes have some additional common use cases that should be handled in vNext out of the box. New use cases are marked.

Additionally, to reduce confusion, we should remove the `model` property in favor of the `value` property, if possible.

**basic checkbox**

- when checked, `checked = true`
- when unchecked, `checked = false`
- checked when `!!checked`
- unchecked when `!checked`

```html
<label>
  <input type="checkbox" checked.bind="checked" />
  Checked
</label>
```

⭐️ **negated checkbox**

- when checked, `checked = false`
- when unchecked, `checked = true`
- checked when `!checked`
- unchecked when `!!checked`

```html
<label>
  <input type="checkbox" checked.bind="checked" value.bind="false" />
  !Checked
</label>
```

**scalar-valued radio**

- when checked, `checked = value`
- checked when `checked == value`
- unchecked when `checked != value`

```html
<label repeat.for="value of values">
  <input type="radio" checked.bind="checked" value.bind="value" />
  ${value}
</label>
```

**object-valued radio**

- when checked, `checked = value`
- checked when `checked == value`
- unchecked when `checked != value`

```html
<label repeat.for="value of values">
  <input type="radio" checked.bind="checked" value.bind="value" />
  ${value.label}
</label>
```

⭐️ **scalar-valued checkbox**

- when `Array.isArray(value)`
  - when checked, `checked.splice(0, checked.length, ...value)`
  - when unchecked, `checked.splice(0, checked.length)`
  - checked when `checked.length === value.length && checked.every(c => value.includes(c))`
  - indeterminate when `checked.length != value.length || checked.some(c => !value.includes(c))`
  - unchecked when `checked.length === 0`
- when `!Array.isArray(value)`
  - when checked, `checked = value`
  - when unchecked, `checked = null`
  - checked when `checked == value`
  - unchecked when `checked != value`

```html
<label>
  <input type="checkbox" checked.bind="checked" value.bind="values" />
</label>
<label repeat.for="value of values">
  <input type="checkbox" checked.bind="checked" value.bind="value" />
  ${value}
</label>
```

⭐️ **object-valued checkbox**

- when `Array.isArray(value)`
  - when checked, `checked.splice(0, checked.length, ...value)`
  - when unchecked, `checked.splice(0, checked.length)`
  - checked when `checked.length === value.length && checked.every(c => value.includes(c))`
  - indeterminate when `checked.length != value.length || checked.some(c => !value.includes(c))`
  - unchecked when `checked.length === 0`
- when `!Array.isArray(value)`
  - when checked, `checked = value`
  - when unchecked, `checked = null`
  - checked when `checked == value`
  - unchecked when `checked != value`
```html

<label>
  <input type="checkbox" checked.bind="checked" value.bind="values" />
</label>
<label repeat.for="value of values">
  <input type="checkbox" checked.bind="checked" value.bind="value" />
  ${value.label}
</label>
```

**Comment by bigopon** [comment]
I think the issue with this is

it breaks `.value` for object scenario if we patch/override that property
It makes binding unpredictable when `value` binding nolonger consistent with the rest

**Comment by davismj** [comment]
Makes sense to me. It would be a nice to have but I don't really think it is critical.

**Comment by bigopon** [comment]
Our current form of checkbox/radio binding is intuitive and unobtrusive enough, I don't think we would need to make a breaking change enhancement in v2. And we should also collect more feedback, if anyone can contribute a concrete example of how the existing behavior doesn't suffice.
