### ISSUE TITLE
DI Documentation

### ISSUE THREAD

**Issue by scottrippey** [aurelia/aurelia#477]
I was hoping for some documentation around the `DI` class, and how to use it.

Specifically, I found the `Registration.*` methods to be confusing.  
`singleton` makes sense, and works as expected.
I expected `instance` to return instances of the dependency (instead of the raw value).
I couldn't figure out how `factory` worked.

So it'd be nice to have some docs around those methods!
It'd also be great to understand how the `IRegistry` interface works, so that we could provide our own registrations.

**Comment by EisenbergEffect** [comment]
I think I can get preliminary documentation on this in particular in place pretty soon.

**Comment by EisenbergEffect** [comment]
@scottrippey Here's the first draft of DI docs. I had this sitting around, so it didn't take long to clean it up and get it in: https://github.com/aurelia/aurelia/blob/master/docs/user-docs/articles/foundations/dependency-injection.md I'll mark this issues as resolved. Then, as you read this, if you want to open additional issues for specific topics that you want me to add to this doc, please do that and I'll tackle them one by one.
