### ISSUE TITLE
Kernel: Make DI Registration strongly typed

### ISSUE THREAD

**Issue by scottrippey** [aurelia/aurelia#478]
# 🙋 Feature Request

When using DI, I'd love if there was type-checking, to ensure my injected services correctly implement their interfaces.

## 🤔 Expected Behavior

Here's how I'd like it to work:

```
import { DI, Key, Registration } from '@aurelia/kernel';

const IService = Symbol('IService') as Key<IService>;
interface IService {
    methodOne(): void;
    methodTwo(): void;
}


class ServiceImpl {
    methodOne(): void { }
    methodTwo(): void { }
}
class BadServiceImpl {
    methodOne(doesNotMatchInterface: boolean) { }
    // methodTwo is missing
}


DI.createContainer().register(
    // Should work fine:
    Registration.singleton(IService, ServiceImpl),
    // Should give a type error:
    Registration.singleton(IService, BadServiceImpl),
);
```

## 😯 Current Behavior

Currently, the above code will work just fine, and would result in runtime errors, since `BadServiceImpl` doesn't have any of the required interface methods.

## 💁 Possible Solution

In this example, `Registration.singleton` could be strongly typed as:
```
Registration = { ...
  singleton<T>(key: Key<T>, value: Constructable<T>): IRegistration;
}
```

## 🔦 Context

I've been developing a `VirtualService`, which dynamically implements certain interfaces, and executes it remotely (eg. via IPC or WebSocket or HTTP).  
In most instances, the `VirtualService` is completely async, which means all methods on the interface must also be async.  
By adding this type-checking, it will ensure that a `VirtualService` is compatible with the interface it's being injected for.

**Comment by EisenbergEffect** [comment]
@scottrippey I think we can probably add a a few overloads to the Registration API for this. I'll look into it in a bit.

**Comment by fkleuver** [comment]
@scottrippey 
This can't be enforced with inference without breaking other scenarios (e.g. string registrations or aliases). I've been all over the place with overloads.

You can, however, add a generic type argument to the call with `Constructable<IMyInferfac>` and enforce it like this:

```ts
// Will work fine
Registration.singleton<Constructable<IService>>(IService, ServiceImpl),
// Type error
Registration.singleton<Constructable<IService>>(IService, BadServiceImpl),
```

I'm closing this because we can't narrow the `Registration` calls any further. We should probably add this as a "trick" to the docs, though.
