### ISSUE TITLE
au-compose should pass through bindings and content

### ISSUE THREAD

**Issue by EisenbergEffect** [aurelia/aurelia#497]
# 🐛 Bug Report

When using the `au-compose` element, any bindings on `au-compose` should function as if they were actually declared on the composed element instead. Any content placed inside the `au-compose` start and end tags, should render as if it were placed in between the composed element's start and end tags.

## 🤔 Expected Behavior

Elements that are dynamically composed should function exactly as if they were statically declared inline, with their bindings and content HTML.

## 😯 Current Behavior

Currently, neither bindings nor content are passing through. The original implementation I did was a quick hack and the templating engine has changed significantly since it was done. So, we need to revisit this and get it working.

## 🔦 Context

Without this feature, the `au-compose` element is significantly reduced in power, since there's no way to get any contextual data into the composed element.

## 💻 Code Sample

We'd like to be able to write something like this:

```HTML
<au-compose subject.bind="myElement" some-prop.bind="foo">
  <div>Some content...</div>
</au-compose>
```

And have the runtime behave as if this were written:

```HTML
<my-element some-prop.bind="foo">
  <div>Some content...</div>
</my-element>
```

> Note: `my-element` is determined at runtime based on the value of `myElement`. The concrete element name is used here for example purposes.

**Comment by fkleuver** [comment]
So this does not overlap with this one right? https://github.com/aurelia/aurelia/issues/422

**Comment by EisenbergEffect** [comment]
It’s different scenarios. #422 is about making composed elements act as normal elements, where this ticket is about breaking the encapsulation boundary and having them bind directly to the outer scope.

**Comment by bigopon** [comment]
Should we also mention surrogate instructions handling strategy?

**Comment by EisenbergEffect** [comment]
If the composed element has surrogate instructions, those should definitely work. I’m not sure why that wouldn’t just work. I think it does today. I need to check…

**Comment by wasnotrice** [comment]
I was looking for this functionality today. This proposal sounds very useful!

**Comment by Vheissu** [comment]
@bigopon Is this still something we are going to implement or already exists?

**Comment by bigopon** [comment]
It can be done though the details for this is a bit unclear, I think I'll need to work it out first. It'll be done based on current attr transferring infra that we have.
