### ISSUE TITLE
Uncaught TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by baerrach** [aurelia/aurelia#503]
# 🐛 Bug Report

I'm running through the tutorial https://aurelia.io/docs/tutorials/creating-a-todo-app#rendering-the-app

Up to adding in an input form.

When typing into the text box and hitting enter, Chrome 75.0.3770.100 throws an error
```
onloadwff.js:71 Uncaught TypeError: Cannot read property 'type' of undefined
    at e.setFieldValue (onloadwff.js:71)
    at HTMLFormElement.formKeydownListener (onloadwff.js:71)
```

Running under Firefox 67.0.4 works fine.

## 💁 Possible Solution

Looking at devtools the error is because `r` is undefined.

```
                    this.setFieldValue = function(t) {
                        var n = t.input
                          , r = t.field
                          , i = t.fromUser
                          , o = void 0 !== i && i;
                        r = r || e.inputMap.get(n);
                        var a = e.getFormProfile(n)
                          , s = n.value;
                        if ("password" === r.type)
```

Because `t = {input: input.au-target, fromUser: true}` ad have no `t.field`.

## 🔦 Context

Can't complete todo app tutorial on Chrome.

## 💻 Code Sample

Directly followed tutorial examples.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | ? as per downloaded tutorial file
| Language         | Javascript
| Browser          | Chrome 75.0.3770.100
| Bundler          | None
| Operating System | Window 10
| NPM/Node/Yarn    | None

**Comment by EisenbergEffect** [comment]
@baerrach This is very odd. I just ran through the tutorial myself and tested in several browsers, including Chrome, with both JS and TypeScript. Can you double check to make sure there isn't some odd extension running in Chrome? Also, can you double check that your configuration is for JavaScript and that the code you typed in is JS and not TypeScript?

FYI The error is coming from `onloadwff.js`, which isn't part of Aurelia or the loader that we distribute with this setup, as far as I know. That makes me suspicious that there's some 3rd party script running and messing with things.

**Comment by baerrach** [comment]
Great, thanks for that.
Clearly the extension doesn't have a problem in Firefox since its also loaded there.
Googling for `onloadwff.js` points to https://github.com/lastpass/lastpass-cli/issues/428
Which I suspect is the culprit.
