### ISSUE TITLE
Suggestions for the documentation structure

### ISSUE THREAD

**Issue by StevenHiggs24** [aurelia/aurelia#522]
In regards to the currently posted plan for the documentation structure, I have some suggestions, for whatever they are worth. I will point out that I am certainly not a developer or coding expert. I am looking at it from the point of view of an expert technical writer, whose job is often to decipher very technical things from a novice's perspective and translate it into words that every type of user will understand clearly and concisely, and to create a structure that will make it as easy for every type of user to find what they are looking for as quickly as possible.

When I first started reading the names of the main sections, I was already lost. I had to go back and read the description of each section thoroughly to understand the types of topics that will be included in each section and to get a better understanding of the type of audience each section is meant for. In my opinion, no one should have to read a description of a section to find out the type of content it will contain. The actual name of the section should be so clear that there is no question about the type of content that will be found inside. In my opinion, you will have new users who are reaching the documentation for the first time, wanting to learn how to use the product, or potential users who are skimming over the documentation to see if this product is what they are looking for and if it's easy to use with clear instructions, and many of these users are already going to be frustrated and lost when they see ambiguous words such as "Foundations", "Essentials", "Mastery", and "Recipes", all of which could mean a lot of different things. I'm not sure if these words are buzzwords in the community. If so, I'm sure many of the advanced users will understand what is meant and many of those types of users are probably just going to the documentation to do a search for something very specific and won't care what the sections are named. I guess it's a matter of your intended audience. In my opinion, it's always best to try to reach as many types of users as possible. The novices shouldn't be scared away with unclear words or concepts, and the experts are still going to appreciate words and instructions that are clear and can be understood by anyone. Again, I also don't think you want to make any user have to read a description to understand the names of sections (and in most cases, even the titles for topics within each section). The names and titles should be very clear.

Anyway, based on my understanding of the intended purpose for each section, my suggestions are as follows:

1. "Foundations" could be named "Getting Started". As mentioned in the description for 'Foundations', this section should contain everything a new user would need to get up and running as quickly as possible.

2. If possible, I think it would also be helpful to have a topic inside the "Getting Started" section called something like "Quick Start Guide". It would be one topic that provides all the step by step instructions that a new user must or should do to quickly get to point where they are set up and using the product to develop their app. This topic could have links to other topics within this section (or other sections), but it would be a one-stop instructional tutorial that would cover all the basics of a typical workflow for a new user to go from purchasing the product to functionally using it. However, this type of "Quick Start Guide" is usually only possible if there is a typical, linear workflow. If there are a lot of different ways to achieve this or it depends on what they want to do, maybe it's not possible. Just a suggestion in case this is possible.

3. "Essentials" could be named "Basic Customization" or "Basics for Building an App", or something similar. It would include the most common and simple types of activities.

4. "Mastery" could be named "Advanced Customization". This would make it clear that this section only includes topics for advanced users.

5. "API Reference" is good. Everyone knows what that means.

6. "Recipes" could be named "Code Examples" or something similar. It seemed that this is what is meant by "Recipes". Maybe hipster coders know what is meant by this word in this community, but it may not be clear to others. They might think: Is it a list of pre-defined scripts that can be combined to create an app? Is it a list of components or snippets that can be combined? Is it a set of instructions or tutorials? Etc. Etc. Etc.  I think something like "Code Examples" makes it very clear what they would find here.

7. "Contributing" could be named "Community Contributions". This is just a suggestion to make it very clear that this section includes information about them (the community) making contributions to the project.

8. "FAQ" should be a topic by itself or a section by itself. It could be a single topic that has a growing list of questions along with the answers/solutions. It could also be its own section and each topic within the section would be posed as a question and offer the answer/solution. Personally, I think one topic is best, but either is fine.

9. The rest of the topics within that section (currently "FAQ") could be in a section named "Other Resources" or just "Resources".

**Comment by EisenbergEffect** [comment]
This is great feedback. Let me rejig things a bit and then get you to take a second look. I'll ping you here when I've got it updated.

**Comment by EisenbergEffect** [comment]
Ok, I’ve taken most if not all of this advice in some fashion and applied it to the documents involved. I’ll close this now as resolved. @StevenHiggs24 Please take a second look and let me know what you think our next steps are. I’m planning to start writing some of these articles this week and next (hopefully). Any objection to me getting started on that?
