### ISSUE TITLE
[RFC] Handling CSS

### ISSUE THREAD

**Issue by EisenbergEffect** [aurelia/aurelia#524]
# 💬 RFC

Component and application developers need a way to provide style for what they build. While this can be handled independently of Aurelia, by simply including a stylesheet in the `index.html` page, this doesn’t always play well with componentized architectures and certainly doesn’t work well with Shadow DOM. To address these shortcomings, Aurelia’s component system should provide a mechanism for providing global/shared styles as well as per-component styles.

## Common Setups

For the purpose of this discussion, I want to present three typical ways that Aurelia would be used.

### No Shadow DOM

In this architecture, real Shadow DOM is not used in the application. Slotted composition, if required, is handled by the end user adding the [ShadyDOM Polyfill](https://github.com/webcomponents/polyfills/tree/master/packages/shadydom) with `ShadyDOM = {force: true}` to ensure consistent behavior regardless of browser.

This configuration is optimal for apps that leverage Bootstrap or other component CSS libraries which rely on a large set of global styles. However, developers may still want to build their app with per-component styles, following a naming convention. e.g. `my-component.js`, `my-component.html`, `my-component.css`. Typically, in this setup, CSS would still be handled by a CSS build step that concatenates all these styles, which the developer would then add to the head of the document. However, in a componentized world, there is often a desire to still keep individual app component styles isolated. For this, CSS Modules is the recommended solution.

#### Requirements

* Aurelia's runtime should detect slots and use shadow dom automatically, only for those scenarios. This should work with the Shady DOM polyfill.
* There should be a reasonable way to configure Webpack/Dumber/etc. for CSS Modules without breaking our AoT and conventions. 
  * The AoT/conventions system needs to know to leave the CSS files alone in this setup, as they should be handled by the CSS Modules plugin. 
  * The CSS Modules plugin needs to run earlier in the process, since it will alter the HTML to use the new class names generated through CSS Modules. 
  * CSS imports should be removed from source, if present, since the CSS Modules build will handle creating the final CSS output.
* Document the setup and tradeoffs of this configuration.

### Only Native Shadow DOM

In this architecture, 100% of components use native Shadow DOM, whether they utilize slots or not. In this situation, there isn't typically a large set of shared styles (e.g. Bootstrap). However, there are usually some, typically a `normalize.css`. As a result, there needs to be a way to get this `normalize.css` injected into every component's Shadow DOM. When importing CSS in an HTML template or via a naming convention, the CSS needs to be injected into template itself, so that it's inside the Shadow DOM, after the shared normalize.

#### Requirements

* The convention system needs a way to turn Shadow DOM on across all components, so it doesn't have to be manually configured for each component. However, manual configuration to turn it off should override the user convention.
* Custom element configuration needs to have a way to provide styles that should be injected into the template if shadow dom is on.
* The runtime needs to have a way to provide styles that should be injected into every custom element that uses Shadow DOM, at the top of the template.
* The AoT/convention system that builds HTML templates into JS modules should export any imported (or conventionally derived) CSS to the appropriate configuration setting that inputs into the custom element options.
* Document the setup and tradeoffs of this configuration.

### No Shadow DOM for App; Native Shadow DOM for "Widgets"

This is a hybrid architecture in which reusable components (widgets) use native Shadow DOM, but the application components (e.g. screens, panels, dialogs, routes) do not use Shadow DOM.

The recommended approach for this setup would be to factor out the shared components into their own library, which can be configured with the "Only Native Shadow DOM" setup and then consumed by the main app, that uses the "No Shadow DOM" setup.

> Note that Aurelia is not affected by leveraging a 3rd party library that is built out of pure W3C components and Shadow DOM already. However, if the 3rd party library expects styles to be scoped by Shadow DOM, the developer may also need to add the [Shady CSS Polyfill](https://github.com/webcomponents/polyfills/tree/master/packages/shadycss) if they have configured their app with the "No Shadow DOM" setup.

#### Requirements

* Document the setup and tradeoffs of this configuration.
* Provide a skeleton for a multi-project setup which contains a component project and an app project that leverages it.

## Single File Components

For single file components, we want to leverage the upcoming [HTML Modules specification](https://github.com/w3c/webcomponents/issues/645). If a developer is using a single-file component, we want to apply all the same behaviors as above. The only difference is that rather than HTML, CSS, and JS being in separate files, they are in a single file. This is straight forward for native Shadow DOM scenarios, but may not be as easy when someone wants no Shadow DOM in combination with CSS Modules. For the first pass we may want to require ShadowDOM for single-file components.

## 🔦 Context

All of my current Aurelia vNext projects are built using "Only Native Shadow DOM". To work around the lack of runtime support, I have created a custom decorator called `component` which wraps the `customElement` decorator and does the following:

* Turns Shadow DOM on.
* Parse the HTML template and injects a `style` tag with the contents of my `normalize.css` as the beginning of the template.

Additionally, all per-component styles are inlined in the HTML template with a `style` element, rather than living in separate files.

Unfortunately, all of this means that I will not be able leverage conventions on any component, and must add decorators to everything. While I could separate out my CSS into another file and augment my `component` decorator to do additional template manipulation at runtime, this is less efficient and further deviates my basic component architecture from the supported scenarios. 

While it's possible to use CSS Modules and Native Shadow DOM in Aurelia vCurrent, it's not necessarily easy. At present, it's also not particularly easy with vNext. This has presented a stumbling block for people in the past and we'd like vNext to ship with this solved from the beginning, including explicit documentation and guidance for developers.

## Technical Approach

I'll try to lay out a way to achieve the above with mostly a couple of small additions to the core codebase and one or two minor modifications in key areas. To start with, we'll lay out some code that a developer might want to write with the following basic custom element:

#### my-element.ts
```TypeScript
export class MyElement {
  public message: string  = 'Hello World';
}
```

#### my-element.css
```CSS
.message {
  color: red;
}
```

#### my-element.html
```HTML
<div class="message">
  ${message}
</div>
```

Ultimately, we want all three of these pieces to come together so that we can use `<my-element>` in HTML, rendering with the proper template and styled correctly, but without the styles affecting other HTML. We'd like to be able to write our code the same way (as above), regardless of whether we are using Shadow DOM or CSS Modules. To enable that, we need to add some core infrastructure.

### Core Infrastructure

The main idea I have to enable this is to treat CSS like a dependency of the custom element. Since the DI doesn't know what to do with CSS and compiling of things like CSS Modules is the job of other libraries, we need a sort of interpreter, which would know how to register the correct styles service in the DI container for an element, allowing it to provide the appropriate CSS behavior.

Below is a new type of DI registration, which I've named `interpret`.

```TypeScript
class Registration {
  public static interpret(format: any, ...data: any[]): IRegistry {
    return {
      register(container: IContainer): void {
        const resolver = container.getResolver<IRegistry>(format);

        if (resolver !== null) {
          let interpreter: IRegistry | null =  null;

          if (resolver.getFactory) {
            const factory = resolver.getFactory(container);

            if (factory !== null) {
              interpreter = factory.construct(container, data); // important
            }
          } else {
            interpreter = resolver.resolve(container, container);
          }

          if (interpreter !== null) {
            interpreter.register(container); // important
          }
        }
      }
    };
  }
}
```

The `interpret` registration is, more or less, a registration that instantiates another registration from the DI container based on a format key, passing to the constructor the data that is to be interpreted. The resolved registration can then register within the container whatever services are needed, based on its interpretation of the data.

With this new registration, we can now ask the DI container to "interpret" CSS with the following code `Registration.interpret('.css', styles)`. We can write a helper function for this as follows:

```TypeScript
function styles(...styles: any[]) {
  return Registration.interpret('.css', styles);
}
```

Without any conventions and AoT in place, here's how we could define our custom element from above:

#### my-element.ts
```TypeScript
import css from './my-element.css';
import template from './my-element.html';

@customElement({
  name: 'my-element',
  template,
  dependencies: [styles(css)]
})
export class MyElement {
  public message: string  = 'Hello World';
}
```

At runtime, the `styles` helper allows the DI to resolve a service that knows how to properly handle the CSS for this element. What that service is, depends on whether you have configured your app for Shadow DOM or CSS Modules. More details below on how each of those would work.

### View Compilation and Conventions

With view compilation and conventions, let's see how the HTML file from above would be turned into JavaScript:

```TypeScript
import css from './my-element.css';

export const name = 'my-element';
export const template = '<div class="message">${message}</div>'; //TODO: AoT compile this.
export const dependencies = [
  Registration.interpret('.css', css),
];
export default template;
```

AoT need not know how CSS will be handled. That can be left up to existing CSS pre/post processors. It only needs to turn the CSS into a dependency using the `interpret` registration with the file extension as key. Once the above is generated, AoT can insert the decorator as follows:

#### my-element.ts

```TypeScript
import * as html from './my-element.html';

@customElement(html)
export class MyElement {
  public message: string  = 'Hello World';
}
```

Interestingly, AoT can use this technique to handle any file extension it doesn't natively handle:

#### my-other-element.html

```HTML
<import from="./my-other-element.css">
<import from="./my-element">
<import from="./my-prose.md">

<div class="some-class">
  <my-element></my-element>
  <my-prose></my-prose>
</div>
```

It can be compiled to this JavaScript:

```TypeScript
import css from './my-other-element.css';
import md from './my-prose.md';

export const name = 'my-other-element';
export const template = '...html here...';
export const dependencies = [
  Registration.interpret('.css', css),
  Registration.interpret('.md', md)
];
export default template;
```

At runtime, an interpreter can consume the markdown content and register a custom element with the container capable of rendering that Markdown. This establishes a simple pattern for view compilation, allowing it to handle any file extension in a simple and consistent way.

### CSS Modules Interpreter

Let's have a look at how interpreters would work. Here is some code for a basic CSS Modules interpreter:

```TypeScript
export class CSSModulesInterpreter {
  constructor(private styles: any[]) {}

  public static register(container: IContainer) {
    container.register(Registration.transient('.css', CSSModulesInterpreter));
  }

  public register(container: Register) {
    const styles = this.styles;

    @customAttribute('class')
    class ClassCustomAttribute {
      @bindable public value;

      constructor(private element: HTMLElement) {}

      bound() {
        valueChanged();
      }

      public valueChanged() {
        // parse class values
        // lookup in styles map provided by CSS Modules build
        // update element's actual classes
      }
    }

    container.register(ClassCustomAttribute);
  }
}
```

To enable CSS Modules for your app, you would only need to register the interpreter with the application container as follows:

```TypeScript
container.register(CSSModulesInterpreter);
```

The interpreter registers itself with the ".css" key. When an interpreter registration resolves it, and its register instance method is called (per the implementation of the interpreter registration explained earlier), the interpreter creates a custom attribute and registers that with the custom element's container. This custom attribute replaces the default `class` attribute with one that can take a class string and map it to the obfuscated values, using the JS object provided by the CSS Modules post-processor.

> **Note:** So far, no changes to Aurelia are required. We're just adding new stuff and some conventions. CSS Modules can be achieved today in vNext with the above techniques, without altering the core. However, the same cannot be said for Shadow DOM CSS.

### Shadow DOM Interpreter

To enable Shadow DOM, we use a different interpreter:

```TypeScript
export class ShadowDOMInterpreter {
  public static inject = [optional(ShadowDOMStyleManager))];

  public static register(container: IContainer) {
    container.register(Registration.transient('.css', ShadowDOMInterpreter));
  }

  constructor(private parent: ShadowDOMStyleManager, private styles: any[]) {}

  public register(container: IContainer) {
    container.register(
      Registration.instance(
        ShadowDOMStyleManager, 
        new ShadowDOMStyleManager(this.styles, this.parent)
      )
    );
  }
}
```

To enable Shadow DOM CSS for your app, you would only need to register the interpreter with the application container as follows:

```TypeScript
container.register(ShadowDOMInterpreter);
```

This interpreter provides a ShadowDOMStyleManager to the element. Let's have a look at that code:

```TypeScript
export class ShadowDOMStyleManager {
  constructor(private styles[], private parent: ShadowDOMStyleManager = null) {}

  public applyTo(shadowRoot) {
    if (this.parent !== null) {
      this.parent.applyTo();
    }

    // Use constructable style sheets on the shadow root if supported
    // https://wicg.github.io/construct-stylesheets/
    // https://developers.google.com/web/updates/2019/02/constructable-stylesheets
    // Otherwise, add styles shadow root as first nodes
  }
}
```

A style manager has an array of styles that it applies to a shadow root. It uses different techniques for this depending on what the browser supports. Additionally, the style manager can have a parent manager, allowing for certain styles to be set up at the application level and shared across all elements. To do this, you would configure your app like this:

```TypeScript
import normalize from './normalize.css';

container.register(ShadowDOMInterpreter);
container.register(
  Registration.instance(
    ShadowDOMStyleManager,
    new ShadowDOMStyleManager([normalize])
  )
);
```

> **Note:** We can create a nice helper method for this so configuration is simpler.

Above I mentioned that we can't make this work today. The reason for this is that we need to make a single modification to the ShadowDOMProjector, so that it resolves the ShadowDOMStyleManager and applies it to its root. Something like this:

```TypeScript
export class ShadowDOMProjector {
  public project(nodes: INodeSequence<Node>): void {
    nodes.appendTo(this.shadowRoot);
    container.get(ShadowDOMStyleManager).applyTo(this.shadowRoot); // new code here
  }
}
```

> **Note:** While it looks like we only need to modify one line of code in Aurelia, there's a little bit more work involved. Currently, the projector does not have access to the element's container (renderContext). However, the controller which creates the projector has a reference to the container. We would need to update this code to pass the container (renderContext) through to the the projector. With these two changes, we'll have automatic shadow dom styles and shared shadow dom styles support.

### Wrapping Up

I've got a pretty critical need to get this working for Shadow DOM styles soon and I don't think we should go to alpha without both Shadow DOM and CSS Modules solutions in place. Otherwise, people will hit a serious blocker around styles pretty quickly. I'd love to start putting together a PR to make this happen. Please take some time to read through this and let me know if it all makes sense before I get working.

**Comment by HamedFathi** [comment]
@EisenbergEffect  Thank you so much for all your efforts. 

I'm not sure this question is relevant! 
Is it possible to use `CSS-in-JS` like [emotion](https://github.com/emotion-js/emotion) or [aphrodite](https://github.com/Khan/aphrodite) with this RFC?
In some scenarios using `CSS-in-JS` helps us to be more dynamic, especially when you support JSX in vNext.

**Comment by EisenbergEffect** [comment]
@HamedFathi I think that's a good question, in general. However, I don't think this proposal would either help or harm that goal. In fact, I think you could accomplish this today in both vCurrent and vNext through the use of some custom attribute, as one way. In your JS, simply import the CS in JS library and set up your CSS object as a property of your view-model. Then, in HTML, use a custom attribute to bind to property of that model. The custom attribute would take the CSs object and apply it to the element's styles. That's one way you could do it even without JSX today, that's completely compatible with tomorrow's Aurelia as well.

**Comment by akircher** [comment]
I agree with all these points but am having trouble wrapping my head around what the code would/could look like with the various options especially with JIT vs AOT.  If it's not too early, can we get some pseudo code options like we got in https://github.com/aurelia/aurelia/issues/116?

**Comment by EisenbergEffect** [comment]
@akircher Certainly! I've got a technical proposal to add to this soon. I started working out the details today. I need to write up some explanation and then I'll post it here.

**Comment by EisenbergEffect** [comment]
Ok, I’ve added a technical approach to the above description. @fkleuver I finally remembered what I had in mind for the old “interpret” registration that we removed 🤣

**Comment by bigopon** [comment]
I think for this, we need to have consfructable stylesheet in the picture as well

**Comment by EisenbergEffect** [comment]
@bigopon See my note inside the `ShadowDOMStyleManager` class. We can use it there, if it’s present.

**Comment by 3cp** [comment]
There is some complication around `import css from './my-other-element.css';`.

This import is not standard js, it depends on bundler configuration. For example, users normally use style-loader in webpack which will automatically inject that css onto html head.

We want to skip style-loader for all the css import in our html-to-js code, while still allow user to use style-loader on other files (for instance, some npm packages uses `import 'a.css';` to load styles).

Ideally you would also want to allow user to write `import 'a.css';` in their own js/ts files. It's possible, but the config is very sensitive and not easy to understand.

```
{
  test: /\.css$/i,
  issuer: [{ not: [{ test: /\.html$/i }] }],
  use: ['style-loader', 'css-loader']
},
{
  test: /\.css$/i,
  issuer: [{ test: /\.html$/i }],
  use: ['css-loader']
},
```

**Comment by EisenbergEffect** [comment]
I’d like to get this in as soon as possible. Does anyone have a reason not to proceed with the plan above?

**Comment by fkleuver** [comment]
Let's go so we can start writing tests. We can deep dive on all the edge cases via integration / e2e tests.

**Comment by 3cp** [comment]
Following on my previous question on the bundler sensitivity on `import css from './my-other-element.css';`.

I am thinking about two possible ways to bypass bundler.
1. translate `<import from="./foo.css">` to an inline `<style>inlined css content</style>` within `<template>` tag.
2. only apply shadow style for conventional `foo.html` `foo.css`(or less/sass/scss/styl) pair. **This is a new convention, vCurrent doesn't have it.** Put the content of `foo.css` to an inline `<style>inlined css content</style>` within `<template>` tag. **Leave `<import from="./a.css">` to bundler to handle, which by default loads the css globally.**

Inline `<style>` tag will leave the shadow css to browser to handle nativelly. We would need to replace (preprocess) some relative path `url(a.png)` in the css content just like vCurrent did.

**Comment by EisenbergEffect** [comment]
@3cp Did you have a chance to read the new section I added on to the original post titled “Technical Approach”? I propose that we always leave the actual CSS to the bundler to handle. We just take the imported module and pass it to a special function that allows the runtime to choose to respond to that based on the configuration at runtime, if and only if it needs to.

We don’t want to do any inlining of styles as that will actually harm shadow DOM scenarios. The reason for this is the new adopted style sheets standard which has already shipped in all Chromium-based browsers. This feature allows constructing and sharing of styles across shadow dom roots. Placing the styles in a style tag will subvert that, resulting in greater memory consumption and degraded performance. Rather, at runtime we need to detect whether the browser supports adopted style sheets and use them if present, otherwise inject the styles into the template. It can’t be done ahead of time.

To reiterate, my proposal is that we just let the bundler do whatever it wants to do; whatever the end user has configured it to do. We just compile all CSS imports from HTML templates and wrap them in the `Registration.interpret` wrapper described above. We can add the same name file convention on top of this, but that could be an option that users turn on, for example.

**Comment by 3cp** [comment]
> we just let the bundler do whatever it wants to do;

@EisenbergEffect that was my raised concern.

Most bundlers will do the same thing, inject css into html head, for both
```js
import './my-other-element.css';
// bundler doesn't cater whether use exported value
import css from './my-other-element.css';
```

`import css from './my-other-element.css';` doesn't give you what you want without side effect.

To skip bundler default behaviour, and **only load text from css module**, you have to use bundler specific syntax, which is not standard ES code.

webpack, this will bypass webpack.config on css file.
```js
import css from 'raw-loader!./my-other-element.css';
```
requirejs or dumber
```js
import css from 'text!./my-other-element.css';
```

parcel: no idea, might be impossible.
browserify: no syntax available. Have to use `stringify` transform conditionally in build script.
fuse-box: no idea.

**Comment by EisenbergEffect** [comment]
Then I think we may want to allow the convention system to be configured so that it can treat the css as text and applies a bundler-specific loader when creating the import statement. We can't just cram it into a style tag and add it to the template though. That's a bad practice when you have adopted style sheets available at runtime.

**Comment by EisenbergEffect** [comment]
And I'm ok if this only works for webpack, dumber and require.js. We don't need to support the conventions system for the other options if they don't have the necessary apparatus.

**Comment by 3cp** [comment]
Great, your approach is what I preferred. I guess I need to wait for the runtime implementation before upgrade conventions code?

**Comment by EisenbergEffect** [comment]
Yep. No action needed from you yet @3cp. Let me get the basic stuff I outlined above in place first. Then we can follow that up with the convention lib update. I'll let you know when it's ready. I imagine it's going to be another 7-10 days before I can get it implemented, tested and merged, based on my current todos.

**Comment by EisenbergEffect** [comment]
Closing as implemented and merged to master.
