### ISSUE TITLE
replaceable has some unintended breaking change

### ISSUE THREAD

**Issue by 3cp** [aurelia/aurelia#565]
# 🐛 Bug Report

Originated from https://discourse.aurelia.io/t/why-aurelia-struggles-to-gain-popularity/1749/132?u=huochunpeng 

my-custom-element.html

```html
<template>
  <table>
    <thead></thead>
    <tbody replaceable part="content"></tbody>
  </table>
</template>
```

## 🤔 Expected Behavior

The app.html should work in au2.

app.html
```html
<my-custom-element>
  <tbody replace-part="content">
    <tr repeat.for="...">...</tr>
  </tbody>
</my-custom-element>
```

Plus following variation should also work in au2, as this is what's working in au1.
```html
<my-custom-element>
  <template replace-part="content">
  <tbody>
    <tr repeat.for="...">...</tr>
  </tbody>
  </template>
</my-custom-element>
```

## 😯 Current Behavior

The app.html didn't work as expected in au2.

It doesn't work in au1 which is expected.

For au1 to work:
```html
<my-custom-element>
  <template replace-part="content">
    <tbody>
      <tr repeat.for="...">...</tr>
    </tbody>
  </template>
</my-custom-element>
```

But the above working au1 code **didn't work in au2**. It should.

Somehow an extra `table` wrapper can fix usage in au2. The wrapper is considered unnecessary ideally.
```html
<my-custom-element>
  <table>
    <tbody replace-part="content">
      <tr repeat.for="...">...</tr>
    </tbody>
  </table>
</my-custom-element>
```
## 💁 Possible Solution

As @fkleuver said, this would be due to au2 replaceable try to mutate `<tbody replaceable-part="content">...` into `<template replace-part="content"><tbody>...`, the browser somehow prevents `<tbody>` to be created outside of `<table>`.

It's a myth why the direct `<template replace-part="content"><tbody>...` (which requires no mutation) didn't work.

## 🌍 Your Environment

**Comment by Sayan751** [comment]
@3cp Can you please verify this with `au-slot`? I think both of your templates should work with `au-slot`. If similar problem does not exist there this can be closed.

**Comment by 3cp** [comment]
Will do.

**Comment by 3cp** [comment]
I tried following, it did not work. I think `<tbody><au-slot></au-slot></tbody>` is not working because of DOM. How to define a containerless slot in the tbody?

```html
<template>
  <table>
    <thead>
      <tr>
        <th>Test</th>
      </tr>
    </thead>
    <tbody>
      <au-slot></au-slot>
    </tbody>
  </table>
</template>
```

```
<import from="./my-custom-element.html"></import>
<my-custom-element>
  <tbody au-slot>
    <tr>
      <td>${a}</td>
    </tr>
  </tbody>
</my-custom-element>
```

**Comment by Sayan751** [comment]
@3cp You are right. I overlooked this use-case; my bad. To track this problem, I have opened #1007. I am closing this one in favor of that. We can continue the discussion there.

**Comment by 3cp** [comment]
Is the "replaceable" feature going to stay in au2? If so, this is still an open issue.

**Comment by fkleuver** [comment]
It's replaced by `au-slot`, so this bug would need to be fixed in `au-slot`. `replaceable` no longer exists.

**Comment by bigopon** [comment]
Well, it's replaceable after alla
