### ISSUE TITLE
Relative links, scopes and viewports

### ISSUE THREAD

**Issue by jwx** [aurelia/aurelia#576]
# 💬 RFC

Looking for sounding boards/opinions to something long and not so structured: how relative links find the right scope to search for viewports. It'll help if you understand how the new router works and approve of viewports within viewports.

## 🔦 Context

In a scoped viewport (which is to become the new default) all relative links/hrefs are looking (deeply) for child viewports within the element of the anchor. So

app
```html
<a href="a">A</a>
<au-viewport name="top-viewport"></au-viewport>
```
a
```html
<a href="b">B</a>
<au-viewport name="a-viewport"></au-viewport>
```

The `b` link will load in the child viewport `a-viewport`. Now, if the link had been 
```html
<a href="/b">B</a>
```
it would've loaded in `top-viewport`.

The questions arise when another level is added to this: links in `b`. Let's say 

b
```html
<a href="c">C</a>
<a href="/c">C</a>
<au-viewport name="b-viewport"></au-viewport>
```
The first `c` would be loaded in the viewport `b-viewport`, but the second `c` would be loaded in `top-viewport`. If I wanted to load it in the same viewport as `b`, `a-viewport`, and replace the b (which I think will be a common scenario) I would currently have to provide the full "component path"

```html
<a href="/a/c">This would replace b with c</a>
```

But it feels a bit cumbersome since the `c` link now needs to know about its parent(s). 

To clarify: the (**_interim_**) rule here is that if links are relative, they address viewports within the current scope. And since the scope starts with, but _excludes_, the viewport the link is in, the link can't address the viewport it's in.

There's two "obvious" solutions to this: the first one is to introduce scope traversal syntax (..) into the link and the other is to make the enclosing viewport the first viewport in the scope. So either

app
```html
<a href="a">A, nothing changes here since it's the top</a>
<au-viewport name="top-viewport"></au-viewport>
```
a
```html
<a href="b">B, in a-viewport</a>
<a href="/b">B, from top viewport, replacing a</a>
<a href="../b">B, one step up, that is in top-viewport, replacing a</a>
<au-viewport name="a-viewport"></au-viewport>
```
b
```html
<a href="c">C, in b-viewport</a>
<a href="/c">C, in top viewport, replacing a</a>
<a href="../c">C, one step up, that is in a-viewport, replacing b</a>
<au-viewport name="b-viewport"></au-viewport>
```

OR

app
```html
<a href="a">A, nothing changes here</a>
<au-viewport name="top-viewport"></au-viewport>
```
a
```html
<a href="b">B, in same viewport, replacing a</a>
<a href="/b">B, from top viewport, replacing a</a>
<a href="a/b">B, in first child viewport, that is in a-viewport</a>
<au-viewport name="a-viewport"></au-viewport>
```
b
```html
<a href="b/c">C, in b-viewport</a>
<a href="/c">C, in top viewport, replacing a</a>
<a href="c">C, in same viewport, that is in a-viewport, replacing b</a>
<au-viewport name="b-viewport"></au-viewport>
```

And of course I can do a combination of those two as well: move start of resolve one step up (alternative 2) but then also support further traversal upwards from there (alternative 1).

So if you wanted to link into a child viewport and into the same viewport, would you prefer
```html
<a href="another-component">Loaded in child viewport</a>
<a href="../another-component">Loaded in the same viewport, replacing</a>
```
or
```html
<a href="this-component/another-component">Loaded in child viewport</a>
<a href="another-component">Loaded in the same viewport, replacing</a>
```
?

An obvious shortcut for 
```html
<a href="this-component/another-component">Loaded in child viewport</a>
```
would be 
```html
<a href="./another-component">Loaded in child viewport</a>
```

I've got a preference, but would like some thoughts and opinions before presenting it.

**Note** that regardless of solution there will be no `..` or similar in the browser's location url. The url will always be full path so that deep links work.

**Comment by Vheissu** [comment]
@jwx Is this issue still relevant or can it be closed?

**Comment by Sayan751** [comment]
ping @jwx
