### ISSUE TITLE
Manipulate the binding context in any HTML behavior [RFC]

### ISSUE THREAD

**Issue by davismj** [aurelia/aurelia#577]
# 💬 RFC

Any custom element or attribute may have special properties or methods relative to the behavior. A developer should be able to add these properties and methods in the bind() method.

## 🔦 Context

Most recently I built a validation component `<da-rulez>`.

```html
<da-rulez valid.bind="$rules.required(prop)">
  Ya need props, yo!
</da-rulez>
```

In v1 we could only solve this case with view engine hooks that add `$rules` to the binding context. What I would have preferred to do is scope it to the `<da-rulez>` component in the bind() method.

```ts
import * as $rules from 'lib/rules';

export class DaRulezCustomElement
  bind(context: any, overrideContext: any) {
    Object.assign(overrideContext, { $rules });
  }
}
```

## 💻 Examples

This would have strong use cases internally as well. Consider `route-href`: With this feature, it could be written as:

`<a route-href.bind="$generate('my-route', { id: id })">`.

**Comment by EisenbergEffect** [comment]
I think this is already covered in vNext. There's an explicit scope property you can get access to through the controller. @fkleuver Please correct me if I'm wrong.

**Comment by EisenbergEffect** [comment]
Oh, actually, I may have misunderstood this. Hmm. If you want the route-href to be able to add a $generate function for use in its bindings....actually, I think it would just add it to the overrideContext on the scope of its controller, or maybe the parent scope? @fkleuver will know.

**Comment by fkleuver** [comment]
You can do this in v2 during `binding` as that's roughly the equivalent (timing wise) as `beforeBind` hook in v1.

I'm not really sure why you're using `Object.assign` with an inline object as the source though.

This:
```ts
Object.assign(overrideContext, { $rules });
```

Is a very inefficient detour for this:
```ts
overrideContext.$rules = $rules;
```

Anyway, you would do that during `binding`
```ts
import * as $rules from 'lib/rules';

export class DaRulezCustomElement
  binding() {
    this.$controller.scope.overrideContext.$rules = $rules;
  }
}
```

Then still. I don't see any reason to use the overrideContext here. That's more of a thing for framework-provided properties or plugins so as to avoid potential conflicts with user properties.

If you need something in your binding context, just assign it to `this`:
```ts
import * as $rules from 'lib/rules';

export class DaRulezCustomElement
  binding() {
    this.$rules = $rules;
  }
}
```

`this` *is* the binding context;
```ts
export class DaRulezCustomElement
  binding() {
    this === this.$controller.scope.bindingContext; // true
  }
}
```
It couldn't be more simple, I think.
