### ISSUE TITLE
Shadow DOM by Convention

### ISSUE THREAD

**Issue by EisenbergEffect** [aurelia/aurelia#578]
# 🙋 Feature Request

When using the new conventions plugin, we'd like to be able to specify for it to use a particular shadow DOM configuration for elements.

## 🤔 Expected Behavior

Turning on shadow dom in the convention settings results in shadow dom config being generated properly for each compiled view.

## 😯 Current Behavior

There's no way to make shadow dom the default today.

## 💁 Possible Solution

Enhance the conventions module so that it can take a configuration object that sets up the conventions for the project it is being used to build. The first convention could be `shadowOptions`. Here's how that is defined int he framework:

```
shadowOptions?: { mode: 'open' | 'closed' } | null,
```

**Comment by EisenbergEffect** [comment]
@3cp I created this based on our conversation the other day. I've got a new styles PR to add support for shadow dom styles. I'd like to try to get this feature in close in timing to the styles support for the feature I'm working on.

If you've got questions, ask away! 😄

**Comment by 3cp** [comment]
Question, to use shadow dom, is it a simple option on tooling? or do we require user to turn it on in `src/main.js` too?

Ideally, we should give user a single place, instead of two, to turn this feature on.

**Comment by EisenbergEffect** [comment]
Currently, there's no framework-level setting to turn it on everywhere. I thought about that, but I felt that it could be a bad idea and negatively affect library authors. For example, if you are using a library with elements in it that don't use shadow dom and then you turn it on in your app, you just broke their elements. So, I'm thinking it should be a build configuration option and only affect the HTML in your app.

For libraries, I'm thinking they will have a build that applies their own conventions, which happens before they distribute.

Does that make sense?

**Comment by 3cp** [comment]
That works for me.

For clarify, can you review/fix the expected results for 2) shadow dom open and 3) shadow dom closed?

`foo.html`
```html
<import from="./foo.css">
<import from="./bar">
<template>
  <bar></bar>
</template>
```
1. no shadow dom.
```js
import './foo.css';
import * as d1 from './bar';
export const name = 'foo';
export const template = '<template>\n  <bar></bar>\n</template>\n';
export default template;
export const dependencies = [d1];
let _e;
export function getHTMLOnlyElement() {
  if (!_e) {
    _e = CustomElement.define({ name, template, dependencies });
  }
  return _e;
}
```
2. shadow dom open
```js
// first, show me where to import Registration

// for webpack
import d0 from 'raw-loader!./foo.css';
// or for dumber
// import d0 from 'text!./foo.css';
import * as d1 from './bar';
export const name = 'foo';
export const template = '<template>\n  <bar></bar>\n</template>\n';
export default template;
export const dependencies = [
  Registration.interpret('.css', d0),
  d1
];
let _e;
export function getHTMLOnlyElement() {
  if (!_e) {
    _e = CustomElement.define({ name, template, dependencies });
  }
  return _e;
}
```
3. shadow dom closed, show me the API to pass through open/closed option.

**Comment by EisenbergEffect** [comment]
The CSS importing isn't related to the shadow dom option. I'll write another bit up for that once my runtime PR is merged. Basically, you need to export their options. So, if they configure things something like this in your plugin:

```
{
  defaultShadowOptions: { mode: 'open' } 
}
```

Then you need to create a module like this:

```
import * as d1 from './bar';
export const name = 'foo';
export const template = '<template>\n  <bar></bar>\n</template>\n';
export default template;
export const dependencies = [d1];
export const shadowOptions = { mode: 'open' } ;
let _e;
export function getHTMLOnlyElement() {
  if (!_e) {
    _e = CustomElement.define({ name, template, dependencies, shadowOptions }); // don't forget this
  }
  return _e;
}
```

**Comment by EisenbergEffect** [comment]
For the CSS configuration, once my PR is merged, you would have this:

```
import { Registration } from '@aurelia/kernel';
import d0 from 'raw-loader!./foo.css';
// or for dumber
// import d0 from 'text!./foo.css';
import * as d1 from './bar';
export const name = 'foo';
export const template = '<template>\n  <bar></bar>\n</template>\n';
export default template;
export const shadowOptions = { mode: 'open' } ;
export const dependencies = [
  Registration.defer('.css', d0),
  d1
];
let _e;
export function getHTMLOnlyElement() {
  if (!_e) {
    _e = CustomElement.define({ name, template, dependencies, shadowOptions });
  }
  return _e;
}
```

Note: `Registration.defer` won't exist until my PR is merged.

**Comment by 3cp** [comment]
name it defaultShadowOptions or defaultShadowDOMOption?

**Comment by EisenbergEffect** [comment]
Let's go with `defaultShadowOptions` since the template property is `shadowOptions`.

**Comment by 3cp** [comment]
Is that any reason for repeated `{ mode: 'open' | 'closed' }` in `packages/runtime/src/definitions.ts`? Should not we have an interface type for shadowOptions?

BTW in the same file, I don't understand what's the issue for TS compiler, it should be smart enough in this if-condition.
```js
if (ctor.shadowOptions) {
  def.shadowOptions = ctor.shadowOptions as unknown as { mode: 'open' | 'closed' };
}
```

**Comment by EisenbergEffect** [comment]
Pinging @fkleuver as he might know whether there's a reason or if this is something we just need to clean up.

**Comment by fkleuver** [comment]
Didn't feel necessary for such a simple single-property type that never changes. But there are no particular reasons for the way things are wrt the shadow options on the definitions, so feel free to clean/fixup at your discretion

**Comment by 3cp** [comment]
I see. Anyway I am not going to change the TS typing definition which is an area I am not familiar with.

**Comment by 3cp** [comment]
@EisenbergEffect I hit a runtime error with an app in either open or closed mode. I tried Chrome, Safari and Firefox.

Chrome:
`Uncaught DOMException: Failed to execute 'attachShadow' on 'Element': This element does not support attachShadow`

Safari and Firefox
`NotSupportedError: Operation is not supported`

On this line:

https://github.com/aurelia/aurelia/blob/a1aca9ff1a0c05d9201c9ee2dc5162f8b1036e64/packages/runtime-html/src/projectors.ts#L73

**Comment by EisenbergEffect** [comment]
My guess is that your element name needs a hyphen. Only certain built-in elements support shadow dom and custom elements must have a hyphen in their name to support shadow dom. (Probably a good opportunity for a compiler warning.) That's my guess based on the error without any other information.

**Comment by 3cp** [comment]
I don't understand. I tried `the-app` instead of `app`, but it doesn't help.

**Comment by 3cp** [comment]
Sorry, it worked. I forgot to modify index.ejs for the host element.

**Comment by 3cp** [comment]
Seriously there will be lots of elements in user app without a dash in the name, what should we do?

**Comment by EisenbergEffect** [comment]
There's no way around it, as it's required by the spec. It hasn't caused a real practical issue in any of my apps though. I usually recommend that people adopt an app or org specific prefix for their widgets. Many screen/page components end up being two words naturally as well.

**Comment by EisenbergEffect** [comment]
We could also have a setting that auto-prefixes things for people. Just a thought.

**Comment by 3cp** [comment]
Auto-prefixes could surprise user in css selector.

For now I suggest: if element name is one word, turn off shadowdom. If user wanted shadowdom, print a warning at compile time, also print a warning at runtime as well.

**Comment by EisenbergEffect** [comment]
That sounds good to me.
