### ISSUE TITLE
[RFC] more metadata in html template

### ISSUE THREAD

**Issue by 3cp** [aurelia/aurelia#585]
# 💬 RFC

Aurelia 2 has new import/require tags above the opening `<template>` tag. It looks like we can extend this practice to cover more metadata.

## 🔦 Context

This RFC is related to #116, #465. While keeping the old v1 syntax, we can have a new recommended syntax to put all metadata above the opening `<template>` tag for better readability and deliver a visual clue that these metadata are preprocessed in Aurelia 2, comparing to runtime processing in Aurelia v1.

## 💻 Examples

In v1, we have:

```html
<template use-shadow-dom="open" bindable="firstName, lastName" containerless>
  <require from="./foo.css"></require>
  <require from="./bar"></require>
</template>
```

In v2, **the above continues to work** (but preprocessed). This RFC suggests a new recommended syntax.

```html
<use-shadow-dom mode="open">
<containerless>
<bindable name="firstName" mode="one-way"> <!-- TBD mode="oneWay" or mode="one-way"  -->
<bindable name="lastName">
<import from="./foo.css">
<import from="./bar">

<template>
</template>
```

Notes:
1. The metadata nodes need no closing tag (like `</import>`).
  * They are above the opening `<template>` tag, they are all preprocessed before browser native html parser sees html template. This is very different from Aurelia v1 where all html string are processed at runtime by browser native html parser.
2. `<import>` and `<require>` tag are already implemented.
3. `use-shadow-dom` is for #465.
4. `bindable` I am not quite sure. Is it still processed at runtime in Aurelia 2? Should we move it to preprocessing?

**Comment by eriklieben** [comment]
The above would also open up the possibility to enable you to set the other options for ```bindable``` right, which currently isn't possible in v1. Not sure if that is useful/makes sense for all the options, but seems like a logical step.

```typescript
@bindable({
    name:'myProperty',
    attribute:'my-property',
    changeHandler:'myPropertyChanged',
    defaultBindingMode: bindingMode.oneWay,
    defaultValue: undefined
  }) 
```
If this is how we would use our html only component:
```html
<custom-welcome firstname.bind="firstName"></custom-welcome>
```
Then we could potentially allow you to do:
```html
<bindable name="firstname" default-binding-mode="one-time" default-value="you">
<template>
  <p>Hey, ${firstname}!</p>
</template>
```
Looks like it's easier to read than:
```html
<template bindable="firstname">
  <p>Hey, ${firstname ? firstname  : 'you' & oneTime }!</p>
</template>
```
but I am not sure if that's still the case with:
```html
<import from="./foo-custom.css">
<import from="./bar-custom.css">
<import from="./foo">
<import from="./bar">

<bindable name="firstname" default-binding-mode="one-time" default-value="you">
<bindable name="lastname" default-binding-mode="one-time" default-value="not provided">
<bindable name="occupation" default-binding-mode="one-time" default-value="unknown">
<bindable name="age" default-binding-mode="one-time" default-value="unknown">
<bindable name="approved">

<template>
  <p>Hey, ${firstname}!</p>
  <p>We will store the following information from the information you just entered in our system:</p>
  <ul>
    <li>lastname: ${lastname}</li>
    <li>age: ${age}</li>
    <li>occupation: ${occupation}</li>
  </ul>
   <label><input type="checkbox" checked.bind="approved" >
    Yes, I allow you to store this information about me</label>
</template>
```

---
It's currently not possible to use a ```<template>``` tag inside another ```<template>``` tag that actually behaves as custom element right (with for example bindable on it)? Because that could potentially give issues.

So you could do something like (which isn't possible as far as I am aware):

```html
<template>

  <template name="name-card" bindable="name">
    <p>
      <img src="${name}.jpg">
      ${name}
    </p>
  </template>

  <h1>Our departments</h1>
  <section repeat.for="department of departments">
    <h2>${department.name}</h2>
    <name-card repeat.for="name of department.employees" name.bind="name"></name-card>
  </section>

  <h1>Our management team</h1>
  <template repeat.for="department of departments | filterType:'manager'">
    <name-card repeat.for="name of department.employees" name.bind="name"></name-card>
  </template>

</template>
```
Not sure why you would want that, assume if you want something that is reusable but only in a given view or something. Feels more logical to create a separate custom element of the ```name-card``` with its own files and import/require that and don't import it elsewhere.

You can only use it inside the main template tag as a containerless wrapper as far as I know, right? Which has no impact at all at the proposed structure/ practice.

```html
<template>
  <template if.bind="foo">
    <p>lorem ipsum</p>
  </template>
</template>
```

```html
<template>
  <template repeat.for="item of items">
    <p>lorem ipsum ${item}</p>
  </template>
</template>
```

**Comment by bigopon** [comment]
For inlined template dependencies, I remember we have discussed it a several times in the past.
For the new way to define bindable, it looks a lot nicer when taking all of those configs into account 👍 

 cc @jods4.

**Comment by bigopon** [comment]
for:
```html
<import from="./foo-custom.css">
<import from="./special-offers-custom.css">
<import from="./foo">
<import from="./special-offers">

<bindable name="firstname" default-binding-mode="one-time" default-value="you">
<bindable name="lastname" default-binding-mode="one-time" default-value="not provided">
<bindable name="occupation" default-binding-mode="one-time" default-value="unknown">
<bindable name="age" default-binding-mode="one-time" default-value="unknown">
<bindable name="approved">

<template>
  <p>Hey, ${firstname}!</p>
  <p>We will store the following information from the information you just entered in our system:</p>
  <ul>
    <li>lastname: ${lastname}</li>
    <li>age: ${age}</li>
    <li>occupation: ${occupation}</li>
  </ul>
   <p>
     <label><input type="checkbox" checked.bind="approved" >
      Yes, I allow you to store this information about me</label>
   </p>
   <foo approved.bind="approved"></foo>
   <special-offers for-occupation.bind="occupation"></special-offers>
</template>
```
I think it's excellently easy to document stuff too

**Comment by 3cp** [comment]
A little formatting helps readability.
```html
<bindable name="firstname"  default-binding-mode="one-time" default-value="you">
<bindable name="lastname"   default-binding-mode="one-time" default-value="not provided">
<bindable name="occupation" default-binding-mode="one-time" default-value="unknown">
<bindable name="age"        default-binding-mode="one-time" default-value="unknown">
<bindable name="approved">
```

**Comment by EisenbergEffect** [comment]
Nice!

**Comment by 3cp** [comment]
Is bindable in html template processed at runtime like v1?

We would need a support from `CustomElement.define({ bindables: [ ... ], ... })` to be able to preprocess them at compile time.

**Comment by EisenbergEffect** [comment]
There is a `bindables` property you can provide as part of the template definitions :) So, if you just add that as another export, it will work 😄

**Comment by EisenbergEffect** [comment]
Here's the full definition for reference:

```TypeScript
export interface IResourceDefinition extends Object {
  name: string;
}

export interface ITemplateDefinition extends IResourceDefinition {
  cache?: '*' | number;
  template?: unknown;
  instructions?: ITargetedInstruction[][];
  dependencies?: Key[];
  build?: IBuildInstruction;
  surrogates?: ITargetedInstruction[];
  bindables?: Record<string, IBindableDescription> | string[];
  childrenObservers?: Record<string, IChildrenObserverDescription>
  containerless?: boolean;
  shadowOptions?: { mode: 'open' | 'closed' };
  hasSlots?: boolean;
  strategy?: BindingStrategy;
  hooks?: Readonly<HooksDefinition>;
  scopeParts?: readonly string[];
}
```

**Comment by EisenbergEffect** [comment]
In light of that, in HTML you could just go with `mode` instead of `default-binding-mode`. There isn't currently a default value. That would have to be added. Other metadata that might be interesting to support is `containerless`

**Comment by 3cp** [comment]
Ok, both bindable and containerless will be added.

**Comment by 3cp** [comment]
#586 now supported following
```html
<containerless>
<template containerless>
<bindable name="lastName" mode="one-time" attribute="surname">
<bindable name="lastName" mode="oneWay">
<template bindable="firstName, lastName">
```
bindable tag has optional attributes: mode and attribute. Mode string is normalized, so "one-time", "one_time", "OneTime", "oneTime" all mean same thing.

@EisenbergEffect does `<bindable>` need to support optional attribute `property` (I am not sure what's difference between that `property` and name of the bindable)?

**Comment by bigopon** [comment]
> bindable tag has optional attributes: mode and attribute. Mode string is normalized, so "one-time", "one_time", "OneTime", "oneTime" all mean same thing.

if we went that far, it would make sense just to support `"one time"`, "One time"` as well

**Comment by 3cp** [comment]
It uses kebabCase from `@aurelia/kernel` to normalize the string.
I didn't want to write code to extend the behaviour until I saw "one_time" actually doesn't work :-(

I will enhance the kernel kebabCase and camelCase to cover more edge cases, as long as those edge cases make sense.

**Comment by 3cp** [comment]
I will leave kebabCase to another PR. Right now, I just remove "one_time" from commit message.

**Comment by 3cp** [comment]
Question about a new idea:

Since metadata tags removed lots of burden on `<template>` tag, is it a good idea to allow user to omit top level `<template>` and `</template>`?

```html
<import from="./foo.css">
<p>hello</p>
```

The conventions can wrap the content inside a `<template>` tag if user didn't provide it.

The argument to support this feature: I am thinking about intuitive support of other template language like `.md`, `.haml`, `.pug`.

All of the alternative template languages provide tooling that compiles them into html string but without a `<template>` wrapper. This new proposed feature can support all existing tooling for those template languages. We don't need to write any code to support those template languages.

For example, `foo.md` will just work out of the box, as long as you correctly configure the bundler.
```md
<use-shadow-dom mode="open">
<containerless>
<bindable name="firstName" mode="one-way">
<bindable name="lastName">
<import from="./foo.css">
<import from="./bar">

# Title
Lorem ipsum dolor sit amet.
<bar></bar>
```

**Comment by fkleuver** [comment]
@3cp The jit already wraps your html in a `<template>` if it needs to. AOT logic will run jit ahead of time, so AOT will do it as well. Meaning conventions don't need to :)

**Comment by 3cp** [comment]
Perfect! I was expecting that runtime took care of that.

**Comment by fkleuver** [comment]
Well, runtime doesn't, jit does :P but important point is you don't need to

**Comment by bigopon** [comment]
For

```html
<import from="./foo-custom.css">
<import from="./special-offers-custom.css">
...
```

I think we should be careful supporting it without a closing tag/signal. As the same template will be broken on browser, as it will be something like this:
```html
<import from="./foo-custom.css">
  <import from="./special-offers-custom.css"></import>
</import>
```

**Comment by 3cp** [comment]
Different from v1, v2 did all of these in preprocessing. Those tags and attributes are removed from the final html string (in html module js code) which browser will read.

That's why I support omitting closing tag.
