### ISSUE TITLE
Local Resource Renaming

### ISSUE THREAD

**Issue by EisenbergEffect** [aurelia/aurelia#622]
# 🙋 Feature Request

We need to support `<import as="foo" from="bar">` in order to support renaming for local disambiguation.

## 🤔 Expected Behavior

A resourced named bar should be registered as foo only for the view where it's imported as foo.

## 😯 Current Behavior

it is not possible to rename a resource upon import.

## 💁 Possible Solution

First we need to change resource registration from this:

```TypeScript
  Type.register = function register(container: IContainer): void {
      const key = CustomElement.keyFrom(description.name);
      Registration.transient(key, this).register(container);
      Registration.alias(key, this).register(container);
    };
```

To this:

```TypeScript
  Type.register = function register(container: IContainer, name?: string): void {
      const key = CustomElement.keyFrom(name || description.name);
      Registration.transient(key, this).register(container);
      Registration.alias(key, this).register(container);
    };
```

Then we need a helper function similar to this:

```TypeScript
export function renameResource(resourceModule, name) {
  return {
    register(container) {
      for (const key in resourceModule) {
        const value = resourceModule[key];
        if (value.register) {
          resource.register(container, name);
          return;
        }
      }
    }
  };
}
```

Note: Helper function above needs some modification to also handle if there's a register method directly on the module, as is the case with html only elements.

Then when you have this:

```HTML
<import as="bar" from="./another/foo">
```

You generate this:

```TypeScript
import * as d0 from './another/foo';
export const dependencies = [ renameResource(d0, 'bar'), /* ... */ ];
```

**Comment by fkleuver** [comment]
I would actually propose updating `RuntimeCompilationResources.find` instead, so that if the passed-in name does not match the name on the description, it clones and renames the description before returning it. Since the `name` property of the description is used in quite a few places related to view factories and replaceable as well, doing it this way would ensure several obscure edge cases will work correctly as well. And there would be no need to update the `register` methods.

Something like this may do the trick:

```ts
  public find<TDef, TProto>(kind: IResourceKind<TDef, TProto>, name: string): ResourceDescription<TDef> | null {
    const key = kind.keyFrom(name);
    const resourceLookup = (this.context as unknown as { resourceLookup: Record<string, IResolver | undefined | null> }).resourceLookup;
    let resolver = resourceLookup[key];
    if (resolver === void 0) {
      resolver = resourceLookup[key] = this.context.getResolver(key, false);
    }

    if (resolver != null && resolver.getFactory) {
      const factory = resolver.getFactory(this.context);

      if (factory != null) {
        const description = (factory.Type as IResourceType<TDef, TProto>).description;
        if (description === void 0) {
          return null;
        }
        if (description.name !== name) {
          description = cloneAndRenameTemplateDefinition(description, name);
        }
        return description;
      }
    }

    return null;
  }
```

**Comment by EisenbergEffect** [comment]
Update for @3cp . Code gen for import as would not use any helper stuff above. We can use the existing alias functionality. It would look something like this:

```HTML
<import from"./foo" as="bar">
```

```TypeScript
import * as m1 from "./foo":
export const edependencies = [Registration.alias(CustomElement.keyFrom('bar'), m1)];
```

**Comment by EisenbergEffect** [comment]
@3cp New approach to code generation on this. We'll need one helper method:

```TypeScript
export function alias(name, resource) {
  return Registration.alias(resource.kind.keyFrom(name), resource);
}
```

We can add this to the framework somewhere.

Then if you have the following HTML:

```HTML
<import bind="{ MyComponent as your-component }" from"./bar">
```

You would generate:

```TypeScript
import { MyComponent as yourComponent } from"./bar";
export const dependencies = [alias('your-component', yourComponent)];
```

**Comment by EisenbergEffect** [comment]
@fkleuver Any thoughts on where we should add the helper? We could call it `aliasResource` and hang it right off the `Registration` class.

**Comment by 3cp** [comment]
I would against `<import bind="{ MyComponent as your-component }" from"./bar">`.

1. it's verbose. Most users' `bar.js` will only define one resource. So the verbosity is utterly unnecessary for most use cases.
2. `as your-component` is not even correct js, this is very confusing because the syntax looks trying to mimic es6 import statement.

`<import as="foo" from="./bar">` is more intuitive. If that means complex helper method, so be it.

**Comment by 3cp** [comment]
The verbose syntax also troubles user when using 3rd party plugin. Now user not only needs to know the custom element name (likely the only thing documented by plugin author), but also needs to know the export name.

The fact is plugin author can name their export anything, the export name does not need to match or relate to element name when manual `@customElement` decorator is used.

**Comment by EisenbergEffect** [comment]
I also feel that a simple as attr would be more ergonomic. I think the issue was that it wouldn't be flexible enough. But maybe it's trying to support edge cases that won't every come up in practice. @fkleuver probably has some thoughts on this.

**Comment by 3cp** [comment]
We don't have to cover all cases.

1. This rename feature itself is a rarely used feature.
2. This is a last resort for user to avoid naming conflicts within a template. There are many ways to avoid conflicts in the first place.

This is exactly why we recommend all plugin authors to name their resources after a prefix.

**Comment by 3cp** [comment]
If we want, we can support
```html
<import as="new-resource-name" from "./bar">
<!-- if bar has multiple resources exported -->
<import resource-name.as="new-resource-name" from "./bar">
<!-- or verbose version (but I prefer the one above) -->
<import resource="resource-name" as="new-resource-name" from "./bar">
```

Note `resource-name` is not export name, but this resource name is more relevant to users. This also means more complex helper method.

**Comment by fkleuver** [comment]
The main edge case to deal with here is when a file exports multiple things. You basically can't use alias then. So, we could explicitly "not support" that scenario and then the edge case is gone as well. Do we want to impose that limitation?

**Comment by 3cp** [comment]
There is no limit in support. For simple `<import as...>`, It will be just additional few lines helper method which we can have in preprocessed html module. For named import, the helper provided by kernel is enough.

I read #625, I think the implementation is enough for conventions to support both the simple case and named case.

**Comment by brandonseydel** [comment]
@3cp  I wrote e2e so you can just review?  Conventions is sitting locally

**Comment by 3cp** [comment]
I just noticed this: https://discourse.aurelia.io/t/dynamically-loading-unloading-css-based-on-route/2938/2?u=huochunpeng

I don't know about scoped css in Aurelia v1, if someone can explain it bit more.

Do we need to change syntax to avoid `<require as="bar">`  `<import as="bar">` because of conflict with `<require as="scoped" from="./only.css">`? Or we can live with it because `as="scoped"` is only for css?

**Comment by EisenbergEffect** [comment]
That scoped feature used scoped CSS which is basically deprecated, so we should not support this and treat it as a necessary breaking change due to web standard stuff. We could throw if you use `as` on a CSS import, I suppose.
