### ISSUE TITLE
[RFC] single npm package "aurelia" for simplified imports

### ISSUE THREAD

**Issue by 3cp** [aurelia/aurelia#630]
# 💬 RFC

This is a record of the decision made on discord few months ago, it will be implemented before alpha release.

## 🔦 Context

To provide single npm package `aurelia` (currently an empty npm package owned by @EisenbergEffect) which just re-exports all internals from `@aurelia/kernel`, `@aurelia/runtime`, `@aurelia/jit`, ...

```js
import { AnyThing } from 'aurelia';
```

Update: a new way to start app, to reduce boilerplate.

```ts
import Aurelia, { StyleConfiguration, RouterConfiguration } from 'aurelia';
import { MyRootComponent } from './my-root-component';
// By default host to element name (<my-root-component> for MyRootComponent),
// or <body> if <my-root-component> is absent.
Aurelia.app(MyRootComponent).start();

// Or load additional aurelia features
Aurelia
  .register(
    StyleConfiguration.shadowDOM(),
    RouterConfiguration.customize({ useUrlFragmentHash: false })
  )
  .app(MyRootComponent)
  .start();

// Or host to <my-start-tag>
Aurelia
  .register(
    StyleConfiguration.shadowDOM(),
    RouterConfiguration.customize({ useUrlFragmentHash: false })
  )
  .app({
    component: MyRootComponent,
    host: document.querySelector('my-start-tag')
  })
  .start();
```

Note the `au` is not a fixed name, it's using default export from `aurelia` package.

## 💻 Examples

So that users don't have to know where to import certain features, they don't have to write 
```js
import {...} from '@aurelia/runtime';
import {...} from '@aurelia/kernel';
```

It will be just `import {...} from 'aurelia'';`. This will simplify user code, and reduce the learning curve.

The downside is that we need to rely on tree-shaking (from various bundlers) to remove unused Aurelia 2 features.

We also need to cleanup existing export names to avoid naming conflicts. For example, there are multiple `BasicConfiguration` exported from few Aurelia 2 core packages. This is a small breaking change.

**Comment by 3cp** [comment]
The list of troublesome duplicated exports for review.

```js
export {
  Tracer as DebugTracer // duplicated in @aurelia/kernel
} from '@aurelia/debug';
export { 
  Scope as RouterScope,  // duplicated in @aurelia/runtime
  State as RouterState // duplicated in @aurelia/runtime
} from '@aurelia/router';
export {
  DOM as RuntimeHtmlDOM // duplicated in @aurelia/runtime
} from '@aurelia/runtime-html';
```

The list of expected duplicated exports for review.

```js
export {
  DefaultComponents as JitDefaultComponents,
  DefaultBindingLanguage as JitDefaultBindingLanguage,
  BasicConfiguration as JitBasicConfiguration,
} from '@aurelia/jit';

export {
  DefaultComponents as JitHtmlDefaultComponents,
  DefaultBindingLanguage as JitHtmlDefaultBindingLanguage
  BasicConfiguration as JitHtmlBasicConfiguration
} from '@aurelia/jit-html';

export {
  BasicConfiguration as JitHtmlBrowserBasicConfiguration
} from '@aurelia/jit-html-browser';

export {
  DefaultComponents as RouterDefaultComponents,
  DefaultResources as RouterDefaultResources
} from '@aurelia/router';

export {
  DefaultResources as RuntimeDefaultResources
} from '@aurelia/runtime';

export {
  DefaultComponents as RuntimeHtmlDefaultComponents,
  DefaultResources as RuntimeHtmlDefaultResources,
  BasicConfiguration as RuntimeHtmlBasicConfiguration,
} from '@aurelia/runtime-html';

export {
  DefaultComponents as RuntimeHtmlBrowserDefaultComponents,
  BasicConfiguration as RuntimeHtmlBrowserBasicConfiguration
} from '@aurelia/runtime-html-browser';
```

**Comment by 3cp** [comment]
I need some advice on those 4 troublesome duplicated exports. The debug and router ones might be better to be renamed within those packages.

**Comment by EisenbergEffect** [comment]
Ok, for the duplicated exports, I think we just need to make the breaking change to rename them in their source as you've re-exported them here. It's a bit verbose, but people won't be interacting with these a ton, so I think it's ok.

For Tracer, I think we keep Tracer in the kernel, but rename the debug version to DebugTracer as you have.

For DOM, that's just a re-export. Need to see what @fkleuver says about that since it's a bit odd.

Let's also get @jwx to chime in on the router renames.

---

For app startup, I very much like `au(MyApp)`. However, I wonder that instead of adding other nameless parameters, we should instead support an options object.

```TypeScript
au(MyApp, {
  host: 'my-app',
  dependencies: [PluginA, PluginB]
});
```

**Comment by 3cp** [comment]
The startup code was discussed with @fkleuver. I like your 2nd param with named options, which is more readable. I would like to have an alias from "deps" to "dependencies" too. Let's have more discussion, and finalise the wrapper design.

I would suggest not to attempt to duplicate all features of `new Aurelia()`, because user still can do this:

```js
import { Aurelia } from 'aurelia';
new Aurelia()
  ...
```

The new wrapper is designed to reduce boilerplate (common config and debug config) for maybe 80% of the users.

cc @brandonseydel and @bigopon

**Comment by EisenbergEffect** [comment]
I'm not too thrilled about "dependencies" either. It is consistent with our custom element config. We could add a "deps" alias there. If we go that route, then maybe we should add it to the element config as well so people don't have to remember one or the other.

**Comment by 3cp** [comment]
BTW, if I implement it like this:
```js
export default function(component, optionalHost) {
  const au = new Aurelia();
  // ...
  au.app({ host, component });
  setTimeout(() => au.start()); // delay the magic
  return au;
}
```

It can actually allow user to do:
```js
au(MyApp).register(...);
```
Without me writing any code...

**Comment by jwx** [comment]
The `Scope` in Router will be refactored away in next PR. `State` is from `RouteRecognizer` which I'm not familiar with, but I think it's internal and don't really need to be exported at all. If it does, I would think either `RouteState` or `RecognizerState` would be better names. @fkleuver will know.

I know this isn't necessarily correct, but how do you feel about `Au` as the short name? It is, after all, pure gold.

**Comment by 3cp** [comment]
Thx. There is no need of short name in this RFC, the quick booting wrapper is the default export of "aurelia", no name at all.

**Comment by fkleuver** [comment]
We don't need to export everything. We have a gazillion micro interfaces in the runtime, for example, most of the stuff is exported just because other core packages need it. We can trim most of it for a single entry package. Having a single package with 2.500 exports won't make anyone happy either.

**Comment by 3cp** [comment]
Ok, I will put out a draft PR with most exports commented out. Then we review and pick more exports to be exposed. @jwx let's not rename router exports now.

**Comment by 3cp** [comment]
Question, should we recommend plugin authors to use "aurelia" or individual `@aurelia/*` packages (seems bit learning curve for authors)?

**Comment by fkleuver** [comment]
I would recommend plugin authors to use `@aurelia/*` packages. Slightly more learning curve but early improved exposure to some of the internals that will ultimately lead to more robust plugins

**Comment by HamedFathi** [comment]
I am working on Aurelia 2 API/Project documentation generator. I extracted all the sources information that I need for all the Aurelia packages.
Like the following pictures:

![2](https://user-images.githubusercontent.com/8418700/65711772-80b24000-e0a2-11e9-8e1a-fa636b352f7b.png)

![3](https://user-images.githubusercontent.com/8418700/65711786-83ad3080-e0a2-11e9-9d27-92e7a5507d54.png)

We want to show the final result in [GitBook](https://www.gitbook.com/).

I want to make all `types` clickable to their definition pages.
For example:

![au](https://user-images.githubusercontent.com/8418700/65711698-52ccfb80-e0a2-11e9-853e-76606ab24e7e.png)

Part of information that I extracted

![4](https://user-images.githubusercontent.com/8418700/65711971-e1417d00-e0a2-11e9-96d9-92374c4798b1.png)

We will use `from` block plus a `mapper function` to map types location to `GitBook url`.
Something like:

```
Name: `convertToRenderLocation`
ReturnType: IRenderLocation<AuNode> & AuNode

`AuNode` will map to `gitbook.com/testing/au-dom#AuNode`
[AuNode](/testing/au-dom#AuNode)

`IRenderLocation` will map to `gitbook.com/runtime/dom#IRenderLocation`
[IRenderLocation](/runtime/dom#IRenderLocation)
```

@3cp 
With your changes for Aurelia packages What will happen to `from` block? Can I use this technique to gain the result?
I use a `mapper function` to map **file type location to url** Is it possible after changes?

**Comment by 3cp** [comment]
@HamedFathi I have no idea what it takes for the API doc. But you can try on my branch, I don't think I did anything unusual.

**Comment by 3cp** [comment]
@fkleuver in that sense, we would better do not change the current conventions from injecting inner packages import. Because conventions plugins can be used by both app and plugin users.

I would need to adjust conventions implementation to check existing import like `import { customElement } form 'aurelia';`. In order to avoid duplicated import, one is from user imported "aurelia" package, another one is from injected inner import.

**Comment by HamedFathi** [comment]
@EisenbergEffect @fkleuver @3cp 

>  you can try on my branch

OK, I checked it quickly. Please consider the following example

![Untitled](https://user-images.githubusercontent.com/8418700/65740077-62753000-e0f4-11e9-8bcf-ce45485caca6.png)

And the information that I extracted

![1](https://user-images.githubusercontent.com/8418700/65740508-debc4300-e0f5-11e9-8243-12240e8d201d.png)

![2](https://user-images.githubusercontent.com/8418700/65740510-e0860680-e0f5-11e9-8e67-ab831a1daf99.png)

![3](https://user-images.githubusercontent.com/8418700/65740512-e1b73380-e0f5-11e9-905e-c239418a758b.png)

Based on the new changes `BasicConfiguration` has a new name: `JitHtmlBrowserBasicConfiguration` the name that I should show to users in the API documentation.
I change the final name based on the import statement (as) so I support `as` in the source file level but in a separate package NO!. (the new package level)
For me `BasicConfiguration` is `RuntimeHtmlConfiguration` not  `JitHtmlBrowserBasicConfiguration`.
What should I do? a pre/post-processing type detection based on `aurelia` package?

**Comment by 3cp** [comment]
@fkleuver should we rename BasicConfiguration (and some other common names) in source package to avoid renaming in "aurelia" package? (But it is a breaking change)
Proper unique name is better for documentation and clarity.

**Comment by fkleuver** [comment]
We can rename the configuration objects. Let's remove the word "Basic" though as I don't think that adds any meaning when there is no such thing as "Normal" or "Advanced" alongside it to choose from.

We also have this abbreviation problem. Perhaps we should use underscores or something. Not sure. Thoughts?
**@aurelia/jit**
```ts
JitConfiguration
// or
JIT_Configuration
// or
JITConfiguration
```

**@aurelia/jit-html**
```ts
JitHtmlConfiguration
// or
JIT_HTML_Configuration
// or
JIT_HTMLConfiguration
```

**@aurelia/jit-html-browser**
```ts
JitHtmlBrowserConfiguration
// or
JIT_HTML_Browser_Configuration
// or
JIT_HTMLBrowserConfiguration
```

**@aurelia/jit-html-jsdom**
```ts
JitHtmlJsdomConfiguration
// or
JIT_HTML_JSDOM_Configuration
// or
JIT_HTMLJSDOMConfiguration
```


**@aurelia/runtime**
```ts
RuntimeConfiguration
// or
Runtime_Configuration
```

**@aurelia/runtime-html**
```ts
RuntimeHtmlConfiguration
// or
Runtime_HTML_Configuration
// or
Runtime_HTMLConfiguration
```

**@aurelia/runtime-html-browser**
```ts
RuntimeHtmlBrowserConfiguration
// or
Runtime_HTML_Browser_Configuration
// or
Runtime_HTMLBrowserConfiguration
```

**@aurelia/runtime-html-jsdom**
```ts
RuntimeHtmlJsdomConfiguration
// or
Runtime_HTML_JSDOM_Configuration
// or
Runtime_HTMLJSDOMConfiguration
```

@EisenbergEffect

**Comment by EisenbergEffect** [comment]
I'd prefer not to use underscores if possible :) That's my only real feedback.

**Comment by 3cp** [comment]
@fkleuver do you want a separated PR for the breaking change of renaming configuration? We can release it first so @EisenbergEffect, @brandonseydel and @Vheissu can update their apps.

The whole "aurelia" package needs convenstions update before updating apps.

**Comment by 3cp** [comment]
Let's just use the capitalized camel case, it's same as the existing internal rename when jit-html-browser imports other basic configurations.

**Comment by fkleuver** [comment]
@3cp Shouldn't be a problem, this breaking change, as it's a matter of simple rename. But regardless I think we should only export the one from jit-html-browser for now.

**Comment by 3cp** [comment]
To be consistent, I think we probably need to rename lots of internal names to avoid `import as`.

For example, this is BasicConfigration from jit-html, it uses lots of other `Default...` and `Basic...` from other packages.

```js
import {
  DefaultBindingLanguage as JitDefaultBindingLanguage,
  DefaultBindingSyntax as JitDefaultBindingSyntax,
  DefaultComponents as JitDefaultComponents
} from '@aurelia/jit';
import { BasicConfiguration as RuntimeHtmlBasicConfiguration } from '@aurelia/runtime-html';
export const BasicConfiguration = {
  /**
   * Apply this configuration to the provided container.
   */
  register(container: IContainer): IContainer {
    return RuntimeHtmlBasicConfiguration
      .register(container)
      .register(
        ...JitDefaultComponents,
        ...JitDefaultBindingSyntax,
        ...JitAttrBindingSyntax,
        ...JitDefaultBindingLanguage,
        ...DefaultComponents,
        ...DefaultBindingLanguage
      );
  },
  /**
   * Create a new container with this configuration applied to it.
   */
  createContainer(): IContainer {
    return this.register(DI.createContainer());
  }
};
```

**Comment by 3cp** [comment]
@EisenbergEffect the quick start wrapper has been redesigned based on @fkleuver's recommendation to not introduce new API. The wrapper is now a subclass of `Aurelia`, added static methods `register`, `app` and `start` with same signature of the instance methods, overrode `app` instance method to implement `.app(MyApp)` shortcut.

The wrapper class is exported twice, a named `Aurelia` export and also the default export.

The new startup code looks like this:
```js
import Aurelia, { StyleConfiguration, RouterConfiguration } from 'aurelia';
import { MyRootComponent } from './my-root-component';

Aurelia // as Aurelia is default import, user can switch to shorter name
  .app(MyRootComponent)
  .start();

// Or
Aurelia
  .register(
    StyleConfiguration.shadowDOM(),
    RouterConfiguration.customize({ useUrlFragmentHash: false })
  )
  .app(MyRootComponent)
  .start();
```

The good thing is there are no new APIs to confuse user, just added static helper methods. The helper cannot be added to original `Aurelia` class because of the abstraction in `@aurelia/runtime`.

Any future startup code improvement should happen inside `Aurelia` class itself without touching this helper layer much. We think this humble and thin helper layer is flexible and not intrusive.

**Comment by EisenbergEffect** [comment]
Sounds good to me :)

**Comment by 3cp** [comment]
It's released. Makes skeleton is updated.

This one will be closed after I cleanup conventions code (to check existing import from aurelia statement).
