### ISSUE TITLE
How to register a plugin in aurelia vNext

### ISSUE THREAD

**Issue by vipintme** [aurelia/aurelia#633]
How we can register a plugin like aurelia-table, aurelia-authentication in aurelia vNext. In the previous version, we are using the following method for registering a plugin

![image](https://user-images.githubusercontent.com/13940939/65523564-14043d80-df0a-11e9-8526-3fb1e96834de.png)

**Comment by brandonseydel** [comment]
https://github.com/brandonseydel/aurelia-material?files=1

**Comment by EisenbergEffect** [comment]
@vipintme au2 is much improved when it comes to configuring plugins :) We incorporated a lot of feedback from the au1 years. Basically, all your plugin needs is to export some object or class with a `register` method. Your users will import that object and pass it to the Aurelia object's `register` method. In your `register` method, you will get the global container instance, so you can configure anything your plugin needs. There's no need for string module names. We're doing everything through the module system so it automatically works with tools.

If you have specific questions about startup, etc. let us know. au2 has the concept of "startup tasks" that you can register in the container if your plugin needs to execute code at specific times during app startup or if it needs to do anything async during startup.

**Comment by EisenbergEffect** [comment]
I should note that we have a full documentation placeholder article dedicated to plugin topics. So, this will get documented better for the new version as well.

**Comment by HamedFathi** [comment]
@EisenbergEffect

Does it support my scenario in [here](https://discourse.aurelia.io/t/exclude-plugins-in-aurelia/1196)

**Comment by EisenbergEffect** [comment]
@HamedFathi It's not easy to do something like that in the framework without being dependent on strings, which has been one of the biggest problems for Aurelia v1 tool integration.

For Aurelia 2, the approach would be that the plugin author export each individual component, as well as a set of default combinations. So, if you used a default, you could just have a one line config, but if you need something custom, you can always select the individual pieces you want.

Ultimately, Aurelia 2 leaves this up to the bundler, which can be configured to exclude things. Trying to do something like this in the framework itself creates a framework-specific mechanism that bundlers and other tools don't understand. With au1, that's been nothing but pain and I think one of the chief preventers of better adoption.
