### ISSUE TITLE
Model-based validation for Aurelia Validation vNext

### ISSUE THREAD

**Issue by HamedFathi** [aurelia/aurelia#638]
# 🙋 Feature Request

The fluent API support in the current version of  Aurelia Validation is great. But sometimes we need model-based validation for our **dynamic scenarios**. It would be great if Aurelia Validation vNext supports Model-based validation officially.

[Dynamic form generator (JSON Schema)](https://discourse.aurelia.io/t/dynamic-form-generator-json-schema/2400/11)

## 🤔 Expected Behavior

To work like [bcx-validation](https://buttonwoodcx.github.io/doc-bcx-validation/) that is made by @3cp 

Having `Fluent` and `Model-based` validation together is so valuable.

## 😯 Current Behavior

Just supports Fluent-based API.

## 💻 Examples

**bcx-validation:**
```js
@inject(Validation)
export class SimpleForm {
  triedSubmit = false;
  isSaving = false;
  model = {
    // keep all numbers as js number, not string
    cpu: 1,
    memory: 512,
    disk: 10,
    willHostJava: true
  };

  constructor(validation) {
    this.validate = validation.generateValidator({
      cpu: ['mandatory', {validate: 'number', min: 1, max: 64}],
      memory: [
        'mandatory',
        {
          if: 'willHostJava', // `if` accepts an expression to be evaluated
          validate: 'number',
          min: 2048,
          message: 'are you kidding me, ${$value}MB for Java?! you need at least 2048MB',
          // don't want to show irrelevant double error "must be at least 256"
          stopValidationChainIfFail: true
        },
        {validate: 'number', min: 256, max: 64 * 1024}
      ],
      disk: ['mandatory', {validate: 'number', min: 10, max: 1000}]
    });
  }
```

**Vuelidate:**
![image](https://user-images.githubusercontent.com/8418700/65753286-8dbf4580-e11b-11e9-872c-30fd0cb34e35.png)

**Comment by 3cp** [comment]
I designed bcx-validation to decouple validation from rendering, because validation is model level logic. So I can reuse it in other places such as private npm packages doing pure domain logic in POJO. It also works with Aurelia 2 or any other frameworks because it only does validation logic.

bcx-validation has performance problem in vcurrent because getter in vCurrent got duplicated calls which is an aurelia issue. I have a decorator on getter to reduce this issue, but Aurelia 2 fixed the issue by design.

**Comment by HamedFathi** [comment]
@3cp

Can be part of Aurelia 2 validation library? This is so useful.
Actually, I have a plan to write interactive form designer based on JSON schema for Aurelia-Toolbelt 2.

**Comment by 3cp** [comment]
There is no need to bring bcx-validation to Aurelia umbrella, as it is a generic validation tool.

bcx-validation is standalone, it uses bcx-expression-evaluator which is an extracted expression parser from old aurelia-binding.

**Comment by Sayan751** [comment]
@HamedFathi @fkleuver Now the validation plugin supports model-based validation, I think this can be closed for housekeeping purpose.

**Comment by HamedFathi** [comment]
Thanks so I close this.
