### ISSUE TITLE
[RFC] SSR / Aurelia http-server package (placeholder)

### ISSUE THREAD

**Issue by fkleuver** [aurelia/aurelia#676]
# 💬 RFC

**Comment by Vheissu** [comment]
Ideally, the implementation of SSR would be a little more robust than the vCurrent implementation. The way in which vCurrent works, it is lacking a lot of features and is quite fickle. A lot of the problems I have experienced in Aurelia and helped others with is server-side rendering.

Some of the painful areas of the current implementation I have experienced include;

- Issues around debugging. When things break, the server doesn't seem to return any meaningful error messages or ways of stepping through to see what has broken.
- Lack of support for SEO features such as meta tags (description, keywords, social media open graph tags)
- Issues with using libraries only meant to work within the browser breaking the SSR functionality, requiring if statement checks around numerous blocks of code and conditionally loading libraries which rely on globals such as `window`.
- Memory leaks. This isn't an Aurelia-specific problem, it seems many SSR implementations in other frameworks and libraries thanks to Node are prone to memory leaks.

Ideally, it would be a "nice to have" for the SSR functionality to support different forms of rendering. Right now, vCurrent SSR is primitive in that it effectively just renders all of the HTML and returns it. The ReactJS DOM Server API exposes some useful methods for this:

- https://en.reactjs.org/docs/react-dom-server.html#rendertostring
- https://en.reactjs.org/docs/react-dom-server.html#rendertostaticmarkup

A super nice to have would be the ability to return a stream like this React DOM Server method: https://en.reactjs.org/docs/react-dom-server.html#rendertonodestream

Understandably, being a framework and not a library, some of these things are not that trivial and would possibly require a bit of work. Even just a fast and somewhat configurable SSR implementation would be an improvement.

**Comment by shahabganji** [comment]
I have once created a library for aurelia, [aurelia-meta](https://github.com/shahabganji/aurelia-meta), in which I tried to integrate meta tags into route engine, and beside add functionality like the [this one](https://angular.io/api/platform-browser/Meta#meta) in angular. I am not sure tho whether meta tags are related to SSR or routing since each page/route could have predefined meta tags as well as dynamically generated tags.

**Comment by kyttike** [comment]
I would like to second the usefulness of being able to generate static HTML pages so that Aurelia could be used for [JAMstack](https://jamstack.org/) sites. Having support for both SSR and static HTML export would make Aurelia able to compete with the other frameworks out there.
