### ISSUE TITLE
TODO: Support RelativeTimeFormat for i18n on Node 10

### ISSUE THREAD

**Issue by BBosman** [aurelia/aurelia#710]
Follow up to #701 

We need to add a `RelativeTimeFormat` polyfill so that `i18n` once again works on Node 10, the soon to be Node LTS version. `RelativeTimeFormat` was only added in Node 12.

Once that's done we can also relax the engine restriction on `__tests__` again.

**Comment by Sayan751** [comment]
This might work https://www.npmjs.com/package/intl-relative-time-format. However, this should be included as an optional dependency. @zewa666 What do you think?

**Comment by zewa666** [comment]
Yes absolutely. Don't need to clutter the deps and optional should be enough

**Comment by Sayan751** [comment]
I think it might be better to update the docs with polyfill example instead of adding any sort of dependencies.
