### ISSUE TITLE
TODO: encapsulate css process option in html module at build time

### ISSUE THREAD

**Issue by 3cp** [aurelia/aurelia#715]
# 🙋 Feature Request

@EisenbergEffect this is to record the issue we discussed in discord few weeks ago.

Current implementation of css handling has a design fault.

Currently the choice of css processing is in user's app configuration, in `main.ts` and `webpack.config.js`. This user choice not only affects the local html module in the app, but also
affects existing compiled html module in plugins (node_modules).

This is wrong for plugins where the plugin authors should have the control on how to process css resource.

## 🤔 Expected Behavior

To encapsulate css processing choice inside compiled html module.

## 😯 Current Behavior

User app's css processing setup affects all plugins' html module.

## 💁 Possible Solution

We cannot rely on `Registration.defer('.css', a.css, b.css)` which will use app's css process option at runtime.

We need to replace the `Registration.defer('.css', a.css, b.css)` with hard coded shadowDOM css or css-module methods.

Another good side effect of this hard coded css processing:
1. We can remove `StyleConfiguration.shadowDOM()` and `StyleConfiguration.cssModulesProcessor()` from user app entry `main.ts`.
2. User only needs to config css processing in bundler config, e.g. `webpack.config.js` for webpack.

**Comment by EisenbergEffect** [comment]
We may still need the main.ts configuration, esp. if there are shared shadow dom styles. I'll assign this to me to figure out what the API will be to be used by the conventions code. Once I add that, we can then fix that conventions code. Afterward, we can remove any old code that is deprecated, that way we don't break anything during the transition period.

**Comment by EisenbergEffect** [comment]
On second thought, that approach isn't going to work. I'll need to create a PR with the runtime changes, then @3cp you will need to jump in and add the conventions changes in the same branch so that it all merges together. I'll get started on the runtime stuff soon.

**Comment by EisenbergEffect** [comment]
I've got a way to do it with zero config. So, this will be a nice improvement :)

**Comment by EisenbergEffect** [comment]
Yeah, this is going to work out nicely. I should have a PR soon....need to fix all the tests I broke 🤣

**Comment by Vheissu** [comment]
@EisenbergEffect If you say "tests broke" in the mirror three times, legend has it @fkleuver appears in your pull request 🤣

**Comment by fkleuver** [comment]
What tests broke? 😮

**Comment by 3cp** [comment]
@EisenbergEffect I think this was done with your new APIs.
