### ISSUE TITLE
Consolidate "Binding: Observables" and "Binding: The Binding Engine"

### ISSUE THREAD

**Issue by Alfhir** [aurelia/aurelia#725]
Hello,

i'd like to propose a consolidation of [Binding: Observables](https://aurelia.io/docs/binding/observable-properties#observable-properties) and [Binding: The Binding Engine](https://aurelia.io/docs/binding/binding-engine#observing-a-property-on-an-object).

The information on how to subscribe to a CollectionObserver is duplicated and the example containing the splices properties is missing in  [Binding: The Binding Engine](https://aurelia.io/docs/binding/binding-engine#observing-a-property-on-an-object). 
All content from "Observing a property / expression on an object" could be moved to [Binding: Observables](https://aurelia.io/docs/binding/observable-properties#observable-properties).

**Comment by fkleuver** [comment]
I agree.
The `@observable` decorator and the `BindingEngine` class are closely related means to observe arbitrary data outside of the context of templating.

Merging them into a single article makes sense to me, and makes it easier to provide more complex examples in context, such as using the two together to observe a property where the instance change as well as the collection change is relevant.

@EisenbergEffect

**Comment by Alfhir** [comment]
> (which is this repo, and the docs are about v1)

Oops, sorry about that. Just to make shure, [this](https://github.com/aurelia/documentation) would would be the right place for documentation issues concerning v1?
