### ISSUE TITLE
Support increment operators in view

### ISSUE THREAD

**Issue by davismj** [aurelia/aurelia#732]
# 🙋 Feature Request

Support the following operators in the view:

- `+=`
- `-=`
- `++`
- `--`
- `*=` 
- `/=`

## 🤔 Expected Behavior

Particularly, this is for event handlers.

```html
<button click.delegate="value++">Increment</button>
```

## 😯 Current Behavior

Throws an error.

**Comment by 3cp** [comment]
add `*=` and `/=`.

**Comment by Vheissu** [comment]
@bigopon @3cp Do we still want to add support for these?

**Comment by bigopon** [comment]
We may want to support it. I'll work out the AST for this before we initiate the parser work for @fkleuver

**Comment by bigopon** [comment]
resolved in #2004
