### ISSUE TITLE
Clarify what `npx` is for newcomers

### ISSUE THREAD

**Issue by LarsKemmann** [aurelia/aurelia#733]
Hi! I noticed your documentation (both in this repo and in the _aurelia/new_ repo) makes mention of a tool called "npx".

What is that?

It's not traditional npm and, yes, I'm going to google it momentarily, but I just wanted to suggest that you not assume too much about what developers new to Aurelia might already be familiar with. Every little bit of non-hurdle helps. Thanks!

**Comment by EisenbergEffect** [comment]
This is good feedback. It's always tricky to find the balance. What if we said something like:

"Using `npx`, a tool installed with Node.js, we can create a new Aurelia 2 app with the command `npx makes aurelia`. `npx` will download the `makes` scaffolding tool, along with the `aurelia` generator, which will use to guide you through the setup process."

**Comment by 3cp** [comment]
Need some small adjustment to make clear it's makes not npx (which the current sentence implies) downloading `aurelia` generator.

**Comment by matthewcorven** [comment]
I could be wrong but I believe that NPX is not installed with node, the developer has to install it globally on their own.

**Comment by 3cp** [comment]
npx is included in npm.

https://github.com/npm/cli/blob/3e7ed30d6e9211e39bd93ec4e254cc5a2b159947/package.json#L31-L33

**Comment by 3cp** [comment]
> a tool installed with Node.js

Not very clear it's already installed in default nodejs. Maybe "a tool provided by Node.js"?

**Comment by 3cp** [comment]
Should also add a link to original introduction of npx.

https://medium.com/@maybekatz/introducing-npx-an-npm-package-runner-55f7d4bd282b

**Comment by EisenbergEffect** [comment]
"Using [npx](https://medium.com/@maybekatz/introducing-npx-an-npm-package-runner-55f7d4bd282b), a tool distributed as part of Node.js, we can create a new Aurelia 2 app. At a command prompt, run the command `npx makes aurelia`. This will cause `npx` to download the `makes` scaffolding tool, along with the `aurelia` generator, which it will use to guide you through the setup process."

**Comment by LarsKemmann** [comment]
Wow. Can I just say the Aurelia team rocks? :) Thanks for the quick response on this! I'm so excited to start trying out v2!!

**Comment by EisenbergEffect** [comment]
Thank you @LarsKemmann We're a passionate group of people who genuinely believe in the work we're doing and genuinely care for the people in our community. We aren't always able to respond so quickly or effectively, but we do try the best we're able. Glad to have you here and we really appreciate the feedback. I'll take this wording and push it into the few places we have it, most likely a bit later this evening.

**Comment by EisenbergEffect** [comment]
Erm...I almost forgot I need to take the kids trick or treating...so might be an extra day on this one 🤣

**Comment by EisenbergEffect** [comment]
Ok, I ended up getting time to take care of this. I think I've updated all the relevant locations. Thanks again for the feedback!
