### ISSUE TITLE
Error from terser when building application

### ISSUE THREAD

**Issue by ah1508** [aurelia/aurelia#735]
When using `npx makes`, the project cannot be built with `npm run-script build`, terser throw an error because of two semicolons in file /node_modules/@aurelia/runtime/dist/esnext/binding/property-binding.js : 

```
ERROR in main.js from Terser
Unexpected token: punc (;) [./node_modules/@aurelia/runtime/dist/esnext/binding/property-binding.js:27,0][main.js:5669,4]
```

Indeed : 

```javascript
    constructor(sourceExpression, target, targetProperty, mode, observerLocator, locator) {
      // code
    }
    ;
    ;
    updateTarget(value, flags) {
      // code
    }
```
Removing the second one, or both, solves the issue but I guess the fix has to be made on the ts source file.

**Comment by fkleuver** [comment]
The fix will be on npm in about 10 minutes. Thanks for reporting! Let us know if there are any issues remaining

**Comment by fkleuver** [comment]
I should point out here that, while sloppy on our side, this is a bug in terser because a semicolon is a [valid class element](http://www.ecma-international.org/ecma-262/#prod-ClassElement). I'm filing an issue with them as well.

**Comment by fkleuver** [comment]
FYI: https://github.com/terser/terser/issues/505
