### ISSUE TITLE
Make binding and templating more intelligent with information from to the w3/whatwg specs

### ISSUE THREAD

**Issue by fkleuver** [aurelia/aurelia#75]
Just some notes:

- Defaults/conventions for input element attributes: 
    - https://www.w3.org/TR/html52/sec-forms.html#common-input-element-attributes
- Look into `document.createRange` as an alternative for / supplement to using document fragments
- Look into edge cases for content editable:
    - https://www.w3.org/TR/html52/editing.html#making-document-regions-editable-the-contenteditable-content-attribute
- Look into making HTML commands first-class citizens:
    - https://www.w3.org/TR/html52/interactive-elements.html#commands
- Look into making HTML element activation as a concept a first-class citizen (activationEvents are `change`, `click`, `contextmenu`, `dblclick`, `mouseup`, `pointerup`, `reset`, `submit`, `touchend`): 
    - https://www.w3.org/TR/html52/editing.html#activation-behavior
    - https://html.spec.whatwg.org/#activation
    - https://dom.spec.whatwg.org/#eventtarget-activation-behavior
- Review event handling:
    - https://dom.spec.whatwg.org/#concept-event-dispatch
    - https://developer.mozilla.org/en-US/docs/Web/API/EventTarget
    - https://w3c.github.io/input-events/index.html#event-definitions
- Make templating / two-way bindings aware of (and more intelligent about) input modes (`none`, `text`, `tel`, `url`, `email`, `numeric`, `decimal`, `search`):
    - https://html.spec.whatwg.org/#input-modalities:-the-inputmode-attribute

**Comment by fkleuver** [comment]
In response to https://github.com/aurelia/binding/issues/347

@EisenbergEffect 
I'm thinking about a specialized `InputObserver` instead of the generic `ValueAttributeObserver` to handle `input` elements, since they have so many special behaviors and edge cases.
- There are about 25 different `type` attributes (making up 15 different types of values that an input may have).
- In addition there are about 25 content attributes that affect the constraints of these values
- And a total of 9 attributes whose value can be changed from the UI (meaning they can be two-way bound)

It's not just the `input` element (although that is by far the biggest one). Several other elements also have behaviors that vCurrent isn't explicitly dealing with.
Building all of the behavior in is sure to take up quite some library space so we need to make sure it can be tree-shaken, which means a loosely-coupled configuration class that can be injected into observers at startup might be a good way to go.

As I discussed with @bigopon I have a similar idea in mind for `ObserverLocator`. Many edge cases it doesn't deal with, several cases it simply gets wrong. They're not particularly common but when they do surface, they're ugly. We can achieve 100% without sacrificing library size, by making them externally configurable so the unused configuration can be tree-shaken.

**Comment by EisenbergEffect** [comment]
Thanks for updating this here. The approach makes sense. I also think that they should have to opt-out to keep the strings. In most cases I don't think people will want that. Note, we should consider how this relates to validation as well.

**Comment by fkleuver** [comment]
With respect to validation, inputs always have a [validity](https://developer.mozilla.org/en-US/docs/Web/API/ValidityState) property that has the appropriate indicators based on the native constraints you put on them. With a `validity.bind` (that translates to `validity.from-view`) we can expose the native html validation behavior in the core pretty much without adding any special code.
Then for a separate validation library, to degree that vCurrent's validation library doesn't already do this, we can build on top of that and stick close to the conventions of native validation. One more for the argument "if you learn Aurelia, you learn native html/js"

**Comment by davismj** [comment]
do you want me to write specs / docs for how this should work, either with ownership or as a jumping off point for you

**Comment by fkleuver** [comment]
With regards to this issue: https://github.com/aurelia/aurelia/issues/368 I think it would be nice to get a little baseline, but don't spend too much time on it though because ultimately a lot of this stuff I can simply take from the html specs.

**Comment by bigopon** [comment]
We have good enough input/text/content editable change handling. I don't think intuitiveness wise we have a problem here. 
Existing capability example:
![image](https://user-images.githubusercontent.com/9994529/226518843-07d744b6-cfba-4b19-ba16-ba99a1e31a9c.png)

There' enough extension points to teach Aurelia to handle various properties. Any improvement should clarify what can be done clearer.
