### ISSUE TITLE
Proxies for array.length and array[index] observation

### ISSUE THREAD

**Issue by fkleuver** [aurelia/aurelia#76]
I have been experimenting with this but it will be more involved than simply adding it on top of the existing observation infrastructure (in which case it breaks). Creating an issue for this because I've been procrastinating on this and I would welcome any suggestions.

**Comment by bigopon** [comment]
In order to have full observation, normal code needs to work on proxied array, instead of the raw array. So I think it's the matter of a documentation: if `array.length / array[index]` usage needs to be observable, then wrap the array with our provided `ProxyObserver`, some pseudo code:

```js
export class App {
  // items = []; // this can't work
  items = ProxyObserver.for([]);
  
  get stuff() {
    return this.items.filter(item => item.isStuff)
  }

  removeAllStuff() {
    this.items.length = 0; // this works instead of this.items.splice(0);
  }
}
```

**Comment by fkleuver** [comment]
This actually already works under the hood without explicitly needing to do that, I believe I just need to hook up the length observer still.

**Comment by bigopon** [comment]
Implicit observation is supported on read access. It's the write that isn't easily supported. I think we either have to force wrapping or use splice. Using splice is a much easier/safer way to teach/understand than forced wrapping.
