### ISSUE TITLE
'Bindable' watchers not invoked, when a vue model has a bind function

### ISSUE THREAD

**Issue by mklef121** [aurelia/aurelia#799]
# 🐛 Bug Report

I have a bindable called "players" passed into an custom element, set some event listeners at the "bind" function of the view model I decided to  run some step on the first call of  of "playersChanged" function which is a watcher for the bindable, This watcher was never called at component instantiation, But when I removed the "bind" function, the "playersChanged" watcher was called.

## 🤔 Expected Behavior

The watcher should be called on component instantiation, in case a user wants to make use of the initial value of the bindable at instantiation of the view model.

## 😯 Current Behavior
The  "playersChanged" watcher for the "players" bindable is not called on view model instantiation when a "bind" ` component life cycle` function is available

####### This Fails
     @useView(PLATFORM.moduleName("./views/player-row.html"))
     export class playerRow implements IViewModels  {
     @bindable
      public players:Iplayer[] = [];
      //This function is not called on component instantiation since the bind function is present
      // When the bind function is removed or commented, it is called
      public playersChanged(players:Iplayer[]){
		// console.log("player Change called");
		this.playersCopy = utils.alphaSort<Iplayer>(players, 'name');
      }

     public bind(): void{
		
		document.addEventListener("click", this.clickHandler);
	

	}
     }

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          |   "version": "0.1.0",
| Language         | Typescript
| Browser          | Firefox
| Bundler          |  Webpack
| Operating System | Ubuntu 18
| NPM/Node/Yarn    | NPM

**Comment by EisenbergEffect** [comment]
Based on the code sample, this appears to be an Aurelia v1 issue. This is the Aurelia v2 repo, where we have made significant improvements and fixes to bindables and the lifecycle, including better consistency for this specific use case. We are unable to make these changes in v1, as it would be a major breaking change (hence the fix is in v2).
