### ISSUE TITLE
Rework Binding/Ref/Call/Listener and/or deprecate BindingMode

### ISSUE THREAD

**Issue by fkleuver** [aurelia/aurelia#80]
We could consider deprecating `BindingMode` and merging it into `BindingFlags`, or simply renaming it to `BindingCommand`. There is overlap and they serve the same purpose: add contextual information about a binding command for the `IBinding` implementor.
We might be able to have a single `Binding` class that handles all commands, or at least have less duplicated code across them and reuse logic via decorators. I thought about applying `@binding` or `@bindingCommand` to a class that handles a binding / binding command.

We could also go in the opposite direction: completely remove the contextual information from the flags, remove `BindingMode`, not have a `BindingCommand`, but simply have a separate `IBindingCommand` implementor for each command. So there will be a specialized `ToViewBinding`, `TwoWayBinding`, `FromViewBinding`, `CallBinding`, etc for each command. This would likely be a fair performance improvement because less checks need to happen, and we might be able to do this without adding a lot of code, by reusing logic in decorators.

I don't think backwards compatibility would suffer too much from this because we can have a fairly thin compatibility adaption layer to make some translations if need be.

I need to experiment with both of these, but in the meantime any thoughts are welcome.

**Comment by EisenbergEffect** [comment]
I think we should avoid merging all this into `BindingFlags`. I'm worried about that becoming a dumping ground for everything. It seems to me that things like ref, call, binding, etc. are of a different nature than the binding flags. I'd be interested in adding `BindingCommand` as an explicit concept.

**Comment by fkleuver** [comment]
@EisenbergEffect @bigopon @davismj The binding commands were already addressed a while ago and the binding mode is staying as is, so I'm closing this as it doesn't have any open todo's anymore
