### ISSUE TITLE
How to bind to SVG Attributs in Aurelia 2?

### ISSUE THREAD

**Issue by akesser** [aurelia/aurelia#812]
# Issue

Im trying to bind to an svg Attribute in Aurelia2 with the following view:
```html
<svg width="300" height="300">
<circle cy.bind="cx" cy="150" r=10></circle>
</svg>
```
And the following view-model
```typescript
export class MyApp {
  public cx = 100;
}
```

I found the plugin-svg plugin, but I am not sure I am using it in the correct way:

```typescript
import Aurelia, { StyleConfiguration } from 'aurelia';
import { MyApp } from './my-app';
import  { register } from '@aurelia/plugin-svg';

Aurelia.register(StyleConfiguration.shadowDOM(), register)
.app(MyApp).start();
```

## 🤔 Expected Behavior

The attribute should be bound to the property of the view-model

## 😯 Current Behavior

In the browser I get the following error in Safari:

Unhandled Promise Rejection: TypeError: Attempted to assign to readonly property.

In Chrome the errors is shown like this:

Uncaught (in promise) TypeError: Cannot assign to read only property 'cy' of object '#<SVGCircleElement>'

Thank You for Your Help

Viele Grüße

-akesser-

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | dev
| Language         |
| Browser          | safari 13.0.4 / chrome 79.0.3935
| Bundler          | web pack
| Operating System |
| NPM/Node/Yarn    |

**Comment by timfish** [comment]
I haven't tried your code so I might be completely wrong... but it looks like you've defined the `cy` attribute twice whereas I'm guessing it should be `cx.bind`:

```html
<svg width="300" height="300">
  <circle cx.bind="cx" cy="150" r=10></circle>
</svg>
```

**Comment by akesser** [comment]
Oh, 
that's my fault with the example. But even without the typo
```html
<svg width="300" height="300">
  <circle cx.bind="cx" cy="150" r="10"></circle>
</svg>
```
the error is the same

**Comment by bigopon** [comment]
@akesser thanks fo reporting this. A fix will come soon. this is because we haven't put in proper svg attributes recognition yet

**Comment by fkleuver** [comment]
@akesser Apologies for the delayed response. The SVG plugin registration API hasn't been updated for a while so the registration mechanism is still a but message. Could you try this?
```ts
Aurelia.register(StyleConfiguration.shadowDOM(), { register }) // add braces to turn it into an `IRegistry` compliant object
                                                 ^          ^
.app(MyApp).start();
```

**Comment by akesser** [comment]
You don't have to apologise, I appreciate the work of all of you to make Aurelia 2 even more fantastic than Aurelia 1.

To my error:

Your suggested fix turning the register function to an object does not work, I still get the same error.

**Comment by arjendeblok** [comment]
I have the same problem. It works fine in v1. But v2 tries to set the cx attribute on the SVGCircleElement interface which is read-only (ElementPropertyAccessor.flushChanges). 
It should use `circle.setAttribute("cx", value);`

**Comment by arjendeblok** [comment]
Found the solution: 

`npm i @aurelia/plugin-svg`

in main.ts
```typescript
import { register } from '@aurelia/plugin-svg';

var registerSVG = {
  register: register
};

Aurelia
  .register(registerSVG)
  .app(MyApp)
  .start();
``

**Comment by bigopon** [comment]
This should already be working fine.
