### ISSUE TITLE
Implement destructuring in the AST

### ISSUE THREAD

**Issue by fkleuver** [aurelia/aurelia#82]
The classes are already there (see `ArrayBindingPattern` and `ObjectBindingPattern`), but the parsing might need a few tweaks and the logic still needs to be implemented.

The idea is this, consider `repeat.for="{ prop1, prop2: { prop2Child1, prop2Child2 } }"`. This can be done in a fully spec-compliant manner with the existing array and object literal parsing logic that we already have in place.
All that the AST nodes need to do is recursively loop through the keys in the `BindingPattern` and flatten+assign them to the `BindingContext`. The question is: what should `evaluate` do? Actually do the assignment, or just return a nested key + flat key mapping? Or should `assign` take care of it? Maybe add a new method instead, such as `destructure`? Needs experimenting

**Comment by bigopon** [comment]
I would love to see @EisenbergEffect thought on this

**Comment by EisenbergEffect** [comment]
It's not a critical scenario for me. I'm open to adding this but I think I'd want to get our core system rock solid. I guess I'd consider this more of a "bell and whistle" feature for the binding language. I'm not sure what the best path to implementation would be. Whatever it is, we don't want to get into situations where the developers is hitting unexpected behavior or things aren't updating like they think they should. I don't really have strong opinions beyond these.

**Comment by bigopon** [comment]
This is not a critical scenario, also we support the main one which is map destructuring. If it's necessary, we can open a new issue for this.
