### ISSUE TITLE
Implement rest/spread operators

### ISSUE THREAD

**Issue by fkleuver** [aurelia/aurelia#83]
We have `Assign`, so I think this also belongs in our expression syntax. It's easy to implement, just needs a `DotDotDotToken` in the parser, a small tweak to the scanning logic and possibly a new AST node.

**Comment by bigopon** [comment]
For reference, this is my old attempt: https://github.com/aurelia/binding/pull/647

It no longer works due to Lexer and Scanner being removed. But the main point to keep in mind is @jdanyow [comment](https://github.com/aurelia/binding/pull/647#issuecomment-343789874)

> I'm worried about adding something like this without being able to support common scenarios. I'm afraid it will cause a lot of confusion when simple things like foo.bind="{ ...myArray }" doesn't update when the array mutates or when foo.bind="[ ...myObj ] doesn't update when a property is added.

> Today we have a almost entirely clean distinction between property observation and collection mutation observation. Adding something like this is either going to fall short of expectations or force us to mix property observation and collection observation with a healthy dose of dirty-checking to cover all the scenarios.

**Comment by fkleuver** [comment]
Yeah those are good points. I would run into them and systematically try to cover all the scenarios through a few iterations.

My view on this is pretty straightforward I think: spread operator means that the whole object or array is expanded and each individual property (or element) assigned to the target context. Therefore each individual property or element is also observed.
For an object that means having a property observer on each property, for an array that means a collection observer for the elements (optionally a proxy as well) + instance observer for the object itself.
Now that we have proxies, properties being added is something we can account for without too much hassle. So we wouldn't need dirty checking.
The implementation might be large enough however to make it a better fit for a separate plugin.

**Comment by fkleuver** [comment]
I'm closing this because even if it were to be implemented, this would happen at a *very* late stage. Better to keep the issue list a bit more tidy and reopen later if there is a need.
