### ISSUE TITLE
Metadata.getOwn does not behave in the same way as Reflect.getOwnMetadata, when passing 'design:paramtypes'

### ISSUE THREAD

**Issue by xenoterracide** [aurelia/aurelia#833]
I've written this little "test"
```
const reflectKeys = Reflect.getMetadataKeys(OrderService).map( (k) => Reflect.getOwnMetadata(k, OrderService));
  let getOwnKeys = Metadata.getOwnKeys(OrderService).map((k) => Metadata.getOwn(k, OrderService));
  const dependencies = DI.getDependencies(OrderService);

  root.get<Logger>(LoggerDefault).info( 'Reflect %O Metadata %O Dependencies %O', reflectKeys, getOwnKeys, dependencies);
```
```
info:     Reflect [
  [
    [Function: AmqpSender] { register: [Function: register] },
    [Function: Object] --- must be 'LoggerDefault`
  ]
] Metadata [
  [ <1 empty item>, 'LoggerDefault' ],
  [ 'au:annotation:di:paramtypes', 'au:annotation:di:dependencies' ]
] Dependencies [ <1 empty item>, 'LoggerDefault' ]
```

So here's `AmqpSender`
```ts
@singleton()
export class AmqpSender implements Sender<any, void> {
  constructor(
    @inject(LoggerDefault) private readonly log: Logger,
    @inject(AmqpChannel) private readonly channel: Channel,
  ) {}

  async send(exchange: Exchange, message: AggregateEvent<any, any>): Promise<void> {
    this.log.silly('publishing to %s %j', exchange, message);
    if (!this.channel.publish(exchange, message.type, Buffer.from(JSON.stringify(message)))) {
      this.log.error('failed to publish %s %j', exchange, message);
    }
  }
}
```

and more importantly, what's needed from `OrderService`

```ts
@singleton()
export class OrderService {
  constructor(
    private readonly sender: AmqpSender,
    @inject(LoggerDefault) private readonly log: Logger,
  ) {}
```

this is what's in `tsconfig`

```
{
  "compilerOptions": {
    "outDir": "build",
    "target": "es2018",
    "module": "commonjs",
    "lib": [
      "es2018"
    ],
    "moduleResolution": "node",
    "declaration": true,
    "strict": true,
    "esModuleInterop": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true,
    "resolveJsonModule": true
  },
  "include": [
    "src/**/*"
  ],
  "exclude": [
    "node_modules"
  ],
  "plugins": [
    {
      "name": "@divyenduz/ts-graphql-plugin"
    }
  ]
}
```

## 🌍 Your Environment

this is a node app, no browser involved
```
Darwin Calebs-MBP 18.7.0 Darwin Kernel Version 18.7.0: Thu Jan 23 06:52:12 PST 2020; root:xnu-4903.278.25~1/RELEASE_X86_64 x86_64
v12.15.0
yarn list v1.21.1
warning ../package.json: No license field
warning Filtering by arguments is deprecated. Please use the pattern option instead.
├─ @aurelia/kernel@0.7.0-dev.202004012038
└─ typescript@3.7.4
✨  Done in 1.00s.
```

## Workaround

I updated `dist/umd/di.js` to have the below and it fixes all my problems with this feature

```
        getDesignParamtypes(Type) {
            const meta =  Reflect.getOwnMetadata('design:paramtypes', Type);
            return meta;
        },
```

---

further investigation suggests that the additional data is being populated with  `Reflect.decorate`, but `Meta.decorate` is never being called

---

looks like `$define` is never called with `design:paramtypes`

---

neither is `metadata` which is also being called for me as a I breakpoint.

---

looking at the js of my service, it does have this

```js
OrderService = __decorate([
    kernel_1.singleton(),
    __param(1, kernel_1.inject(LoggerProvider_1.LoggerDefault)),
    __metadata("design:paramtypes", [AmqpSender_1.AmqpSender, Object])
], OrderService);
```

**Comment by xenoterracide** [comment]
yes it does, though not with the same parameters, I don't actually ever see Metadata use `design:paramtypes` except when `DI.getDependencies` is called. I have an idea about how to fix this... after digging through it all day. It'll probably be the wrong idea... but we'll see, working on a patch now.

**Comment by fkleuver** [comment]
> though not with the same parameters

What's different then?

> after digging through it all day

Oh wow. Really appreciate the effort! Should you run out of time/energy to spend on this, by all means feel free to just provide a simple repro and I'll be more than happy to look into it.

**Comment by xenoterracide** [comment]
the parameters that I see running are for `au:something`, but never `design:paramtypes`

**Comment by fkleuver** [comment]
That would be correct in all situations *except* for `DI.getDependencies`. That call specifically retrieves the metadata that's assigned by tslib's `__decorate` calls. After that, Aurelia gets out of the way and prefixes everything it stores.

What you'd need to verify is whether that emitted `__decorate` block actually goes into the `$define` function that lives in `metadata.ts`. If not, then `Reflect` is apparently not patched by metadata before tslib gets to it and tslib falls back to its own static property based polyfill.

**Comment by xenoterracide** [comment]
So it looks like the problem is if `reflect-metadata` is loaded before, that'll cause this issue.

**Comment by fkleuver** [comment]
So as we discussed on Discord the solution is to simply get rid of the `reflect-metadata` polyfill. I'll keep this issue open as a todo for letting `@aurelia/metadata` detect this situation and reporting on it accordingly.

Important to note: `@aurelia/metadata` is based on `reflect-metadata`. They both polyfill the same `Reflect` apis.
The "problem" is that I wrote `@aurelia/metadata` in such a way that it only patches `Reflect` if it wasn't already patched by another polyfill, and only throws if the polyfill is incomplete. `reflect-metadata` is a complete polyfill but it does have some subtle bugs which I found out on re-reading the specs and adding additional tests.

Therefore, the real solution is probably to just throw whenever anything else already patched `Reflect` because chances are that our `@aurelia/metadata` is currently the most robust polyfill out there.

**Comment by xenoterracide** [comment]
also for future people, if you want to use the full `Reflect` api, but `@aurelia/metadata` you can add 'reflect-metadata' as a dev dependency, and then import like so.

```ts
/// <reference types="reflect-metadata" />
import from '@aurelia/metadata';
```

**Comment by fkleuver** [comment]
Fixed by https://github.com/aurelia/aurelia/pull/907
