### ISSUE TITLE
i18n: Fetch backend doesn't have typescript bindings

### ISSUE THREAD

**Issue by xenoterracide** [aurelia/aurelia#847]
unless I did something wrong, adding the fetch backend as documented doesn't work if using typescript as it has no types.

https://docs.aurelia.io/app-basics/internationalization#i-18-next-backend-plugin

I created a downstream bug, but would be nice to see this fixed someway or another before release https://github.com/perrin4869/i18next-fetch-backend/issues/43

**Comment by Sayan751** [comment]
@xenoterracide When you say "doesn't work", is TS generating any compilation error or it does not work at all in runtime?

If it is TS compilation error, then the right course of action would be to submit a PR for the package in https://github.com/DefinitelyTyped/DefinitelyTyped.

**Comment by Sayan751** [comment]
Also there is this http backend as well with type definitions. https://github.com/i18next/i18next-http-backend
This should also work for fetching the resources.

**Comment by xenoterracide** [comment]
it doesn't compile, honestly DefinitelyTyped is an option, but I think of that as a last resort these days, if you can't get the author to bundle them, themselves. Either way, I think someone (maybe me) should get around to this before GA (personal opinion that the docs should also work with TS)

**Comment by Sayan751** [comment]
It seems the Authors are not interested in adding TS support. Refer: https://github.com/perrin4869/i18next-fetch-backend/issues/37

In that case we can do very little other than creating a custom type definition for it. I may give it a try in few days. But currently, my hands are full.

**Comment by xenoterracide** [comment]
yeah, I'm in no rush, otherwise I might too ;).

**Comment by perrin4869** [comment]
Hey guys, I'm not very well versed in `typescript` toolchain, but if there is a way to include the typings without changing the current workflow (keep `rollup` and the typings separate from the source code) I am willing to package them together

**Comment by xenoterracide** [comment]
yes, we can create a typescript definition file, which is separate from the other source code

**Comment by perrin4869** [comment]
Cool! If you drop me a PR I'll review quickly and publish a minor upgrade

**Comment by Sayan751** [comment]
@xenoterracide Thanks for opening this issue. I tried to have the type defs in place for this in last November, but slipped my mind to bring it to completion :P

**Comment by perrin4869** [comment]
Thanks for the PR, hope this is useful to you guys!
Published as `2.3.0`, please confirm that everything is working as expected.

**Comment by Sayan751** [comment]
@xenoterracide This should be fixed with #859, combined with https://github.com/perrin4869/i18next-fetch-backend/pull/44. The new dev version is out, you can give it a try.

**Comment by xenoterracide** [comment]
I will just as soon as I'm done with #837
