### ISSUE TITLE
Add convenient title support

### ISSUE THREAD

**Issue by xenoterracide** [aurelia/aurelia#848]
it seems that it is not easy to add a `<title>` in Aurelia 2, or at least not if you're using convention based routing, it might still be easy using explicit routing... but I haven't actually figured that out (it's not `RouterConfiguration.customize({ title: 'myTitle' })`. @bigopon suggested

```html
<title portal="head">my title</title>
```
but this doesn't work because a `<title>` already exists in `<head>` and there should not be 2 (also it appears that chrome at least takes the first).

However, Something like portal, or perhaps extending portal seems like a good fit, as it seems to fit nicely in an html template, and without needing a view model.

I suggested maybe

```html
<title replaceIn="head">... 
```
or even a crazier, just support xpath (no this is probably dumb, and I'm not sure it would work even if you did do it)

```html
 <title xpath="//title[translate(text(), text() 'my title' )]">
```

or maybe as suggested by @bigopon 

```html
<title portal="target: head; replace.bind: true" />
```

honestly, I don't care what, but updating the title per route which was easy in aurelia 1 should be easy in aurelia 2 even using convention based routing.

**Comment by bigopon** [comment]
We would have some api like this, to align with `insertAdjacentHTML` api (https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentHTML):
```html
<title portal="target: head; position: afterbegin">
```

**Comment by 3cp** [comment]
I think the requested `replace` feature sounds good. But not sure about the complication on router, as router also touch the title element.

**Comment by jwx** [comment]
It should be fine from the perspective of the router since the router isn't planned to use the title element.

**Comment by Sayan751** [comment]
Closing this as both [router](https://docs.aurelia.io/getting-to-know-aurelia/routing/aurelia-router/getting-started#customizing-the-title) and [router-lite](https://docs.aurelia.io/getting-to-know-aurelia/routing/aurelia-router-lite/router-configuration#customizing-title) provide ways to update the title.
