### ISSUE TITLE
kernel: better logging options for expensive calls

### ISSUE THREAD

**Issue by xenoterracide** [aurelia/aurelia#849]
promises usually back expensive calls, and you may not want to run them if you're not logging at their level. I propose 2 solutions, 1 add "is" methods to `ILogger`

e.g.

```ts
const log: ILogger = ...
if ( log.isDebug() ) {
    const thing = await getThing()
    log.debug( 'thing', await thing.lazyList() );
} 
```
however, this is very verbose, though I think it would be good if you actually needed to multiple steps. This approach also

additionally I think adding simple support for returning promises in the callback approach would also be good

```ts
log.debug( async () => util.format('%O', await thing.lazyList() );
```
the underlying implementation would detect the promise and log after a then or reject at the same level.

**Comment by fkleuver** [comment]
Promise support seems fine by me.
The `isDebug` thing makes sense, but I'm reluctant on adding API surface like that this early. It would be trivial to extend the logger with this functionality:
```ts
export interface IExtendedLogger extends ILogger {
  readonly isDebug: boolean;
}
export class ExtendedLogger extends DefaultLogger implements IExtendedLogger {
  public get isDebug(): boolean {
    return this.config.level <= LogLevel.debug;
  }
}
```

And then register it.

**Comment by Sayan751** [comment]
@fkleuver I feel a bit differently on this issue. Making an`async` call for debugging might not usually get pushed to production. 

On the other hand, if the data returned from the `async` operation is indeed used later in the code, then it is not purely for debugging purpose. That needs to be properly awaited and handled. Considering that, before logging any `async` operation can be `await`ed and then logged. 

The async logging is bit confusing. IMO logging should simply be a way to capture "interesting" events for future audit and troubleshoot.

**Comment by fkleuver** [comment]
Yeah having given it some more thought, I'm inclined to agree. Logging should be used for information the app already has, not to fetch information from somewhere else.

**Comment by Sayan751** [comment]
@bigopon Can this be closed?

**Comment by bigopon** [comment]
Lets close for bow. Im not sure if we need it immediately.
