### ISSUE TITLE
Metadata: provide Reflect apis

### ISSUE THREAD

**Issue by xenoterracide** [aurelia/aurelia#850]
> if you want to use the full `Reflect` api, but `@aurelia/metadata` you can add 'reflect-metadata' as a dev dependency, and then import like so.

```ts
/// <reference types="reflect-metadata" />
import from '@aurelia/metadata';
```

this is dumb, `@aurelia/metadata` imho, should just provide the full `Reflect` api, unless I'm missing something about why it shouldn't.

**Comment by fkleuver** [comment]
Why not just use the `Metadata` api?

**Comment by xenoterracide** [comment]
you could but, standards I guess... isn't the `Reflect` api part of some spec? just seems like a nice feature to have.

**Comment by fkleuver** [comment]
Yeah an early stage one, but I've noticed a fair amount of reluctance to actually push through with it. TS folks want to do it but chromium folks are worried about performance. Anyway, the `Metadata` api is an exact copy of the `Reflect` api in every way (they refer to the same functions). I don't have anything against including the `Reflect` type defs, but in the framework we also use `Metadata` instead. `Reflect` is mainly patched for things like tslib

**Comment by xenoterracide** [comment]
I don't feel super strongly about this, I guess maybe my point of confusion request is 

```
/// <reference types="reflect-metadata" />
```
and that aurelia itself has `reflect-metadata` as a direct dev dependency.
