### ISSUE TITLE
repeat.for doesn't work on all Iterable's

### ISSUE THREAD

**Issue by xenoterracide** [aurelia/aurelia#851]
maybe it can't but I think it should... the other day I was trying to iterate over collections from 
https://www.npmjs.com/package/jstreemap I thought it should work, but it didn't
```
Uncaught (in promise) Error: Code 0: Cannot add observers to object.
    at Object.error (reporter.js:39)
    at ForOfStatement.iterate (ast.js:939)
    at Repeat.normalizeToArray (repeat.js:175)
    at Repeat.beforeBind (repeat.js:37)
    at Controller.bindCustomAttribute (controller.js:399)
    at Controller.bind (controller.js:257)
    at Controller.bindControllers (controller.js:453)
    at Controller.bindBindings (controller.js:443)
    at Controller.bindCustomElement (controller.js:379)
    at Controller.bind (controller.js:255)
```

simple repro

```html
  <ul>
    <li repeat.for="e of set">${e}</li>
  </ul>
```

```ts
  set = new TreeSet();
  constructor() {
    this.set.add('c');
    this.set.add('a');
    this.set.add('b');
  }
```

**Comment by fkleuver** [comment]
We *could* add support for all iterables, at least for rendering. I'll add this to the backlog.

However, we can't do out-of-the-box collection observation on arbitrary 3rd party types because we have no way of knowing all the ways in which those types can be mutated. So change notification would have to be triggered by hand whenever you modify the collection.

**Comment by atSridharIyer** [comment]
Is this a related issue? Has repeat.for been partly disabled in Aurelia 2 latest and dev releases?
The following code from guide does not work and no errors reported.
 <p repeat.for="[greeting, friend] of friends">${greeting}, ${friend.name}!</p>
Only basic repeats (and with arrays) work.

**Comment by atSridharIyer** [comment]
Is this a related issue? Has repeat.for been partly disabled in Aurelia 2 latest and dev releases?
The following code from guide does not work and no errors are reported.
` <p repeat.for="[greeting, friend] of friends">${greeting}, ${friend.name}!</p>`
Only basic repeats (and the ones with arrays) seem to work.

**Comment by bigopon** [comment]
The template
```html
<p repeat.for="[greeting, friend] of friends">${greeting}, ${friend.name}!</p>
```
requires destructuring for each of the item in the collection. That's what we don't have at the moment, as we want to do it in a more formal way (real destructuring). For now, you can do;
```html
<p repeat.for="pair of friends">${pair[0]}, ${pair[1]}!</p>
```

**Comment by atSridharIyer** [comment]
What I eventually want to do with Aurelia 2 is this:
```
<div repeat.for="[name,values] of nameToValuesMap">
    <div>
        <div>
            ${name}
        </div>
        <div>
        <a repeat.for="value of values" >${value}</a>
        </div>
    </div>
</div>
```
Will something like this work in the beta release?
What would be the best work around for this structure right now with the alpha?

**Comment by atSridharIyer** [comment]
Ok. So using your `<p repeat.for="pair of friends">${pair[0]}, ${pair[1]}!</p>` example above I can use a repeat.for and extract items from pair[1] in the inner loop.
