### ISSUE TITLE
Integration

### ISSUE THREAD

**Issue by bigopon** [aurelia/aurelia#87]
The rendering targets that should be easily integrated with vNext, which I hope it will help shape the 
abstraction layer APIs:

* libui for native UI on Windows, Linux & Mac: https://github.com/parro-it/libui-node
* nativescript for native Androi, iOS: https://github.com/NativeScript/NativeScript
* pixi, three, phaser for graphical app

... to be updated

@EisenbergEffect @fkleuver

**Comment by fkleuver** [comment]
You think AOT could play a role here? Replace HTML-specific api calls with the appropriate compatible other UI api calls? Or maybe have separate plugin packages instead and try to keep templating free of HTML as much as possible?

**Comment by EisenbergEffect** [comment]
I think AOT can play a role, but it might be easier if it can be based on a known abstraction pattern. For example `DOM.appendChild(parent, child)` can be implemented to actually work at runtime without any AOT, but it's also possible to have an AOT process convert this into `parent.appendChild(child)` with 100% accuracy. It could also be converted to any other API such as `parent.add(child)` or `child.appendTo(parent)` or whatever the target API supports. But having the `DOM` APIs as known, distinguishable operations, enables us to get it working today without any AOT and later, reliably build an AOT mechanism to produce slightly more optimized code.

**Comment by EisenbergEffect** [comment]
Things have changed a bit, but do you all think we can close this now that we've factored things out to separate rendering?

**Comment by bigopon** [comment]
Yes. Its good for now
