### ISSUE TITLE
Remove the need of having a Js file

### ISSUE THREAD

**Issue by jppianta** [aurelia/aurelia#882]
# 🙋 Feature Request

It would be nice if we could define the module inside the html file as well.

Instead of having two files, one with the model view and the other with the view model, we could have the html file defining both, like this:
```html
<template>
    <div class="message">${message}</div>
    <script>
        export class MyApp {
            message = 'Hello World!';
        }
    </script>
</template>
```

## 🤔 Expected Behavior

Should behave just as like having a js file containing the module.

## 😯 Current Behavior

You must have a js file with the same name describing the logic.

## 💁 Possible Solution

Look for a script tag inside the html and if the module is already defined, don't look for a js file.

## 🔦 Context

I would like to extend Aurelia for another project, and I don't want the user to be worried about JavaScript, so removing the need of a js file would be very helpful.

**Comment by EisenbergEffect** [comment]
@jppianta Take a look at a gist I authored a while back based on the proposed HTML module standard: https://gist.github.com/EisenbergEffect/5b470efa46bdeba953501be1df4c0ad4

Rather than coming up with our own single file component solution, we'd like to adopt the standard as it emerges.

Thoughts?

**Comment by jppianta** [comment]
Works like a charm, that's what I was looking for. Thank you
