### ISSUE TITLE
Cleanup / separate the tests

### ISSUE THREAD

**Issue by fkleuver** [aurelia/aurelia#89]
Some sets of unit tests have gotten a bit too messy and take a long time to run, in particular the observer and repeater tests.
I would propose getting rid of the `unit` subfolder and appending the "suite" name to the file:
- `.unit.spec.ts`
  - Very fast (< 5 seconds total). Stick to the definition of a unit test to the extent that it's practical.
  - Every module that has code, should have a corresponding `.unit.spec.ts`
- `.integration.spec.ts`
  - Relatively slow (up to a minute or more) and thorough
  - Mostly non-kernel/runtime packages, and high-level api's like `aurelia.ts`, `renderer.ts`
- `.smoke.spec.ts`
  - Similar to integration tests, but higher level, fewer in numbers and run fast, making them a good supplement for TDD / watch mode. Typically use jit/aot to cover lots of ground per test. Not sensitive to low-level api changes.
  - Don't need to map to specific files - one file per package (e.g. `runtime.smoke.spec.ts`) could be just fine
- `.regression.spec.ts`
  - Can fall under any of the 3 above categories and more. Target parts of the code base that probably won't change much (if ever) and thus don't need to be verified with every run. Examples: extra thorough variants of the parser and observer tests, and compiler tests that try many combinations of elements/attributes/events/data types.
  - May map to specific files or packages. May also map to issue numbers or pieces of the ES / HTML specs, etc.

Test commands:
- `npm run tdd` - runs the unit and smoke tests in watch mode, for during development. Only a few seconds to finish
- `npm run test` - runs the unit, integration and smoke tests in non-watch mode (single run), for before pushing. CI will also run this on each commit. Up to 2-3 minutes to finish for all packages
- `npm run test:full` - runs all tests. CI will run this on a nightly basis and will only publish a new `dev` version when the tests passed. Up to 30 minutes to finish
- `npm run e2e` - runs the e2e tests (can only be run from within examples that have them). CI will run these on each commit. Might later be split up as well, but no plans for that yet.

@EisenbergEffect @bigopon This is just an initial idea, I don't feel particularly strongly about this. Thoughts?

**Comment by EisenbergEffect** [comment]
This is an interesting idea. I'm wondering if anyone else is doing something like this? Is "regression" really needed or could we get away with just three categories?

**Comment by fkleuver** [comment]
Regression would be home to 3 kinds of tests:
- Tests that are reactive to issues/bug reports (and the corresponding fix)
- Excessively thorough, somewhat redundant (but still useful) loops, to keep the integration tests run time within acceptable boundaries.
- Generated tests that fix/verify certain invariants (constructors, property initializers, input parameter validation, etc) which I plan to add at some point
There are no tests at the moment that I would classify as "regression". This would start evolving after vNext is released and the maintenance starts.

**Comment by fkleuver** [comment]
@EisenbergEffect This issue is largely already addressed (tests are pretty clean compared to what they were back then) and what remains has no clear scope anymore, so I'm closing this as it doesn't add any particular value as a standalone issue in its current form
