### ISSUE TITLE
[RFC]: Local template

### ISSUE THREAD

**Issue by Sayan751** [aurelia/aurelia#891]
# 💬 RFC

Proposal for supporting local templates, and related discussion.

## 🔦 Context

In real-life Aurelia *apps* it is quite common that a custom element ends up getting used in one single custom element. This scenario excludes the reusable component libraries, offering a bunch custom elements.

For example, let's consider this simplistic example of a `person-template`.

```html
<!--person-template-->
${person.lastName}, ${person.firstName}
```
```html
<!--user-info-->

<!--initial display-->
<person-template person.bind="person"></person-template>

<!--in popup-->
<person-template person.bind="person"></person-template>
```
In this hypothetical scenario, this can be used in a CE that shows logged-in user's info in a popup like menu. Let's also assume that the `person-template` CE gets used multiple times in the user info CE. Therefore, having the person template as a CE makes it easier to reuse. However, there is a fair chance that such specialized templates get used only in one CE. Therefore, creating a full-fledged CE for that purpose seems a bit overkill.

An alternative idea is to support local named templates.

## 💻 Examples

With the named template, the example above will look something like this:

```html
<!--user-info-->
<!--define local template-->
<template id="person-template">
  <bindable property="person" mode="toView"></bindable>
  ${person.lastName}, ${person.firstName}
</template>

<!--usages-->
<!--initial display-->
<person-template person.bind="person"></person-template>

<!--in popup-->
<person-template person.bind="person"></person-template>
```

This removes the need of having the template in form of a separate custom element. This approach can be considered analogous to [local functions](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/local-functions). Moreover, local templates offer more freedom in terms of refactoring, as it is already known that this is not used in elsewhere, and the ripple of change is limited to this particular CE.

### More examples

* Local template w/o `bindable`s

```html
<template id="local-template">
  template body
</template>

<local-template></local-template>
```

* Local template with `bindable`s

```html
<template id="local-template">
  <bindable property="prop" mode="bindingMode" attribute="attr"></bindable>
  template body using 'prop'
</template>

<local-template attr.binding-mode="value"></local-template>
```

Note that the attributes used in `bindable`s refer to this:

https://github.com/aurelia/aurelia/blob/685df881206668f4b26185c8e10aef23d0f97ba3/packages/runtime/src/templating/bindable.ts#L17-L24

For a local template, `callback`, `primary`, and `set` probably do not make much sense. The rest should be supported in the `bindable`s in a local template.

## Goals and Non-Goals

From the discussion so far, we can draw the line between the goals and non-goals. 

The **goal is** to reduce the boilerplate code and to promote highly cohesive, better encapsulated components/custom elements.

> Keep the things together that varies together.
> \-Old jungle sayings

The **goal is not** to reuse these local templates in another custom elements. In such cases, the template can be pulled out to a separate full-fledged custom element.

## Open questions

1. What attribute to use as the local template identifier? The examples above use the `id` property as the template identifier. This is also aligned with the [standard usage of `template`s](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template). Alternatives can be `<template name="...">`, `<template custom-element="...">`, etc. 
1. Should a local template, defined in a parent CE, be allowed to be used in nested child CE? Consider the following example.
  ```html
  <!--custom-element-->
  <template id="local-template">
  ...
  </template>

  <another-custom-element>
    <!-- this can be a custom element defined externally or another local template -->
  </another-custom-element>
  ```

  ```html
  <!--another-custom-element-->
  <local-template></local-template>
  ```

  If `another-custom-element` is used elsewhere (other than `custom-element`), then `local-template` might end up getting ignored. The question however is that, when it is used in `custom-element` whether or not to allow such usage of local templates? As outlined above this is also a non-goal.

## Solution Idea

The preliminary idea is to create a custom element with the template body, using the template identifier as custom-element name. The `bindable`s can be stripped from the template definition/body and appropriate metadata can be defined on an anonymous class. The same class is also used while defining the custom element definition. This new custom element can then be registered with the current render context, thereby making it available for future compilation steps.

**Note#1:** Registering with the render context will possibly make the new CE available for the child CEs as well. This brings us back the Q#2 as stated above. If the usage shown in the question is allowed then the advantage of "limited ripple of change" is compromised.
**Note#2:** As the template compilation goes top-to-bottom, any usage of the local template before the definition of the template can end up being non-hydrated. The question is whether that's a reasonable restriction, or the processing of the local templates should be prioritized and thereby effectively hoisting those templates?

[Inspiration from olden days](https://knockoutjs.com/documentation/template-binding.html) :)

**Comment by Vheissu** [comment]
I really like this idea. Takes me back to the early days of JS templating. Instead of ID, you could also use a data attribute as well. `<template data-template="local-template">` I like the idea of the ID attribute and because `<template>` elements only implement Global attributes, using ID would keep it compliant with the browser.

**Comment by bigopon** [comment]
> What attribute to use as the local template identifier? The examples above use the id property as the template identifier. This is also aligned with the standard usage of templates. Alternatives can be <template name="...">, <template custom-element="...">, etc.

I think the identifier attribute should be as clear as possible. For that, I'd go with `custom-attribute`. Some folks may dislike it, because of the lengthiness though.

> Should a local template, defined in a parent CE, be allowed to be used in nested child CE? Consider the following example.

It shouldn't. Otherwise parent may accidentally break child. If parent and child need to have the same custom element, we have an existing solution for this: normal html only element registration. 

For this proposal, maybe add goal/non-goal so that the questions can become clearer? For example, one of the goals could be: reduce boilerplate for simple local component

**Comment by brandonseydel** [comment]
Can this take a function to switch the kind of template by id?

**Comment by Sayan751** [comment]
@bigopon I am now also inclined towards using a different attribute other than `id` to specify the template identifier. My primary reason being that as `id` is a native HTML attribute, a user might want to use that to manually use a template, for whatever reason might be. Au2 using `id` to specify the local template identifier robs the devs of that opportunity. Now I am more inclined towards `custom-element`, or `as-custom-element`.

> using ID would keep it compliant with the browser.

@Vheissu During compilation, the template will be converted to a custom element, so we can even strip the local template from the parent template. From that perspective, having a non-id identifier should work fine as well.

> Can this take a function to switch the kind of template by id?

@brandonseydel Can you please elaborate? Not exactly sure what you meant.

**Comment by Sayan751** [comment]
@bigopon Added a goals section. I think the scope is now well defined.

**Comment by bigopon** [comment]
Nice 👍 

> Note#1: Registering with the render context will possibly make the new CE available for the child CEs as well. This brings us back the Q#2 as stated above. If the usage shown in the question is allowed then the advantage of "limited ripple of change" is compromised.

It shouldn't. At the moment, resources of a view is encapsulated to that view only, as least it's what @fkleuver has fixed for this I believe (also it's the behavior of v1).

> Note#2: As the template compilation goes top-to-bottom, any usage of the local template before the definition of the template can end up being non-hydrated. The question is whether that's a reasonable restriction, or the processing of the local templates should be prioritized and thereby effectively hoisting those templates?

I think we can try to enforce a rule: must be direct child of root `<template/>`, otherwise people are going to define them inside an `if`, or `repeat`. With that, we can easily do a local registration before the compilation process.

**Comment by fkleuver** [comment]
I believe they should remain local to the declaring custom element, just as if they were specified in the `dependencies` array of the declaring custom element's decorator.
This by the way is the automatic behavior anyway when you register a resource: they're stored in a special lookup in the container that is not traversed upwards.

I'd also like these inline templates to be available to the router, just something to keep in mind.

We also need to decide on whether we're going to follow var, let or const declaration semantics.
- With var semantics, we will need a separate pre-compile step to grab any inline templates before doing normal compilation. Multiple templates with the same name would mean only the last one "stays"
- With lexical semantics, we don't need a separate step but we do need to mutate the ResourceModel during compilation. Also re-declaring a template with the same name would give you potentially different definitions at different positions in the template.
- With const semantics, you just need to declare before using, and re-declaring will throw. I'm personally for this one as it would be easiest to reason about.

**Comment by bigopon** [comment]
> We also need to decide on whether we're going to follow var, let or const declaration semantics.

Can we have a hybrid mode so that it has the "hoisting" behavior of "var", but the "semantic" of const? The case in mind is a bit lengthy local template (10 lines), putting them at the end really help focus on the readability

**Comment by Sayan751** [comment]
> This by the way is the automatic behavior anyway when you register a resource: they're stored in a special lookup in the container that is not traversed upwards.

Perfect 👍 

> Can we have a hybrid mode so that it has the "hoisting" behavior of "function", but the "semantic" of const? 

I also thought in that line. I think that will be most clear usage of local templates. I think I can start the work with the info I have, then the way and the difficulties will be clearer.

**Comment by fkleuver** [comment]
Yeah you have a point. So we'll need the pre-compile step for that

**Comment by brandonseydel** [comment]
> @brandonseydel Can you please elaborate? Not exactly sure what you meant.

It seems that if we get this working we can do something more yet...
```ts
html = `<template><table>${renderTableInfo()}</table></template>`;
export class MyCustomElement
{

name = "initialized"

tableRow = `<tr>\${name}</tr>`;
tableData = `<td></td>`

renderTableInfo(info:string){
if(info === '') return tableRow
else return tableData;
}
}

```

**Comment by Sayan751** [comment]
If you pass that function as a bindable property then *probably* that's also possible, using the `.call` syntax. Although that does not change the local template strictly speaking, rather it works via the primitives of CE and bindables.

**Comment by brandonseydel** [comment]
I know having a function return compiled definitions natively is something I want in au2 all the time.  So.  Being you are almost there i think we should pivot it a bit and also supply this.

**Comment by Sayan751** [comment]
I understand that you want to compose the template from JS function programatically/dynamically. I think the function like `processContent` might be more suited for this.

Otherwise, I am not sure if such functions can be invoked during compilation of parent element. If I am not wrong, then such kind of action happen only during rendering. The current idea is to detach the local template from parent and create a CE on the fly. During this step, I am not sure, from where to invoke this template generating function. 

@fkleuver  What do you think?

**Comment by brandonseydel** [comment]
Yea this just sparked conversation.  I really would like to chunk data out in JS and return them to the view.

```html
<repeatable-div repeat.for="i of 5></repeatable-div>
```
```ts
const repeatableDiv = `<div>\${$index}</div>
```
This capability will really appease to people.
