### ISSUE TITLE
The preventDefault behavior is not being called for submit events.

### ISSUE THREAD

**Issue by danfma** [aurelia/aurelia#892]
# 🐛 Bug Report

By following the documentation at (https://docs.aurelia.io/getting-started/handling-events), the `preventDefault` should be called by default, every time that I use a `.delegate` to handle some events.

## 🤔 Expected Behavior

The `.preventDefault` should be called for the `submit` event in a form, so the form won't be submitted automatically.

## 😯 Current Behavior

The form is being submitted anyway.

## 💁 Possible Solution

Follow the current behavior in the documentation or update it.

## 🔦 Context

I was just playing with the current `dev` version of the Aurelia to see it's current evolution.

## 💻 Code Sample

person.ts

```typescript

export class Person {
    constructor(
        public name: string = '', 
        public surname: string = '') {

    }
}

```

my-app.html

```html

<form submit.delegate="add($event)">
    <div>
        <label for="name">Name:</label>
        <input type="text" id="name" value.bind="newPerson.name">
    </div>

    <button type="submit">
        Add Person
    </button>
</form>

```

my-app.ts

```typescript

import { Person } from './models/person';

export class MyApp {
  people = [] as Person[];
  newPerson = new Person();

  add(e: Event) {
    e.preventDefault();
    this.people.push(this.newPerson);
    this.newPerson = new Person();
    console.log('people', this.people);
  }
}

```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | dev        |
| Language         | Typescript |
| Browser          | Chrome     |
| Bundler          | Webpack    |
| Operating System | Windows    |
| NPM/Node/Yarn    | Yarn/Node  |

**Comment by fkleuver** [comment]
Apologies for the delayed follow-up, thanks for reporting this. This is indeed a specific functionality that hasn't been ported from v1 yet. It's on the backlog!

**Comment by bigopon** [comment]
Just putting some note: we should inject the root node of an application in `runtime-html` and add a listener to the submit event, then call `preventDefault()` there. This way apps will remain isolated. This is different behavior with v1, but it should be probably more preferred way.

**Comment by fkleuver** [comment]
Wouldn't `submit.trigger="$event.preventDefault()"` be better anyway?

**Comment by bigopon** [comment]
It may, though I think it would be better if we move this behavior into a plugin for normalizing some of the common surprises like this. Could be:
```ts
import { AppTask } from '@aurelia/runtime-html';

export const INormalization = {
  register(container) {
    AppTask.with(IAppRoot).beforeCreate().call(appHost => {
      // add the v1 prevent default on form submission on appHost here
    });
  }
}
```

**Comment by fkleuver** [comment]
v1 legacy mode config perhaps?

**Comment by bigopon** [comment]
Legacy may be a bit misleading, since it's, to me, more of a set of quality of life stuff

**Comment by fkleuver** [comment]
Then we might as well just make it a `ISinglePageApp`-level setting. W.r.t. earlier comments on isolation, this is implemented now and accessible in various ways. For example the dependency `IEventTarget` is the configurable delegation root (which is also used by `IEventDelegator`). Question is how/where exactly do we put it. I think `beforeActivate` and `beforeDeactivate` might be good?

**Comment by bigopon** [comment]
I'm not sure about that either, many of those behaviors are one off configuration, maybe `beforeCreate`? If the intention is about turning on/off with the app then yeah, maybe activate/deactivate

**Comment by fkleuver** [comment]
Yeah for every `addEventListener` there should be a `removeEventListener`

**Comment by bigopon** [comment]
This is supported via our `compat-v1` package.
