### ISSUE TITLE
Global option to On/Off Shadow DOM for whole application

### ISSUE THREAD

**Issue by HamedFathi** [aurelia/aurelia#898]
#  🙋   Feature Request

I want to be able to globally enable/disable Shadow DOM for all elements. As I talked with @fkleuver, I made this issue as a reminder.

**Comment by Sayan751** [comment]
The PR for `au-slot` is merged. That mimics the slot behavior without shadow DOM. The usage of native `<slot>` brings shadow DOM as expected. Primary examples of `au-slot`s can be found in the PR, but the docs PR will follow. 

Closing this in favor of `au-slot`. Feel free to open and/or continue discussion.
