### ISSUE TITLE
sharedStyles for ShadowDOM does not seem to work?

### ISSUE THREAD

**Issue by mikeesouth** [aurelia/aurelia#904]
# 🐛 Bug Report

I'm trying to use shared styles for ShadowDOM but the shared styles are not applied for my components in the ShadowDOM.
NOTE! I'm very new to aurelia2 and I do not have previous experience with ShadowDOM. I do know that ShadowDOM and shared styles aren't "best friends" but since there is a concept of sharedStyles in the makes skeleton I figured it should work (?) But maybe I've misunderstood the shared styles functionality and if so - please correct me and I will close this issue.

## 🤔 Expected Behavior

If I add a shared style I would expect it to be shared with the shadow dom components.

## 😯 Current Behavior

The shared styles are applied to elements in the index.ejs file but it's not applied for any of the components in the ShadowDOM.

## 💻 Code Sample

https://github.com/mikeesouth/aurelia2-shadow-dom-shared-styles

I've only made one change from the original repo, it is in this commit: [2e74a68](https://github.com/mikeesouth/aurelia2-shadow-dom-shared-styles/commit/2e74a685821a6af319fac4fbe4e6928b92832d28)
I've added a shared style (shared.scss). I've imported it in main.ts according to the commented code in the ShadowDOM example. Finally I've added simple <span> elements that uses this shared style both outside of the ShadowDOM and inside the ShadowDOM. The shared style is applied to the span in the index.ejs file but not the elements in my-app (ShadowDOM) or welcome (non-ShadowDOM component but wrapped inside a ShadowDOM component so it is in the ShadowDOM?).

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | 0.8.0-dev.202006241024 |
| Language         | sv-SE |
| Browser          | Chrome 83 |
| Bundler          | webpack |
| Operating System | Windows |
| NPM/Node/Yarn    |  NPM 6.13.4 |

**Comment by Vheissu** [comment]
Shared styles are working fine in the latest release. I am closing issue.
