### ISSUE TITLE
e2e test scenarios (todos)

### ISSUE THREAD

**Issue by fkleuver** [aurelia/aurelia#906]
Placeholder issue for things that cannot directly be unit or integration tested because they need specific project setups:
- Verify that multiple versions of the same `@aurelia/metadata` module is detected and thrown properly
- Verify that `reflect-metadata` can be prevented from applying itself by specific `applyMetadataPolyfill` options

**Comment by Vheissu** [comment]
Given we removed the `@aurelia/metadata` error message and other changes since this was created, is this issue still needed @fkleuver @bigopon ?

**Comment by bigopon** [comment]
It's fine now. I've resolved it. Metadata will try reusing the existing weakmap if it detects any.
