### ISSUE TITLE
Bug: realworld example not working

### ISSUE THREAD

**Issue by mroeling** [aurelia/aurelia#917]
# 🐛 Bug Report

Realworld example is not working atm.

## 🤔 Expected Behavior

It should at least build properly and show the application in its current state.

## 😯 Current Behavior

The build fails. After build fix error in main.ts, 

```
ERROR in /.../au2-realworldapp/test/realworld/src/app.ts
./src/app.ts
[tsl] ERROR in /.../au2-realworldapp/test/realworld/src/app.ts(48,7)
      TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type '() => true | never[]' is not assignable to parameter of type 'HookFunction'.
      Type '() => true | never[]' is not assignable to type 'BeforeNavigationHookFunction'.
        Type 'true | never[]' is not assignable to type 'Promise<boolean | ViewportInstruction[]>'.
          Type 'true' is not assignable to type 'Promise<boolean | ViewportInstruction[]>'.
```

## 💁 Possible Solution

Working on fix, creating this issue to refer in PR. 

## 🔦 Context

Not applicable

## 💻 Code Sample

Not applicable

## 🌍 Your Environment

Starting application from within the folder, so all according to settings within the folder. Tried both Yarn and Npm, but no differences.

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | master (d425f66) |
| Operating System | WIN10/WSL2/Ubuntu 20.04 |

**Comment by fkleuver** [comment]
Thanks for reporting this. The reason for this failure is due to a breaking change in TS 3.8 or 3.9 (don't recall which one) and this manifestation of that breaking changed slipped our attention due to the realworld app not being included in our CI/CD process. So, the TODO here is to fix the typings and then to include it in CI/CD. Will get to that before alpha.

**Comment by fkleuver** [comment]
This is fixed
