### ISSUE TITLE
afterAttach event firing twice, with <au-viewport default=x> configured

### ISSUE THREAD

**Issue by hanssens** [aurelia/aurelia#922]
# 🐛 Bug Report

The `afterAttach` event, and perhaps other lifecycle events, are triggered twice when using default page route like so:

    <au-viewport default="welcome" fallback="missing"></au-viewport>

<img width="224" alt="CleanShot 2020-08-14 at 15 04 47@2x" src="https://user-images.githubusercontent.com/493382/90252307-868e4c80-de3f-11ea-8612-eeeb016af676.png">

* Cause is the `<au-viewport default=x`
* It only happens when you navigate directly to a secondary page, like /#/About or /#/Welcome. It does not occur when you navigate to the root of the app, effectively triggering the default page. 
* It is quite easy to reproduce by simply doing a page refresh on those pages (see sample further on)
* Enabling/disabling HTML5 pushState routes has no effect.

## 🤔 Expected Behavior

Life cycle events should only trigger once.

## 😯 Current Behavior

Life cycle events are triggered twice, but only after a page refresh.

## 💁 Possible Solution

Originator is using the `default` attribute on the au-viewport, like so:

    <au-viewport default="welcome" fallback="missing"></au-viewport>

Workaround is to omit `default`, like so:

    <au-viewport fallback="missing"></au-viewport>

## 💻 Code Sample

I've setup a barebone, empty sample at https://github.com/hanssens/bug-au2-default-page. 

**Steps to reproduce:**

1. Run the project through `npm start`
2. Open the console - all is fine
3. Refresh the page (Cmd + R, or F5) - lifecycles are now rendered twice

Cause is because you navigated directly to the localhost:9000/#/welcome page. If you go to the root (e.g. localhost:9000) all is well.

Please run the project and inspect the console to see that . 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | dev (not sure how to verify this?)
| Language         | English
| Browser          | Brave 1.12.112 / Chromium: 84.0.4147.125 (Official Build) (64-bit)
| Bundler          | Webpack
| Operating System | macOS
| NPM/Node/Yarn    | NPM

**Comment by fkleuver** [comment]
Thanks for reporting this. We were aware of this issue but for some reason forgot to reply, apologies!
A fix for this (among many other issues) is present in in-progress PRs and will be released this month.

**Comment by fkleuver** [comment]
This is fixed
