### ISSUE TITLE
Split up packages?

### ISSUE THREAD

**Issue by fkleuver** [aurelia/aurelia#93]
I see several potential benefits in extracting `task-queue`, `resources` (perhaps a package per resource / logically similar resources), and the `dom` into their own packages.

Same for two-way  element observers (the ones in `element-observation.ts`). 
I personally think having one observer class for each `input type=` would make the whole observation system more robust, performant and easier to understand. We can use decorators to register events instead of using the EventManager, etc.
But why bloat up the runtime with that if people might not always need two-way observation.

The main argument against splitting stuff up was the difficulty in testing and versioning. We've overcome that problem by moving to a monorepo. We can easily cross-reference packages (even internal api) and there are no hacky workarounds needed to do cross-package integration tests.

I'm not advocating a split-up similar to vCurrent though. `templating` and `binding` make sense to have in the same package (runtime) since the separation is only in terms of lifecycle hooks - it's not like one would be usable without the other. But I don't think we should cram all runtime into the runtime package.

Good / bad idea?

If good idea, the next question is: how will we prefix these package (if we'll add them at all)? `@aurelia/runtime-element-observation` or simply `@aurelia/element-observation`?

**Comment by bigopon** [comment]
I think the move will likely have negative effect on bundle size, what do you think about it ?

**Comment by EisenbergEffect** [comment]
I'm concerned that this will not only enlarge the bundle size but make it much harder for people to start a new project. We want to have a way to do this without needing npm or a bundler. Single-file script is still something we eventually want.

I'd vote to wait on anything like this for a while. However, I don't see any reason not to do the design work on breaking things into different classes. I think we should consider that independent of how the packages are shipped right now.

**Comment by EisenbergEffect** [comment]
Sounds good :)

**Comment by fkleuver** [comment]
Closing this since my request for comment has been fulfilled :)
