### ISSUE TITLE
Router: Router breaks when using URL parameters containing question mark

### ISSUE THREAD

**Issue by Vheissu** [aurelia/aurelia#950]
# 🐛 Bug Report

I recently implemented oAuth authentication into my Aurelia 2 application which works on the premise of a callback URL being called containing a token. The token is then grabbed from the URL and used to authenticate the user. The router is acting quite strange in that if it sees a question mark denoting the beginning of route parameters, it will duplicate the `?` 

The URL ends up looking somewhat like this: `http://localhost:9000/oauth(provider=github)??code=d46eee41c3014097b943` this makes parsing the parameters a little difficult, because if the user were to keep refreshing (theoretically), the router keeps on adding a new `?` to the URL.

## 🤔 Expected Behavior

The router should not add any additional parameter `?` to the URL if it already contains one. The above callback URL should look like this: `http://localhost:9000/oauth(provider=github)?code=d46eee41c3014097b943`

## 😯 Current Behavior

Currently, as already noted above, the router keeps adding a `?` into the URL if one is present, but will continue to add a new one if the current URL is refreshed.

## 💁 Possible Solution

Ignore `?` in the URL or count them, if one exists, don't do anything.

## 🔦 Context

This is an oAuth callback URL, which is a common paradigm for oAuth authentication. 

## 💻 Code Sample

This can be replicated by creating any kind of route in your Aurelia 2 application, configure the router to not use URL fragments `RouterConfiguration.customize({ useUrlFragmentHash: false })` and then add a dummy param into the URL `?dummy=somevalue` it will duplicate.

## 🌍 Your Environment

Windows 10, Aurelia 2 (dev), Node.js 14.

**Comment by fkleuver** [comment]
Fixed
