### ISSUE TITLE
Router: Timing is off trying to access the current window location object inside of a routeable component

### ISSUE THREAD

**Issue by Vheissu** [aurelia/aurelia#951]
# 🐛 Bug Report

Trying to access the current URL from inside of a component, `enter`, `beforeAttach`, `afterAttach`, etc results in the wrong URL being returned when using `window.location.href`. The only thing that fixes it is wrapping the code in a `setTimeout` with an arbitrary value (I used 100) to get the correct value.

## 🤔 Expected Behavior

Accessing `window.location.href` from inside of any lifecycle method in a routeable component should return the current value as seen in the browser.

```
afterAttach() {
    console.log(window.location.href);
}
```

## 😯 Current Behavior

Running the following will not provide the URL seen in the browser URL bar, but rather, the existing URL.

```
afterAttach() {
    console.log(window.location.href);
}
```

If you wrap this in a `setTimeout` it works

```
afterAttach() {
    setTimeout(() => {
        console.log(window.location.href);
    }, 100);
}
```

## 💁 Possible Solution

Not sure. This appears to be related to the router overriding the history API functionality, perhaps it is because the router comes in a little later, so although the URL looks correct, it's a matter of milliseconds and the user doesn't see the switch.

## 🔦 Context

I am trying to manually parse out non-router parameters and values from the URL, specifically, an oAuth authentication callback.

## 💻 Code Sample

Please see above. This issue can be replicated by creating a routeable component and attempting to route to it. This would be visible in the default direct navigation application that `npx makes aurelia` produces.

## 🌍 Your Environment

Windows 10, Node 14, Npm, Aurelia 2 (dev)

**Comment by fkleuver** [comment]
Should work if you use either `attached` or, if needed, `await PLATFORM.taskQueue.yield()` (which is used internally by the router). No need for `setTimeout`
