### ISSUE TITLE
Allow extending HtmlAttrSyntaxTransformer behaviour

### ISSUE THREAD

**Issue by MaximBalaganskiy** [aurelia/aurelia#975]
# 🙋 Feature Request
Allow component authors to extend default `HtmlAttrSyntaxTransformer` behaviour to automatically transform `.bind` into `.two-way`

## 🤔 Expected Behavior
As a component author, I should be able to override default transformation algorithm so that consumers of my components can use `.bind` syntax for two way binding

## 😯 Current Behavior
Currently, consumers need to explicitly use `.two-way` for two way binding

## 💁 Possible Solution
* **Option 1** Expose a method on `IAttrSyntaxTransformer` to register additional binding mode transformations
* **Option 2** Introduce a "virtual" method instead of a local `shouldDefaultToTwoWay` function and export `HtmlAttrSyntaxTransformer`

## 🔦 Context
I am creating components and registering binding adapters for properties exposed on html elements.
For Aurelia v1 I was able to monkey-patch framework classes https://github.com/aurelia-ui-toolkits/aurelia-mdc-web/blob/4514f3d6769d8a5bfb8af72d02a3b0ce2c6f6dde/packages/base/src/mdc-component-adapters.ts#L63

**Comment by zewa666** [comment]
Love the idea. Would the user thought still be able to override the two-way default to something else?

**Comment by MaximBalaganskiy** [comment]
The only change would be exposing that "should" function to allow covering more custom elements. Core logic would stay the same - only replace "bind" with the default.

**Comment by fkleuver** [comment]
We already have this kind of extensibility via either `@bindingCommand` or `@attributePattern`. Two examples of how to achieve this:

```ts
// A simple static override at the syntax interpreter level
@attributePattern({ pattern: 'PART.bind', symbols: '.' })
export class BindAttributePattern {
  'PART.bind'(rawName: string, rawValue: string, parts: string[]): AttrSyntax {
    return new AttrSyntax(rawName, rawValue, parts[0], 'two-way');
  }
}

// in your app startup
.register(BindAttributePattern)
```

Alternatively, you can omit the default `bind` binding command by not using the standard configuration but rather registering the whole framework config explicitly. This seems more convoluted for this case, but if you want to take more fine-grained control over Aurelia's binding language then this would open the door for doing so more easily in other ways in the future:
```ts
new Aurelia()
.register(
  // You can see the exact composition of all of these variables in packages/runtime-html/configuration.ts
  ...DefaultComponents,
  ...DefaultBindingSyntax,
  ...DefaultResources,
  ...DefaultComposers,
  // These are all the values from DefaultBindingLanguage *except* for DefaultBindingCommandRegistration
  // DefaultBindingCommandRegistration,
  OneTimeBindingCommandRegistration,
  FromViewBindingCommandRegistration,
  ToViewBindingCommandRegistration,
  TwoWayBindingCommandRegistration,
  CallBindingCommandRegistration,
  ForBindingCommandRegistration,
  RefBindingCommandRegistration,
  TriggerBindingCommandRegistration,
  DelegateBindingCommandRegistration,
  CaptureBindingCommandRegistration,
  ClassBindingCommandRegistration,
  StyleBindingCommandRegistration,
  AttrBindingCommandRegistration,
);

// This is identical to the `two-way` bindingCommand implementation but instead named 'bind'
@bindingCommand('bind')
export class DefaultBindingCommand implements BindingCommandInstance {
  readonly bindingType: BindingType.BindCommand = BindingType.BindCommand;

  compile(binding: PlainAttributeSymbol | BindingSymbol): AttributeInstruction {
    return new TwoWayBindingInstruction(binding.expression as IsBindingBehavior, getTarget(binding, false));
  }
}
```

The same thing applies for attribute patterns by the way, if you wanted to change this. The only different with the attribute patterns is that it works a bit like the route recognizer and you can override existing stuff by simply having fewer dynamic PARTs.

Works the same way if you wanted to have your own kind of pattern:
```ts
// if you register this, <my-component $prop> would behave as <my-component prop.two-way>
@attributePattern({ pattern: '$PART', symbols: '$' })
export class DollarAttributePattern {
  '$PART'(rawName: string, rawValue: string, parts: string[]): AttrSyntax {
    return new AttrSyntax(rawName, rawValue, parts[0], 'two-way');
  }
}
```

For completeness sake:
There is no intent to allow any kind of subclassing or especially monkey patching of framework classes. In fact, things are specifically designed to prevent users from doing that, as it causes tight coupling between framework internals and 3rd party code, which dramatically increase the "attack surface" of potential breaking changes. We have this problem in v1 and we really don't want to have it again in v2.
But we think, with extension points like the above (which will be properly documented soon), no one should need or want to resort to subclassing or monkey patching anyway.

**Comment by bigopon** [comment]
At the moment, binding mode is interpreted based on at least 2 variables: element name and attribute name, sometimes extra attribute on elements are used. For example:
- `value.bind` on an `<input type="text" />` => `value.two-way`
- `value.bind` on an `<input type="checkbox" />` => `value.to-view`
- `value.bind` on a `div` => `value.to-view`

This requirement probably fits `BindingCommand`, as it knows everything: the element & attr syntax & binding command. Even only `.bind` binding command needs to be aware of this, it's still beneficial to have a proper interface/API for this.

Below is an example of what is probably minimum to have an extensible templating syntax:

interfaces:
```ts
import { BindingMode } from 'aurelia';

type BindingModeInterpreter = (element: Element, attrName: string) => BindingMode | null;

interface ISyntaxIntepreter {
  register(interpreter: BindingModeInterpreter): void;
  interpret(element: Element, attrName: string): BindingMode;
}
```
example implementation:
```ts
export class SyntaxInterpreter implements ISyntaxInterpreter {
  private interpreters: Set<BindingModeInterpreter> = new Set([
    function defaultInterpreter(element, attrName) {
      // first handle the global attr
      switch (attrName) {
        case 'scrolltop': case 'scrollleft': return BindingMode.TwoWay;
        case 'textcontent': case 'innerhtml':
          if (element.contentEditable === 'true') return BindingMode.TwoWay;
      }
      // then handle the attr that should be determined based on the element
      switch (element.tagName) {
        case 'input':
          switch (attrName) {
            case 'value': return BindingMode.TwoWay;
            // more stuff here
          }
        case 'textarea':
          // more stuff here
      }
    }
    return null;
  ]);

  public register(interpreter: BindingModeInterperter): void {
    this.interpreters.add(interpreter);
  }

  public interpret(element: Element, attrName: string): BindingMode {
    let mode: BindingMode | null = null;
    for (const interpret of this.interpreters) {
      mode = interpret(element, attrName);
      if (mode != null) return mode;
    }
    return BindingMode.ToView;
  }
}
```
And we should be able to inject this into our `BindBindingCommand` and use it.

For plugin authors, who want to make `value.bind` default to `value.two-way` for an element `<my-input/>`, an example could be as below:
```ts
export const = MyPlugin {
  register(container: IContainer) {
    const interpreter = container.get(ISyntaxInterpreter);
    interpreter.register((element, attrName) => {
      if (element.tagName === 'MY-INPUT' && attrName === 'value') {
        return BindingMode.TwoWay;
      }
    });
    // register <MyInput/> here
  }
}
```
---
### Next step from here

Similar design needs to be applied to `.getObserver` of `TargetObserverLocator` to teach Aurelia how to observe element properties based on event names. This is done in v1 via event manager. An example of how v1 is taught to observe `<input/>` https://github.com/aurelia/binding/blob/ed35588117f52508e628570921bc2361c3861cc7/src/event-manager.js#L251-L258

```ts
    this.registerElementConfig({
      tagName: 'input',
      properties: {
        value: ['change', 'input'], // use change/input events to observe value property
        checked: ['change', 'input'], // use change/input events to observe checked property
        files: ['change', 'input'] // use change/input events to observe files property
      }
    });
```

**Comment by fkleuver** [comment]
I understand the idea that you need to have "element + attribute -> binding command", but that's precisely what the binding command extensibility point is for. The element config registration is not something we need anymore in v2.

**Comment by fkleuver** [comment]
By the way, if I take this sentence literally:
> As a component author, I should be able to override default transformation algorithm so that consumers of my components can use .bind syntax for two way binding

You can do this:
```ts
export class MyComponent {
  @bindable({ mode: BindingMode.twoWay }) prop;
}
```

And this will behave like two-way:
```html
<my-component prop.bind="value"></my-component>
```

The syntax interpreter seems like the (very) wrong tool for the job if that's all you need

**Comment by MaximBalaganskiy** [comment]
This is only if attributes are bindables on view models. What about Web Components, or HTML elements enhanced with properties?

**Comment by fkleuver** [comment]
Okay fair enough. And based on which inputs do you want to make this transformation? Is this an across the board "all bind should be two-way" or just on some types of elements?

**Comment by MaximBalaganskiy** [comment]
Just on some elements - `mdc-text-field`, `mdc-select`, `mdc-checkbox`, `mdc-radio`

**Comment by fkleuver** [comment]
Okay so this is very specifically about extending what `bind` attributes Aurelia defaults to `two-way` right?

We currently have this function somewhere in the compilation process that decides which things default to two-way or not:
```ts
function shouldDefaultToTwoWay(element: HTMLElement, attr: AttrSyntax): boolean {
  switch (element.tagName) {
    case 'INPUT':
      switch ((element as HTMLInputElement).type) {
        case 'checkbox':
        case 'radio':
          return attr.target === 'checked';
        default:
          return attr.target === 'value' || attr.target === 'files';
      }
    case 'TEXTAREA':
    case 'SELECT':
      return attr.target === 'value';
    default:
      switch (attr.target) {
        case 'textcontent':
        case 'innerhtml':
          return element.hasAttribute('contenteditable');
        case 'scrolltop':
        case 'scrollleft':
          return true;
        default:
          return false;
      }
  }
}
```

Used like so internally:
```ts
    if (attrSyntax.command === 'bind' && shouldDefaultToTwoWay(node, attrSyntax)) {
      attrSyntax.command = 'two-way';
    }
```

If you had a way to "add" your own function to the list of function that function belongs to, and it would do something like:
```ts
if (fns.some(x => x(node, attrSyntax)) {
  attrSyntax.command = 'two-way';
}
```

Would that solve your problem?

**Comment by MaximBalaganskiy** [comment]
This is to just add new transformations, either way is fine, as long as it's doing the job

**Comment by brandonseydel** [comment]
I came across this with my ionic implementation the value on ionic components would have been nice to have defaulted to two-way.  Fast and material web components also had the same issue when I wrapped them for prototypes.
