### ISSUE TITLE
viewEngineHooks alternative

### ISSUE THREAD

**Issue by MaximBalaganskiy** [aurelia/aurelia#978]
# 🙋 Feature Request
As a component author, I would like to automatically add custom attributes to elements

## 🤔 Expected Behavior
When a certain custom attribute is set on an element, the framework should be able to add another custom attribute

## 😯 Current Behavior
I could not find `viewEngineHooks` alternatives

## 🔦 Context
* **Scenario 1** In Google MDC certain elements in the top app bar can be marked as "action items". It would be nice to automatically set ripple effect on them via another custom attribute.
* **Scenario 2** Google MDC button requires a certain HTML structure. In the MDC bridge this button is implemented as a custom element - `mdc-button`. The problem is that sometimes this element must present itself in the DOM as `<button>` and sometimes as `<a>`. In au1 I've created a hook which replaces `mdc-button` attribute with `as-element="mdc-button"`, which allows achieving the result. End users can certainly just use `as-element="mdc-button"` but is not as convenient.

## 💻 Examples

https://github.com/aurelia-ui-toolkits/aurelia-mdc-web/blob/master/packages/top-app-bar/src/enhance-top-app-bar-actions.ts
https://github.com/aurelia-ui-toolkits/aurelia-mdc-web/blob/master/packages/button/src/enhance-mdc-button.ts

**Comment by fkleuver** [comment]
Thanks for creating this issue, the API is on the backlog and will be added before alpha.

**Comment by fkleuver** [comment]
Will be implemented by https://github.com/aurelia/aurelia/issues/1044
