### ISSUE TITLE
[RFC] Make $console as a separate sink for LoggerConfiguration

### ISSUE THREAD

**Issue by HamedFathi** [aurelia/aurelia#985]
# 💬 RFC

The new `logger` approach in Aurelia 2 is really amazing but a little weird to me!
The current log design style is very similar to [Serilog](https://github.com/serilog/serilog) in .NET ecosystem.

In Serilog, [Console](https://github.com/serilog/serilog-sinks-console) is a sink just like File, ElasticSearch, and ... but in Aurelia 2 this is a special property! which is incomprehensible to me

```js
const logger = new ConsoleAppender();

Aurelia
  .register(LoggerConfiguration.create({
    $console: logger, // <<< HERE
    level: 0,
    sinks: [EventLog]
  }))
  .app(MyApp)
  .start();
```

It seems that this part should change a bit and everything should be considered as a sink, even a **console**.

## 🔦 Context

I am just saying `console` is another sink and should not add it as a specific property to `LoggerConfiguration`.

## 💻 Examples

Maybe something like

```js
const logger = new ConsoleAppender();

Aurelia
  .register(LoggerConfiguration.create({
    level: 0,
    sinks: [logger]
  }))
  .app(MyApp)
  .start();
```

**Comment by fkleuver** [comment]
Fixed
