### ISSUE TITLE
[RFC] @processHost API prior to a custom element host compilation

### ISSUE THREAD

**Issue by bigopon** [aurelia/aurelia#995]
say we have a component wrapping a button:
```ts
@customElement({
  name: 'at-button',
  containerless: true,
  template: '<button color="green"><b>${text}</b></button>'
})
class AtButton {}
```
So that when a user writes:
```html
app.html
<at-button id="buttonHost" text="say hello" />
```
The user will get the following rendered html
(1)
```html
<!--au-start-->
<button color="green"><b>say hello</b></button>
<!--au-end-->
```
instead of
(2)
```html
<at-button>
  <button color="green"><b>say hello</b></button>
</at-button>
```

Issues:
- host element (`at-button#buttonHost`) is replaced with 2 anchor elements to stabilize the child node operations
- not being able to inject host, as it's replaced with anchor comments

Potential solution:
- a way to turn
```html
<at-button id="hostButton" text="say hello">
```
inside `app.html` into
```html
<button id="hostButton" text="say hello">
```
and compile this `button#hostButton` as if it was
```html
<button as-element="at-button" id="hostButton" text="say hello"></button>
```

So that we can have simpler component template:
```html
<b>${text}</b>
```
 and simpler final rendered html:
```html
<button color="green"><b>say hello</b></button>
``` 
(note that there's no wrapping comment anchors)

Pros:
- provides a way to have custom elements work similar to extended built-in element webcomponents
- simpler rendered html
- enable a way to have harmony for containerless and host injection
- TBU...

**Comment by fkleuver** [comment]
> Pros:
> - provides a way to have custom elements work similar to extended built-in element webcomponents

ShadowDOM won't work.

> - simpler rendered html

FAST is using empty text nodes instead of comments, so I also want to start doing that soon.

> - enable a way to have harmony for containerless and host injection

In v1 the original host is injected, and we should do this in v2 as well.

**Comment by bigopon** [comment]
Having a text node, even empty has side effects like unable to use CSS empty selector, or fallback content of slot not displaying because empty text node = has slotted content. Another issue is that its more difficult to distinguish a normal text node, and an Aurelia controlled one when users need to perform some dom manipulation.

That said, we can try to switch between text node and comment where it makes sense, or is beneficial. The main upside of this proposal is that we can have a nice (static) templating hook during compilation with the timing as follow:
- @processHost: after the template compiler has detected that the current element it's dealing with is a custom element host, but before compiling it
- @processContent:  in a custom element usage, after compiling the host element of a custom element it self, but before compiling the child elements of it

**Comment by Sayan751** [comment]
Consolidating from chats on Discord.

Let us say that `parent-ce` has both `processContent` and `processHost` hooks. It in turn uses `my-ce1` and `my-ce2` in its own definition template. Now the `my-ce*` may or may not have these hooks. The `parent-ce` is itself used in `root-ce`. Given this scenario, the compilation pipeline steps will look as follows.

- invoke `processContent` on `my-ce` during compilation of `root-ce`
- ...
- compilation of `my-ce`
  - invoke the `processHost` hook on `my-ce`, as the hoook is defined.
  - walk the content of `my-ce` (currently the `binder.bind`) and invoke `processContent` hook on the `my-ce*`s provided the hooks are defined. If the `processContent` returns `false` for any `my-ce*` "skip compilation" for that CE. For more info refer https://github.com/aurelia/aurelia/issues/667#issuecomment-748589278

**Comment by Sayan751** [comment]
@bigopon Is this something we still like to address?

**Comment by Sayan751** [comment]
@bigopon I am moving this to v2.x milestone for now.

**Comment by bigopon** [comment]
I think we may not need this PR, unless we can clearly defined what existing APIs lack.
