### ISSUE TITLE
Injectable PostProcessor

### ISSUE THREAD

**Issue by xenoterracide** [aurelia/aurelia#998]
Support Spring like [BeanPostProcessor](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/beans/factory/config/BeanPostProcessor.html)  https://howtodoinjava.com/spring-core/spring-bean-post-processors/

## Use Case: Injectable validation

```ts
export interface InjectablePostProcessor {
    postProcessAfterInitialization?: (resolved: unknown, Key key) => unknown;
    postProcessBeforeInitialization?: (resolved: unknown, Key key) => unknown;
}

export const InjectablePostProcessor = DI.createInterface<InjectablePostProcessor>('InjectectablePostProcessor').noDefault();
```
```ts
import { IsUrl } from 'class-validator';

@singleton
class APIConnectionProperties {
   constructor( @inject('api.url') @IsUrl()readonly url: string ) {
   }
}
```

```ts
import { validator } from 'class-validator';
container.register(Registration.instance(InjectablePostProcessor, { postProcessAfterInitialization: ( resolved ) => validator.validate( resolved) } ) );
container.register(Registration.instance('database.url', 'foo'));
container.get(DatabaseConnectionProperties); // throws 
```

another thing that's been done with postprocessors is proxies, like one to auto implement transaction wrappers, I could also see auto circuit breakers like cockatiel. 

# Other Solutions

Obviously this could just be done by everyone growing their own resolvers, but that'd mean reimplementing every resolver

# Problems to consider

if doing a proxy you probably want to cache the proxy instead of creating a new one on each resolve, so maybe the postprocessors get passed into a given `IResolver`, on the other hand, this means that every `IResolver` has to remember to call it.

**Comment by bigopon** [comment]
Thanks @xenoterracide, we have `registerTransformer` for this purpose, though it's only about post initialization:
```ts
container.registerTransformer(MyClass, myClassInstance => {
  // do dynamic stuff with the instance here
});
```
